import type { ClinicalCaseDefinition } from "../case-definition";
import type { DermLesionLayer, MediaAsset } from "../types";
import { photo } from "./media";

const plaques = (count: number, size: number): DermLesionLayer[] => [{ morphology: "plaque", count, size, region: "central" }];
const shin = (lesions: DermLesionLayer[], seed: number, caption: string): MediaAsset =>
  photo({ site: "shin", phototype: 4, lesions, seed }, "Close-up clinical photograph of the shin.", caption);

export const dermPsoriasis: ClinicalCaseDefinition = {
  id: "derm-psoriasis-01",
  specialty: "Dermatology",
  track: "opd",
  level: "college",
  setting: "OPD",
  weight: 4,
  difficulty: 3,
  patient: { name: "Harpreet", age: 41, sex: "Male", city: "Rajouri Garden, Delhi", occupation: "Runs a hardware shop", context: "Dermatology OPD" },
  arrivalMinuteOfDay: 16 * 60 + 30,
  briefing: "A 41-year-old shopkeeper is waiting in Dermatology OPD. He has rolled up his trouser legs.",
  opening: [
    { role: "system", kind: "finding", text: "Clinical photograph taken by the OPD nurse.", media: shin(plaques(2, 26), 3, "Right shin · at presentation") },
    { role: "patient", kind: "speech", text: "Doctor, these patches keep coming back. Now they're on my elbows and scalp as well." },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "138/88" },
    hr: { key: "hr", value: "82" },
    weight: { key: "weight", value: "86" },
    height: { key: "height", value: "172" },
    bmi: { key: "bmi", value: "29.1" },
    rbs: { key: "rbs", value: "124" },
  },
  profile: {},

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential",
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened"],
      reply: "Thick, scaly patches on my legs, elbows and now my scalp, doctor. They never go away completely.",
      fact: "Recurrent scaly plaques — legs, elbows, scalp" },
    { id: "onset", group: "hpi", label: "Course", importance: "essential",
      match: ["how long", "since when", "when did", "duration", "start", "started", "onset", "tell me about", "tell me more", "patches", "progression", "come and go", "winter", "season", "getting worse"],
      reply: "About three years. They get much worse every winter and with stress at the shop. Summer is a little better.",
      fact: "3 years; winter and stress flares" },
    { id: "itch", group: "hpi", label: "Itch & scale", importance: "useful",
      match: ["itch", "itching", "itchy", "scale", "scales", "flakes", "flaking", "bleed", "bleeding", "pain"],
      reply: "Some itching. White flakes fall everywhere — on my bed, my clothes. If I pick them, they bleed in tiny spots.",
      fact: "Mild itch; heavy scaling; pinpoint bleeding on picking" },
    { id: "joints", group: "systemic", label: "Joint symptoms", importance: "essential", abnormal: true,
      match: ["joint", "joints", "joint pain", "stiffness", "morning stiffness", "swelling", "fingers", "toes", "back pain", "arthritis", "heel pain", "sausage"],
      reply: "Now that you ask — my fingers are stiff for half an hour every morning, and this finger swelled up a few months ago. One toe looks like a sausage.",
      fact: "Morning stiffness ~30 min; swollen finger; sausage-like toe" },
    { id: "nails", group: "hpi", label: "Nail changes", importance: "useful", abnormal: true,
      match: ["nails", "nail", "fingernails", "toenails"],
      reply: "My nails have small dents, and two of them are lifting from the tip.",
      fact: "Nail pitting; onycholysis" },
    { id: "treatments", group: "medication", label: "Treatments tried", importance: "essential", abnormal: true,
      match: ["tried", "treatment", "treatments", "creams", "cream", "medicines", "medicine", "tablets", "injection", "injections", "taking any", "taking anything", "what have you used", "applied", "applying"],
      reply: "A local doctor gave me two injections last year — the patches vanished in a week, but a month later they came back worse than ever, all over my body. Now I only use coconut oil.",
      fact: "Systemic steroid injections ×2 last year — rapid clearance then severe rebound; coconut oil only now" },
    { id: "alcohol", group: "social", label: "Alcohol & smoking", importance: "essential",
      match: ["alcohol", "drink", "drinking", "smoke", "smoking", "cigarettes", "tobacco", "pegs"],
      reply: "I smoke about ten cigarettes a day. Drinks only at weddings, maybe twice a month.",
      fact: "Smoker 10/day; occasional alcohol" },
    { id: "past", group: "past", label: "Past history", importance: "useful",
      match: ["past", "medical history", "diabetes", "sugar", "bp", "blood pressure", "heart", "liver", "kidney", "tuberculosis", "hepatitis", "jaundice", "comorbidities", "any disease", "illness", "medical problems"],
      reply: "No sugar or BP that I know of. No liver problem, no jaundice, no TB.",
      fact: "No known diabetes, hypertension, liver disease, hepatitis or TB" },
    { id: "family", group: "family", label: "Family history", importance: "useful",
      match: ["family", "father", "mother", "siblings", "brother", "sister", "anyone else", "runs in", "parents"],
      reply: "My father had similar patches on his knees.",
      fact: "Father — similar plaques" },
    { id: "plans", group: "sexual", label: "Family planning", importance: "useful",
      match: ["children", "family planning", "more children", "wife pregnant", "trying for a baby", "contraception", "sexual"],
      reply: "We have two children. We're not planning more.",
      fact: "Not planning further children" },
    { id: "impact", group: "social", label: "Impact", importance: "minor",
      match: ["affect", "affecting", "how do you feel", "mood", "stress", "embarrassed", "work"],
      reply: "Customers stare at my elbows. I've stopped wearing half sleeves.",
      fact: "Embarrassment; covers up at work" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful",
      match: ["allergy", "allergic", "allergies", "drug reaction", "sulfa", "sulpha"],
      reply: "No allergies.",
      fact: "No known drug allergies" },
  ],

  exam: [
    { id: "local", group: "local-exam", label: "Skin", importance: "essential", abnormal: true,
      match: ["lesion", "lesions", "patches", "plaques", "local examination", "local", "skin", "examine skin", "examine the skin", "elbows", "knees", "shins", "legs", "rash", "distribution", "bsa", "body surface area"],
      finding: "Multiple well-demarcated, erythematous plaques with thick silvery-white scale over both elbows, knees, shins and the lumbosacral area; largest 8 × 6 cm on the right shin. Estimated body surface area ~12%.",
      fact: "Well-demarcated scaly plaques — elbows, knees, shins, lower back; BSA ~12%",
      media: shin(plaques(3, 22), 19, "Left knee and shin · close-up") },
    { id: "scalp", group: "local-exam", label: "Scalp", importance: "useful", abnormal: true,
      match: ["scalp", "hair", "head", "hairline"],
      finding: "Thick scaly plaques over the occiput and both temples, extending about 1 cm beyond the hairline.",
      fact: "Scalp plaques crossing the hairline" },
    { id: "nail-exam", group: "local-exam", label: "Nails", importance: "useful", abnormal: true,
      match: ["nails", "nail", "fingernails", "toenails", "nail examination"],
      finding: "Multiple pits on most fingernails; distal onycholysis of the right index and middle fingernails; oil-drop discolouration.",
      fact: "Pitting, onycholysis, oil-drop sign" },
    { id: "joint-exam", group: "systemic-exam", label: "Joints", importance: "essential", abnormal: true,
      match: ["joints", "joint", "joint examination", "hands", "fingers", "toes", "dactylitis", "musculoskeletal", "spine", "sacroiliac", "examine the hands"],
      finding: "Swollen, tender distal interphalangeal joint of the left index finger. Dactylitis of the right third toe. Spine and sacroiliac joints non-tender.",
      fact: "DIP synovitis; dactylitis",
      patientReaction: "Ah — that finger is the sore one." },
    { id: "auspitz", group: "local-exam", label: "Grattage & Auspitz sign", importance: "minor",
      match: ["auspitz", "grattage", "scrape", "scraping", "candle grease", "pinpoint bleeding"],
      finding: "Grattage produces candle-grease scale; removing the last membrane reveals pinpoint bleeding points.",
      fact: "Candle-grease sign and Auspitz sign positive" },
    { id: "general", group: "general-exam", label: "General examination", importance: "minor", match: [],
      finding: "Conscious, oriented. Overweight (central obesity). No pallor, icterus, lymphadenopathy or pedal oedema.",
      fact: "Central obesity" },
  ],

  investigations: [
    { id: "cbc", priority: "essential", teaching: { whenToOrder: "Baseline before methotrexate; 2 weeks after starting, then monthly ×3, then 3-monthly.", whatItTellsYou: "Marrow reserve — methotrexate's commonest serious toxicity." } },
    { id: "lft", priority: "essential", teaching: { whenToOrder: "Baseline and during methotrexate.", whatItTellsYou: "Hepatotoxicity (raised transaminases, low albumin)." } },
    { id: "rft", priority: "essential", teaching: { whenToOrder: "Baseline — methotrexate is renally cleared.", whatItTellsYou: "Reduced clearance means toxic levels at ordinary doses." } },
    { id: "viral-markers", priority: "useful", teaching: { whenToOrder: "Before methotrexate, ciclosporin or biologics.", whatItTellsYou: "Hepatitis B/C (liver risk, reactivation) and HIV." } },
    { id: "lipid", priority: "useful",
      rows: [
        { analyte: "Total cholesterol", value: "214", unit: "mg/dL", reference: "< 200", flag: "high" },
        { analyte: "LDL cholesterol", value: "136", unit: "mg/dL", reference: "< 100", flag: "high" },
        { analyte: "HDL cholesterol", value: "38", unit: "mg/dL", reference: "> 40", flag: "low" },
        { analyte: "Triglycerides", value: "198", unit: "mg/dL", reference: "< 150", flag: "high" },
      ],
      teaching: { whenToOrder: "Psoriasis is associated with metabolic syndrome — screen BP, lipids and glucose.", whatItTellsYou: "Cardiometabolic risk." } },
    { id: "fbs", priority: "useful", rows: [{ analyte: "Fasting plasma glucose", value: "108", unit: "mg/dL", reference: "70–99", flag: "high" }],
      teaching: { whenToOrder: "Metabolic screening in psoriasis.", whatItTellsYou: "Impaired fasting glucose." } },
    { id: "esr", priority: "useful", rows: [{ analyte: "ESR", value: "32", unit: "mm/1st h", reference: "0–15", flag: "high" }],
      teaching: { whenToOrder: "Suspected psoriatic arthritis.", whatItTellsYou: "Inflammatory activity (often normal in PsA)." } },
    { id: "crp", priority: "useful", rows: [{ analyte: "CRP", value: "14", unit: "mg/L", reference: "< 6", flag: "high" }],
      teaching: { whenToOrder: "Suspected psoriatic arthritis.", whatItTellsYou: "Inflammation." } },
    { id: "cxr", priority: "situational", teaching: { whenToOrder: "Before biologics (TB screening), or with chest symptoms.", whatItTellsYou: "Latent/active TB, baseline lungs." } },
    { id: "hands-xray", name: "X-ray both hands", short: "X-ray hands", category: "imaging",
      match: ["xray hands", "x ray hands", "hand xray", "hand x ray", "x ray both hands", "xray of hands"],
      turnaroundMin: 20, cost: 500, priority: "situational",
      report: "Soft-tissue swelling around the left index DIP joint. Joint spaces preserved. No erosions or periostitis yet.",
      teaching: { whenToOrder: "Established psoriatic arthritis, to stage damage.", whatItTellsYou: "Erosions, pencil-in-cup changes, periostitis." } },
    { id: "skin-biopsy", priority: "unnecessary", teaching: { whenToOrder: "Only if the diagnosis is uncertain.", whatItTellsYou: "Psoriasiform hyperplasia, Munro microabscesses — not needed for classic plaques." } },
    { id: "koh", priority: "unnecessary", teaching: { whenToOrder: "If annular or atypical plaques suggest tinea.", whatItTellsYou: "Fungal hyphae." } },
  ],

  therapeutics: [
    { id: "mtx", kind: "drug", drugIds: ["methotrexate"], label: "Methotrexate once weekly", appropriateness: "ideal",
      doseRange: { min: 5, max: 25, unit: "mg" },
      wrongFrequencies: ["OD", "BD", "TDS", "QID", "HS", "alternate days"],
      praise: "Chose weekly methotrexate — it treats both the skin and the joints." },
    { id: "folic", kind: "drug", drugIds: ["folic-acid"], label: "Folic acid", appropriateness: "ideal" },
    { id: "topical", kind: "drug", drugIds: ["calcipotriol-beta", "calcipotriol", "clobetasol", "betamethasone-topical", "mometasone", "salicylic-acid"], label: "Topical therapy (vitamin D analogue ± steroid)", appropriateness: "ideal" },
    { id: "emollient", kind: "drug", drugIds: ["moisturiser"], label: "Emollient", appropriateness: "acceptable" },
    { id: "ciclosporin", kind: "drug", drugIds: ["cyclosporine"], label: "Ciclosporin", appropriateness: "acceptable",
      critique: { what: "Chose ciclosporin.", why: "It works quickly for skin but does little for psoriatic arthritis and is nephrotoxic and hypertensive — he is overweight with borderline BP.", better: "Methotrexate weekly covers skin and joints; keep ciclosporin for short-term rescue.", severity: "minor" } },
    { id: "apremilast", kind: "drug", drugIds: ["apremilast"], label: "Apremilast", appropriateness: "acceptable" },
    { id: "systemic-steroid", kind: "drug", drugIds: ["prednisolone", "dexamethasone", "methylprednisolone", "hydrocortisone"], label: "Systemic corticosteroid", appropriateness: "harmful",
      critique: { what: "Gave a systemic corticosteroid.", why: "Steroids clear psoriasis briefly, then precipitate severe rebound — erythrodermic or pustular psoriasis — exactly what happened after his injections last year.", better: "Never use systemic steroids for psoriasis.", severity: "major" } },
    { id: "nsaid", kind: "drug", drugClasses: ["nsaid"], label: "NSAID for joint pain", appropriateness: "acceptable" },
    { id: "cotrimoxazole", kind: "drug", drugIds: ["cotrimoxazole"], label: "Co-trimoxazole", appropriateness: "dangerous",
      critique: { what: "Prescribed co-trimoxazole alongside methotrexate.", why: "Both are antifolates; together they cause severe marrow suppression.", better: "Avoid trimethoprim/co-trimoxazole in anyone on methotrexate.", severity: "major" } },
    { id: "mtx-counsel", kind: "counsel", label: "Methotrexate safety counselling", appropriateness: "ideal",
      match: ["once a week", "once weekly", "only once a week", "same day every week", "every sunday", "weekly only", "mouth ulcers", "fever or sore throat", "avoid alcohol", "contraception", "blood tests", "monitoring", "side effects of methotrexate"],
      response: [{ role: "patient", kind: "speech", text: "Only once a week — every Sunday. And the folic acid on the other days. I'll write it on the strip." }],
      praise: "Counselled on weekly dosing, warning symptoms and monitoring." },
    { id: "lifestyle", kind: "counsel", label: "Smoking, weight & alcohol", appropriateness: "acceptable",
      match: ["quit smoking", "stop smoking", "lose weight", "weight loss", "reduce alcohol", "stop alcohol", "lifestyle", "exercise"],
      response: [{ role: "patient", kind: "speech", text: "I'll try to cut down the cigarettes." }] },
    { id: "rheum", kind: "referral", label: "Rheumatology referral", appropriateness: "acceptable",
      match: ["rheumatology", "rheumatologist", "refer to rheumatology", "joint specialist"],
      praise: "Referred the psoriatic arthritis to rheumatology." },
    { id: "phototherapy", kind: "procedure", label: "Narrowband UVB phototherapy", appropriateness: "acceptable",
      match: ["phototherapy", "nbuvb", "nb uvb", "narrowband", "uv therapy", "light therapy"],
      note: "Phototherapy schedule arranged — three sessions a week." },
  ],
  hazards: [],

  followUp: [
    { when: "ideal", status: "improving",
      lines: [
        { role: "system", kind: "finding", text: "Clinical photograph at follow-up.", media: shin(plaques(2, 16), 3, "Right shin · follow-up") },
        { role: "patient", kind: "speech", text: "The patches are much thinner and the flakes have reduced a lot. My finger isn't stiff in the mornings now. The blood tests at two weeks were normal." },
      ],
      facts: [{ group: "local-exam", label: "Follow-up", value: "Plaques thinner, less scale; joint symptoms improved" }] },
    { when: "acceptable", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "The creams help a bit on the skin. The finger is still stiff every morning." }] },
    { when: "harmful", status: "deteriorating",
      lines: [{ role: "patient", kind: "speech", text: "It got better first, doctor, and now it has spread everywhere — my whole body is red and peeling." }] },
    { when: "untreated", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "Same as before. Winter is coming; it will get worse." }] },
  ],

  truth: {
    diagnosis: "Chronic plaque psoriasis with psoriatic arthritis",
    qualifier: "Moderate-to-severe (BSA ~12%), scalp and nail involvement; oligoarticular psoriatic arthritis with dactylitis",
    reasoning: [
      { stage: "History", text: "Three years of recurrent scaly plaques, worse in winter and with stress; rebound after systemic steroid injections; morning finger stiffness, a swollen finger and a 'sausage' toe; father affected." },
      { stage: "Examination", text: "Well-demarcated plaques with silvery scale on extensor surfaces and lower back (BSA ~12%), scalp beyond the hairline, nail pitting and onycholysis, DIP synovitis and dactylitis." },
      { stage: "Investigation", text: "Clinical diagnosis. Baseline CBC, LFT, RFT and viral markers for methotrexate; ESR/CRP raised; metabolic screen abnormal." },
      { stage: "Diagnosis", text: "Moderate-to-severe chronic plaque psoriasis with psoriatic arthritis — an indication for systemic therapy." },
    ],
  },

  rubric: {
    diagnosisAccept: ["psoriasis with psoriatic arthritis", "psoriatic arthritis", "psoriatic arthropathy", "plaque psoriasis with arthritis", "psoriasis and psoriatic arthritis"],
    diagnosisPartial: ["psoriasis", "plaque psoriasis", "chronic plaque psoriasis", "psoriasis vulgaris", "scalp psoriasis", "nail psoriasis"],
    differentials: ["psoriatic arthritis", "seborrhoeic dermatitis", "nummular eczema", "discoid eczema", "lichen simplex chronicus", "tinea corporis", "pityriasis rubra pilaris", "hypertrophic lichen planus", "rheumatoid arthritis", "gout", "reactive arthritis"],
    idealTreatment: [["mtx"], ["folic"], ["topical"], ["mtx-counsel"]],
    expertActionCount: 18,
    followUpDays: { min: 14, max: 42 },
    expectsReassessment: false,
    weights: { history: 20, examination: 15, differential: 12, investigationSelection: 12, investigationInterpretation: 5, treatment: 14, drugSafety: 12, reassessment: 5, efficiency: 2, outcome: 3 },
    misses: {
      joints: { what: "Did not ask about joint symptoms.", why: "Up to 30% of psoriasis patients develop psoriatic arthritis; it changes treatment from creams to systemic therapy.", better: "Ask every psoriasis patient about morning stiffness, swollen fingers or toes, heel and back pain.", severity: "major" },
      treatments: { what: "Did not ask about previous treatment.", why: "The rebound after systemic steroid injections is both a teaching point for the patient and a warning for you.", better: "Ask what has been tried, how it worked, and what happened after stopping.", severity: "moderate" },
      alcohol: { what: "Did not ask about alcohol and smoking.", why: "Alcohol raises methotrexate liver risk; smoking worsens psoriasis.", better: "Quantify both before choosing a systemic drug.", severity: "moderate" },
      local: { what: "Did not examine the skin systematically.", why: "BSA, site and morphology decide topical versus systemic therapy.", better: "Estimate BSA (patient's palm ≈ 1%); check scalp, nails, folds and genitals.", severity: "major" },
      "joint-exam": { what: "Did not examine the joints.", why: "DIP synovitis and dactylitis confirm psoriatic arthritis.", better: "Examine hands, feet, spine and entheses.", severity: "moderate" },
      cbc: { what: "No baseline blood count.", why: "Methotrexate's most dangerous toxicity is marrow suppression.", better: "CBC, LFT, RFT before the first dose.", severity: "moderate" },
      lft: { what: "No baseline liver tests.", why: "Methotrexate is hepatotoxic.", better: "LFT at baseline and during treatment.", severity: "moderate" },
      rft: { what: "No baseline renal function.", why: "Methotrexate is renally cleared; reduced clearance causes toxicity at normal doses.", better: "Creatinine/eGFR before starting.", severity: "moderate" },
      mtx: { what: "No systemic therapy.", why: "BSA > 10% with psoriatic arthritis is an indication for systemic treatment; creams alone won't protect the joints.", better: "Methotrexate 7.5–10 mg once weekly with folic acid, increasing to 15 mg as tolerated.", severity: "major" },
      folic: { what: "No folic acid with methotrexate.", why: "Folic acid reduces mucositis, GI upset and liver toxicity without reducing efficacy.", better: "Folic acid 5 mg on the days methotrexate is not taken.", severity: "moderate" },
      topical: { what: "No topical treatment.", why: "Topicals speed clearance of plaques while methotrexate takes 8–12 weeks to act.", better: "Calcipotriol + betamethasone gel once daily for 4 weeks, then calcipotriol for maintenance.", severity: "moderate" },
      "mtx-counsel": { what: "Methotrexate safety was not counselled.", why: "Weekly-dose confusion is the classic fatal methotrexate error.", better: "Name the day of the week, write it on the strip, explain mouth ulcers/fever/sore throat as warning signs, and schedule blood tests.", severity: "major" },
    },
    strengths: {
      joints: "Screened for psoriatic arthritis — and found it.",
      treatments: "Uncovered the steroid-injection rebound.",
      alcohol: "Asked about alcohol and smoking before systemic therapy.",
      "joint-exam": "Examined the joints.",
      "nail-exam": "Examined the nails.",
      cbc: "Ordered baseline blood counts before methotrexate.",
      "viral-markers": "Screened viral markers before immunosuppression.",
      mtx: "Chose weekly methotrexate for skin and joints.",
      folic: "Added folic acid.",
    },
  },

  teaching: {
    patientBand: "severe",
    severityBands: [
      { id: "mild", label: "Mild", media: shin(plaques(1, 12), 51, "Mild"),
        recognition: ["BSA < 3%", "Few plaques, no special sites, no arthritis"],
        investigation: ["None — clinical"],
        treatment: ["Calcipotriol + betamethasone once daily ×4 weeks → calcipotriol maintenance", "Emollients; salicylic acid for thick scale"],
        followUp: ["4–8 weeks"] },
      { id: "moderate", label: "Moderate", media: shin(plaques(2, 18), 52, "Moderate"),
        recognition: ["BSA 3–10%, or significant impact on life", "Scalp, nails or genital involvement"],
        investigation: ["Metabolic screen (BP, lipids, glucose, BMI)"],
        treatment: ["Topicals plus phototherapy (NB-UVB)", "Systemic therapy if topicals fail or special sites"],
        followUp: ["4–6 weeks"] },
      { id: "severe", label: "Severe / with arthritis", media: shin(plaques(3, 24), 53, "Severe"),
        recognition: ["BSA > 10%", "Psoriatic arthritis — dactylitis, DIP synovitis, enthesitis"],
        investigation: ["CBC, LFT, RFT, viral markers before systemic drugs", "ESR/CRP; X-ray hands/feet; TB screen before biologics"],
        treatment: ["Methotrexate once weekly + folic acid (first line, covers joints)", "Alternatives: ciclosporin (short-term), acitretin (no PsA), apremilast", "Biologics if inadequate response"],
        followUp: ["Labs at 2 weeks, monthly ×3, then 3-monthly"] },
      { id: "emergency", label: "Erythrodermic / pustular",
        recognition: ["> 90% BSA erythema, or sheets of sterile pustules", "Fever, chills, fluid and temperature instability — often after stopping steroids"],
        investigation: ["CBC, RFT, electrolytes, albumin, cultures"],
        treatment: ["Admit; fluids, temperature control, emollients", "Ciclosporin or acitretin; never systemic steroids"],
        followUp: ["Inpatient"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Methotrexate", brand: "Folitrax", dose: "7.5–10 mg, increasing to 15 mg", route: "PO", frequency: "ONCE A WEEK — same day (e.g. every Sunday)", duration: "Long term; response by 8–12 weeks",
        indication: "Moderate-to-severe psoriasis and psoriatic arthritis",
        mechanism: "Inhibits dihydrofolate reductase → less purine/pyrimidine synthesis in rapidly dividing keratinocytes and T cells; also releases anti-inflammatory adenosine.",
        whyItWorks: "Slows the hyperproliferating epidermis and damps the immune drive in skin and joints.",
        avoidWhen: ["Pregnancy or planned conception (men and women)", "Liver disease, heavy alcohol use", "Renal impairment", "With co-trimoxazole/trimethoprim"],
        adverseEffects: ["Mouth ulcers, nausea", "Marrow suppression", "Hepatotoxicity", "Pneumonitis (rare)"],
        monitoring: ["CBC, LFT, creatinine at 2 weeks, monthly ×3, then 3-monthly", "Ask about ulcers, fever, cough at every visit"] },
      { generic: "Folic acid", brand: "Folvite", dose: "5 mg", route: "PO", frequency: "Once daily on non-methotrexate days", duration: "As long as methotrexate is taken",
        indication: "Reducing methotrexate toxicity",
        mechanism: "Replenishes folate pools in normal cells → protects mucosa, gut and liver from antifolate toxicity.",
        whyItWorks: "Reduces side effects without blunting methotrexate's effect in psoriasis.",
        avoidWhen: ["Do not take on the methotrexate day"],
        adverseEffects: ["Rare"],
        monitoring: ["None"] },
      { generic: "Calcipotriol 0.005% + betamethasone dipropionate 0.05% gel", brand: "Daivobet", dose: "Thin layer to plaques", route: "TOP", frequency: "Once daily", duration: "Up to 4 weeks, then calcipotriol alone",
        indication: "Plaque and scalp psoriasis",
        mechanism: "Calcipotriol binds the vitamin D receptor → normalises keratinocyte proliferation and differentiation; betamethasone damps inflammation.",
        whyItWorks: "Faster and better tolerated than either agent alone.",
        avoidWhen: ["Face and folds (steroid)", "Hypercalcaemia", "More than ~100 g/week"],
        adverseEffects: ["Local irritation", "Steroid atrophy with prolonged use"],
        monitoring: ["Response at 4 weeks"] },
    ],
    routines: [
      { label: "Weekly methotrexate schedule",
        steps: [
          { order: 1, step: "Sunday, after dinner", product: "Methotrexate 10 mg", note: "Only on Sunday — write “SUNDAY” on the strip" },
          { order: 2, step: "Monday to Saturday", product: "Folic acid 5 mg", note: "Never on Sunday" },
          { order: 3, step: "Blood tests", note: "CBC, LFT, creatinine at week 2, then monthly ×3, then every 3 months" },
        ],
        avoid: ["Taking methotrexate on any other day", "Co-trimoxazole (Septran/Bactrim)", "Alcohol", "Pregnancy — use contraception during and for 3 months after"] },
      { label: "Daily skin routine",
        steps: [
          { order: 1, step: "Lukewarm bath", note: "No scrubbing the scales" },
          { order: 2, step: "Emollient on damp skin", howMuch: "Generous", where: "All dry skin" },
          { order: 3, step: "Medicated gel at night", product: "Daivobet", where: "Plaques only", note: "Up to 4 weeks continuously" },
        ],
        improvementTimeline: "Topicals help in 2–4 weeks; methotrexate's full effect takes 8–12 weeks." },
    ],
    followUp: {
      interval: "2 weeks (labs), then monthly ×3, then 3-monthly",
      reassess: ["PASI/BSA and joint count", "CBC, LFT, creatinine", "Adherence to weekly dosing and folic acid", "BP, weight, lipids"],
      redFlags: ["Mouth ulcers, fever, sore throat, bruising — stop methotrexate, urgent CBC", "Breathlessness or dry cough (pneumonitis)", "Generalised redness or pustules"],
      whenToEscalate: ["< 50% improvement at 12–16 weeks on 15 mg/week → switch or add (apremilast, biologic)", "Progressive arthritis → rheumatology and biologics"],
    },
    treatmentFailure: { steps: [
      "Check adherence — weekly dose taken? folic acid? creams applied?",
      "Check the diagnosis — tinea, eczema, lichen planus",
      "Check severity — BSA, joints, special sites",
      "Check triggers — infections, stress, alcohol, smoking, drugs (lithium, β-blockers)",
      "Alternative — raise methotrexate to 15–20 mg/week, or switch to apremilast/ciclosporin",
      "Escalate — biologic therapy (TNF, IL-17, IL-23 inhibitors) after TB and hepatitis screening",
    ] },
    pearl: "Write methotrexate as a day of the week, not a frequency. “Once weekly” becomes “once daily” in a pharmacy or a patient's memory — and daily methotrexate kills through mucositis and marrow failure within days. And ask every psoriasis patient about their joints.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "If methotrexate had been written “OD” instead of “once weekly”, he would have returned within a week with mouth ulcers, fever and pancytopenia — a frequently fatal error.",
      sequence: ["Stop methotrexate", "Admit; folinic acid (leucovorin) every 6 hours until counts recover", "Blood cultures and broad-spectrum IV antibiotics for fever", "Daily CBC, renal and liver function; G-CSF if severe neutropenia"],
    },
  },
};
