import type { ClinicalCaseDefinition } from "../case-definition";
import { acneLesions, acnePhoto, photo } from "./media";

export const dermAcne: ClinicalCaseDefinition = {
  id: "derm-acne-moderate-01",
  specialty: "Dermatology",
  track: "opd",
  level: "district",
  setting: "OPD",
  weight: 6,
  difficulty: 1,
  patient: { name: "Ananya", age: 19, sex: "Female", city: "Rohini, Delhi", occupation: "B.Com student at Delhi University", context: "Dermatology OPD" },
  arrivalMinuteOfDay: 11 * 60 + 20,
  briefing: "A 19-year-old college student is waiting in Dermatology OPD, room 3.",
  opening: [
    { role: "system", kind: "finding", text: "Clinical photograph taken by the OPD nurse.", media: acnePhoto("moderate", 41, "Left cheek · at presentation") },
    { role: "patient", kind: "speech", text: "Doctor, these pimples on my face just aren't going away. I've tried so many face washes." },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "112/72" },
    hr: { key: "hr", value: "76" },
    weight: { key: "weight", value: "54" },
    height: { key: "height", value: "158" },
    bmi: { key: "bmi", value: "21.6" },
  },
  profile: { pregnancyPossible: true, currentDrugs: ["betamethasone-topical"] },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential",
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened"],
      reply: "These pimples on my face, doctor. They just won't go away, no matter what I try.",
      fact: "Persistent facial pimples" },
    { id: "onset", group: "hpi", label: "Onset & evolution", importance: "essential",
      match: ["how long", "since when", "when did", "duration", "start", "started", "onset", "how did it start", "tell me about", "tell me more", "pimples", "acne", "progression", "getting worse", "how has it changed", "first noticed"],
      reply: "It started about a year and a half ago — just small bumps on my forehead. For the last six months it has spread to my cheeks, and now there are these red, painful ones too.",
      fact: "~18 months; forehead → cheeks; inflammatory lesions for 6 months" },
    { id: "symptoms", group: "hpi", label: "Pain / itch", importance: "useful",
      match: ["painful", "pain", "itch", "itching", "itchy", "tender", "sore", "burning", "hurt", "hurts"],
      reply: "Some of the red ones hurt when I touch them. They don't really itch.",
      fact: "Tender inflammatory lesions; no itch" },
    { id: "sites", group: "hpi", label: "Distribution", importance: "useful",
      match: ["where", "other places", "back", "chest", "shoulders", "body", "only on the face", "anywhere else", "trunk", "other parts"],
      reply: "Mostly on my cheeks and forehead. A few on my upper back, but not many.",
      fact: "Face (cheeks, forehead) > upper back" },
    { id: "aggravating", group: "hpi", label: "Aggravating factors", importance: "useful",
      match: ["worse", "aggravate", "aggravates", "triggers", "trigger", "before periods", "before your periods", "premenstrual", "exams", "anything makes it worse", "flare", "flares"],
      reply: "It gets worse just before my periods, and during exams. Oily food also seems to make it worse, I think.",
      fact: "Premenstrual and exam-stress flares" },
    { id: "treatments", group: "medication", label: "Treatments tried", importance: "essential", abnormal: true,
      match: ["tried", "treatment", "treatments", "used", "using", "applying", "apply", "cream", "creams", "ointment", "medicine", "medicines", "face wash", "anything for it", "taking anything", "home remedies", "remedies", "chemist", "what have you used", "products you use"],
      reply: "I've tried lots of face washes. For the last two months I've been putting on a cream at night that the chemist gave me — Betnovate-something. At first it seemed to calm things down, but now it's worse than before. No tablets.",
      fact: "OTC betamethasone cream nightly × 2 months — initial settling, then worse; no oral medicines" },
    { id: "menstrual", group: "obstetric", label: "Menstrual history", importance: "essential",
      match: ["periods", "period", "menstrual", "menses", "cycle", "cycles", "regular", "lmp", "last period", "pcos", "pcod", "monthly"],
      reply: "My periods are regular — every 28 to 30 days. The last one was about two weeks ago.",
      fact: "Regular cycles (28–30 d); LMP ~2 weeks ago" },
    { id: "androgen", group: "systemic", label: "Hyperandrogenism symptoms", importance: "useful",
      match: ["facial hair", "excess hair", "hair growth", "hirsutism", "unwanted hair", "hair fall", "hair loss", "weight gain", "deep voice", "voice"],
      reply: "No, nothing like that. My weight has been the same for years.",
      fact: "No hirsutism, hair loss or weight gain" },
    { id: "sexual", group: "sexual", label: "Sexual history & contraception", importance: "useful",
      match: ["sexually active", "sexual", "boyfriend", "relationship", "contraception", "contraceptive", "pregnant", "pregnancy", "married", "partner"],
      reply: "I'm not married… and I'm not sexually active, doctor.",
      fact: "Not sexually active; no contraception" },
    { id: "family", group: "family", label: "Family history", importance: "useful", abnormal: true,
      match: ["family", "mother", "father", "siblings", "brother", "sister", "anyone else", "parents", "runs in"],
      reply: "My elder brother had very bad pimples in college. He still has marks and small pits on his cheeks.",
      fact: "Brother — severe acne with scarring" },
    { id: "diet", group: "diet", label: "Diet", importance: "useful",
      match: ["diet", "eat", "eating", "food", "milk", "dairy", "sweets", "junk", "chocolate", "tea", "what do you eat"],
      reply: "Mostly home food. But I have three or four cups of milk tea a day, and sweets quite often. Junk food with friends sometimes.",
      fact: "High glycaemic load; milk tea 3–4 cups/day" },
    { id: "cosmetics", group: "social", label: "Cosmetics & hair care", importance: "useful",
      match: ["makeup", "make up", "cosmetics", "skin care", "skincare", "hair oil", "oil your hair", "moisturiser", "moisturizer", "sunscreen", "products", "foundation"],
      reply: "I use a little foundation for college. And I oil my hair twice a week — coconut oil, left overnight. No sunscreen.",
      fact: "Daily foundation; overnight coconut-oil hair oiling; no sunscreen" },
    { id: "impact", group: "social", label: "Psychosocial impact", importance: "useful", abnormal: true,
      match: ["affect", "affecting", "how do you feel about", "mood", "confidence", "upset", "sad", "embarrassed", "bothering you", "how is this affecting", "low", "depressed"],
      reply: "Honestly, doctor… I don't like going out anymore. I keep checking the mirror. Everyone has advice, and it just makes me feel worse.",
      fact: "Avoids going out; significant distress" },
    { id: "past", group: "past", label: "Past medical history", importance: "minor",
      match: ["past", "medical history", "illness", "diabetes", "thyroid", "asthma", "any other problem", "any disease", "surgery", "hospital", "comorbidities", "comorbidity", "previously", "medical problems"],
      reply: "No, I've always been healthy.",
      fact: "No past illness" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful",
      match: ["allergy", "allergic", "allergies", "drug reaction", "reaction to any"],
      reply: "No allergies that I know of.",
      fact: "No known drug allergies" },
    { id: "habits", group: "social", label: "Smoking / alcohol", importance: "minor",
      match: ["smoke", "smoking", "alcohol", "drink alcohol", "tobacco", "drugs"],
      reply: "No, doctor. Nothing like that.",
      fact: "No smoking or alcohol" },
  ],

  exam: [
    { id: "local", group: "local-exam", label: "Face", importance: "essential", abnormal: true,
      match: ["face", "examine the face", "local examination", "local", "lesion", "lesions", "examine skin", "skin", "examine the skin", "look at the face", "cheeks", "forehead", "pimples", "acne", "morphology", "distribution", "examine the lesions", "rash"],
      finding: "Oily skin. Multiple open and closed comedones over the forehead, nose and both cheeks. About 20 erythematous papules and 8–10 pustules over the cheeks and forehead. No nodules or cysts. Several hyperpigmented macules at sites of resolved lesions. No atrophic or hypertrophic scars.",
      fact: "Comedones; ~20 papules, 8–10 pustules; no nodules; PIH; no scars",
      media: photo({ site: "forehead", phototype: 4, lesions: acneLesions("moderate"), seed: 77 }, "Close-up clinical photograph of the forehead.", "Forehead · close-up") },
    { id: "back", group: "local-exam", label: "Upper back & chest", importance: "useful", abnormal: true,
      match: ["back", "trunk", "chest", "shoulders", "examine back", "examine the back", "upper back"],
      finding: "A few open comedones and 4–5 small papules over the upper back. Chest clear. No nodules.",
      fact: "Few comedones and papules, upper back" },
    { id: "scars", group: "local-exam", label: "Scarring", importance: "useful",
      match: ["scar", "scars", "scarring", "pits", "pitting", "marks", "dark marks", "dark spots"],
      finding: "No atrophic or hypertrophic scars. Multiple hyperpigmented macules, 2–4 mm, at sites of previous lesions.",
      fact: "No scarring; post-inflammatory hyperpigmentation" },
    { id: "androgen-exam", group: "general-exam", label: "Signs of androgen excess", importance: "useful",
      match: ["hirsutism", "facial hair", "hair distribution", "ferriman", "ferriman gallwey", "acanthosis", "acanthosis nigricans", "signs of androgen excess", "androgen", "virilisation", "virilization", "body hair"],
      finding: "No hirsutism (modified Ferriman–Gallwey score 3). No acanthosis nigricans. No androgenetic hair thinning.",
      fact: "No hirsutism; no acanthosis" },
    { id: "dermoscopy", group: "local-exam", label: "Dermoscopy", importance: "minor",
      match: ["dermoscopy", "dermatoscopy", "dermatoscope", "dermoscope"],
      finding: "Open comedones with central dark keratin plugs; closed comedones as whitish-yellow dots. Papules with surrounding erythema and dotted vessels. No scale, no follicular yeast-pattern papules.",
      fact: "Comedones and inflammatory papules on dermoscopy" },
    { id: "telangiectasia", group: "local-exam", label: "Skin atrophy / telangiectasia", importance: "minor",
      match: ["atrophy", "telangiectasia", "thin skin", "steroid damage", "redness", "erythema", "flushing"],
      finding: "Mild background erythema over both cheeks. No telangiectasia or atrophy.",
      fact: "Mild cheek erythema; no atrophy" },
  ],

  investigations: [
    { id: "hormonal-profile", priority: "unnecessary",
      teaching: { whenToOrder: "Only with signs of hyperandrogenism — irregular cycles, hirsutism, androgenetic alopecia, sudden severe acne, or acne resistant to standard therapy.", whatItTellsYou: "Screens for PCOS, non-classical CAH and androgen-secreting tumours." } },
    { id: "upt", priority: "situational",
      teaching: { whenToOrder: "Before starting isotretinoin (and monthly during it), or any teratogenic drug, in a woman of child-bearing potential.", whatItTellsYou: "Excludes pregnancy before a teratogen." } },
    { id: "lft", priority: "situational",
      teaching: { whenToOrder: "Baseline before isotretinoin; repeat at 1–2 months.", whatItTellsYou: "Transaminase rise on isotretinoin." } },
    { id: "lipid", priority: "situational",
      teaching: { whenToOrder: "Baseline before isotretinoin; repeat at 1–2 months.", whatItTellsYou: "Hypertriglyceridaemia on isotretinoin." } },
    { id: "koh", priority: "situational",
      teaching: { whenToOrder: "When monomorphic itchy follicular papules (forehead, chest, back) suggest Malassezia folliculitis, often after steroid use.", whatItTellsYou: "Budding yeasts and short hyphae." } },
    { id: "cbc", priority: "unnecessary",
      teaching: { whenToOrder: "Not needed in uncomplicated acne.", whatItTellsYou: "Nothing that changes acne management." } },
    { id: "usg-abdomen", priority: "unnecessary",
      teaching: { whenToOrder: "Pelvic ultrasound only when PCOS is suspected clinically.", whatItTellsYou: "Polycystic ovarian morphology." } },
  ],

  therapeutics: [
    { id: "adapalene-bpo", kind: "drug", drugIds: ["adapalene-bpo"], label: "Adapalene + benzoyl peroxide gel", appropriateness: "ideal" },
    { id: "topical-retinoid", kind: "drug", drugIds: ["adapalene", "adapalene-clinda", "tretinoin"], label: "Topical retinoid", appropriateness: "acceptable" },
    { id: "bpo", kind: "drug", drugIds: ["benzoyl-peroxide"], label: "Benzoyl peroxide", appropriateness: "acceptable" },
    { id: "topical-antibiotic", kind: "drug", drugIds: ["clindamycin-topical", "nadifloxacin"], label: "Topical antibiotic", appropriateness: "acceptable" },
    { id: "oral-doxycycline", kind: "drug", drugIds: ["doxycycline", "minocycline"], label: "Oral doxycycline", appropriateness: "ideal",
      doseRange: { min: 50, max: 200, unit: "mg" } },
    { id: "azithro-pulse", kind: "drug", drugIds: ["azithromycin"], label: "Azithromycin pulse", appropriateness: "acceptable",
      critique: { what: "Azithromycin pulse therapy chosen over doxycycline.", why: "Evidence for azithromycin in acne is weaker, and macrolide resistance in C. acnes is high in India.", better: "Doxycycline 100 mg daily for 8–12 weeks with BPO.", severity: "minor" } },
    { id: "sunscreen", kind: "drug", drugIds: ["sunscreen"], label: "Sunscreen", appropriateness: "ideal" },
    { id: "moisturiser", kind: "drug", drugIds: ["moisturiser"], label: "Non-comedogenic moisturiser", appropriateness: "ideal" },
    { id: "cleanser", kind: "drug", drugIds: ["cleanser"], label: "Gentle cleanser", appropriateness: "acceptable" },
    { id: "isotretinoin", kind: "drug", drugIds: ["isotretinoin"], label: "Oral isotretinoin", appropriateness: "unnecessary",
      critique: { what: "Started isotretinoin as first-line therapy.", why: "This is moderate acne without scarring that has never had standard therapy. Isotretinoin is reserved for severe, scarring or treatment-resistant acne, and needs pregnancy prevention and laboratory monitoring.", better: "Topical retinoid + BPO with oral doxycycline; reassess at 8–12 weeks; escalate if < 50% better or scarring develops.", severity: "moderate" } },
    { id: "topical-steroid", kind: "drug", drugClasses: ["topical-steroid"], label: "Topical corticosteroid", appropriateness: "harmful",
      critique: { what: "Prescribed a topical corticosteroid for acne.", why: "Steroids on the face worsen acne, cause steroid-induced acneiform eruptions and rosacea-like dermatitis, and create dependence — this patient was already worse after two months of one.", better: "Never use topical steroids for acne. Stop the existing cream and warn about a short rebound flare.", severity: "major" } },
    { id: "systemic-steroid", kind: "drug", drugIds: ["prednisolone", "dexamethasone", "methylprednisolone"], label: "Systemic corticosteroid", appropriateness: "harmful",
      critique: { what: "Gave a systemic corticosteroid.", why: "Steroids aggravate acne and have no role outside acne fulminans.", better: "Topical retinoid + BPO ± oral doxycycline.", severity: "major" } },
    { id: "ocp", kind: "drug", drugIds: ["ocp"], label: "Combined oral contraceptive", appropriateness: "unnecessary",
      critique: { what: "Prescribed a combined oral contraceptive.", why: "There is no hyperandrogenism and cycles are regular; COCs add thrombotic risk without a clear indication here.", better: "Reserve hormonal therapy for women with hyperandrogenism or as an adjunct after standard therapy fails.", severity: "minor" } },
    { id: "stop-steroid", kind: "counsel", label: "Stop the steroid cream", appropriateness: "ideal",
      concernsDrugs: ["topical-steroid", "betamethasone-topical", "steroid-fdc", "clobetasol"],
      match: ["stop the cream", "stop betnovate", "stop the betnovate", "stop steroid", "stop the steroid", "stop using the cream", "discontinue the cream", "no steroid", "avoid steroid", "avoid steroids", "stop applying", "stop that cream", "steroid cream", "dont use the cream", "do not use the cream"],
      response: [{ role: "patient", kind: "speech", text: "Oh… I didn't know it could make it worse. I'll stop it today, doctor." }],
      praise: "Stopped the over-the-counter steroid cream and explained why." },
    { id: "diet-counsel", kind: "counsel", label: "Low-glycaemic diet", appropriateness: "acceptable",
      match: ["low glycemic", "low glycaemic", "reduce milk", "cut down sweets", "reduce sugar", "avoid sweets", "diet advice", "reduce dairy", "avoid junk", "healthy diet", "less sugar", "cut down on tea", "reduce tea"],
      response: [{ role: "patient", kind: "speech", text: "Okay. I'll cut down the tea and sweets." }] },
    { id: "no-picking", kind: "counsel", label: "Avoid picking", appropriateness: "acceptable",
      match: ["dont pick", "do not pick", "avoid picking", "dont squeeze", "do not squeeze", "avoid squeezing", "no picking", "dont touch", "do not touch", "dont pop", "stop picking"],
      response: [{ role: "patient", kind: "speech", text: "I do pick at them sometimes… I'll stop." }],
      praise: "Advised against picking — the commonest cause of scarring and dark marks." },
    { id: "hair-oil-counsel", kind: "counsel", label: "Avoid overnight hair oil on the hairline", appropriateness: "acceptable",
      match: ["hair oil", "stop oiling", "avoid hair oil", "oiling", "wash off the oil"],
      response: [{ role: "patient", kind: "speech", text: "I didn't know the hair oil could matter. I'll wash it off sooner." }] },
    { id: "makeup-counsel", kind: "counsel", label: "Non-comedogenic cosmetics", appropriateness: "acceptable",
      match: ["avoid makeup", "avoid foundation", "non comedogenic", "remove makeup", "oil free makeup", "no makeup"] },
    { id: "expectations", kind: "counsel", label: "Expectations & irritation", appropriateness: "acceptable",
      match: ["takes time", "will take time", "purging", "irritation", "expect", "dryness", "patience", "dont stop", "do not stop", "initial worsening", "may sting", "might sting", "stinging", "be patient"],
      response: [{ role: "patient", kind: "speech", text: "Okay — so I shouldn't stop if it feels dry in the first couple of weeks." }],
      praise: "Set realistic expectations about irritation and the 6–12 week timeline — the main driver of adherence." },
    { id: "procedures", kind: "procedure", label: "Cosmetic procedure", appropriateness: "unnecessary",
      match: ["chemical peel", "peel", "glycolic peel", "salicylic peel", "comedone extraction", "laser", "microneedling", "dermaroller", "derma roller"],
      note: "Procedure performed.",
      critique: { what: "Booked a cosmetic procedure during active acne.", why: "Peels and lasers are for residual pigmentation and scars once active acne is controlled; they do not replace medical therapy.", better: "Control active acne first; consider peels for PIH after 3–6 months of control.", severity: "minor" } },
  ],
  hazards: [],

  followUp: [
    { when: "ideal", status: "improving",
      lines: [
        { role: "system", kind: "finding", text: "Clinical photograph at follow-up.", media: { ...acnePhoto("mild", 41, "Left cheek · follow-up"), spec: { kind: "derm", site: "cheek", phototype: 4, seed: 41, lesions: [ { morphology: "comedone-closed", count: 8, size: 1 }, { morphology: "comedone-open", count: 4, size: 1 }, { morphology: "papule", count: 4, size: 2.2 }, { morphology: "hyperpigment", count: 9, size: 2.3 } ] } } },
        { role: "patient", kind: "speech", text: "It's much better, doctor! The red ones have mostly gone. The gel stung a bit in the first week, but I kept going like you said. The dark marks are still there, though." },
      ],
      facts: [{ group: "local-exam", label: "Follow-up", value: "~75% fewer inflammatory lesions; PIH persists" }] },
    { when: "acceptable", status: "stable",
      lines: [
        { role: "system", kind: "finding", text: "Clinical photograph at follow-up.", media: acnePhoto("moderate", 43, "Left cheek · follow-up") },
        { role: "patient", kind: "speech", text: "It's a little better, but new ones keep coming, especially on my cheeks." },
      ],
      facts: [{ group: "local-exam", label: "Follow-up", value: "Partial improvement; new inflammatory lesions" }] },
    { when: "harmful", status: "deteriorating",
      lines: [
        { role: "system", kind: "finding", text: "Clinical photograph at follow-up.", media: acnePhoto("moderately-severe", 45, "Left cheek · follow-up") },
        { role: "patient", kind: "speech", text: "It's worse, doctor. My face has become red, and there are lots of small bumps everywhere." },
      ],
      facts: [{ group: "local-exam", label: "Follow-up", value: "Worse: monomorphic papules, erythema" }] },
    { when: "untreated", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "No real change, doctor. Maybe a little worse before my period." }] },
  ],

  truth: {
    diagnosis: "Acne vulgaris — moderate",
    qualifier: "Inflammatory (papulopustular), with post-inflammatory hyperpigmentation; aggravated by an over-the-counter topical steroid",
    reasoning: [
      { stage: "History", text: "Adolescent onset 18 months ago; comedones evolving to painful red lesions; premenstrual flares; a chemist's steroid cream made it worse; brother scarred." },
      { stage: "Examination", text: "Polymorphic eruption — open and closed comedones, ~20 papules, 8–10 pustules — on face and upper back. No nodules, no scars; PIH present." },
      { stage: "Investigation", text: "None needed. Regular cycles and no signs of androgen excess mean no hormonal work-up." },
      { stage: "Diagnosis", text: "Moderate acne vulgaris with PIH, steroid-aggravated." },
    ],
  },

  rubric: {
    diagnosisAccept: ["moderate acne", "acne vulgaris moderate", "acne moderate", "papulopustular acne", "inflammatory acne", "grade 2 acne", "grade ii acne", "acne grade 2", "acne grade ii", "acne vulgaris grade 2", "acne vulgaris grade ii", "moderate inflammatory acne", "papulo pustular acne"],
    diagnosisPartial: ["acne vulgaris", "acne", "steroid acne", "steroid induced acne", "acneiform", "mild acne", "severe acne"],
    differentials: ["steroid acne", "steroid induced acne", "steroid induced acneiform", "malassezia folliculitis", "pityrosporum folliculitis", "rosacea", "pcos", "polycystic ovary", "folliculitis", "acne cosmetica", "perioral dermatitis", "hyperandrogenism"],
    idealTreatment: [["adapalene-bpo", "topical-retinoid"], ["adapalene-bpo", "bpo"], ["oral-doxycycline"], ["stop-steroid"], ["sunscreen", "moisturiser"]],
    expertActionCount: 15,
    followUpDays: { min: 21, max: 84 },
    expectsReassessment: false,
    weights: { history: 20, examination: 15, differential: 15, investigationSelection: 10, investigationInterpretation: 5, treatment: 15, drugSafety: 10, reassessment: 5, efficiency: 2, outcome: 3 },
    misses: {
      onset: { what: "Did not establish the duration and evolution of the lesions.", why: "Acne beginning in adolescence and evolving from comedones to inflammatory lesions is classic; sudden adult onset or a monomorphic eruption points elsewhere.", better: "Ask when it started, where, and how the lesions have changed.", severity: "moderate" },
      treatments: { what: "Did not ask what she was already applying.", why: "She had used an over-the-counter betamethasone cream for two months. Topical steroids aggravate acne and are the commonest reason for 'nothing works' in Indian OPDs.", better: "Always ask: “What creams, face washes or home remedies have you used?” — and ask to see the tube.", severity: "major" },
      menstrual: { what: "Did not take a menstrual history.", why: "Irregular cycles, hirsutism or sudden severe acne suggest PCOS or another hyperandrogenic state, which changes treatment.", better: "In every woman with acne, ask about cycle regularity, hirsutism, weight change and scalp hair thinning.", severity: "moderate" },
      local: { what: "Did not examine the lesions systematically.", why: "Grading depends on counting comedones, papules, pustules and nodules and looking for scars and PIH.", better: "Inspect face, chest and back; count lesion types; look for scarring.", severity: "major" },
      "adapalene-bpo": { what: "No topical retinoid prescribed.", why: "Retinoids treat the microcomedone — the precursor of every acne lesion — and are the backbone of treatment and maintenance.", better: "Adapalene 0.1% + BPO 2.5% gel at night, a pea-sized amount for the whole face.", severity: "major" },
      bpo: { what: "No benzoyl peroxide in the regimen.", why: "BPO kills C. acnes without inducing resistance and protects any antibiotic from resistance.", better: "Combine every antibiotic, topical or oral, with BPO.", severity: "moderate" },
      "oral-doxycycline": { what: "No oral antibiotic for moderate inflammatory acne.", why: "With ~30 inflammatory lesions, truncal spread, PIH and a family history of scarring, systemic therapy shortens the time to control.", better: "Doxycycline 100 mg once daily after food for 8–12 weeks (max 3–4 months), always with a topical retinoid + BPO.", severity: "moderate" },
      "stop-steroid": { what: "The steroid cream was not stopped.", why: "Continuing a facial steroid perpetuates steroid-induced acne and risks rosacea-like dermatitis and atrophy.", better: "Stop it explicitly, and warn about a 1–2 week rebound flare.", severity: "major" },
      sunscreen: { what: "No photoprotection or moisturiser.", why: "Retinoids and BPO irritate and photosensitise; PIH darkens with UV. Without a moisturiser and sunscreen, adherence drops.", better: "Gel-based moisturiser and broad-spectrum SPF 50 every morning.", severity: "moderate" },
    },
    strengths: {
      treatments: "Uncovered the over-the-counter steroid cream — the key aggravating factor.",
      menstrual: "Screened for hyperandrogenism with a menstrual history.",
      "androgen-exam": "Examined for signs of androgen excess before deciding against a hormonal work-up.",
      impact: "Explored the psychosocial impact — a reason to treat early and adequately.",
      family: "Elicited a family history of scarring acne — a reason to treat more decisively.",
      "adapalene-bpo": "Chose a fixed-dose retinoid + BPO combination — first-line for moderate acne.",
      "oral-doxycycline": "Added doxycycline appropriately for moderate inflammatory acne.",
      sunscreen: "Built photoprotection into the regimen.",
      scars: "Looked specifically for scarring, which determines how aggressively to treat.",
    },
  },

  teaching: {
    patientBand: "moderate",
    severityBands: [
      { id: "mild", label: "Mild", media: acnePhoto("mild", 11, "Mild"),
        recognition: ["Mostly comedones (open and closed)", "A few papules or pustules, no nodules", "No scarring"],
        investigation: ["None — clinical diagnosis"],
        treatment: ["Topical retinoid (adapalene 0.1%) at night", "± BPO 2.5%, or fixed retinoid + BPO", "Gentle cleanser, moisturiser, sunscreen"],
        followUp: ["Review at 8–12 weeks", "Maintenance with topical retinoid once clear"] },
      { id: "moderate", label: "Moderate", media: acnePhoto("moderate", 12, "Moderate"),
        recognition: ["Many comedones", "Several to many papules and pustules", "No or very few small nodules", "PIH common in Indian skin"],
        investigation: ["None, unless features of hyperandrogenism"],
        treatment: ["Fixed-dose adapalene + BPO at night", "Add oral doxycycline 100 mg OD for 8–12 weeks if widespread, truncal, or scarring-prone", "Never antibiotic monotherapy"],
        followUp: ["Review at 6–8 weeks", "Stop oral antibiotic by 3–4 months", "Continue topical retinoid as maintenance"] },
      { id: "moderately-severe", label: "Moderately severe", media: acnePhoto("moderately-severe", 13, "Moderately severe"),
        recognition: ["Numerous papules and pustules", "A few nodules", "Early scarring risk"],
        investigation: ["Baseline LFT, lipids and UPT if isotretinoin is planned"],
        treatment: ["Retinoid + BPO + oral doxycycline", "Low threshold for oral isotretinoin, especially if any scarring"],
        followUp: ["Review at 4–6 weeks", "Escalate early if response < 50% at 12 weeks"] },
      { id: "severe", label: "Severe", media: acnePhoto("severe", 14, "Severe"),
        recognition: ["Many nodules and cysts", "Extensive inflammation, often trunk", "Scarring present or imminent"],
        investigation: ["UPT, LFT, fasting lipids before isotretinoin", "Repeat LFT/lipids at 1–2 months; monthly UPT"],
        treatment: ["Oral isotretinoin 0.3–0.5 mg/kg/day (e.g. 20 mg OD after food for a 55 kg patient)", "Two reliable contraceptive methods; 1 month before to 1 month after", "Short prednisolone course only for acne fulminans"],
        followUp: ["Monthly reviews", "Watch mood, lipids, LFTs, dryness", "Continue until clear, then 1–2 more months"] },
      { id: "scarring", label: "Scarring & complications", media: acnePhoto("scarring", 15, "Scarring"),
        recognition: ["Atrophic scars — ice-pick, boxcar, rolling", "Hypertrophic or keloidal scars on trunk/jaw", "Persistent PIH"],
        investigation: ["None routinely"],
        treatment: ["Control active acne first — scarring is an indication for isotretinoin", "Then: chemical peels for PIH; microneedling, subcision, fractional laser, TCA CROSS for scars"],
        followUp: ["Procedures only after 6 months of quiescent acne (and after isotretinoin wash-out)"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Adapalene 0.1% + benzoyl peroxide 2.5% gel", brand: "Epiduo", dose: "Pea-sized amount for the whole face", route: "TOP", frequency: "Once at night", duration: "12 weeks, then retinoid maintenance",
        indication: "First-line for mild to moderate acne",
        mechanism: "Adapalene normalises follicular keratinisation → fewer microcomedones; BPO releases free radicals → kills C. acnes and is mildly comedolytic.",
        whyItWorks: "It attacks the two main drivers at once — plugging and bacteria — without creating antibiotic resistance.",
        avoidWhen: ["Pregnancy (avoid retinoids)", "Eczema or broken skin on the face", "Simultaneous use with other irritant actives"],
        adverseEffects: ["Dryness, peeling, stinging in the first 2–4 weeks", "BPO bleaches fabric — pillowcases, towels"],
        monitoring: ["Irritation at 2–4 weeks", "Lesion counts at 8–12 weeks"] },
      { generic: "Doxycycline 100 mg", brand: "Doxy-1 L-DR Forte", dose: "100 mg", route: "PO", frequency: "Once daily after food, upright, with a full glass of water", duration: "8–12 weeks (max 3–4 months)",
        indication: "Moderate to severe inflammatory acne, or truncal acne",
        mechanism: "Inhibits bacterial 30S ribosome → reduces C. acnes; also anti-inflammatory (inhibits neutrophil chemotaxis and matrix metalloproteinases).",
        whyItWorks: "Calms inflamed papules and pustules quickly while the retinoid works on comedones.",
        avoidWhen: ["Pregnancy and breastfeeding", "Children under 8", "With isotretinoin (intracranial hypertension)"],
        adverseEffects: ["Pill oesophagitis — take upright, not at bedtime", "Photosensitivity", "GI upset"],
        monitoring: ["Response at 6–8 weeks", "Stop by 3–4 months; continue topical retinoid + BPO"] },
      { generic: "Isotretinoin", brand: "Isotroin", dose: "0.3–0.5 mg/kg/day (e.g. 20 mg)", route: "PO", frequency: "Once daily after a fatty meal", duration: "Until clear, then 1–2 months; cumulative ~120 mg/kg",
        indication: "Severe, nodular, scarring or treatment-resistant acne",
        mechanism: "Shrinks sebaceous glands and sebum output by up to 90%, normalises keratinisation, reduces C. acnes and inflammation.",
        whyItWorks: "The only drug that acts on all four drivers of acne — the source of its durable remissions.",
        avoidWhen: ["Pregnancy — severely teratogenic", "With tetracyclines", "Significant hepatic disease or uncontrolled hyperlipidaemia"],
        adverseEffects: ["Cheilitis, dry skin and eyes", "Raised triglycerides and transaminases", "Mood change — ask every visit"],
        monitoring: ["UPT before and monthly", "LFT and fasting lipids at baseline and 1–2 months", "Mood"] },
      { generic: "Broad-spectrum sunscreen SPF 50, PA+++ (gel, oil-free)", brand: "La Shield", dose: "Two finger-lengths for face and neck", route: "TOP", frequency: "Every morning; reapply every 3 h outdoors", duration: "Indefinitely",
        indication: "Photoprotection on retinoids; prevents darkening of PIH",
        mechanism: "Absorbs and scatters UV (and visible light if tinted) → less UV-driven melanogenesis.",
        whyItWorks: "In Indian skin, PIH fades only if UV keeps it from re-darkening.",
        avoidWhen: ["Known allergy to a filter"],
        adverseEffects: ["Rarely comedogenic if greasy — choose gel"],
        monitoring: ["Daily use"] },
    ],
    routines: [
      { label: "Morning",
        steps: [
          { order: 1, step: "Cleanser", product: "Cetaphil Gentle Skin Cleanser", howMuch: "Coin-sized", where: "Whole face", note: "Lukewarm water; pat dry — no scrubbing" },
          { order: 2, step: "Moisturiser", product: "Oil-free gel moisturiser", howMuch: "Pea-sized ×2", where: "Whole face" },
          { order: 3, step: "Sunscreen", product: "La Shield gel SPF 50", howMuch: "Two finger-lengths", where: "Face and neck", note: "Reapply every 3 h outdoors" },
        ],
        avoid: ["Scrubs, lemon, toothpaste, home remedies", "Any steroid cream", "Picking or squeezing"] },
      { label: "Night",
        steps: [
          { order: 1, step: "Cleanser", product: "Cetaphil Gentle Skin Cleanser", howMuch: "Coin-sized", where: "Whole face" },
          { order: 2, step: "Medication", product: "Epiduo gel", howMuch: "One pea-sized amount", where: "Dot on forehead, cheeks, chin → spread over the whole face, not just spots", note: "Apply 15 min after washing, on fully dry skin; avoid eyes, lips, nasal folds" },
          { order: 3, step: "Moisturiser", product: "Oil-free gel moisturiser", howMuch: "Pea-sized ×2", where: "Whole face" },
        ],
        avoid: ["Overnight hair oil along the hairline", "Heavy foundation overnight"],
        expectedIrritation: "Dryness, mild redness and peeling in weeks 1–4; a few new spots may surface early.",
        ifIrritated: "Use on alternate nights for 2 weeks; apply moisturiser first; or wash off after 1 hour. Stop and review if there is swelling or blistering.",
        improvementTimeline: "Fewer new lesions by 4–6 weeks; clear improvement by 8–12 weeks; dark marks fade over 3–6 months with sunscreen." },
    ],
    followUp: {
      interval: "6–8 weeks",
      reassess: ["Inflammatory and comedonal lesion counts", "Irritation and adherence", "PIH and any new scarring", "Mood"],
      redFlags: ["Nodules, cysts or new scars", "Severe irritation or swelling", "Sudden severe acne with virilisation", "Low mood or suicidal thoughts on isotretinoin"],
      whenToEscalate: ["< 50% improvement at 12 weeks on retinoid + BPO + doxycycline", "Any scarring → consider isotretinoin early", "Antibiotics never beyond 3–4 months"],
    },
    treatmentFailure: { steps: [
      "Check adherence and technique — pea-sized, whole face, every night? stopped because of irritation?",
      "Check the diagnosis — steroid acne, Malassezia folliculitis, rosacea, PCOS",
      "Check severity — nodules or scars mean a step up",
      "Check aggravators — steroids, cosmetics, hair oils, whey/anabolic supplements",
      "Alternative — switch retinoid (tretinoin), change the oral antibiotic (max 3–4 months)",
      "Escalate — isotretinoin with pregnancy prevention; hormonal therapy if hyperandrogenic",
    ] },
    pearl: "In Indian skin, every inflamed papule is a future dark mark. Treat acne early and adequately — and always ask what the patient is already applying. An over-the-counter steroid cream is the commonest reason “nothing works.”",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "Isotretinoin is the most effective acne drug and one of the most teratogenic. Starting it without excluding pregnancy, or without two reliable methods of contraception, risks severe embryopathy.",
      sequence: ["Confirm a clear indication (severe, scarring or resistant acne)", "Negative pregnancy test before starting and monthly", "Two forms of contraception from 1 month before until 1 month after", "Baseline LFT and lipids; repeat at 1–2 months", "Ask about mood at every visit"],
    },
  },
};
