import type { ClinicalCaseDefinition } from "../case-definition";
import type { DermLesionLayer, MediaAsset } from "../types";
import { photo } from "./media";

const rings = (count: number, size: number, extra: DermLesionLayer[] = []): DermLesionLayer[] => [
  { morphology: "annular", count, size, region: "central" },
  { morphology: "hyperpigment", count: 5, size: 5 },
  ...extra,
];
const waist = (lesions: DermLesionLayer[], seed: number, caption: string): MediaAsset =>
  photo({ site: "trunk", phototype: 4, lesions, seed }, "Close-up clinical photograph of the skin at the waist.", caption);

export const dermTinea: ClinicalCaseDefinition = {
  id: "derm-tinea-01",
  specialty: "Dermatology",
  track: "opd",
  level: "chc",
  setting: "OPD",
  weight: 6,
  difficulty: 2,
  patient: { name: "Imran", age: 28, sex: "Male", city: "Mayur Vihar, Delhi", occupation: "Field sales executive", context: "Dermatology OPD" },
  arrivalMinuteOfDay: 12 * 60 + 5,
  briefing: "A 28-year-old sales executive has come to Dermatology OPD in the lunch hour. He keeps scratching his waist.",
  opening: [
    { role: "system", kind: "finding", text: "Clinical photograph taken by the OPD nurse.", media: waist(rings(2, 24, [{ morphology: "pustule", count: 4, size: 1.6, region: "central" }]), 9, "Left flank, belt line · at presentation") },
    { role: "patient", kind: "speech", text: "Doctor, this itching is driving me mad. These rings keep spreading — I've tried so many creams." },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "124/80" },
    hr: { key: "hr", value: "80" },
    rbs: { key: "rbs", value: "112" },
    weight: { key: "weight", value: "76" },
    height: { key: "height", value: "174" },
    bmi: { key: "bmi", value: "25.1" },
  },
  profile: { currentDrugs: ["steroid-fdc"] },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential",
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened"],
      reply: "Itchy red rings around my waist and in the groin, doctor. For three months now.",
      fact: "Itchy rings — waist and groin × 3 months" },
    { id: "onset", group: "hpi", label: "Onset & spread", importance: "essential",
      match: ["how long", "since when", "when did", "duration", "start", "started", "onset", "spread", "spreading", "tell me about", "tell me more", "rings", "patches", "rash", "progression"],
      reply: "It started in the groin during the monsoon, then went to the belt area, my buttocks and inner thighs. Each time a ring heals in the middle, it grows at the edge.",
      fact: "Groin → waist, buttocks, thighs; expanding rings with central clearing" },
    { id: "itch", group: "hpi", label: "Itch pattern", importance: "useful",
      match: ["itch", "itching", "itchy", "night", "worse", "sweat", "sweating", "scratch", "scratching"],
      reply: "It's worst at night and when I sweat during field work. I scratch until it bleeds sometimes.",
      fact: "Intense itch, worse at night and with sweating" },
    { id: "creams", group: "medication", label: "Treatments tried", importance: "essential", abnormal: true,
      match: ["tried", "treatment", "treatments", "creams", "cream", "applied", "applying", "apply", "medicines", "medicine", "tablets", "using anything", "chemist", "what have you used", "ointment", "taking anything"],
      reply: "The chemist gave me Panderm Plus — I've put it twice a day for two months. It settles in a few days, then the rings come back bigger. A local doctor gave me one white tablet a week for three weeks last year.",
      fact: "Steroid–antifungal–antibiotic FDC (Panderm Plus) BD × 2 months; brief relief then worse; fluconazole weekly ×3 last year" },
    { id: "family", group: "family", label: "Household contacts", importance: "essential", abnormal: true,
      match: ["family", "wife", "brother", "anyone else", "household", "home", "others at home", "contacts", "children", "roommate", "same problem"],
      reply: "Yes — my wife has started itching under her breasts, and my younger brother has the same rings on his thighs. We share the bathroom.",
      fact: "Wife and brother similarly affected; shared bathroom" },
    { id: "clothing", group: "social", label: "Clothing & hygiene", importance: "essential",
      match: ["clothes", "clothing", "jeans", "underwear", "innerwear", "tight", "towel", "towels", "hygiene", "bath", "bathe", "laundry", "wash", "dry", "drying", "sharing"],
      reply: "I wear jeans all day for work and synthetic innerwear. We share towels at home. I bathe once a day, at night.",
      fact: "Tight jeans, synthetic innerwear; shared towels; bathes once daily" },
    { id: "foot-symptoms", group: "hpi", label: "Feet & nails", importance: "useful", abnormal: true,
      match: ["feet", "foot", "toes", "between the toes", "nails", "toenails", "shoes", "socks", "athlete"],
      reply: "Between my toes it peels and itches sometimes. I wear closed shoes all day.",
      fact: "Itchy peeling toe webs; closed shoes all day" },
    { id: "diabetes", group: "past", label: "Past history", importance: "useful",
      match: ["diabetes", "sugar", "past", "medical history", "illness", "comorbidities", "any disease", "hiv", "immunity", "steroids", "previous episodes", "before", "medical problems"],
      reply: "No sugar, no other illness. It happened once last year too, milder.",
      fact: "No diabetes; similar milder episode last year" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful",
      match: ["allergy", "allergic", "allergies", "drug reaction"],
      reply: "No allergies.",
      fact: "No known drug allergies" },
    { id: "habits", group: "social", label: "Alcohol / smoking", importance: "minor",
      match: ["alcohol", "drink", "smoke", "smoking", "tobacco"],
      reply: "I don't smoke. A beer occasionally with friends.",
      fact: "Occasional alcohol" },
    { id: "pets", group: "social", label: "Animal contact", importance: "minor",
      match: ["pets", "pet", "dog", "cat", "animals", "cattle"],
      reply: "No pets.",
      fact: "No animal contact" },
  ],

  exam: [
    { id: "local", group: "local-exam", label: "Skin — trunk, groin & thighs", importance: "essential", abnormal: true,
      match: ["lesion", "lesions", "rash", "rings", "patches", "local examination", "local", "skin", "examine skin", "examine the skin", "groin", "waist", "thighs", "buttocks", "examine the rash", "examine the lesions", "distribution"],
      finding: "Multiple large annular and polycyclic plaques over the waist, lower back, buttocks, both groins and inner thighs. Raised, erythematous, scaly active borders with papules and a few pustules; relative central clearing with hyperpigmentation. Some plaques are ill-defined and eczematised. Scrotum spared.",
      fact: "Polycyclic annular plaques, scaly active edge, central clearing; papulopustules; scrotum spared",
      media: waist(rings(3, 20, [{ morphology: "papule", count: 6, size: 1.4, region: "margins" }]), 21, "Right groin and inner thigh · close-up") },
    { id: "feet", group: "local-exam", label: "Feet & toe webs", importance: "useful", abnormal: true, match: [],
      finding: "Maceration and fine scaling in the 4th toe webs of both feet. Toenails normal.",
      fact: "Interdigital tinea pedis; nails spared" },
    { id: "nails", group: "local-exam", label: "Nails", importance: "minor",
      match: ["nails", "toenails", "fingernails", "nail"],
      finding: "Finger- and toenails normal. No subungual hyperkeratosis or discolouration.",
      fact: "Nails normal" },
    { id: "dermoscopy", group: "local-exam", label: "Dermoscopy", importance: "minor", match: [],
      finding: "Peripheral white scale at the active edge; translucent and broken vellus hairs within the border; dotted vessels.",
      fact: "Peripheral scale; broken translucent hairs" },
    { id: "woods-lamp", group: "local-exam", label: "Wood's lamp", importance: "minor", match: [],
      finding: "No fluorescence.",
      fact: "No fluorescence" },
  ],

  investigations: [
    { id: "koh", priority: "essential",
      report: "10% KOH mount of scrapings from the active edge: abundant long, septate, branching hyaline hyphae.",
      teaching: { whenToOrder: "Every suspected dermatophyte infection, before systemic therapy — from the active scaly edge, ideally after a week off topical steroids.", whatItTellsYou: "Confirms a fungal infection at the bedside in 15 minutes for ₹150." } },
    { id: "fungal-culture", priority: "useful",
      report: "Trichophyton mentagrophytes complex (ITS genotype VIII — T. indotineae) isolated at 3 weeks.",
      teaching: { whenToOrder: "Extensive, recurrent or treatment-resistant dermatophytosis.", whatItTellsYou: "Species — T. indotineae is now dominant in India and often terbinafine-resistant." } },
    { id: "lft", priority: "situational",
      teaching: { whenToOrder: "Baseline before a prolonged (> 4 week) course of systemic antifungals, or with liver disease or alcohol excess.", whatItTellsYou: "Hepatotoxicity risk." } },
    { id: "viral-markers", priority: "situational",
      teaching: { whenToOrder: "Unusually extensive or recalcitrant infection with other risk factors.", whatItTellsYou: "Immunosuppression (HIV)." } },
    { id: "skin-biopsy", priority: "unnecessary",
      teaching: { whenToOrder: "Only if KOH is negative and the diagnosis is uncertain.", whatItTellsYou: "PAS-positive hyphae; excludes mimics." } },
    { id: "cbc", priority: "unnecessary",
      teaching: { whenToOrder: "Not needed for dermatophytosis.", whatItTellsYou: "Nothing that changes management." } },
  ],

  therapeutics: [
    { id: "itraconazole", kind: "drug", drugIds: ["itraconazole"], label: "Systemic itraconazole", appropriateness: "ideal",
      doseRange: { min: 100, max: 400, unit: "mg" } },
    { id: "terbinafine", kind: "drug", drugIds: ["terbinafine"], label: "Systemic terbinafine", appropriateness: "acceptable",
      critique: { what: "Chose terbinafine.", why: "Terbinafine resistance (SQLE mutations in T. indotineae) is now common in India; failure rates are high in extensive disease.", better: "Itraconazole 100 mg BD (or 200 mg OD) with food for 4–6 weeks, continued 2 weeks beyond clinical cure.", severity: "minor" } },
    { id: "fluconazole", kind: "drug", drugIds: ["fluconazole", "griseofulvin"], label: "Fluconazole / griseofulvin", appropriateness: "acceptable",
      critique: { what: "Chose fluconazole or griseofulvin.", why: "Both are less effective than itraconazole for extensive tinea corporis/cruris in India today.", better: "Itraconazole 200 mg daily for 4–6 weeks.", severity: "minor" } },
    { id: "topical-antifungal", kind: "drug", drugIds: ["luliconazole", "sertaconazole", "eberconazole", "clotrimazole", "ketoconazole-topical", "amorolfine"], label: "Topical azole", appropriateness: "ideal" },
    { id: "antihistamine", kind: "drug", drugClasses: ["antihistamine"], label: "Antihistamine for itch", appropriateness: "acceptable" },
    { id: "steroid-fdc", kind: "drug", drugClasses: ["topical-steroid"], label: "Topical steroid / steroid combination", appropriateness: "harmful",
      critique: { what: "Prescribed a steroid or steroid-combination cream.", why: "Steroids suppress local immunity, let the fungus spread and modify its appearance (tinea incognito) — the main driver of India's dermatophytosis epidemic.", better: "Azole antifungal cream alone, plus systemic itraconazole for extensive disease.", severity: "major" } },
    { id: "systemic-steroid", kind: "drug", drugIds: ["prednisolone", "dexamethasone", "methylprednisolone"], label: "Systemic corticosteroid", appropriateness: "harmful",
      critique: { what: "Gave a systemic corticosteroid.", why: "It relieves itch briefly while the infection spreads.", better: "Antihistamine for itch; antifungals for the infection.", severity: "major" } },
    { id: "stop-steroid", kind: "counsel", label: "Stop the steroid combination cream", appropriateness: "ideal",
      concernsDrugs: ["topical-steroid", "steroid-fdc"],
      match: ["stop panderm", "stop the panderm", "stop the cream", "stop steroid", "stop the steroid", "no steroid", "avoid steroid", "avoid steroids", "stop using the cream", "throw the cream", "stop that cream"],
      response: [{ role: "patient", kind: "speech", text: "But it gives relief… okay, doctor. If it's making it worse, I'll stop." }],
      praise: "Stopped the steroid combination cream and explained why." },
    { id: "contacts", kind: "counsel", label: "Treat household contacts", appropriateness: "ideal",
      match: ["treat wife", "treat your wife", "treat the wife", "family members", "treat family", "treat the family", "treat contacts", "household contacts", "brother also", "wife also", "bring your wife", "examine family", "everyone at home"],
      response: [{ role: "patient", kind: "speech", text: "I'll bring my wife and brother tomorrow." }],
      praise: "Treated the household — untreated contacts are the commonest cause of reinfection." },
    { id: "hygiene", kind: "counsel", label: "Clothing & hygiene", appropriateness: "ideal",
      match: ["loose cotton", "cotton clothes", "cotton underwear", "loose clothes", "dont share towels", "do not share towels", "separate towels", "wash clothes", "hot water", "iron", "dry properly", "dry the area", "bathe twice", "keep dry", "hygiene", "avoid tight", "no jeans", "sun dry"],
      response: [{ role: "patient", kind: "speech", text: "Okay — cotton, separate towels, and I'll iron the innerwear." }],
      praise: "Gave practical hygiene and laundry advice." },
    { id: "feet-counsel", kind: "counsel", label: "Treat the feet", appropriateness: "acceptable",
      match: ["dusting powder", "antifungal powder", "toe webs", "between the toes", "open footwear", "change socks", "treat the feet", "socks"],
      response: [{ role: "patient", kind: "speech", text: "I'll change socks at lunch and use the powder." }],
      praise: "Treated the foot reservoir." },
    { id: "duration", kind: "counsel", label: "Complete the course", appropriateness: "acceptable",
      match: ["complete the course", "full course", "two weeks after", "2 weeks after", "even after it clears", "dont stop early", "do not stop early", "continue till"],
      response: [{ role: "patient", kind: "speech", text: "So I continue even after it looks clear." }] },
  ],
  hazards: [],

  followUp: [
    { when: "ideal", status: "improving",
      lines: [
        { role: "system", kind: "finding", text: "Clinical photograph at follow-up.", media: waist([{ morphology: "hyperpigment", count: 9, size: 9, region: "central" }], 9, "Left flank · follow-up") },
        { role: "patient", kind: "speech", text: "The itching is almost gone, doctor. The rings have faded — just dark marks now. My wife and brother are on the cream too." },
      ],
      facts: [{ group: "local-exam", label: "Follow-up", value: "Active borders resolved; post-inflammatory hyperpigmentation" }] },
    { when: "acceptable", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "Better, but new small rings keep coming on my thighs." }] },
    { when: "harmful", status: "deteriorating",
      lines: [
        { role: "system", kind: "finding", text: "Clinical photograph at follow-up.", media: waist(rings(4, 26, [{ morphology: "pustule", count: 8, size: 1.6 }]), 13, "Trunk · follow-up") },
        { role: "patient", kind: "speech", text: "It's spread to my chest and arms now, doctor. The cream helps for a day and then it's worse." },
      ] },
    { when: "untreated", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "Still the same. Maybe bigger." }] },
  ],

  truth: {
    diagnosis: "Tinea corporis et cruris (dermatophytosis)",
    qualifier: "Extensive and steroid-modified, with interdigital tinea pedis and affected household contacts",
    reasoning: [
      { stage: "History", text: "Three months of intensely itchy, expanding rings from the groin to the waist, buttocks and thighs; transient relief then worsening with an OTC steroid–antifungal combination; wife and brother affected; tight jeans, shared towels, sweaty field work." },
      { stage: "Examination", text: "Polycyclic annular plaques with scaly active borders and central clearing, papulopustules within; scrotum spared; macerated toe webs." },
      { stage: "Investigation", text: "KOH mount: abundant septate branching hyphae. Culture (3 weeks): T. mentagrophytes ITS genotype VIII (T. indotineae)." },
      { stage: "Diagnosis", text: "Extensive, steroid-modified tinea corporis et cruris with tinea pedis." },
    ],
  },

  rubric: {
    diagnosisAccept: ["tinea corporis", "tinea cruris", "tinea corporis et cruris", "dermatophytosis", "dermatophyte infection", "ringworm", "tinea incognito", "steroid modified tinea", "tinea"],
    diagnosisPartial: ["fungal infection", "superficial fungal infection", "fungal", "intertrigo", "tinea pedis"],
    differentials: ["nummular eczema", "discoid eczema", "psoriasis", "annular psoriasis", "granuloma annulare", "pityriasis rosea", "erythema annulare centrifugum", "contact dermatitis", "seborrhoeic dermatitis", "candidiasis", "erythrasma", "hansen", "leprosy", "subacute cutaneous lupus"],
    idealTreatment: [["itraconazole", "terbinafine", "fluconazole"], ["topical-antifungal"], ["stop-steroid"], ["contacts"], ["hygiene"]],
    expertActionCount: 16,
    followUpDays: { min: 14, max: 42 },
    expectsReassessment: false,
    weights: { history: 20, examination: 15, differential: 12, investigationSelection: 10, investigationInterpretation: 8, treatment: 18, drugSafety: 10, reassessment: 3, efficiency: 2, outcome: 2 },
    misses: {
      creams: { what: "Did not ask what he had been applying.", why: "Two months of a steroid–antifungal–antibiotic combination explains the relapse, the spread and the atypical look.", better: "Always ask about chemist creams — and ask to see the tube.", severity: "major" },
      family: { what: "Did not ask about household contacts.", why: "His wife and brother are infected; treating him alone guarantees reinfection.", better: "Ask who else at home itches, and treat everyone together.", severity: "major" },
      clothing: { what: "Did not explore clothing and hygiene.", why: "Tight jeans, synthetic innerwear, shared towels and sweat maintain the infection.", better: "Ask about clothing, towels, laundry and bathing.", severity: "moderate" },
      local: { what: "Did not examine the lesions systematically.", why: "The active scaly edge, central clearing and spared scrotum are the clinical signature; extent decides systemic therapy.", better: "Examine all folds and the trunk; map extent; look at the feet and nails.", severity: "major" },
      koh: { what: "Did not confirm with a KOH mount.", why: "A ₹150, 15-minute bedside test confirms the diagnosis before weeks of systemic therapy.", better: "KOH from the active edge in every suspected dermatophytosis.", severity: "moderate" },
      itraconazole: { what: "No systemic antifungal.", why: "With multiple sites and steroid modification, topical therapy alone fails.", better: "Itraconazole 100 mg BD (or 200 mg OD) after food for 4–6 weeks, continued 2 weeks beyond clinical cure.", severity: "major" },
      "topical-antifungal": { what: "No topical antifungal.", why: "Topical azoles reduce fungal load at the surface and speed cure.", better: "Luliconazole 1% once daily, 2 cm beyond the edge, for 4–6 weeks.", severity: "moderate" },
      "stop-steroid": { what: "The steroid combination cream was not stopped.", why: "Continuing it keeps the infection going whatever else you prescribe.", better: "Stop it explicitly; warn about a short flare of itch.", severity: "major" },
      contacts: { what: "Household contacts not treated.", why: "Reinfection from family members is the commonest reason for 'recurrence'.", better: "Examine and treat all symptomatic household members at the same time.", severity: "major" },
      hygiene: { what: "No hygiene or laundry advice.", why: "Fomites — towels, innerwear, bedding — re-seed the skin.", better: "Loose cotton clothing, separate towels, hot-wash and iron innerwear, dry the folds thoroughly.", severity: "moderate" },
    },
    strengths: {
      creams: "Uncovered the over-the-counter steroid combination cream.",
      family: "Found the infected household contacts.",
      clothing: "Explored clothing, towels and hygiene.",
      feet: "Looked for the foot reservoir.",
      koh: "Confirmed the diagnosis with a KOH mount.",
      "fungal-culture": "Sent a culture in extensive, recurrent disease.",
      itraconazole: "Chose itraconazole — the most reliable systemic agent against Indian dermatophytes today.",
    },
  },

  teaching: {
    patientBand: "extensive",
    severityBands: [
      { id: "localised", label: "Localised", media: waist(rings(1, 18), 41, "Localised"),
        recognition: ["One site, a few plaques", "No previous steroid use"],
        investigation: ["KOH mount"],
        treatment: ["Topical azole (luliconazole) once daily, 2 cm beyond the edge, 4 weeks", "Hygiene measures"],
        followUp: ["2–4 weeks; continue 2 weeks after clearance"] },
      { id: "extensive", label: "Extensive / multi-site", media: waist(rings(3, 20, [{ morphology: "papule", count: 6, size: 1.4, region: "margins" }]), 42, "Extensive"),
        recognition: ["Several sites — groin, waist, buttocks, thighs", "Large polycyclic plaques"],
        investigation: ["KOH; culture if recurrent", "LFT if long course planned"],
        treatment: ["Itraconazole 200 mg/day + topical azole", "Treat household contacts and the feet", "Laundry and clothing measures"],
        followUp: ["2-weekly until 2 weeks beyond clinical cure (usually 4–8 weeks)"] },
      { id: "steroid-modified", label: "Recalcitrant / steroid-modified", media: waist(rings(4, 22, [{ morphology: "pustule", count: 8, size: 1.6 }]), 43, "Steroid-modified"),
        recognition: ["Bizarre, ill-defined, papulopustular plaques", "Repeated relapses after steroid creams"],
        investigation: ["KOH, culture ± antifungal susceptibility", "Look for immunosuppression if unusually severe"],
        treatment: ["Stop steroids", "Itraconazole for longer (6–8 weeks or more), adequate dose with food", "Combine topical azole"],
        followUp: ["Every 2–3 weeks; check adherence and contacts"] },
      { id: "complicated", label: "Complicated",
        recognition: ["Majocchi granuloma (follicular papules/nodules)", "Kerion (boggy scalp plaque)", "Nail involvement (onychomycosis)"],
        investigation: ["Biopsy for Majocchi", "Nail clipping KOH/culture"],
        treatment: ["Longer systemic therapy (nails: 3–6 months)"],
        followUp: ["Monthly"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Itraconazole", brand: "Itaspor", dose: "100 mg twice daily (or 200 mg once daily)", route: "PO", frequency: "With food or an acidic drink", duration: "4–6 weeks; 2 weeks beyond clinical cure",
        indication: "Extensive, recurrent or steroid-modified dermatophytosis",
        mechanism: "Inhibits fungal lanosterol 14α-demethylase → no ergosterol → leaky, failing fungal cell membrane.",
        whyItWorks: "Concentrates in skin and sebum and stays there for weeks; remains active against most Indian T. indotineae strains.",
        avoidWhen: ["Heart failure", "Liver disease", "Interacting drugs (statins, some antiarrhythmics, benzodiazepines)", "Pregnancy"],
        adverseEffects: ["GI upset, headache", "Raised transaminases (rare)", "Oedema"],
        monitoring: ["LFT if > 4 weeks or risk factors", "Absorption: take with a full meal"] },
      { generic: "Luliconazole 1% cream", brand: "Lulifin", dose: "Thin layer extending 2 cm beyond the edge", route: "TOP", frequency: "Once daily", duration: "4–6 weeks",
        indication: "Topical therapy for dermatophytosis",
        mechanism: "Azole — blocks ergosterol synthesis in the fungal membrane → fungal death.",
        whyItWorks: "High potency against dermatophytes at the skin surface with once-daily use.",
        avoidWhen: ["Known azole allergy"],
        adverseEffects: ["Mild irritation"],
        monitoring: ["Clinical response at 2 weeks"] },
      { generic: "Levocetirizine", brand: "Levocet", dose: "5 mg", route: "PO", frequency: "Once at night", duration: "2–3 weeks",
        indication: "Symptomatic relief of itch",
        mechanism: "Blocks H1 histamine receptors → less itch signalling.",
        whyItWorks: "Breaks the itch–scratch cycle while antifungals clear the infection.",
        avoidWhen: ["Severe renal impairment"],
        adverseEffects: ["Drowsiness (mild)", "Dry mouth"],
        monitoring: ["None"] },
    ],
    routines: [
      { label: "Daily skin routine",
        steps: [
          { order: 1, step: "Bathe twice a day", note: "After field work too; use a separate towel" },
          { order: 2, step: "Dry thoroughly", where: "Groin, under the belt, buttock cleft, between the toes", note: "Pat dry; a hair dryer on cool works for folds" },
          { order: 3, step: "Antifungal cream", product: "Luliconazole 1%", howMuch: "Thin layer", where: "Every patch plus 2 cm of normal-looking skin around it" },
          { order: 4, step: "Dusting powder", where: "Folds and feet", note: "Change socks at lunch; open footwear when possible" },
          { order: 5, step: "Loose cotton clothes", note: "No jeans until healed; cotton innerwear" },
        ],
        avoid: ["Steroid or 'combination' creams", "Sharing towels, bedding or clothes", "Stopping when the itch goes"],
        improvementTimeline: "Itch eases in 1–2 weeks; rings fade by 3–4 weeks; dark marks take months." },
      { label: "Laundry & household",
        steps: [
          { order: 1, step: "Wash clothes, towels and bedsheets in hot water" },
          { order: 2, step: "Dry in the sun, then iron innerwear" },
          { order: 3, step: "Treat every itchy family member at the same time" },
        ] },
    ],
    followUp: {
      interval: "2 weeks, then every 2–3 weeks until 2 weeks beyond clinical cure",
      reassess: ["Active borders and new lesions", "Itch", "Adherence (dose with food, topical extent)", "Household contacts", "Culture result"],
      redFlags: ["New lesions despite 4 weeks of adherent itraconazole", "Nail or scalp involvement", "Jaundice or dark urine on systemic antifungals"],
      whenToEscalate: ["Failure at 4–6 weeks → check adherence, absorption, contacts; culture and susceptibility", "Consider longer duration or higher-dose itraconazole under specialist supervision", "Unusually extensive disease → screen for immunosuppression"],
    },
    treatmentFailure: { steps: [
      "Check adherence — itraconazole taken with food, every day, for long enough?",
      "Check the diagnosis — KOH; eczema and psoriasis mimic tinea",
      "Check reservoirs — feet, nails, groin, household contacts, towels",
      "Check aggravators — steroid creams, occlusive clothing, sweating",
      "Alternative — extend itraconazole; culture with susceptibility",
      "Escalate — specialist care for resistant T. indotineae",
    ] },
    pearl: "In India today, a ring that keeps coming back is rarely just “resistant fungus.” Look for the steroid cream, the itching wife, the sweaty jeans and the toe webs — treat the person, the household and the reservoir, and continue for two weeks after the skin looks clear.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "Another steroid combination cream — or an oral steroid for the itch — would have relieved symptoms for days and spread the infection for months, producing a bizarre steroid-modified tinea that is far harder to clear.",
      sequence: ["Stop all steroid-containing creams", "Confirm with KOH", "Itraconazole + topical azole for long enough", "Treat contacts, feet and fomites"],
    },
  },
};
