import type { ClinicalCaseDefinition } from "../case-definition";
import { photo } from "./media";
import type { DermLesionLayer, MediaAsset } from "../types";

const melasma = (size: number, confluence: number, extra = 0): DermLesionLayer[] => [
  { morphology: "patch", count: 2, size, confluence, region: "central" },
  ...(extra ? [{ morphology: "hyperpigment" as const, count: extra, size: 6, region: "central" as const }] : []),
];
const cheek = (lesions: DermLesionLayer[], seed: number, caption: string): MediaAsset =>
  photo({ site: "cheek", phototype: 4, lesions, seed }, "Close-up clinical photograph of the cheek.", caption);

export const dermMelasma: ClinicalCaseDefinition = {
  id: "derm-melasma-01",
  specialty: "Dermatology",
  track: "opd",
  level: "district",
  setting: "OPD",
  weight: 6,
  difficulty: 2,
  patient: { name: "Priya", age: 34, sex: "Female", city: "Dwarka, Delhi", occupation: "Schoolteacher", context: "Dermatology OPD" },
  arrivalMinuteOfDay: 10 * 60 + 10,
  briefing: "A 34-year-old teacher is waiting in Dermatology OPD, room 2, holding a tube of cream.",
  opening: [
    { role: "system", kind: "finding", text: "Clinical photograph taken by the OPD nurse.", media: cheek(melasma(40, 0.7, 5), 5, "Right cheek · at presentation") },
    { role: "patient", kind: "speech", text: "Doctor, these dark marks on my cheeks have been there for months. They keep getting darker." },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "118/76" },
    hr: { key: "hr", value: "74" },
    weight: { key: "weight", value: "61" },
    height: { key: "height", value: "160" },
    bmi: { key: "bmi", value: "23.8" },
  },
  profile: { currentDrugs: ["ocp"] },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential",
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened"],
      reply: "These dark patches on both my cheeks, doctor. Everyone at school has started asking about them.",
      fact: "Dark patches on both cheeks" },
    { id: "onset", group: "hpi", label: "Onset & course", importance: "essential",
      match: ["how long", "since when", "when did", "duration", "start", "started", "onset", "tell me about", "tell me more", "progression", "getting darker", "first noticed", "patches", "marks"],
      reply: "About eight or nine months. It started as light brown on the cheeks, and after this summer it became much darker and spread to my upper lip and forehead a little.",
      fact: "8–9 months; darkened after summer; cheeks → upper lip, forehead" },
    { id: "symptoms", group: "hpi", label: "Itch / redness", importance: "useful",
      match: ["itch", "itching", "itchy", "burning", "pain", "red", "redness", "rash", "scaly", "irritation"],
      reply: "No itching, no pain. They're just dark.",
      fact: "Asymptomatic" },
    { id: "sun", group: "social", label: "Sun exposure", importance: "essential", abnormal: true,
      match: ["sun", "sunlight", "outdoors", "outside", "travel", "commute", "scooty", "scooter", "two wheeler", "sunscreen", "sun exposure", "how do you travel"],
      reply: "I ride my scooty to school — about forty minutes each way — and I do bus duty in the afternoon. I don't use sunscreen. I just cover with my dupatta sometimes.",
      fact: "~1.5 h daily sun exposure on a two-wheeler; no sunscreen" },
    { id: "hormones", group: "medication", label: "Medications & OCP", importance: "essential", abnormal: true,
      match: ["medicines", "medicine", "medication", "tablets", "taking any", "contraception", "contraceptive", "pills", "ocp", "birth control", "family planning", "hormones", "hormone", "drugs"],
      reply: "I take the pill — Ovral L — for the last year, since my second baby. Nothing else regularly.",
      fact: "Combined OCP (Ovral L) × 1 year" },
    { id: "pregnancy", group: "obstetric", label: "Pregnancies & periods", importance: "useful",
      match: ["pregnancy", "pregnant", "pregnancies", "children", "kids", "delivery", "periods", "period", "menstrual", "lmp", "cycles", "regular"],
      reply: "Two children — the younger one is two now. The marks started a few months after I began the pill. My periods are regular.",
      fact: "G2P2; marks began months after starting OCP; regular cycles" },
    { id: "cosmetics", group: "social", label: "Creams & cosmetics", importance: "essential",
      match: ["cream", "creams", "applying", "apply", "using", "face wash", "cosmetics", "makeup", "parlour", "parlor", "bleach", "facial", "home remedies", "remedies", "what have you used", "fairness", "products", "tried", "treatment"],
      reply: "A fairness cream from the market for a few months, and I get a facial and bleach at the parlour every month. Nothing from a doctor.",
      fact: "Cosmetic fairness cream; monthly parlour bleach/facials; no medicated creams" },
    { id: "family", group: "family", label: "Family history", importance: "essential", abnormal: true,
      match: ["family", "mother", "father", "sister", "siblings", "anyone else", "parents", "runs in", "clot", "clots", "thrombosis"],
      reply: "My mother had the same marks. And — I don't know if it matters — she had a blood clot in her leg after her uterus operation a few years ago.",
      fact: "Mother: melasma; DVT after hysterectomy" },
    { id: "clots", group: "past", label: "Past history (clots, migraine)", importance: "useful",
      match: ["past", "medical history", "illness", "thyroid", "diabetes", "bp", "migraine", "headache", "clot in your leg", "leg swelling", "stroke", "comorbidities", "any disease", "medical problems"],
      reply: "No illnesses. No clots myself. I get ordinary headaches sometimes, nothing with flashing lights.",
      fact: "No personal VTE; no migraine with aura" },
    { id: "thyroid", group: "systemic", label: "Thyroid symptoms", importance: "minor",
      match: ["weight change", "tired", "tiredness", "cold intolerance", "hair fall", "constipation", "palpitations"],
      reply: "No, I'm fine otherwise.",
      fact: "No thyroid symptoms" },
    { id: "heat", group: "social", label: "Heat exposure", importance: "minor",
      match: ["heat", "kitchen", "stove", "cooking", "tandoor"],
      reply: "I cook for the family morning and evening, over the gas stove.",
      fact: "Daily cooking over gas stove" },
    { id: "impact", group: "social", label: "Psychosocial impact", importance: "useful",
      match: ["affect", "affecting", "how do you feel about", "mood", "confidence", "upset", "bothering you", "embarrassed"],
      reply: "I've stopped going to family functions without heavy makeup. It bothers me a lot, doctor.",
      fact: "Significant distress" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful",
      match: ["allergy", "allergic", "allergies", "drug reaction"],
      reply: "No allergies.",
      fact: "No known drug allergies" },
  ],

  exam: [
    { id: "local", group: "local-exam", label: "Face", importance: "essential", abnormal: true,
      match: ["face", "examine the face", "local examination", "local", "lesion", "lesions", "patches", "pigmentation", "cheeks", "skin", "examine skin", "examine the skin", "look at the face", "distribution", "morphology"],
      finding: "Symmetrical, irregular, light-to-dark brown macules coalescing into patches over both malar areas, the nasal bridge, upper lip and a small area of the central forehead. Borders irregular and geographic. No erythema, scaling, atrophy or telangiectasia. Remaining skin normal.",
      fact: "Symmetric brown malar, nasal, upper-lip patches; no erythema or atrophy",
      media: cheek(melasma(36, 0.75, 6), 17, "Left cheek · close-up") },
    { id: "woods-lamp", group: "local-exam", label: "Wood's lamp", importance: "useful", match: [],
      finding: "Pigmentation is accentuated over parts of the cheeks and upper lip but not over the nasal bridge and lateral cheeks.",
      fact: "Partial accentuation under Wood's light" },
    { id: "dermoscopy", group: "local-exam", label: "Dermoscopy", importance: "useful", match: [],
      finding: "Light-brown pseudo-reticular network with darker brown granules and globules; perifollicular sparing; no arborising vessels or scale.",
      fact: "Pseudo-reticular network; perifollicular sparing" },
    { id: "legs", group: "general-exam", label: "Legs", importance: "minor",
      match: ["legs", "calf", "calves", "leg swelling", "varicose", "dvt", "homans"],
      finding: "No calf tenderness, swelling or varicosities.",
      fact: "Legs normal" },
  ],

  investigations: [
    { id: "tft", priority: "situational",
      teaching: { whenToOrder: "If there are thyroid symptoms; autoimmune thyroid disease is commoner in women with melasma.", whatItTellsYou: "Thyroid status." } },
    { id: "cbc", priority: "situational",
      teaching: { whenToOrder: "Before oral tranexamic acid, along with a clotting-risk history.", whatItTellsYou: "Baseline blood count." } },
    { id: "coag", priority: "situational",
      teaching: { whenToOrder: "Rarely needed — a careful thrombosis history matters more before tranexamic acid.", whatItTellsYou: "Clotting profile." } },
    { id: "upt", priority: "situational",
      teaching: { whenToOrder: "Before hydroquinone or tretinoin if pregnancy is possible (avoid in pregnancy).", whatItTellsYou: "Pregnancy status." } },
    { id: "skin-biopsy", priority: "unnecessary",
      teaching: { whenToOrder: "Only if the diagnosis is uncertain (lichen planus pigmentosus, drug-induced or exogenous ochronosis).", whatItTellsYou: "Pigment depth and pattern — not needed for classic melasma." } },
    { id: "hormonal-profile", priority: "unnecessary",
      teaching: { whenToOrder: "Not indicated in melasma without features of hyperandrogenism.", whatItTellsYou: "Nothing that changes melasma treatment here." } },
    { id: "venous-doppler", name: "Lower-limb venous Doppler", short: "Venous Doppler", category: "imaging",
      match: ["venous doppler", "venous duplex", "doppler of the leg", "leg veins", "compression ultrasound", "dvt scan", "doppler leg veins"],
      turnaroundMin: 40, cost: 2500, priority: "unnecessary",
      report: "Deep veins of both lower limbs fully compressible with normal phasic flow.",
      teaching: { whenToOrder: "Suspected deep vein thrombosis — a swollen, tender calf.", whatItTellsYou: "Non-compressible veins with thrombus." } },
    { id: "ctpa", name: "CT pulmonary angiography", short: "CTPA", category: "imaging",
      match: ["ctpa", "ct pulmonary angiography", "ct pulmonary angiogram", "ct angiography chest", "pe protocol"],
      turnaroundMin: 60, cost: 7500, priority: "unnecessary",
      report: "No filling defects in the pulmonary arteries.",
      teaching: { whenToOrder: "Suspected pulmonary embolism.", whatItTellsYou: "Filling defects in the pulmonary arteries." } },
  ],

  therapeutics: [
    { id: "sunscreen", kind: "drug", drugIds: ["sunscreen"], label: "Broad-spectrum tinted sunscreen", appropriateness: "ideal",
      praise: "Made sunscreen the core of treatment — melasma is a disease of light." },
    { id: "hydroquinone", kind: "drug", drugIds: ["hydroquinone"], label: "Hydroquinone", appropriateness: "ideal" },
    { id: "tcc", kind: "drug", drugIds: ["triple-combination"], label: "Triple combination cream (short, supervised course)", appropriateness: "acceptable",
      critique: { what: "Chose a steroid-containing triple combination cream.", why: "It works quickly but contains a corticosteroid; beyond 8–12 weeks it causes atrophy, telangiectasia and steroid dependence — the commonest harm in Indian melasma practice.", better: "Use it only as a time-limited, supervised course (≤ 8 weeks), then maintain with hydroquinone pauses or azelaic acid.", severity: "minor" } },
    { id: "azelaic", kind: "drug", drugIds: ["azelaic-acid", "kojic-acid"], label: "Azelaic or kojic acid", appropriateness: "acceptable" },
    { id: "moisturiser", kind: "drug", drugIds: ["moisturiser", "cleanser"], label: "Gentle cleanser & moisturiser", appropriateness: "acceptable" },
    { id: "txa", kind: "drug", drugIds: ["tranexamic-acid"], label: "Oral tranexamic acid", appropriateness: "dangerous", arms: "vte",
      critique: { what: "Prescribed oral tranexamic acid.", why: "She takes a combined oral contraceptive and her mother had a DVT. Tranexamic acid is antifibrinolytic; with oestrogen and a family history, the thrombosis risk is unacceptable.", better: "Avoid tranexamic acid here. If melasma is refractory, discuss stopping the OCP (with her gynaecologist) before considering it — and only after a full thrombosis-risk history.", severity: "major" } },
    { id: "topical-steroid", kind: "drug", drugClasses: ["topical-steroid"], label: "Topical corticosteroid", appropriateness: "harmful",
      critique: { what: "Prescribed a topical steroid for pigmentation.", why: "Steroids do not treat melasma; on the face they cause atrophy, telangiectasia and steroid rosacea.", better: "Photoprotection plus hydroquinone, azelaic acid or a short supervised triple-combination course.", severity: "major" } },
    { id: "glutathione", kind: "procedure", label: "Glutathione / skin-lightening injections", appropriateness: "harmful",
      match: ["glutathione", "skin lightening injection", "whitening injection", "iv glutathione"],
      note: "Administered as ordered.",
      critique: { what: "Ordered glutathione 'skin-lightening' injections.", why: "There is no good evidence of benefit, and IV glutathione has caused serious adverse events; regulators have warned against it.", better: "Evidence-based topical therapy with strict photoprotection.", severity: "major" } },
    { id: "peel-laser", kind: "procedure", label: "Chemical peel / laser", appropriateness: "unnecessary",
      match: ["chemical peel", "peel", "glycolic peel", "laser", "q switched", "q-switched", "toning"],
      note: "Procedure performed.",
      critique: { what: "Booked a peel or laser at the first visit.", why: "Procedures in Fitzpatrick IV skin risk post-inflammatory hyperpigmentation and rebound; they are second-line after 3 months of topical therapy and photoprotection.", better: "Start with photoprotection + a topical agent; consider superficial peels later as adjuncts.", severity: "minor" } },
    { id: "photoprotection", kind: "counsel", label: "Sun & heat protection", appropriateness: "ideal",
      match: ["avoid sun", "sun protection", "umbrella", "hat", "cover the face", "cover your face", "photoprotection", "avoid sunlight", "full face helmet", "scarf", "avoid heat", "reapply sunscreen", "reapply"],
      response: [{ role: "patient", kind: "speech", text: "I'll wear a full-face helmet on the scooty and reapply at lunch." }],
      praise: "Gave practical photoprotection advice — helmet, reapplication, visible light." },
    { id: "stop-cosmetics", kind: "counsel", label: "Stop fairness creams & parlour bleach", appropriateness: "acceptable",
      match: ["stop the fairness cream", "stop fairness cream", "avoid fairness cream", "no bleach", "avoid bleach", "stop bleach", "avoid parlour", "stop facials", "avoid facials"],
      response: [{ role: "patient", kind: "speech", text: "Okay — no more bleach or that cream." }] },
    { id: "ocp-review", kind: "counsel", label: "Review contraception with gynaecology", appropriateness: "acceptable",
      match: ["stop the pill", "stop ocp", "stop the ocp", "change contraception", "alternative contraception", "copper t", "iucd", "gynaecologist", "gynecologist", "review the pill", "discuss contraception"],
      concernsDrugs: ["ocp"],
      response: [{ role: "patient", kind: "speech", text: "I didn't know the pill could cause this. I'll talk to my gynaecologist about a copper-T." }],
      praise: "Identified the OCP as a trigger and arranged a contraception review." },
    { id: "expectations", kind: "counsel", label: "Expectations & relapse", appropriateness: "acceptable",
      match: ["takes time", "will take time", "chronic", "relapse", "recur", "come back", "maintenance", "months to improve", "patience"],
      response: [{ role: "patient", kind: "speech", text: "So it's something I'll have to keep managing, especially in summer." }] },
  ],

  hazards: [
    { id: "vte", label: "Venous thromboembolism on tranexamic acid + OCP",
      prescribedOnsetMin: 16 * 1440,
      stages: [
        { afterMin: 0, status: "guarded", setting: "OPD", interrupts: true,
          vitals: [{ key: "hr", value: "96" }, { key: "temp", value: "99.2" }],
          observation: { role: "patient", text: "Doctor, I came early — my left calf has been swollen and painful for three days. It hurts when I walk." },
          examFindings: { legs: "Left calf 3 cm larger than the right, tender along the deep veins, warm. Pitting oedema to mid-shin." },
          investigations: {
            "venous-doppler": { report: "Non-compressible left popliteal and superficial femoral veins with echogenic thrombus; absent flow augmentation." },
            "d-dimer": { rows: [{ analyte: "D-dimer", value: "3.8", unit: "µg/mL FEU", reference: "< 0.5", flag: "critical" }] },
          },
          patientSays: "My leg is heavy and painful." },
        { afterMin: 4 * 1440, status: "critical", setting: "ER", interrupts: true,
          vitals: [{ key: "hr", value: "124" }, { key: "rr", value: "28" }, { key: "spo2", value: "89" }, { key: "bp", value: "104/70" }],
          observation: { role: "attendant", text: "Doctor, she suddenly became very breathless at home and had chest pain when breathing in." },
          examFindings: { rs: "Tachypnoeic. Air entry equal; no crackles.", general: "Anxious, breathless at rest, cool peripheries." },
          investigations: {
            ctpa: { report: "Filling defects in the right lower lobe and left lingular segmental pulmonary arteries. RV/LV ratio 1.1." },
            ecg: { media: { spec: { kind: "ecg", rate: 124, rhythm: "sinus", morphology: { t: { V1: -1, V2: -1, V3: -0.6, III: -0.8 } } }, alt: "Twelve-lead ECG at 124 per minute.", caption: "12-lead · 25 mm/s · 10 mm/mV" }, report: "Rate 124/min. QRS 96 ms. T-wave inversion V1–V3 and III." },
          },
          patientSays: "I can't breathe properly… it hurts to take a breath." },
        { afterMin: 4 * 1440 + 240, status: "deceased",
          vitals: [{ key: "hr", value: "0" }, { key: "bp", value: "0/0" }, { key: "spo2", value: "0" }],
          observation: { role: "nurse", text: "Sudden collapse — pulseless electrical activity. No return of circulation." } },
      ],
      rescue: [["drug:enoxaparin", "drug:heparin", "drug:apixaban", "drug:rivaroxaban"]],
      fullRecoveryWindowMin: 3 * 1440,
      lastRescueMin: 4 * 1440 + 200,
      recovery: [
        { afterMin: 2880, status: "improving", vitals: [{ key: "hr", value: "84" }, { key: "spo2", value: "97" }], examFindings: { legs: "Calf swelling reducing; less tender." }, patientSays: "The leg is better. I've stopped the pill and the tablets." },
      ],
      review: {
        cause: "Oral tranexamic acid was added in a woman on a combined oral contraceptive with a first-degree relative with DVT.",
        whyItCausedHarm: "Oestrogen raises clotting factors; tranexamic acid blocks plasmin-mediated clot breakdown. Together with an inherited tendency, a calf DVT formed and embolised to the lungs.",
        earliestRescueWindow: "At the prescription: ask about the pill, personal and family clots, and migraine with aura before any tranexamic acid.",
        correctRescueSequence: [
          "Stop tranexamic acid and the oestrogen pill",
          "Confirm DVT with compression Doppler (and D-dimer)",
          "Start anticoagulation — LMWH (enoxaparin 1 mg/kg SC 12-hourly) or a DOAC (apixaban / rivaroxaban)",
          "Breathlessness or pleuritic pain: CTPA; risk-stratify PE (RV strain, troponin); oxygen",
          "Arrange non-oestrogen contraception; anticoagulate ≥ 3 months",
        ],
        lastRealisticRescueWindow: "Before the clot embolises — the days of calf pain. Once massive PE occurs, the window is hours.",
      } },
  ],

  followUp: [
    { when: "ideal", status: "improving",
      lines: [
        { role: "system", kind: "finding", text: "Clinical photograph at follow-up.", media: cheek(melasma(30, 0.45, 3), 5, "Right cheek · follow-up") },
        { role: "patient", kind: "speech", text: "They're lighter, doctor — my husband noticed. I wear the helmet and use the sunscreen every day, even indoors. The cream stung a little for the first week." },
      ],
      facts: [{ group: "local-exam", label: "Follow-up", value: "Patches lighter and smaller (~40% better)" }] },
    { when: "acceptable", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "Maybe slightly lighter. Honestly I forget the sunscreen on busy days." }] },
    { when: "harmful", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "My face has become red and the skin feels thin, doctor. And the patches came back darker when I stopped." }] },
    { when: "untreated", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "No change — if anything, darker. It's been very sunny." }] },
  ],

  truth: {
    diagnosis: "Melasma",
    qualifier: "Centrofacial–malar pattern, mixed (epidermal + dermal) type — triggered by UV/visible light and a combined oral contraceptive, with a family history",
    reasoning: [
      { stage: "History", text: "Symmetric facial darkening for 8–9 months, worse after summer; daily two-wheeler sun exposure without sunscreen; began months after starting the OCP; mother affected. Asymptomatic." },
      { stage: "Examination", text: "Symmetric irregular brown patches on malar areas, nasal bridge and upper lip; no erythema, scale or atrophy. Wood's lamp: partial accentuation. Dermoscopy: pseudo-reticular network with perifollicular sparing." },
      { stage: "Investigation", text: "None required — the diagnosis is clinical. A thrombosis history matters more than any test before considering tranexamic acid." },
      { stage: "Diagnosis", text: "Mixed-type centrofacial–malar melasma." },
    ],
  },

  rubric: {
    diagnosisAccept: ["melasma", "chloasma", "mixed melasma", "malar melasma", "centrofacial melasma", "epidermal melasma"],
    diagnosisPartial: ["hyperpigmentation", "facial hyperpigmentation", "pigmentation", "post inflammatory hyperpigmentation", "pih", "solar lentigines", "freckles"],
    differentials: ["post inflammatory hyperpigmentation", "pih", "acquired dermal macular hyperpigmentation", "lichen planus pigmentosus", "riehl", "pigmented contact dermatitis", "exogenous ochronosis", "hori", "nevus of hori", "drug induced pigmentation", "solar lentigines", "freckles", "ephelides", "photo contact dermatitis"],
    idealTreatment: [["sunscreen"], ["photoprotection"], ["hydroquinone", "tcc", "azelaic"]],
    expertActionCount: 14,
    followUpDays: { min: 28, max: 90 },
    expectsReassessment: false,
    weights: { history: 22, examination: 13, differential: 15, investigationSelection: 10, investigationInterpretation: 5, treatment: 15, drugSafety: 10, reassessment: 5, efficiency: 2, outcome: 3 },
    misses: {
      sun: { what: "Did not ask about sun exposure.", why: "UV and visible light drive melasma; a daily scooter commute without protection explains both the onset and the summer flare.", better: "Ask how they travel and work outdoors, and whether they use sunscreen.", severity: "major" },
      hormones: { what: "Did not ask about the contraceptive pill.", why: "Combined OCPs trigger melasma — and they make oral tranexamic acid dangerous.", better: "Ask every woman with melasma about pills, pregnancy and hormonal treatment.", severity: "major" },
      family: { what: "Did not take a family history.", why: "Her mother had melasma (genetic predisposition) and a DVT — the second fact is a contraindication to tranexamic acid.", better: "Ask about similar pigmentation and about clots in the family.", severity: "moderate" },
      cosmetics: { what: "Did not ask what she was applying.", why: "Fairness creams, parlour bleach and unsupervised steroid combinations are common aggravators in India.", better: "Ask about every cream, bleach and parlour procedure.", severity: "moderate" },
      local: { what: "Did not examine the pattern of pigmentation.", why: "Symmetry, distribution and the absence of inflammation distinguish melasma from PIH, LPP and Hori's naevus.", better: "Map the distribution; use Wood's lamp and dermoscopy to estimate depth.", severity: "major" },
      sunscreen: { what: "No sunscreen prescribed.", why: "Without daily broad-spectrum, ideally tinted (iron-oxide) sunscreen, every other treatment fails.", better: "SPF 50, PA+++ tinted sunscreen every morning, reapplied every 2–3 hours outdoors.", severity: "major" },
      photoprotection: { what: "No practical photoprotection advice.", why: "Sunscreen alone is not enough for 1.5 hours a day on a two-wheeler.", better: "Full-face helmet or scarf, shade, reapplication — and avoiding heat exposure where possible.", severity: "moderate" },
      hydroquinone: { what: "No topical depigmenting agent.", why: "Hydroquinone (or a short supervised triple combination, or azelaic acid) speeds clearance.", better: "Hydroquinone 2–4% at night to the patches for up to 3–4 months, then pause.", severity: "moderate" },
    },
    strengths: {
      sun: "Identified daily unprotected sun exposure as the main driver.",
      hormones: "Found the contraceptive pill — a trigger and a safety issue.",
      family: "Took a family history that revealed both melasma and a DVT.",
      cosmetics: "Asked about creams and parlour bleaching.",
      "woods-lamp": "Used Wood's lamp to estimate pigment depth.",
      dermoscopy: "Used dermoscopy to support the diagnosis.",
      sunscreen: "Built treatment around a broad-spectrum tinted sunscreen.",
      hydroquinone: "Chose hydroquinone appropriately.",
    },
  },

  teaching: {
    patientBand: "moderate",
    severityBands: [
      { id: "mild", label: "Mild", media: cheek(melasma(24, 0.35), 31, "Mild"),
        recognition: ["Light-brown, small patches on the malar areas", "Mostly epidermal — accentuates under Wood's light"],
        investigation: ["None"],
        treatment: ["Sunscreen + photoprotection", "Azelaic acid 20% or hydroquinone 2% at night"],
        followUp: ["8–12 weeks"] },
      { id: "moderate", label: "Moderate", media: cheek(melasma(38, 0.7, 4), 32, "Moderate"),
        recognition: ["Darker, larger, coalescing patches", "Several sites — malar, nose, upper lip, forehead", "Mixed depth"],
        investigation: ["None routinely; thrombosis history before tranexamic acid"],
        treatment: ["Tinted SPF 50 sunscreen + photoprotection", "Hydroquinone 2–4% at night, or a short (≤ 8-week) supervised triple-combination course", "Address triggers — OCP, heat, cosmetics"],
        followUp: ["6–8 weeks, then 3-monthly; maintenance through summer"] },
      { id: "severe", label: "Severe / refractory", media: cheek(melasma(52, 0.9, 8), 33, "Severe"),
        recognition: ["Dark, extensive, centrofacial patches", "Predominantly dermal — little Wood's accentuation", "Relapses despite topical therapy"],
        investigation: ["Thrombosis-risk assessment before oral tranexamic acid", "Biopsy only if atypical"],
        treatment: ["All of the above", "Oral tranexamic acid 250 mg BD for 8–12 weeks — only without OCP use, personal/family VTE, or migraine with aura", "Superficial peels as adjuncts in experienced hands"],
        followUp: ["Monthly while on tranexamic acid"] },
      { id: "complicated", label: "Complicated (iatrogenic)",
        recognition: ["Steroid damage from unsupervised triple-combination or 'fairness' creams — atrophy, telangiectasia, rosacea", "Exogenous ochronosis — blue-black pigmentation after prolonged hydroquinone"],
        investigation: ["Dermoscopy; biopsy if ochronosis suspected"],
        treatment: ["Stop the steroid gradually; treat rosacea; sunscreen", "Stop hydroquinone in ochronosis"],
        followUp: ["Slow recovery over months"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Broad-spectrum tinted sunscreen (iron oxide), SPF 50, PA+++", brand: "La Shield", dose: "Two finger-lengths for face and neck", route: "TOP", frequency: "Every morning; reapply every 2–3 h outdoors", duration: "Indefinitely",
        indication: "Foundation of all melasma treatment",
        mechanism: "Filters UVA/UVB → less UV-driven melanogenesis; iron oxides also block visible light → blocks the visible-light-driven pigmentation that untinted sunscreens miss.",
        whyItWorks: "Melanocytes in melasma are hyper-responsive to light; removing the stimulus is what lets every other treatment work.",
        avoidWhen: ["Known filter allergy"],
        adverseEffects: ["Rarely irritation or comedones"],
        monitoring: ["Adherence — especially reapplication"] },
      { generic: "Hydroquinone 2%", brand: "Eukroma", dose: "Thin layer to the patches with a 1 cm margin", route: "TOP", frequency: "Once at night", duration: "3–4 months, then pause",
        indication: "Epidermal and mixed melasma",
        mechanism: "Inhibits tyrosinase → less melanin synthesis; also toxic to overactive melanocytes.",
        whyItWorks: "Reduces new pigment while existing pigment is shed with epidermal turnover.",
        avoidWhen: ["Pregnancy", "Broken or irritated skin"],
        adverseEffects: ["Irritation, contact dermatitis", "Exogenous ochronosis with prolonged, high-strength use"],
        monitoring: ["Irritation at 2–4 weeks", "Take breaks after 3–4 months"] },
      { generic: "Triple combination cream (hydroquinone + tretinoin + corticosteroid)", brand: "Melacare", dose: "Pea-sized amount to the patches", route: "TOP", frequency: "Once at night", duration: "Maximum 8 weeks, supervised",
        indication: "Moderate melasma needing faster response",
        mechanism: "Hydroquinone blocks melanin synthesis → tretinoin speeds turnover and penetration → the steroid reduces irritation and melanocyte activity.",
        whyItWorks: "The three agents act synergistically.",
        avoidWhen: ["Pregnancy", "Rosacea, steroid damage", "Unsupervised or long-term use"],
        adverseEffects: ["Atrophy, telangiectasia, steroid rosacea with misuse", "Irritation"],
        monitoring: ["Stop at 8 weeks; switch to non-steroid maintenance"] },
      { generic: "Tranexamic acid", brand: "Pause", dose: "250 mg", route: "PO", frequency: "Twice daily", duration: "8–12 weeks",
        indication: "Refractory moderate-to-severe melasma in carefully selected women",
        mechanism: "Blocks plasminogen activation → less plasmin-driven release of melanogenic mediators from keratinocytes; reduces dermal vascularity.",
        whyItWorks: "Targets the vascular and inflammatory component that topicals miss.",
        avoidWhen: ["Combined oral contraceptive use", "Personal or family history of VTE", "Migraine with aura, smoking, pregnancy"],
        adverseEffects: ["Thrombosis (rare but serious)", "Menstrual reduction, GI upset"],
        monitoring: ["Ask about calf pain and breathlessness at every visit"] },
    ],
    routines: [
      { label: "Morning",
        steps: [
          { order: 1, step: "Cleanser", product: "Gentle, non-soap cleanser", howMuch: "Coin-sized", where: "Whole face" },
          { order: 2, step: "Moisturiser", product: "Light non-comedogenic moisturiser", howMuch: "Pea-sized ×2", where: "Whole face" },
          { order: 3, step: "Tinted sunscreen", product: "SPF 50, PA+++ with iron oxides", howMuch: "Two finger-lengths", where: "Face, ears and neck", note: "Reapply every 2–3 h outdoors; full-face helmet or scarf on the scooter" },
        ],
        avoid: ["Bleach, fairness creams, parlour facials", "Heat — sit away from the stove where possible", "Lemon, scrubs, home remedies"] },
      { label: "Night",
        steps: [
          { order: 1, step: "Cleanser", product: "Gentle cleanser", howMuch: "Coin-sized", where: "Whole face" },
          { order: 2, step: "Medication", product: "Hydroquinone 2%", howMuch: "Thin layer", where: "Patches only, with a 1 cm margin", note: "Avoid eyelids and lips" },
          { order: 3, step: "Moisturiser", product: "Light moisturiser", howMuch: "Pea-sized ×2", where: "Whole face, 15 minutes later" },
        ],
        expectedIrritation: "Mild stinging or redness in the first 1–2 weeks.",
        ifIrritated: "Use on alternate nights and apply the moisturiser first; stop and review if the skin becomes red and itchy (contact dermatitis).",
        improvementTimeline: "Lighter by 8–12 weeks. Expect relapse in summer — sunscreen is lifelong." },
    ],
    followUp: {
      interval: "6–8 weeks, then every 3 months",
      reassess: ["Photographs in the same light", "Sunscreen adherence", "Irritation", "Contraception plan"],
      redFlags: ["Red, thin, itchy skin (steroid damage or contact dermatitis)", "Blue-black pigmentation (ochronosis)", "On tranexamic acid: calf pain or breathlessness — urgent"],
      whenToEscalate: ["No response at 3 months of adherent therapy → reassess diagnosis and depth", "Refractory and low thrombosis risk → consider oral tranexamic acid", "Peels/lasers only by experienced dermatologists"],
    },
    treatmentFailure: { steps: [
      "Check adherence — sunscreen amount, reapplication, helmet",
      "Check the diagnosis — Hori's naevus, LPP, PIH, ochronosis, drug-induced",
      "Check depth — dermal melasma responds slowly",
      "Check triggers — OCP, heat, cosmetics, thyroid",
      "Alternative — azelaic acid, a short triple-combination course",
      "Escalate — oral tranexamic acid if safe; peels as adjuncts",
    ] },
    pearl: "Melasma is a chronic disease of light. The sunscreen is the treatment and the cream is the adjunct. And before oral tranexamic acid, ask three questions: Are you on the pill? Have you or your family had a clot? Do you get migraine with aura?",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "Oral tranexamic acid is a popular 'quick fix' for melasma. In this woman — on a combined pill, with a mother who had a DVT — it would have risked a deep vein thrombosis and pulmonary embolism.",
      sequence: ["Take a thrombosis history before any tranexamic acid", "If a calf swells: stop TXA and the pill, Doppler, anticoagulate", "If breathless: CTPA, oxygen, risk-stratify, anticoagulate"],
    },
  },
};
