import type { ClinicalCaseDefinition } from "../case-definition";
import { ecg, radiograph } from "./media";

export const emAdhf: ClinicalCaseDefinition = {
  id: "em-adhf-01",
  specialty: "Emergency",
  track: "emergency",
  level: "college",
  setting: "ER",
  weight: 3,
  difficulty: 3,
  patient: { name: "Kamla", age: 68, sex: "Female", city: "Shahdara, Delhi", occupation: "Homemaker", context: "Emergency" },
  arrivalMinuteOfDay: 3 * 60 + 20,
  briefing: "03:20. A 68-year-old woman is wheeled into the emergency department by her son, sitting bolt upright on the stretcher.",
  initialStatus: "deteriorating",
  opening: [
    { role: "nurse", kind: "action", text: "Triage: breathless at rest, brought by son. Vitals on the board. She won't lie back." },
    { role: "patient", kind: "speech", text: "Can't… breathe… doctor." },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "168/98" },
    hr: { key: "hr", value: "132" },
    rr: { key: "rr", value: "30" },
    spo2: { key: "spo2", value: "88" },
    temp: { key: "temp", value: "98.2" },
    rbs: { key: "rbs", value: "186" },
    weight: { key: "weight", value: "71" },
    urine: { key: "urine", value: "15" },
  },
  triageVitals: ["bp", "hr", "rr", "spo2", "temp"],
  profile: { heartFailure: true, fluidToleranceMl: 500, currentDrugs: ["aspirin", "metformin", "metoprolol", "atorvastatin"] },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential",
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened"],
      reply: "Breath… won't come… since night.",
      fact: "Breathless at rest since tonight" },
    { id: "hpi", group: "hpi", label: "Course", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["how long", "since when", "when did", "started", "start", "onset", "tell me about", "tell me more", "getting worse", "progression", "breathless", "breathlessness", "breathing"],
      reply: "Three days, doctor. Each night worse. Tonight she woke up gasping and couldn't lie down at all.",
      fact: "Progressive breathlessness × 3 days; acute worsening tonight" },
    { id: "orthopnoea", group: "hpi", label: "Orthopnoea / PND", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["lie down", "lying flat", "pillows", "orthopnoea", "orthopnea", "wake up", "woke up", "at night", "sleep", "pnd", "paroxysmal"],
      reply: "She's been sleeping sitting up on three pillows for days. Last night she woke twice, gasping, and sat by the window.",
      fact: "3-pillow orthopnoea; paroxysmal nocturnal dyspnoea" },
    { id: "swelling", group: "hpi", label: "Leg swelling & weight", importance: "useful", abnormal: true, speaker: "attendant",
      match: ["swelling", "swollen", "legs", "feet", "ankles", "oedema", "edema", "weight", "puffy"],
      reply: "Her feet have been swollen for a week. Her slippers don't fit.",
      fact: "Bilateral leg swelling × 1 week" },
    { id: "palpitations", group: "systemic", label: "Palpitations", importance: "useful", abnormal: true,
      match: ["palpitations", "heart racing", "racing", "heartbeat", "fluttering", "irregular"],
      reply: "Heart… racing… since yesterday.",
      fact: "Palpitations since yesterday" },
    { id: "chest-pain", group: "systemic", label: "Chest pain", importance: "essential",
      match: ["chest pain", "chest", "pain", "pressure", "tightness", "heaviness", "angina"],
      reply: "No… pain. Only… breath.",
      fact: "No chest pain" },
    { id: "cough", group: "systemic", label: "Cough & sputum", importance: "useful", abnormal: true, speaker: "attendant",
      match: ["cough", "coughing", "sputum", "phlegm", "spit", "frothy", "fever", "chills"],
      reply: "A dry cough for days, and tonight frothy, slightly pink spit. No fever.",
      fact: "Pink frothy sputum tonight; afebrile" },
    { id: "past", group: "past", label: "Past history", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["past", "medical history", "heart", "heart attack", "stent", "diabetes", "sugar", "bp", "blood pressure", "kidney", "thyroid", "comorbidities", "comorbidity", "known case", "any disease", "illness", "medical problems"],
      reply: "She had a heart attack four years ago — they put a stent. She has sugar and BP too.",
      fact: "MI with PCI 4 years ago; type 2 diabetes; hypertension" },
    { id: "meds", group: "medication", label: "Medications", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["medicines", "medicine", "medication", "tablets", "tablet", "taking any", "drugs", "water tablet", "diuretic", "lasix", "prescription"],
      reply: "Ecosprin, a sugar tablet, Metolar for BP, a cholesterol tablet — and the water tablet, Lasix. The Lasix finished five days ago and we didn't get it refilled.",
      fact: "Aspirin, metformin, metoprolol, atorvastatin; furosemide stopped 5 days ago (ran out)" },
    { id: "diet", group: "diet", label: "Recent diet", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["diet", "eat", "eating", "food", "salt", "salty", "pickle", "pickles", "water intake", "fluids", "wedding"],
      reply: "There was a wedding in the family — for three days she ate pickles, namkeen, papad, everything.",
      fact: "Three days of heavy salt intake (wedding food)" },
    { id: "urine", group: "systemic", label: "Urine output", importance: "useful", abnormal: true, speaker: "attendant",
      match: ["urine", "passing urine", "pass urine", "urination", "toilet"],
      reply: "She's passing much less urine since yesterday.",
      fact: "Reduced urine output" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful", speaker: "attendant",
      match: ["allergy", "allergic", "allergies", "drug reaction"],
      reply: "No allergies that we know of.",
      fact: "No known drug allergies" },
    { id: "habits", group: "social", label: "Smoking / alcohol", importance: "minor", speaker: "attendant",
      match: ["smoke", "smoking", "alcohol", "drink", "tobacco", "hookah", "bidi"],
      reply: "No, never.",
      fact: "Never smoked; no alcohol" },
  ],

  exam: [
    { id: "general", group: "general-exam", label: "General examination", importance: "essential", abnormal: true, match: [],
      finding: "Sitting bolt upright, using accessory muscles, speaking two or three words at a time. Sweaty. No central cyanosis. Pitting oedema to both knees.",
      fact: "Severe respiratory distress; oedema to knees" },
    { id: "jvp", group: "general-exam", label: "JVP", importance: "essential", abnormal: true, match: [],
      finding: "JVP raised to the earlobe at 45°, with hepatojugular reflux.",
      fact: "JVP raised to the earlobe" },
    { id: "oedema", group: "general-exam", label: "Oedema", importance: "useful", abnormal: true, match: [],
      finding: "Bilateral pitting oedema to the knees; sacral oedema.",
      fact: "Pitting oedema to knees; sacral" },
    { id: "crt", group: "general-exam", label: "Perfusion", importance: "useful", match: [],
      finding: "Peripheries warm. Capillary refill 2 s.",
      fact: "Warm peripheries; CRT 2 s" },
    { id: "cvs", group: "systemic-exam", label: "Cardiovascular", importance: "essential", abnormal: true, match: [],
      finding: "Pulse irregularly irregular. Apex displaced to the 6th intercostal space, anterior axillary line. S3 gallop; apical pansystolic murmur radiating to the axilla.",
      fact: "Irregularly irregular; displaced apex; S3; MR murmur" },
    { id: "rs", group: "systemic-exam", label: "Respiratory", importance: "essential", abnormal: true, match: [],
      finding: "Bilateral fine end-inspiratory crackles up to the mid-zones; scattered expiratory wheeze. Dull right base.",
      fact: "Bilateral crackles to mid-zones; wheeze" },
    { id: "abdomen", group: "systemic-exam", label: "Abdomen", importance: "minor", abnormal: true, match: [],
      finding: "Tender, smooth liver edge 3 cm below the costal margin. No ascites.",
      fact: "Tender congestive hepatomegaly" },
  ],

  investigations: [
    { id: "ecg", priority: "essential",
      media: ecg({ rate: 132, rhythm: "afib", morphology: { q: { V1: 2, V2: 3, V3: 2.5, V4: 1.2 }, t: { V2: -0.4, V3: -0.4 } } }, "Twelve-lead ECG at about 130 per minute."),
      report: "Ventricular rate ~132/min, irregularly irregular; no discernible P waves. QRS 104 ms. Q waves V1–V4. No ST elevation.",
      teaching: { whenToOrder: "Every breathless patient — within 10 minutes of arrival.", whatItTellsYou: "Precipitants (AF, ischaemia), old infarction, and STEMI that needs reperfusion." } },
    { id: "cxr", priority: "essential",
      media: radiograph("xray", "AP", [{ id: "cardiomegaly", severity: 2 }, { id: "bat-wing-oedema", severity: 2 }, { id: "pleural-effusion", side: "bilateral", severity: 1 }], 31, "Anteroposterior chest radiograph.", "AP sitting · portable"),
      report: "Cardiothoracic ratio ~0.62. Bilateral perihilar alveolar opacities with upper-lobe venous diversion. Kerley B lines. Small bilateral pleural effusions.",
      teaching: { whenToOrder: "Every acutely breathless patient.", whatItTellsYou: "Pulmonary oedema, effusions, heart size — and alternatives (pneumonia, pneumothorax)." } },
    { id: "troponin", priority: "essential", rows: [{ analyte: "hs-Troponin I", value: "38", unit: "ng/L", reference: "< 19", flag: "high" }],
      report: "Repeat at 3 hours: 41 ng/L (flat).",
      teaching: { whenToOrder: "Acute heart failure — to look for an acute coronary syndrome as the trigger.", whatItTellsYou: "Low, flat rise = myocardial strain (type 2); a dynamic rise suggests ACS." } },
    { id: "rft", priority: "essential",
      rows: [
        { analyte: "Urea", value: "62", unit: "mg/dL", reference: "15–40", flag: "high" },
        { analyte: "Creatinine", value: "1.4", unit: "mg/dL", reference: "0.5–1.1", flag: "high" },
        { analyte: "Sodium", value: "132", unit: "mEq/L", reference: "135–145", flag: "low" },
        { analyte: "Potassium", value: "4.9", unit: "mEq/L", reference: "3.5–5.1", flag: "normal" },
        { analyte: "eGFR", value: "39", unit: "mL/min/1.73m²", reference: "> 90", flag: "low" },
      ],
      teaching: { whenToOrder: "Before and during diuresis.", whatItTellsYou: "Baseline renal function and potassium; cardiorenal syndrome." } },
    { id: "bnp", priority: "useful", rows: [{ analyte: "NT-proBNP", value: "6,840", unit: "pg/mL", reference: "< 125 (age > 75: < 1800)", flag: "critical" }],
      teaching: { whenToOrder: "When the cause of breathlessness is uncertain.", whatItTellsYou: "Supports heart failure; a normal value makes it unlikely." } },
    { id: "abg", priority: "useful",
      rows: [
        { analyte: "pH", value: "7.33", reference: "7.35–7.45", flag: "low" },
        { analyte: "pCO₂", value: "46", unit: "mmHg", reference: "35–45", flag: "high" },
        { analyte: "pO₂", value: "56", unit: "mmHg", reference: "80–100", flag: "critical" },
        { analyte: "HCO₃⁻", value: "23", unit: "mEq/L", reference: "22–26", flag: "normal" },
        { analyte: "Lactate", value: "2.4", unit: "mmol/L", reference: "< 2.0", flag: "high" },
      ],
      report: "Sample drawn on room air.",
      teaching: { whenToOrder: "Hypoxaemia, respiratory distress, before NIV.", whatItTellsYou: "Hypoxaemia, rising CO₂ (tiring), acidosis — guides NIV." } },
    { id: "echo", priority: "useful",
      report: "Dilated LV, LVEF 30%. Akinetic anterior wall and apex. Moderate functional mitral regurgitation. Estimated PASP 52 mmHg. IVC 2.4 cm, < 50% collapse.",
      teaching: { whenToOrder: "Every new or decompensated heart failure — within 48 h.", whatItTellsYou: "Ejection fraction, valve disease, filling pressures — and the long-term treatment plan." } },
    { id: "cbc", priority: "useful", rows: [
        { analyte: "Haemoglobin", value: "10.9", unit: "g/dL", reference: "12.0–15.5", flag: "low" },
        { analyte: "Total leucocyte count", value: "8,900", unit: "/µL", reference: "4,000–11,000", flag: "normal" },
        { analyte: "Platelets", value: "2.2", unit: "lakh/µL", reference: "1.5–4.5", flag: "normal" },
      ],
      teaching: { whenToOrder: "Anaemia and infection can precipitate heart failure.", whatItTellsYou: "Mild anaemia here." } },
    { id: "electrolytes", priority: "useful", teaching: { whenToOrder: "During IV diuresis.", whatItTellsYou: "Potassium and sodium shifts." } },
    { id: "tft", priority: "situational", teaching: { whenToOrder: "New atrial fibrillation.", whatItTellsYou: "Thyrotoxicosis as a cause of AF." } },
    { id: "d-dimer", priority: "unnecessary", teaching: { whenToOrder: "Low-probability PE only.", whatItTellsYou: "Not helpful when the diagnosis is clear." } },
    { id: "ct-head", priority: "unnecessary", teaching: { whenToOrder: "Neurological signs.", whatItTellsYou: "Not relevant here." } },
  ],

  therapeutics: [
    { id: "upright", kind: "supportive", measureIds: ["propped-up"], label: "Sit upright", appropriateness: "acceptable" },
    { id: "oxygen-rule", kind: "supportive", measureIds: ["oxygen"], label: "Oxygen", appropriateness: "ideal" },
    { id: "niv-rule", kind: "supportive", measureIds: ["niv"], label: "Non-invasive ventilation (CPAP/BiPAP)", appropriateness: "ideal",
      vitalsAfter: [{ key: "spo2", value: "93" }, { key: "rr", value: "24" }],
      praise: "Started NIV early — it reduces the need for intubation in cardiogenic pulmonary oedema." },
    { id: "monitor-rule", kind: "supportive", measureIds: ["monitor"], label: "Cardiac monitoring", appropriateness: "acceptable" },
    { id: "diuretic", kind: "drug", drugIds: ["furosemide", "torsemide"], label: "IV loop diuretic", appropriateness: "ideal",
      doseRange: { min: 20, max: 200, unit: "mg" },
      vitalsAfter: [{ key: "urine", value: "180" }, { key: "rr", value: "24" }, { key: "spo2", value: "92" }],
      response: [{ role: "nurse", kind: "action", text: "Furosemide pushed. I'll put a urine bag and start an input–output chart." }],
      rescues: ["respiratory-failure", "fluid-overload"] },
    { id: "nitrate", kind: "drug", drugIds: ["gtn", "isosorbide-dinitrate"], label: "Nitrate (GTN)", appropriateness: "ideal",
      vitalsAfter: [{ key: "bp", value: "142/86" }],
      praise: "Used nitrates for hypertensive pulmonary oedema." },
    { id: "rate-control", kind: "drug", drugIds: ["digoxin", "amiodarone"], label: "Rate control (digoxin / amiodarone)", appropriateness: "acceptable",
      vitalsAfter: [{ key: "hr", value: "108" }] },
    { id: "anticoag", kind: "drug", drugIds: ["enoxaparin", "heparin", "apixaban"], label: "Anticoagulation for AF", appropriateness: "acceptable",
      praise: "Started anticoagulation — CHA₂DS₂-VASc is 6." },
    { id: "beta-blocker", kind: "drug", drugIds: ["metoprolol", "atenolol", "propranolol", "carvedilol", "bisoprolol"], label: "β-blocker in acute pulmonary oedema", appropriateness: "harmful",
      critique: { what: "Gave a β-blocker during acute pulmonary oedema.", why: "Negative inotropy in a decompensated ventricle with EF 30% can tip her into cardiogenic shock.", better: "Decongest first (diuretic, nitrate, NIV); control rate with digoxin or amiodarone; restart β-blockade once euvolaemic.", severity: "major" } },
    { id: "diltiazem", kind: "drug", drugIds: ["diltiazem"], label: "Diltiazem", appropriateness: "harmful",
      critique: { what: "Gave diltiazem for the AF.", why: "Non-dihydropyridine calcium-channel blockers are negatively inotropic and contraindicated in HFrEF.", better: "Digoxin or amiodarone for rate control in decompensated HFrEF.", severity: "major" } },
    { id: "iv-fluids", kind: "drug", drugIds: ["ns", "rl", "dns", "d5"], label: "IV fluids", appropriateness: "dangerous",
      critique: { what: "Gave IV fluids to a patient in pulmonary oedema.", why: "Her lungs were already full of fluid — raised JVP, crackles to mid-zones, oedema to the knees. Extra preload floods the alveoli further.", better: "No IV fluids. Decongest: sit up, oxygen/NIV, IV furosemide, nitrates.", severity: "major" } },
    { id: "morphine", kind: "drug", drugIds: ["morphine"], label: "Morphine", appropriateness: "unnecessary",
      critique: { what: "Gave morphine.", why: "Routine morphine in acute heart failure is associated with more ventilation and higher mortality.", better: "Relieve breathlessness with NIV, nitrates and diuretics.", severity: "minor" } },
    { id: "salbutamol", kind: "drug", drugIds: ["salbutamol", "levosalbutamol-ipratropium"], label: "Bronchodilator nebulisation", appropriateness: "unnecessary",
      critique: { what: "Nebulised a β-agonist for the wheeze.", why: "This is 'cardiac asthma' — the wheeze is oedema. Salbutamol speeds the ventricular rate in AF.", better: "Treat the oedema; the wheeze settles with decongestion.", severity: "minor" } },
    { id: "nsaid", kind: "drug", drugClasses: ["nsaid"], label: "NSAID", appropriateness: "harmful",
      critique: { what: "Gave an NSAID.", why: "NSAIDs cause sodium retention and worsen heart and kidney failure.", better: "Avoid NSAIDs in heart failure.", severity: "moderate" } },
    { id: "catheter-rule", kind: "supportive", measureIds: ["catheter"], label: "Urinary catheter & I/O chart", appropriateness: "acceptable",
      praise: "Catheterised to measure the response to diuresis." },
    { id: "admit", kind: "admit", measureIds: ["admit"], label: "Admit to CCU/ICU", appropriateness: "ideal" },
    { id: "stop-metformin", kind: "counsel", label: "Hold metformin", appropriateness: "acceptable",
      concernsDrugs: ["metformin"],
      match: ["hold metformin", "stop metformin", "withhold metformin"] },
  ],

  hazards: [
    { id: "respiratory-failure", label: "Progressive respiratory failure from untreated pulmonary oedema",
      omission: { byMinute: 45, preventedBy: ["diuretic", "niv-rule"] },
      stages: [
        { afterMin: 0, status: "critical", interrupts: true,
          vitals: [{ key: "spo2", value: "82" }, { key: "rr", value: "36" }, { key: "hr", value: "138" }, { key: "bp", value: "172/100" }],
          observation: { role: "nurse", text: "Doctor, she's gasping — pink froth at the mouth, saturation falling." },
          examFindings: { rs: "Coarse crackles throughout both lung fields.", general: "Exhausted, sweaty, cyanosed lips." },
          patientSays: "(Gasping — cannot speak.)" },
        { afterMin: 35, status: "critical",
          vitals: [{ key: "spo2", value: "74" }, { key: "rr", value: "40" }, { key: "hr", value: "146" }, { key: "bp", value: "92/60" }, { key: "gcs", value: "11" }],
          observation: { role: "nurse", text: "She's getting drowsy and her BP is falling." } },
        { afterMin: 75, status: "deceased",
          vitals: [{ key: "spo2", value: "0" }, { key: "hr", value: "0" }, { key: "bp", value: "0/0" }, { key: "gcs", value: "3" }],
          observation: { role: "nurse", text: "Respiratory arrest, then no pulse." } },
      ],
      rescue: [["diuretic"], ["oxygen-rule", "niv-rule"]],
      fullRecoveryWindowMin: 30,
      lastRescueMin: 65,
      recovery: [
        { afterMin: 30, status: "guarded", vitals: [{ key: "spo2", value: "92" }, { key: "rr", value: "24" }, { key: "hr", value: "116" }], patientSays: "A little… easier." },
        { afterMin: 180, status: "improving", vitals: [{ key: "spo2", value: "96" }, { key: "rr", value: "18" }, { key: "hr", value: "98" }, { key: "bp", value: "136/80" }], patientSays: "I can breathe now, doctor." },
      ],
      review: {
        cause: "Cardiogenic pulmonary oedema was not decongested in time.",
        whyItCausedHarm: "Raised left atrial pressure → alveolar flooding → shunt and hypoxaemia → tachycardia and work of breathing rise → fatigue, hypercapnia, then arrest.",
        earliestRescueWindow: "On arrival: sit up, oxygen/NIV, IV furosemide and nitrates within minutes.",
        correctRescueSequence: [
          "Sit upright; oxygen to SpO₂ 94–98%",
          "CPAP/BiPAP early if RR > 25 or SpO₂ < 90%",
          "IV furosemide 40–80 mg (≥ her usual oral dose ×1–2.5)",
          "GTN sublingual/infusion while systolic BP > 110",
          "Treat the precipitant — rate control for AF (digoxin/amiodarone), anticoagulate; exclude ACS",
          "Catheterise; chart urine output; repeat ABG; CCU",
        ],
        lastRealisticRescueWindow: "Within the first hour — before exhaustion and hypotension set in.",
      } },
  ],

  followUp: [
    { when: "ideal", status: "improving",
      lines: [
        { role: "system", kind: "status", text: "Heart-failure clinic, after discharge" },
        { role: "patient", kind: "speech", text: "I can walk to the market again, doctor, and I sleep with one pillow. I weigh myself every morning like you said." },
        { role: "system", kind: "finding", text: "Weight down 5 kg. In rate-controlled AF, 78/min. On sacubitril–valsartan, bisoprolol, spironolactone, dapagliflozin, furosemide 40 mg, apixaban." },
      ] },
    { when: "acceptable", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "Better than that night, but I still get breathless on the stairs." }] },
    { when: "any", status: "guarded",
      lines: [{ role: "patient", kind: "speech", text: "It's hard, doctor. The swelling comes back." }] },
  ],

  truth: {
    diagnosis: "Acute decompensated heart failure — cardiogenic pulmonary oedema",
    qualifier: "HFrEF (LVEF 30%, ischaemic), 'warm and wet', precipitated by new atrial fibrillation with rapid ventricular rate, a salt load and stopping furosemide",
    reasoning: [
      { stage: "History", text: "Three days of worsening breathlessness with orthopnoea and PND, leg swelling, pink frothy sputum; prior MI; furosemide ran out five days ago; wedding food; palpitations since yesterday." },
      { stage: "Examination", text: "SpO₂ 88%, RR 30, BP 168/98, irregularly irregular 132; JVP to the earlobe, S3, MR murmur, crackles to mid-zones, oedema to the knees; warm peripheries." },
      { stage: "Investigation", text: "ECG: AF with RVR, old anterior Q waves, no STEMI. CXR: cardiomegaly, alveolar oedema, effusions. NT-proBNP 6,840; troponin low and flat; creatinine 1.4; echo LVEF 30%." },
      { stage: "Diagnosis", text: "Warm-and-wet acute decompensated HFrEF with pulmonary oedema, precipitated by AF, salt and diuretic non-adherence." },
    ],
  },

  rubric: {
    diagnosisAccept: ["acute decompensated heart failure", "decompensated heart failure", "adhf", "acute heart failure", "acute pulmonary oedema", "acute pulmonary edema", "cardiogenic pulmonary oedema", "cardiogenic pulmonary edema", "flash pulmonary oedema", "left ventricular failure", "acute lvf", "lvf", "congestive cardiac failure", "ccf", "heart failure", "pulmonary oedema", "pulmonary edema"],
    diagnosisPartial: ["atrial fibrillation", "af with rvr", "fast af", "ischaemic cardiomyopathy", "ischemic cardiomyopathy", "cardiomyopathy", "cardiac asthma"],
    differentials: ["acute coronary syndrome", "nstemi", "myocardial infarction", "pneumonia", "pulmonary embolism", "copd exacerbation", "asthma", "acute kidney injury", "anaemia", "thyrotoxicosis", "sepsis", "atrial fibrillation"],
    idealTreatment: [["oxygen-rule", "niv-rule"], ["diuretic"], ["admit"]],
    expertActionCount: 16,
    expectsReassessment: true,
    definitiveTreatment: { ids: ["diuretic"], byMinute: 30, label: "IV diuretic" },
    weights: { history: 12, examination: 15, differential: 10, investigationSelection: 10, investigationInterpretation: 10, treatment: 18, drugSafety: 12, reassessment: 5, efficiency: 3, outcome: 5 },
    misses: {
      meds: { what: "Did not take a medication history.", why: "Running out of furosemide five days ago is a key precipitant — and she is on metoprolol and metformin, which matter now.", better: "Ask what they take, what has changed, and what has run out.", severity: "major" },
      diet: { what: "Did not ask about recent diet.", why: "Three days of wedding food (salt) is a classic precipitant.", better: "Ask about salt and fluid intake in every heart-failure decompensation.", severity: "moderate" },
      orthopnoea: { what: "Did not ask about orthopnoea and PND.", why: "They are specific for raised left-sided filling pressures.", better: "Ask how many pillows, and whether they wake up gasping.", severity: "moderate" },
      jvp: { what: "Did not examine the JVP.", why: "A raised JVP tells you she is volume-overloaded — and that IV fluids would be harmful.", better: "Look at the neck veins before every fluid decision.", severity: "major" },
      rs: { what: "Did not examine the chest.", why: "Crackles to the mid-zones quantify pulmonary oedema.", better: "Auscultate both lung fields front and back.", severity: "major" },
      cvs: { what: "Did not examine the heart.", why: "An irregularly irregular pulse, S3 and MR murmur point to AF and a failing ventricle.", better: "Pulse rhythm, apex, added sounds and murmurs.", severity: "moderate" },
      ecg: { what: "No ECG.", why: "AF with RVR is the precipitant; a STEMI would need immediate reperfusion.", better: "ECG within 10 minutes of arrival.", severity: "major" },
      cxr: { what: "No chest X-ray.", why: "Confirms pulmonary oedema and excludes pneumonia and pneumothorax.", better: "Portable CXR early.", severity: "moderate" },
      troponin: { what: "No troponin.", why: "An acute coronary syndrome can precipitate heart failure and changes management.", better: "Serial troponin.", severity: "moderate" },
      rft: { what: "No renal function.", why: "Needed before and during diuresis.", better: "Creatinine and potassium at baseline and daily.", severity: "minor" },
      diuretic: { what: "No IV diuretic.", why: "Decongestion is the cornerstone of treating pulmonary oedema.", better: "IV furosemide 40–80 mg now; repeat by urine output.", severity: "major" },
      "oxygen-rule": { what: "No oxygen or NIV.", why: "SpO₂ 88% with RR 30 — hypoxaemia and work of breathing need support now.", better: "Oxygen, and early CPAP/BiPAP.", severity: "major" },
      admit: { what: "Not admitted to a monitored bed.", why: "She needs continuous monitoring, titration and rate control.", better: "CCU/ICU admission.", severity: "moderate" },
    },
    strengths: {
      meds: "Found that furosemide had run out.",
      diet: "Identified the salt load.",
      orthopnoea: "Asked about orthopnoea and PND.",
      jvp: "Checked the JVP before any fluid decision.",
      ecg: "Got an early ECG and found the precipitant.",
      cxr: "Confirmed pulmonary oedema on CXR.",
      troponin: "Checked troponin for an ACS trigger.",
      echo: "Arranged an echocardiogram.",
      diuretic: "Gave IV furosemide promptly.",
      "niv-rule": "Started NIV.",
      "oxygen-rule": "Gave oxygen.",
    },
  },

  teaching: {
    patientBand: "warm-wet",
    severityBands: [
      { id: "warm-wet", label: "Warm & wet (commonest)",
        recognition: ["Congested — orthopnoea, raised JVP, crackles, oedema", "Perfused — warm peripheries, normal or high BP"],
        investigation: ["ECG, CXR, troponin, NT-proBNP, RFT, ABG; echo within 48 h"],
        treatment: ["Sit up; oxygen; early CPAP/BiPAP", "IV furosemide 40–80 mg", "Nitrates if SBP > 110", "Treat the precipitant (AF, ACS, infection, salt, non-adherence)"],
        followUp: ["Daily weight, urine output, creatinine and K⁺"] },
      { id: "hypertensive", label: "Hypertensive / flash pulmonary oedema",
        recognition: ["Very high BP, sudden onset, often preserved EF"],
        investigation: ["As above; renal artery stenosis if recurrent"],
        treatment: ["High-dose nitrates (infusion) + NIV", "Diuretic (less fluid overloaded than it looks)"],
        followUp: ["BP control"] },
      { id: "cold-wet", label: "Cold & wet (cardiogenic shock)",
        recognition: ["Congested and hypoperfused — cold peripheries, low BP, confusion, oliguria, lactate ↑"],
        investigation: ["Lactate, echo urgently"],
        treatment: ["Inotropes (dobutamine) ± vasopressor (noradrenaline)", "Diuretic once perfused", "ICU; consider mechanical support"],
        followUp: ["ICU"] },
      { id: "cold-dry", label: "Cold & dry",
        recognition: ["Hypoperfused but not congested — often over-diuresed"],
        investigation: ["Volume assessment, echo"],
        treatment: ["Careful small fluid challenge; stop diuretics"],
        followUp: ["Close monitoring"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Furosemide", brand: "Lasix", dose: "40–80 mg (≥ 1–2.5× the usual oral dose)", route: "IV", frequency: "Bolus, then 12-hourly or infusion", duration: "Until euvolaemic, then oral",
        indication: "Congestion in acute heart failure",
        mechanism: "Blocks the Na-K-2Cl co-transporter in the thick ascending loop → natriuresis and diuresis; early venodilatation.",
        whyItWorks: "Removes salt and water, lowering filling pressures and drying the lungs.",
        avoidWhen: ["Hypovolaemia or cardiogenic shock without perfusion"],
        adverseEffects: ["Hypokalaemia, hyponatraemia", "Rising creatinine", "Ototoxicity at high doses"],
        monitoring: ["Urine output (> 100–150 mL/h at 6 h)", "Daily weight, creatinine, K⁺"] },
      { generic: "Glyceryl trinitrate", brand: "Millisrol", dose: "SL 0.4–0.5 mg, or infusion 10–200 µg/min", route: "IV", frequency: "Titrated to BP", duration: "24–48 h",
        indication: "Acute pulmonary oedema with SBP > 110 mmHg",
        mechanism: "Releases nitric oxide → venodilatation (less preload) and, at higher doses, arterial dilatation (less afterload).",
        whyItWorks: "Rapidly lowers filling pressures and unloads the left ventricle.",
        avoidWhen: ["SBP < 100", "PDE-5 inhibitor in the last 24–48 h", "Severe aortic stenosis"],
        adverseEffects: ["Hypotension", "Headache"],
        monitoring: ["BP every 5–15 minutes during titration"] },
      { generic: "Sacubitril–valsartan", brand: "Vymada", dose: "24/26 mg → 97/103 mg", route: "PO", frequency: "Twice daily", duration: "Long-term (start once stable)",
        indication: "HFrEF — guideline-directed therapy",
        mechanism: "Neprilysin inhibition → more natriuretic peptides (vasodilatation, natriuresis); valsartan blocks angiotensin II.",
        whyItWorks: "Reduces death and hospitalisation more than ACE inhibitors.",
        avoidWhen: ["Within 36 h of an ACE inhibitor", "History of angioedema", "Pregnancy"],
        adverseEffects: ["Hypotension", "Hyperkalaemia", "Raised creatinine"],
        monitoring: ["BP, creatinine, K⁺ at 1–2 weeks"] },
      { generic: "Dapagliflozin", brand: "Forxiga", dose: "10 mg", route: "PO", frequency: "Once daily", duration: "Long-term",
        indication: "HFrEF (with or without diabetes)",
        mechanism: "SGLT2 inhibition → glycosuria and natriuresis; favourable cardiac and renal haemodynamics.",
        whyItWorks: "One of the four pillars that cut heart-failure deaths and admissions.",
        avoidWhen: ["Type 1 diabetes, ketosis", "eGFR < 20–25"],
        adverseEffects: ["Genital infection", "Volume depletion"],
        monitoring: ["eGFR, volume status"] },
    ],
    routines: [
      { label: "Daily heart-failure self-care",
        steps: [
          { order: 1, step: "Weigh every morning", note: "Same scale, after passing urine, before breakfast — write it down" },
          { order: 2, step: "Take the water tablet in the morning", note: "Never let it run out — keep a week's spare" },
          { order: 3, step: "Salt under 5 g a day", note: "No pickles, papad, namkeen, packaged food" },
          { order: 4, step: "Fluids", howMuch: "About 1.5 L/day if advised" },
          { order: 5, step: "Walk daily", note: "Within comfort; stop if breathless" },
        ],
        avoid: ["NSAIDs (Combiflam, diclofenac)", "Extra salt at functions", "Stopping tablets when well"],
        improvementTimeline: "Gain of > 2 kg in 3 days, or new breathlessness lying down → contact the clinic the same day." },
    ],
    followUp: {
      interval: "7–14 days after discharge, then every 2–4 weeks while titrating",
      reassess: ["Weight and congestion", "BP, heart rate, rhythm", "Creatinine and potassium", "Titrate the four pillars (ARNI, β-blocker, MRA, SGLT2i)"],
      redFlags: ["Weight gain > 2 kg in 3 days", "Breathless lying flat or at night", "Fainting, chest pain"],
      whenToEscalate: ["Persistent NYHA III–IV on optimal therapy → advanced heart-failure team", "EF ≤ 35% after 3 months → ICD/CRT evaluation"],
    },
    treatmentFailure: { steps: [
      "Check adherence — tablets, salt, fluids, daily weights",
      "Check the diagnosis — ACS, valve disease, pericardial disease, PE",
      "Check severity — cold and wet needs inotropes, not more diuretic",
      "Check precipitants — AF, infection, anaemia, thyroid, NSAIDs",
      "Alternative — diuretic resistance: higher dose, infusion, add thiazide",
      "Escalate — ICU, ultrafiltration, mechanical support",
    ] },
    pearl: "In a breathless elderly patient, the most dangerous reflex in an Indian ER is “start NS.” Look at the neck veins and listen to the lung bases before you hang a bag. She needed less water, not more — and the precipitant (AF, salt, the furosemide that ran out) needs as much attention as the oedema.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "Two litres of IV normal saline — given reflexively for 'weakness' or 'dehydration' — would have pushed her from pulmonary oedema into respiratory failure within the hour.",
      sequence: ["Stop all IV fluids", "Sit up; oxygen; CPAP/BiPAP", "IV furosemide 40–80 mg", "GTN while SBP > 110", "Rate control and CCU"],
    },
  },
};
