import type { ClinicalCaseDefinition } from "../case-definition";
import { photo } from "./media";

/** PHC night duty: viper bite with venom-induced consumption coagulopathy. */
export const emViperPhc: ClinicalCaseDefinition = {
  id: "em-viper-phc-01",
  specialty: "Emergency",
  track: "emergency",
  level: "phc",
  setting: "ER",
  weight: 3,
  difficulty: 2,
  patient: { name: "Ganpat", age: 42, sex: "Male", city: "Chiplun, Ratnagiri", occupation: "Paddy farmer", context: "Emergency" },
  arrivalMinuteOfDay: 20 * 60 + 15,
  briefing: "20:15. Primary Health Centre, night duty. A farmer is carried in by his brother, his right leg tied tightly with a cloth above the ankle.",
  initialStatus: "guarded",
  opening: [
    { role: "attendant", kind: "speech", text: "Doctor, a snake bit him in the paddy field, about an hour ago. We tied his leg tight so the poison doesn't go up." },
    { role: "patient", kind: "speech", text: "My foot is burning, doctor… and it's swelling." },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "126/80" },
    hr: { key: "hr", value: "106" },
    rr: { key: "rr", value: "20" },
    spo2: { key: "spo2", value: "97" },
    temp: { key: "temp", value: "98.6" },
    rbs: { key: "rbs", value: "118" },
    weight: { key: "weight", value: "64" },
  },
  profile: { weightKg: 64, thrombocytopenia: true },

  history: [
    { id: "cc", group: "complaint", label: "Bite", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["what happened", "what brings", "chief complaint", "what is the problem", "whats the problem", "how did it happen", "where did it bite", "when did it bite", "what time", "how long ago", "bite", "bitten"],
      reply: "A snake bit him on the right foot in the paddy field at about seven, while he was closing the water channel in the dark.",
      fact: "Snakebite, dorsum right foot, ~19:10 (≈ 1 h before arrival)" },
    { id: "snake", group: "hpi", label: "The snake", importance: "useful", speaker: "attendant",
      match: ["what did the snake look like", "describe the snake", "which snake", "what snake", "kind of snake", "type of snake", "colour", "color", "see the snake", "saw the snake", "spots", "pattern", "killed the snake", "bring the snake", "brought the snake", "photo of the snake", "how big", "hiss"],
      reply: "We didn't kill it. It was thick, about this long (holds hands a metre apart), brown with big dark round spots in rows. It hissed loudly, like a pressure cooker.",
      fact: "≈ 1 m stout brown snake, rows of dark oval spots, loud hiss" },
    { id: "first-aid", group: "hpi", label: "First aid given", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["first aid", "what did you do", "tied", "tie", "tourniquet", "tight", "cloth", "cut", "suck", "sucked", "healer", "ojha", "vaid", "herbal", "medicine applied", "applied anything"],
      reply: "We tied a cloth very tight above the ankle. The village healer cut the bite with a blade and sucked it, then put some leaves on it. Then we brought him here.",
      fact: "Tight cloth tourniquet; incision and suction by a traditional healer" },
    { id: "pain-swelling", group: "hpi", label: "Pain & swelling", importance: "useful", abnormal: true,
      match: ["pain", "swelling", "swollen", "burning", "how far", "spreading", "going up"],
      reply: "It burns like fire, and the swelling is going up my leg.",
      fact: "Severe burning pain; swelling ascending the leg" },
    { id: "bleeding", group: "systemic", label: "Bleeding", importance: "essential", abnormal: true,
      match: ["bleeding", "blood", "gums", "gum", "spit", "nose bleed", "nosebleed", "blood in vomit", "bruise", "bruising", "red spots"],
      reply: "When I spat on the way, there was blood in it. My gums are bleeding a little.",
      fact: "Gum bleeding since ~30 min" },
    { id: "urine", group: "systemic", label: "Urine", importance: "useful", abnormal: true,
      match: ["urine", "passed urine", "pass urine", "passing urine", "urination", "colour of urine", "red urine", "dark urine", "toilet"],
      reply: "I passed urine once on the way. It was dark — like tea.",
      fact: "Dark (tea-coloured) urine ×1" },
    { id: "neuro-hx", group: "systemic", label: "Neurotoxic symptoms", importance: "essential",
      match: ["eyelids", "drooping", "droopy", "double vision", "blurred", "swallow", "swallowing", "speak", "speech", "weakness", "weak", "breathing difficulty", "difficulty breathing", "heavy eyes", "sleepy", "drowsy", "tingling"],
      reply: "No, doctor. I can see clearly and I can swallow. My eyes don't feel heavy.",
      fact: "No ptosis, diplopia, dysphagia or breathlessness" },
    { id: "gi", group: "systemic", label: "Vomiting & giddiness", importance: "useful", abnormal: true,
      match: ["vomit", "vomiting", "nausea", "abdominal pain", "stomach pain", "giddy", "giddiness", "dizzy", "faint", "headache"],
      reply: "I vomited once, and I feel a little giddy.",
      fact: "One vomit; mild giddiness" },
    { id: "past", group: "past", label: "Past history & prior antivenom", importance: "useful",
      match: ["medical history", "illness", "any disease", "sugar", "bp", "kidney", "bitten before", "previous snake bite", "antivenom before", "asv before", "medicines", "tablets", "medication"],
      reply: "I've never been sick, doctor. No tablets. Never bitten before, never had the venom injection.",
      fact: "No comorbidities; no prior antivenom" },
    { id: "allergy", group: "allergy", label: "Allergies & asthma", importance: "useful",
      match: ["allergy", "allergic", "allergies", "drug reaction", "asthma", "horse serum", "reaction to injection"],
      reply: "No allergies, doctor. No asthma.",
      fact: "No allergies or asthma (ASV reaction risk not increased)" },
    { id: "tetanus-hx", group: "past", label: "Tetanus immunisation", importance: "minor",
      match: ["tetanus", "tt injection", "tt", "last injection"],
      reply: "I don't remember — many years ago.",
      fact: "Tetanus status unknown" },
  ],

  exam: [
    { id: "local", group: "local-exam", label: "Bite site", importance: "essential", abnormal: true,
      match: ["bite site", "bite mark", "fang marks", "fang", "foot", "leg", "local examination", "wound", "examine the bite", "swelling", "limb"],
      finding: "Two puncture marks 1 cm apart on the dorsum of the right foot, with a fresh 2 cm blade incision oozing blood that does not clot. Tense swelling up to the mid-calf, tender, with bruising around the bite; no blisters or necrosis. A tight cloth ligature above the ankle; the foot below it is cool.",
      fact: "Fang marks; non-clotting ooze; swelling to mid-calf; tight ligature",
      media: photo({ site: "foot", phototype: 5, seed: 412, lesions: [
        { morphology: "erythema", count: 6, size: 20, confluence: 0.6, region: "central" },
        { morphology: "patch", count: 4, size: 9, colour: "#4f2a44", confluence: 0.5, region: "central" },
      ] }, "Clinical photograph of the dorsum of the right foot.", "Right foot · dorsum") },
    { id: "circulation", group: "local-exam", label: "Distal circulation", importance: "useful", abnormal: true,
      match: ["dorsalis pedis", "pulses", "peripheral pulses", "capillary refill", "crt", "circulation", "compartment", "toes"],
      finding: "Below the ligature the foot is pale and cool; capillary refill 4 s; dorsalis pedis faint. Calf compartment soft, passive toe stretch not painful.",
      fact: "Distal foot pale/cool beneath ligature; compartment soft" },
    { id: "bleeding-sites", group: "general-exam", label: "Bleeding sites", importance: "essential", abnormal: true,
      match: ["gums", "mouth", "oral cavity", "bleeding sites", "look for bleeding", "skin bleeds", "petechiae", "ecchymosis", "conjunctiva", "eyes", "injection site"],
      finding: "Fresh blood oozing from the gum margins. A small subconjunctival haemorrhage in the left eye. No petechiae.",
      fact: "Gum bleeding; left subconjunctival haemorrhage" },
    { id: "neuro", group: "systemic-exam", label: "Neurotoxicity check", importance: "essential",
      match: ["ptosis", "neurological", "neuro", "single breath count", "breath count", "neck flexion", "eye movements", "cranial nerves", "power"],
      finding: "No ptosis or ophthalmoplegia. Neck flexion strong. Single-breath count 34. Speech and swallowing normal.",
      fact: "No neurotoxic signs" },
    { id: "general", group: "general-exam", label: "General examination", importance: "useful", abnormal: true, match: [],
      finding: "Anxious and sweating. Not pale, not icteric. Mild tachycardia.",
      fact: "Anxious, sweating" },
  ],

  investigations: [
    { id: "20wbct", name: "20-minute whole blood clotting test", short: "20WBCT", category: "bedside", minLevel: "phc",
      match: ["20wbct", "20 wbct", "20 minute whole blood clotting", "20 min whole blood clotting", "whole blood clotting test", "whole blood clotting time", "wbct", "clotting time", "bedside clotting test", "clotting test", "20 minute clotting"],
      turnaroundMin: 20, cost: 0, priority: "essential",
      report: "2 mL of venous blood in a new, clean, dry glass tube, left undisturbed for 20 minutes, then tilted: the blood has NOT clotted — it runs freely.",
      phases: [{ fromMin: 330, report: "Repeat 20WBCT: the blood has clotted at 20 minutes." }],
      teaching: { whenToOrder: "Every snakebite on arrival, then every 6 hours until clotted twice — it needs only a glass tube and a clock.", whatItTellsYou: "Incoagulable blood = venom-induced consumption coagulopathy: an indication for ASV, and the test that tells you when to repeat it." } },
    { id: "cbc", priority: "useful",
      rows: [
        { analyte: "Haemoglobin", value: "13.4", unit: "g/dL", reference: "13.0–17.0", flag: "normal" },
        { analyte: "Total leucocyte count", value: "14,600", unit: "/µL", reference: "4,000–11,000", flag: "high" },
        { analyte: "Neutrophils", value: "84", unit: "%", reference: "40–75", flag: "high" },
        { analyte: "Platelets", value: "0.86", unit: "lakh/µL", reference: "1.5–4.5", flag: "low" },
      ],
      teaching: { whenToOrder: "Baseline in systemic envenomation.", whatItTellsYou: "Neutrophilia and thrombocytopenia track the severity of envenomation." } },
    { id: "urine-dip", priority: "useful",
      rows: [
        { analyte: "Blood", value: "+++", reference: "Negative", flag: "high" },
        { analyte: "Protein", value: "+", reference: "Negative", flag: "high" },
        { analyte: "Glucose", value: "Negative", reference: "Negative", flag: "normal" },
      ],
      teaching: { whenToOrder: "Every viper bite — at the bedside.", whatItTellsYou: "Blood on dipstick with dark urine = haemoglobin/myoglobinuria; a warning for acute kidney injury." } },
    { id: "urine-rm", priority: "useful",
      rows: [
        { analyte: "Colour", value: "Dark brown", reference: "Pale yellow", flag: "high" },
        { analyte: "RBCs", value: "10–12", unit: "/hpf", reference: "0–2", flag: "high" },
        { analyte: "Protein", value: "1+", reference: "Nil", flag: "high" },
      ],
      teaching: { whenToOrder: "Viper bites.", whatItTellsYou: "Haematuria and pigmenturia — kidney at risk." } },
    { id: "rft", priority: "useful",
      rows: [
        { analyte: "Urea", value: "42", unit: "mg/dL", reference: "15–40", flag: "high" },
        { analyte: "Creatinine", value: "1.3", unit: "mg/dL", reference: "0.7–1.3", flag: "normal" },
        { analyte: "Potassium", value: "4.6", unit: "mEq/L", reference: "3.5–5.1", flag: "normal" },
      ],
      teaching: { whenToOrder: "At the referral centre — baseline, then daily for 3–5 days.", whatItTellsYou: "Russell's viper AKI usually declares itself over 24–72 hours." } },
    { id: "coag", priority: "useful",
      rows: [
        { analyte: "PT", value: "> 120", unit: "s", reference: "11–14", flag: "critical" },
        { analyte: "INR", value: "Unrecordable", reference: "0.8–1.2", flag: "critical" },
        { analyte: "aPTT", value: "> 180", unit: "s", reference: "25–35", flag: "critical" },
      ],
      teaching: { whenToOrder: "Where available — the 20WBCT is enough to start ASV.", whatItTellsYou: "Unclottable blood confirms consumption coagulopathy." } },
    { id: "blood-group", priority: "situational",
      teaching: { whenToOrder: "Active major bleeding at the referral centre.", whatItTellsYou: "Products help only after venom has been neutralised by ASV." } },
    { id: "ecg", priority: "situational",
      teaching: { whenToOrder: "Hyperkalaemia or myocardial toxicity suspected.", whatItTellsYou: "Not needed to decide ASV." } },
    { id: "malaria", priority: "unnecessary", teaching: { whenToOrder: "Fever with no clear cause.", whatItTellsYou: "Not relevant to a snakebite." } },
    { id: "dengue", priority: "unnecessary", teaching: { whenToOrder: "Fever with thrombocytopenia.", whatItTellsYou: "Not relevant — the bleeding has an obvious cause." } },
  ],

  therapeutics: [
    { id: "asv", kind: "drug", drugIds: ["asv"], label: "Polyvalent anti-snake venom", appropriateness: "ideal",
      doseRange: { min: 8, max: 10, unit: "vials" }, rescues: ["vicc-bleed"],
      response: [{ role: "nurse", kind: "action", text: "ASV reconstituted — running in 200 mL normal saline over one hour. Adrenaline drawn up and kept at the bedside." }],
      praise: "Gave ASV promptly for systemic envenomation — at the PHC, before referral." },
    { id: "remove-tourniquet", kind: "supportive", label: "Remove the tight ligature", appropriateness: "ideal", durationMin: 2,
      match: ["remove the tourniquet", "remove tourniquet", "release the tourniquet", "loosen the tourniquet", "untie", "remove the cloth", "cut the cloth", "remove the ligature", "loosen the cloth", "open the tie", "take off the cloth", "remove the band"],
      response: [{ role: "nurse", kind: "action", text: "Cloth removed carefully. The foot is pinking up." }],
      praise: "Removed the tight ligature — it causes ischaemia and doesn't stop venom spreading." },
    { id: "immobilise", kind: "supportive", label: "Immobilise the limb", appropriateness: "ideal", durationMin: 3,
      match: ["immobilise", "immobilize", "immobilisation", "immobilization", "splint", "keep the limb still", "keep the leg still", "don t move the leg", "do not move the leg", "rest the limb", "limb rest"],
      response: [{ role: "nurse", kind: "action", text: "Leg splinted and resting at heart level." }] },
    { id: "iv-line", kind: "supportive", measureIds: ["iv-access"], label: "IV access", appropriateness: "acceptable" },
    { id: "monitor-rule", kind: "supportive", measureIds: ["monitor"], label: "Monitoring", appropriateness: "acceptable" },
    { id: "fluids", kind: "drug", drugIds: ["ns", "rl"], label: "IV crystalloid", appropriateness: "acceptable" },
    { id: "paracetamol-rule", kind: "drug", drugIds: ["paracetamol"], label: "Paracetamol for pain", appropriateness: "acceptable" },
    { id: "refer", kind: "referral", measureIds: ["refer"], label: "Refer to district hospital (repeat 20WBCT, dialysis, ICU)", appropriateness: "ideal",
      response: [{ role: "nurse", kind: "action", text: "108 informed — the ambulance needs about 25 minutes to reach us, then an hour and a half to the district hospital." }] },
    { id: "admit-rule", kind: "admit", measureIds: ["admit"], label: "Admit for observation", appropriateness: "acceptable" },
    { id: "nsaid", kind: "drug", drugClasses: ["nsaid"], label: "NSAID painkiller", appropriateness: "harmful",
      critique: { what: "Gave an NSAID to a patient whose blood isn't clotting.", why: "NSAIDs impair platelet function and the kidneys — both already under attack by viper venom.", better: "Paracetamol for pain; ASV for the coagulopathy.", severity: "moderate" } },
    { id: "im-injection", kind: "drug", drugIds: ["pentazocine", "tetanus"], label: "Intramuscular injection", appropriateness: "unnecessary",
      critique: { what: "Gave an intramuscular injection during coagulopathy.", why: "With unclottable blood, IM injections cause large haematomas.", better: "IV route only until the 20WBCT is normal; give tetanus toxoid once clotting has recovered.", severity: "minor" } },
    { id: "anticoagulant", kind: "drug", drugIds: ["heparin", "enoxaparin", "warfarin", "apixaban", "rivaroxaban"], label: "Anticoagulant", appropriateness: "dangerous",
      critique: { what: "Gave an anticoagulant.", why: "Viper venom has already consumed the clotting factors; heparin adds to bleeding without helping.", better: "Only ASV reverses venom-induced coagulopathy.", severity: "major" } },
    { id: "premed", kind: "drug", drugIds: ["chlorpheniramine", "hydrocortisone"], label: "Premedication before ASV", appropriateness: "neutral" },
    { id: "adrenaline-ready", kind: "drug", drugIds: ["adrenaline"], label: "Adrenaline", appropriateness: "neutral" },
    { id: "local-measures", kind: "procedure", label: "Incision, suction or ice", appropriateness: "harmful", durationMin: 5,
      match: ["incision", "suck", "suction", "ice pack", "apply ice", "cut the wound", "incise", "cryotherapy"],
      critique: { what: "Used incision, suction or ice.", why: "They don't remove venom; they add infection, bleeding and tissue damage.", better: "Immobilise, remove ligatures, give ASV.", severity: "moderate" } },
  ],

  hazards: [
    { id: "vicc-bleed", label: "Untreated venom-induced consumption coagulopathy",
      omission: { byMinute: 55, preventedBy: ["asv"] },
      stages: [
        { afterMin: 0, status: "deteriorating", interrupts: true,
          vitals: [{ key: "hr", value: "118" }, { key: "bp", value: "108/70" }],
          observation: { role: "nurse", text: "Doctor, he's bleeding from the cut on his foot and from his gums — and he has just passed red urine." },
          examFindings: { "bleeding-sites": "Continuous oozing from the gums and the incision; fresh bruises at pressure points; red urine in the bottle." },
          investigations: { "20wbct": { report: "The blood has not clotted at 20 minutes." } },
          patientSays: "My mouth is full of blood, doctor…" },
        { afterMin: 40, status: "critical", interrupts: true,
          vitals: [{ key: "bp", value: "86/54" }, { key: "hr", value: "132" }, { key: "rr", value: "24" }, { key: "gcs", value: "14" }],
          observation: { role: "nurse", text: "BP is falling — he vomited blood and he's getting drowsy." },
          patientSays: "So tired… my head hurts." },
        { afterMin: 100, status: "critical",
          vitals: [{ key: "bp", value: "72/44" }, { key: "hr", value: "142" }, { key: "gcs", value: "9" }, { key: "urine", value: "5" }],
          observation: { role: "nurse", text: "He hasn't passed urine for an hour and he's hard to wake." } },
        { afterMin: 160, status: "deceased",
          vitals: [{ key: "bp", value: "0/0" }, { key: "hr", value: "0" }, { key: "gcs", value: "3" }],
          observation: { role: "nurse", text: "He had a fit, then stopped breathing. No pulse." } },
      ],
      rescue: [["asv"]],
      fullRecoveryWindowMin: 40,
      lastRescueMin: 120,
      recovery: [
        { afterMin: 60, status: "guarded", vitals: [{ key: "hr", value: "104" }, { key: "bp", value: "116/74" }],
          observation: { role: "nurse", text: "The gum bleeding has slowed." } },
        { afterMin: 360, status: "improving", vitals: [{ key: "hr", value: "94" }, { key: "bp", value: "122/78" }],
          investigations: { "20wbct": { report: "Repeat 20WBCT: the blood has clotted at 20 minutes." } },
          patientSays: "Better, doctor. The leg is still swollen." },
      ],
      review: {
        cause: "Venom-induced consumption coagulopathy was not neutralised with antivenom in time.",
        whyItCausedHarm: "Russell's viper venom activates factors X and V and consumes fibrinogen, so the blood stops clotting; spontaneous bleeding (gums, urine, gut, brain), haemolysis and direct renal toxicity follow — then shock and acute kidney injury.",
        earliestRescueWindow: "On arrival: gum bleeding or an unclotted 20WBCT is an indication for ASV straight away — at the PHC, before referral.",
        correctRescueSequence: [
          "Reassure; immobilise the limb; remove tight ligatures",
          "IV access; 20WBCT",
          "ASV 8–10 vials IV over 1 hour; adrenaline drawn up at the bedside",
          "Refer with ASV running — repeat 20WBCT every 6 hours (6 more vials if still unclotted)",
          "Watch urine output and creatinine for 3–5 days; dialysis for AKI",
        ],
        lastRealisticRescueWindow: "Within about two hours of bleeding onset. Later ASV still stops the coagulopathy, but cannot undo an intracranial bleed or established AKI.",
      } },
  ],

  followUp: [
    { when: "ideal", status: "improving",
      lines: [
        { role: "system", kind: "status", text: "Day 5 — district hospital ward" },
        { role: "patient", kind: "speech", text: "The swelling is going down, doctor. I can walk to the toilet now." },
        { role: "system", kind: "finding", text: "20WBCT clotted at 6 hours and stayed clotted. Creatinine peaked at 2.1 mg/dL and recovered without dialysis." },
      ] },
    { when: "acceptable", status: "stable",
      lines: [
        { role: "system", kind: "status", text: "Day 7 — district hospital" },
        { role: "patient", kind: "speech", text: "They did dialysis three times, doctor. Now my urine is coming properly." },
        { role: "system", kind: "finding", text: "Creatinine peaked at 5.4 mg/dL; three sessions of haemodialysis; recovering." },
      ] },
    { when: "any", status: "guarded",
      lines: [
        { role: "system", kind: "status", text: "Day 3 — district hospital ICU" },
        { role: "attendant", kind: "speech", text: "He's on the dialysis machine, doctor. They gave many bottles of the venom injection there." },
      ] },
  ],

  truth: {
    diagnosis: "Viper snakebite with systemic envenomation — venom-induced consumption coagulopathy",
    qualifier: "Probable Russell's viper: local swelling, an unclotted 20WBCT, gum bleeding, subconjunctival haemorrhage and pigmenturia; no neurotoxicity. At risk of acute kidney injury. Harmful first aid (tight ligature, incision).",
    reasoning: [
      { stage: "History", text: "Night-time bite in a paddy field one hour earlier by a stout brown snake with rows of dark spots and a loud hiss; burning pain and ascending swelling; gum bleeding and tea-coloured urine; no ptosis, diplopia or dysphagia." },
      { stage: "Examination", text: "Fang marks with non-clotting ooze, swelling to mid-calf, gum bleeding and subconjunctival haemorrhage; no neurotoxic signs; tachycardic but normotensive." },
      { stage: "Investigation", text: "20WBCT: unclotted. Platelets 0.86 lakh; urine blood +++. (Where available: PT/INR unrecordable.)" },
      { stage: "Diagnosis", text: "Haemotoxic (viper) envenomation with consumption coagulopathy — ASV now, then refer." },
    ],
  },

  rubric: {
    diagnosisAccept: ["viper bite", "viperine bite", "russell s viper", "russells viper", "russell viper", "daboia", "saw scaled viper", "snake envenomation", "envenomation", "haemotoxic snake bite", "hemotoxic snake bite", "vasculotoxic snake bite", "venom induced consumption coagulopathy", "vicc", "snake bite with coagulopathy", "snakebite with coagulopathy", "systemic envenomation", "poisonous snake bite", "venomous snake bite"],
    diagnosisPartial: ["snake bite", "snakebite", "local envenomation", "coagulopathy", "dic", "disseminated intravascular coagulation"],
    differentials: ["dry bite", "neurotoxic envenomation", "krait bite", "cobra bite", "scorpion sting", "cellulitis", "compartment syndrome", "acute kidney injury", "dic", "disseminated intravascular coagulation", "non venomous bite"],
    idealTreatment: [["asv"], ["remove-tourniquet"], ["refer", "admit-rule"]],
    expertActionCount: 14,
    expectsReassessment: true,
    definitiveTreatment: { ids: ["asv"], byMinute: 45, label: "Anti-snake venom" },
    weights: { history: 13, examination: 15, differential: 8, investigationSelection: 10, investigationInterpretation: 9, treatment: 20, drugSafety: 10, reassessment: 5, efficiency: 5, outcome: 5 },
    misses: {
      "first-aid": { what: "Did not ask what first aid was given.", why: "A tight ligature and a blade incision both cause harm and change what you do next.", better: "Ask what was tied, cut, sucked or applied.", severity: "moderate" },
      bleeding: { what: "Did not ask about bleeding.", why: "Spontaneous bleeding is a sign of systemic envenomation and an indication for ASV.", better: "Ask about gums, spit, vomit, urine and bruising.", severity: "major" },
      "neuro-hx": { what: "Did not screen for neurotoxic symptoms.", why: "Krait and cobra bites paralyse; ptosis or breathlessness change the treatment (ASV plus neostigmine/ventilation).", better: "Ask about drooping eyelids, double vision, swallowing and breathing.", severity: "moderate" },
      local: { what: "Did not examine the bite site.", why: "Swelling, its extent and the state of the limb guide severity.", better: "Examine the bite, mark the edge of the swelling, check distal circulation.", severity: "major" },
      "bleeding-sites": { what: "Did not look for bleeding.", why: "Gum and conjunctival bleeding confirm systemic envenomation at the bedside.", better: "Look at the gums, eyes, skin and the bite.", severity: "moderate" },
      "20wbct": { what: "No 20-minute whole blood clotting test.", why: "It needs only a glass tube and a clock, and it's the test that decides ASV at a PHC.", better: "20WBCT on arrival and every 6 hours.", severity: "major" },
      asv: { what: "No antivenom.", why: "ASV is the only treatment that neutralises venom; bleeding, shock and AKI follow without it.", better: "ASV 8–10 vials IV over 1 hour at the PHC, then refer.", severity: "major" },
      "remove-tourniquet": { what: "Left the tight ligature on.", why: "Arterial ligatures cause limb ischaemia and don't stop venom.", better: "Remove tight ligatures once IV access is in and ASV is ready.", severity: "moderate" },
      refer: { what: "Did not arrange onward care.", why: "Russell's viper bites need repeat 20WBCTs, creatinine monitoring and access to dialysis.", better: "Refer to the district hospital with ASV running.", severity: "moderate" },
    },
    strengths: {
      snake: "Asked what the snake looked like.",
      "first-aid": "Found the ligature and the incision.",
      bleeding: "Asked about bleeding.",
      "neuro-hx": "Screened for neurotoxicity.",
      "20wbct": "Did a 20WBCT on arrival.",
      asv: "Gave ASV at the PHC without waiting for referral.",
      "remove-tourniquet": "Removed the tight ligature.",
      immobilise: "Immobilised the limb.",
      refer: "Referred onward with ASV running.",
    },
  },

  teaching: {
    patientBand: "haemotoxic",
    severityBands: [
      { id: "dry", label: "No envenomation (dry bite)",
        recognition: ["Fang marks but no swelling progression, bleeding or neurotoxicity", "20WBCT clotted"],
        investigation: ["20WBCT on arrival and at 6, 12 and 24 hours"],
        treatment: ["Observe 24 hours; no ASV", "Tetanus toxoid; wound care"],
        followUp: ["Return if swelling, bleeding or weakness"] },
      { id: "local", label: "Local envenomation only",
        recognition: ["Progressive swelling beyond the bite; no systemic signs"],
        investigation: ["Serial 20WBCT; mark the swelling edge hourly"],
        treatment: ["ASV if swelling crosses a joint, involves > half the limb, or advances rapidly"],
        followUp: ["Watch for compartment syndrome"] },
      { id: "haemotoxic", label: "Systemic — haemotoxic (viper)",
        recognition: ["Unclotted 20WBCT, spontaneous bleeding, haematuria", "Shock, oliguria (Russell's viper: AKI)"],
        investigation: ["20WBCT every 6 h; platelets, creatinine, urine"],
        treatment: ["ASV 8–10 vials over 1 h; repeat 6 vials 6-hourly while unclotted", "Treat ASV reactions with adrenaline 0.5 mg IM", "Dialysis for AKI"],
        followUp: ["Daily creatinine for 3–5 days"] },
      { id: "neurotoxic", label: "Systemic — neurotoxic (cobra / krait)",
        recognition: ["Ptosis, ophthalmoplegia, dysphagia, falling single-breath count", "Krait: painless night-time bite, abdominal pain, often no marks"],
        investigation: ["Single-breath count, neck flexion, SpO₂/ABG"],
        treatment: ["ASV 10 vials", "Neostigmine with atropine (cobra)", "Early bag-mask/intubation and ventilation"],
        followUp: ["ICU"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Polyvalent anti-snake venom", brand: "VINS ASV", dose: "8–10 vials (low-dose regimens are acceptable)", route: "IV", frequency: "Over 1 hour; repeat 6 vials 6-hourly while 20WBCT stays unclotted", duration: "Until clotting is restored",
        indication: "Systemic envenomation — bleeding, unclotted 20WBCT, neurotoxicity, shock — or severe local swelling",
        mechanism: "Equine immunoglobulin fragments raised against the 'big four' (cobra, krait, Russell's viper, saw-scaled viper) bind and neutralise circulating venom.",
        whyItWorks: "Neutralises free venom so the liver can rebuild clotting factors (clotting returns in about 6 hours).",
        avoidWhen: ["No signs of envenomation (dry bite)"],
        adverseEffects: ["Early anaphylactoid reactions (common)", "Pyrogenic reactions", "Serum sickness at 5–24 days"],
        monitoring: ["Adrenaline at the bedside during infusion", "20WBCT every 6 hours", "Urine output and creatinine"] },
      { generic: "Adrenaline", brand: "Adrenaline 1 mg/mL", dose: "0.5 mg (0.5 mL of 1:1000)", route: "IM", frequency: "Repeat every 5–10 minutes as needed", duration: "—",
        indication: "Anaphylactoid reaction to ASV",
        mechanism: "α₁ vasoconstriction, β₁ inotropy, β₂ bronchodilatation and mast-cell stabilisation.",
        whyItWorks: "Reverses the hypotension and bronchospasm of a reaction within minutes; ASV is then restarted slowly.",
        avoidWhen: ["None in anaphylaxis"],
        adverseEffects: ["Tachycardia, tremor"],
        monitoring: ["BP, pulse, wheeze"] },
    ],
    routines: [
      { label: "Snakebite at a PHC",
        steps: [
          { order: 1, step: "Reassure; immobilise the whole limb with a splint", note: "Like a fracture — movement spreads venom" },
          { order: 2, step: "Remove rings, tight ligatures and bandages", note: "After IV access is in and ASV is ready" },
          { order: 3, step: "20WBCT in a clean, dry glass tube", howMuch: "2 mL blood, undisturbed for 20 minutes" },
          { order: 4, step: "ASV 8–10 vials IV over 1 hour for any systemic sign", note: "Adrenaline drawn up beforehand" },
          { order: 5, step: "Refer with ASV running and a note of the times", note: "Repeat 20WBCT every 6 hours" },
        ],
        avoid: ["Tight tourniquets", "Cutting, sucking, ice or herbal pastes", "IM injections while blood isn't clotting", "NSAIDs", "Waiting for the referral centre to give ASV"],
        improvementTimeline: "Clotting usually returns within 6 hours of adequate ASV; swelling settles over days. Creatinine can rise for 2–3 days." },
    ],
    followUp: {
      interval: "Daily while admitted; review 1–2 weeks after discharge",
      reassess: ["20WBCT until clotted twice", "Urine output, creatinine and potassium daily for 3–5 days", "Limb swelling and compartments", "Signs of serum sickness at 1–2 weeks"],
      redFlags: ["Bleeding again", "Falling urine output", "Drooping eyelids or breathlessness", "Fever, rash or joint pains a week later (serum sickness)"],
      whenToEscalate: ["Oliguria or rising creatinine → dialysis-capable centre", "Neurotoxicity → ventilator-capable centre", "Tense compartment with proven compartment pressure → surgeon (fasciotomy only after clotting is corrected)"],
    },
    treatmentFailure: { steps: [
      "20WBCT still unclotted at 6 hours → 6 more vials of ASV",
      "Check the tube and technique (new, clean, dry glass)",
      "Bleeding despite clotting recovery → look for a local cause; blood products",
      "Oliguria → fluids carefully, then dialysis",
      "Neurotoxicity appearing → airway first; neostigmine trial",
    ] },
    pearl: "At a PHC the 20-minute whole blood clotting test needs a glass tube and a clock — and an unclotted result means ASV now, before the referral, not after. A non-clotting patient sent on a three-hour journey without antivenom loses the hours that decide whether his kidneys survive.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "Referring him 'for ASV' without starting it would have meant three more hours of unopposed venom: bleeding from the gums and gut, falling BP, and kidney failure by the time he reached the district hospital.",
      sequence: ["20WBCT on arrival", "ASV at the PHC for any systemic sign", "Refer with ASV running", "Repeat 20WBCT every 6 hours"],
    },
  },
};
