import type { ClinicalCaseDefinition } from "../case-definition";
import { ecg } from "./media";

/** Global Centre of Excellence: recurrent "unexplained" abdominal pain — acute intermittent porphyria. */
export const grAip: ClinicalCaseDefinition = {
  id: "gr-aip-01",
  specialty: "Medicine",
  track: "emergency",
  level: "grandrounds",
  setting: "ER",
  weight: 1,
  difficulty: 3,
  patient: { name: "Ananya", age: 26, sex: "Female", city: "Pune", occupation: "Software engineer", context: "Emergency" },
  arrivalMinuteOfDay: 2 * 60 + 10,
  briefing: "02:10. Emergency department of a tertiary hospital. A 26-year-old woman with severe abdominal pain — her third emergency visit this month.",
  initialStatus: "guarded",
  opening: [
    { role: "nurse", kind: "action", text: "Triage: severe abdominal pain with vomiting. Third visit this month — discharged twice with 'gastritis'. Vitals on the board." },
    { role: "patient", kind: "speech", text: "Please… this pain is unbearable. Every time, the tests are normal and they send me home." },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "158/100" },
    hr: { key: "hr", value: "128" },
    rr: { key: "rr", value: "20" },
    spo2: { key: "spo2", value: "98" },
    temp: { key: "temp", value: "98.8" },
    rbs: { key: "rbs", value: "92" },
    weight: { key: "weight", value: "50" },
    pain: { key: "pain", value: "9" },
  },
  triageVitals: ["bp", "hr", "rr", "spo2", "temp"],
  profile: { currentDrugs: ["ocp", "paracetamol"], pregnancyPossible: true, weightKg: 50 },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential", abnormal: true,
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened"],
      reply: "Terrible pain all over my tummy for three days — cramping, coming in waves. I keep vomiting, and I haven't passed stool for four days.",
      fact: "Diffuse colicky abdominal pain × 3 days; vomiting; constipation × 4 days" },
    { id: "previous", group: "hpi", label: "Previous attacks", importance: "essential", abnormal: true,
      match: ["before", "previous", "first time", "earlier", "similar", "past episodes", "happened before", "attacks", "last time", "how many times", "laparoscopy", "operation", "surgery"],
      reply: "Last year I had the same pain — they did a laparoscopy for appendix and found nothing. Then again ten days ago. Both times just before my periods.",
      fact: "Recurrent attacks; negative diagnostic laparoscopy last year; premenstrual timing" },
    { id: "triggers", group: "hpi", label: "Recent changes", importance: "essential", abnormal: true,
      match: ["new medicine", "started any", "changed", "recent changes", "diet", "dieting", "fasting", "eating", "meals", "alcohol", "drink", "party", "stress", "trigger"],
      reply: "I'm dieting for my sister's wedding — one meal a day for a month. And I had a few drinks at a party last week.",
      fact: "Crash diet (one meal/day × 1 month); alcohol last week" },
    { id: "urine", group: "systemic", label: "Urine colour", importance: "essential", abnormal: true,
      match: ["urine", "passing urine", "urine colour", "colour of urine", "dark urine", "red urine", "pee", "toilet"],
      reply: "My urine is dark — reddish, like Coke. If it stands in the bottle it gets even darker.",
      fact: "Dark red urine that darkens on standing" },
    { id: "weakness", group: "systemic", label: "Weakness & tingling", importance: "essential", abnormal: true,
      match: ["weakness", "weak", "numbness", "tingling", "can you move", "arms", "legs", "lift", "walk", "pins and needles", "power"],
      reply: "Since yesterday my arms feel weak — I couldn't lift the kettle. My hands tingle.",
      fact: "Proximal arm weakness since yesterday; hand paraesthesia" },
    { id: "mental", group: "systemic", label: "Mood & sleep", importance: "useful", abnormal: true,
      match: ["sleep", "anxious", "anxiety", "mood", "confused", "confusion", "restless", "hallucination", "seeing things", "hearing things", "irritable"],
      reply: "I can't sleep and I feel jittery all the time. Last night I was sure someone was standing in my room.",
      fact: "Insomnia, anxiety, a transient visual hallucination" },
    { id: "seizure", group: "systemic", label: "Fits or fainting", importance: "useful",
      match: ["fits", "fit", "seizure", "seizures", "convulsion", "faint", "fainted", "blackout"],
      reply: "No fits. I felt faint in the bathroom once.",
      fact: "No seizures" },
    { id: "meds", group: "medication", label: "Medicines", importance: "essential", abnormal: true,
      match: ["medicines", "medicine", "medication", "tablets", "taking any", "drugs", "pill", "pills", "contraceptive", "hormone", "injections", "what did they give"],
      reply: "I started the pill — Ovral-L — three months ago for my periods and acne. Dolo for pain. At the last two visits they gave me injections for pain and vomiting.",
      fact: "Combined oral contraceptive started 3 months ago; paracetamol" },
    { id: "obstetric", group: "obstetric", label: "Periods & pregnancy", importance: "useful",
      match: ["periods", "last period", "lmp", "menstrual", "pregnant", "pregnancy", "sexually active", "married"],
      reply: "My period is due in two or three days. I'm on the pill, so I can't be pregnant.",
      fact: "Premenstrual (period due in 2–3 days); on combined OCP" },
    { id: "family", group: "family", label: "Family history", importance: "essential", abnormal: true,
      match: ["family", "father", "mother", "aunt", "relatives", "anyone in the family", "runs in the family", "similar illness in family"],
      reply: "My father's sister had attacks of stomach pain for years. She died young in an ICU — paralysed. Nobody ever told us why.",
      fact: "Paternal aunt: recurrent abdominal attacks; died with paralysis in ICU" },
    { id: "past", group: "past", label: "Past history", importance: "useful",
      match: ["medical history", "past history", "any illness", "diabetes", "sugar", "bp", "thyroid", "kidney", "liver", "known case"],
      reply: "Nothing else, doctor. Only these attacks.",
      fact: "No other illness" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "minor",
      match: ["allergy", "allergic", "allergies", "drug reaction"],
      reply: "No allergies.",
      fact: "No known drug allergies" },
  ],

  exam: [
    { id: "general", group: "general-exam", label: "General examination", importance: "essential", abnormal: true, match: [],
      finding: "Anxious, restless and sweating. Not pale, not icteric. No rash, blisters or scarring on the hands or face.",
      fact: "Restless, diaphoretic; no skin lesions" },
    { id: "abdomen", group: "systemic-exam", label: "Abdomen", importance: "essential", abnormal: true, match: [],
      finding: "Mildly distended, soft. Diffusely tender without guarding or rigidity; no rebound. Bowel sounds sluggish. Healed laparoscopy port scars. Pain out of proportion to the findings.",
      fact: "Soft, diffusely tender, no peritonism; sluggish bowel sounds" },
    { id: "neuro", group: "systemic-exam", label: "Neurological", importance: "essential", abnormal: true,
      match: ["neurological", "neuro", "power", "reflexes", "tone", "sensation", "cns", "motor", "nervous system", "neurological examination"],
      finding: "Power 3/5 at both shoulders, 4/5 at the elbows, 4+/5 in the hands; hips 4+/5. Biceps and supinator jerks absent; knee and ankle jerks present. Patchy reduced pinprick over both upper arms. Cranial nerves normal. No neck stiffness.",
      fact: "Proximal motor neuropathy (arms > legs); upper-limb areflexia" },
    { id: "breath", group: "systemic-exam", label: "Respiratory muscle strength", importance: "essential",
      match: ["single breath count", "breath count", "vital capacity", "neck flexion", "respiratory muscles", "fvc", "nif", "count in one breath", "respiratory function"],
      finding: "Single-breath count 22. Neck flexion 4/5. No paradoxical breathing.",
      fact: "Single-breath count 22" },
    { id: "urine-look", group: "local-exam", label: "Urine inspection", importance: "useful", abnormal: true,
      match: ["look at the urine", "inspect the urine", "urine sample", "urine bag", "colour of the urine", "see the urine", "urine container"],
      finding: "A reddish-brown sample; left on the window sill for 30 minutes it darkens to port-wine colour.",
      fact: "Red-brown urine darkening on standing" },
    { id: "rs", group: "systemic-exam", label: "Respiratory", importance: "minor", match: [],
      finding: "Chest clear; good air entry.",
      fact: "Chest clear" },
    { id: "cvs", group: "systemic-exam", label: "Cardiovascular", importance: "minor", match: [],
      finding: "Sinus tachycardia; normal heart sounds; no murmur.",
      fact: "Tachycardia; no murmur" },
  ],

  investigations: [
    { id: "electrolytes", priority: "essential",
      rows: [
        { analyte: "Sodium", value: "121", unit: "mEq/L", reference: "135–145", flag: "critical" },
        { analyte: "Potassium", value: "3.6", unit: "mEq/L", reference: "3.5–5.1", flag: "normal" },
        { analyte: "Chloride", value: "88", unit: "mEq/L", reference: "98–107", flag: "low" },
        { analyte: "Magnesium", value: "1.7", unit: "mg/dL", reference: "1.7–2.4", flag: "normal" },
      ],
      teaching: { whenToOrder: "Every acute abdomen with vomiting — and any neuropsychiatric symptoms.", whatItTellsYou: "Hyponatraemia (often SIADH) is common in acute porphyria and can cause seizures." } },
    { id: "urine-pbg", name: "Urine porphobilinogen (PBG) & ALA — quantitative", short: "Urine PBG", category: "lab", minLevel: "college",
      match: ["pbg", "porphobilinogen", "urine pbg", "watson schwartz", "hoesch", "porphyria screen", "porphyrins", "urine porphyrins", "ala", "aminolevulinic", "delta ala", "aminolaevulinic", "porphyria test"],
      turnaroundMin: 240, cost: 2600, priority: "essential",
      rows: [
        { analyte: "Porphobilinogen (spot urine)", value: "68", unit: "mg/g creatinine", reference: "< 2", flag: "critical" },
        { analyte: "Delta-aminolevulinic acid", value: "24", unit: "mg/g creatinine", reference: "< 5", flag: "high" },
      ],
      report: "Spot urine protected from light.",
      teaching: { whenToOrder: "Unexplained severe abdominal pain with any of: dark urine, hyponatraemia, neuropathy, psychiatric symptoms, or a family history.", whatItTellsYou: "PBG > 10× normal during symptoms confirms an acute porphyria attack — treat before subtyping." } },
    { id: "plasma-porphyrins", name: "Plasma fluorescence scan & faecal porphyrins", short: "Plasma porphyrins", category: "lab", minLevel: "college",
      match: ["plasma fluorescence", "plasma porphyrins", "faecal porphyrins", "fecal porphyrins", "stool porphyrins", "fluorescence scan"],
      turnaroundMin: 2880, cost: 4800, priority: "useful",
      report: "No plasma fluorescence peak at 626 nm. Faecal coproporphyrin and protoporphyrin normal.",
      teaching: { whenToOrder: "After a positive PBG, to subtype.", whatItTellsYou: "Normal plasma and faecal porphyrins point to AIP rather than variegate porphyria or hereditary coproporphyria." } },
    { id: "hmbs-gene", name: "HMBS gene sequencing", short: "HMBS gene", category: "lab", minLevel: "college",
      match: ["hmbs", "pbgd", "genetic test", "gene test", "gene sequencing", "porphyria gene", "molecular testing"],
      turnaroundMin: 20160, cost: 14000, priority: "situational",
      report: "Heterozygous pathogenic HMBS variant identified.",
      teaching: { whenToOrder: "Once biochemically confirmed — for family screening.", whatItTellsYou: "Confirms AIP and lets relatives be tested before they are ever given a porphyrinogenic drug." } },
    { id: "serum-osm", name: "Serum & urine osmolality, urine sodium", short: "Osmolality", category: "lab",
      match: ["osmolality", "serum osmolality", "urine osmolality", "urine sodium", "urinary sodium", "siadh workup", "spot urine sodium"],
      turnaroundMin: 90, cost: 900, priority: "useful",
      rows: [
        { analyte: "Serum osmolality", value: "254", unit: "mOsm/kg", reference: "275–295", flag: "low" },
        { analyte: "Urine osmolality", value: "512", unit: "mOsm/kg", reference: "—", flag: "high" },
        { analyte: "Urine sodium", value: "64", unit: "mEq/L", reference: "—", flag: "high" },
      ],
      teaching: { whenToOrder: "Hyponatraemia.", whatItTellsYou: "Low serum osmolality with inappropriately concentrated urine and high urine sodium — SIADH." } },
    { id: "lft", priority: "useful",
      rows: [
        { analyte: "Total bilirubin", value: "0.9", unit: "mg/dL", reference: "0.3–1.2", flag: "normal" },
        { analyte: "AST (SGOT)", value: "48", unit: "U/L", reference: "< 40", flag: "high" },
        { analyte: "ALT (SGPT)", value: "61", unit: "U/L", reference: "< 41", flag: "high" },
        { analyte: "Alkaline phosphatase", value: "96", unit: "U/L", reference: "40–129", flag: "normal" },
      ],
      teaching: { whenToOrder: "Abdominal pain work-up.", whatItTellsYou: "Mild transaminase rise is common in acute porphyria." } },
    { id: "amylase-lipase", priority: "useful",
      rows: [
        { analyte: "Amylase", value: "72", unit: "U/L", reference: "28–100", flag: "normal" },
        { analyte: "Lipase", value: "40", unit: "U/L", reference: "13–60", flag: "normal" },
      ],
      teaching: { whenToOrder: "Severe upper abdominal pain with vomiting.", whatItTellsYou: "Normal — not pancreatitis." } },
    { id: "cbc", priority: "useful",
      teaching: { whenToOrder: "Acute abdomen.", whatItTellsYou: "Normal counts argue against sepsis or a surgical cause." } },
    { id: "rft", priority: "useful",
      teaching: { whenToOrder: "Vomiting and dark urine.", whatItTellsYou: "Normal renal function here." } },
    { id: "upt", priority: "useful", rows: [{ analyte: "Urine pregnancy test", value: "Negative", reference: "Negative", flag: "normal" }],
      teaching: { whenToOrder: "Every woman of reproductive age with abdominal pain.", whatItTellsYou: "Excludes ectopic pregnancy; pregnancy also precipitates porphyria attacks." } },
    { id: "ecg", priority: "useful",
      media: ecg({ rate: 128, rhythm: "sinus" }, "Twelve-lead ECG at about 128 per minute."),
      report: "Sinus tachycardia, 128/min. Normal axis and intervals. No ST changes.",
      teaching: { whenToOrder: "Tachycardia, electrolyte disturbance.", whatItTellsYou: "Sinus tachycardia — autonomic, not cardiac." } },
    { id: "usg-abdomen", priority: "useful",
      report: "No gallstones. Appendix not visualised (post-operative). No free fluid. Ovaries normal. Mild gaseous bowel distension.",
      teaching: { whenToOrder: "First-line imaging for acute abdominal pain in a young woman.", whatItTellsYou: "Excludes gallstones, free fluid and ovarian pathology." } },
    { id: "ncs", name: "Nerve conduction study", short: "NCS", category: "function", minLevel: "college",
      match: ["ncs", "nerve conduction", "nerve conduction study", "emg", "electromyography"],
      turnaroundMin: 240, cost: 3500, priority: "useful",
      report: "Reduced compound muscle action potential amplitudes, upper > lower limbs, with preserved conduction velocities; sensory responses relatively spared — motor-predominant axonal neuropathy.",
      teaching: { whenToOrder: "Weakness with areflexia.", whatItTellsYou: "Axonal motor neuropathy (porphyria) versus demyelination (classic GBS)." } },
    { id: "blood-lead", name: "Blood lead level", short: "Lead", category: "lab",
      match: ["lead", "blood lead", "lead level", "heavy metal", "heavy metals"],
      turnaroundMin: 1440, cost: 1800, priority: "situational",
      rows: [{ analyte: "Blood lead", value: "3", unit: "µg/dL", reference: "< 5", flag: "normal" }],
      teaching: { whenToOrder: "Abdominal pain with neuropathy and anaemia, or occupational exposure.", whatItTellsYou: "Lead poisoning mimics porphyria by inhibiting ALA dehydratase." } },
    { id: "ct-abdomen", priority: "unnecessary",
      report: "Mild gaseous distension of small and large bowel without transition point. No acute abnormality.",
      teaching: { whenToOrder: "Peritonism, suspected obstruction or perforation.", whatItTellsYou: "Her third normal scan — radiation without a question." } },
    { id: "xray-abdomen", priority: "situational",
      teaching: { whenToOrder: "Suspected obstruction or perforation.", whatItTellsYou: "Non-specific gas pattern." } },
    { id: "mri-brain", priority: "situational",
      teaching: { whenToOrder: "Seizures, encephalopathy or visual loss (PRES).", whatItTellsYou: "Normal here." } },
  ],

  therapeutics: [
    { id: "haem", kind: "drug", drugIds: ["haem-arginate"], label: "IV haem arginate (Normosang)", appropriateness: "ideal",
      doseRange: { min: 100, max: 250, unit: "mg" }, rescues: ["porphyric-crisis", "porphyrinogenic-drug"],
      response: [{ role: "nurse", kind: "action", text: "Haem arginate diluted in 100 mL of 20% albumin — running over 30 minutes through the large-bore cannula." }],
      praise: "Gave haem arginate early — the only treatment that switches off hepatic ALA synthase." },
    { id: "glucose", kind: "drug", drugIds: ["d10", "dextrose-25", "d5"], label: "Carbohydrate loading (IV dextrose)", appropriateness: "acceptable",
      praise: "Started IV carbohydrate while arranging haem." },
    { id: "stop-ocp", kind: "counsel", concernsDrugs: ["ocp"], label: "Stop the combined pill", appropriateness: "ideal",
      match: ["stop the pill", "stop ocp", "stop the ocp", "stop oral contraceptive", "stop the contraceptive", "stop hormonal pill", "stop ovral", "no more pills", "stop the hormone"],
      response: [{ role: "patient", kind: "speech", text: "I'll stop it, doctor. What should I use instead?" }],
      praise: "Stopped the combined pill — a precipitant." },
    { id: "porphyrinogenic", kind: "drug", drugClasses: ["porphyrinogenic"], label: "Porphyrinogenic drug", appropriateness: "dangerous", arms: "porphyrinogenic-drug",
      critique: { what: "Gave a drug known to precipitate porphyric attacks.", why: "Barbiturates, carbamazepine, phenytoin, valproate, sulfonamides and progestogens induce hepatic CYP450 and ALA synthase — more porphyrin precursors, a worse attack.", better: "Check every drug against a porphyria safe-drug list (NAPOS / drugs-porphyria.org). For seizures: correct sodium; use levetiracetam, gabapentin or a benzodiazepine.", severity: "major" } },
    { id: "stop-porphyrinogenic", kind: "counsel", concernsDrugs: ["porphyrinogenic"], label: "Stop the unsafe drug", appropriateness: "ideal",
      match: ["stop the unsafe drug", "stop porphyrinogenic"] },
    { id: "opioid", kind: "drug", drugIds: ["morphine", "fentanyl"], label: "Opioid analgesia", appropriateness: "acceptable",
      praise: "Gave opioid analgesia — safe in porphyria." },
    { id: "antiemetic", kind: "drug", drugIds: ["ondansetron"], label: "Ondansetron", appropriateness: "acceptable" },
    { id: "beta", kind: "drug", drugIds: ["propranolol"], label: "Propranolol for tachycardia/hypertension", appropriateness: "acceptable" },
    { id: "safe-aed", kind: "drug", drugIds: ["levetiracetam", "gabapentin"], label: "Porphyria-safe anticonvulsant", appropriateness: "acceptable" },
    { id: "hts", kind: "drug", drugIds: ["hypertonic-saline"], label: "3% saline", appropriateness: "neutral" },
    { id: "icu", kind: "admit", measureIds: ["admit"], label: "Admit to HDU/ICU", appropriateness: "ideal",
      praise: "Admitted to a monitored bed — neuropathy can reach the respiratory muscles." },
    { id: "breath-monitor", kind: "supportive", label: "Serial single-breath count / FVC", appropriateness: "ideal", durationMin: 2,
      match: ["monitor breath count", "serial single breath count", "serial breath count", "monitor vital capacity", "serial fvc", "monitor respiratory function", "4 hourly breath count", "chart breath count", "respiratory monitoring"],
      response: [{ role: "nurse", kind: "action", text: "Single-breath count and neck flexion every 4 hours — I'll call you if it falls below 15." }],
      praise: "Set up serial respiratory monitoring." },
    { id: "surgery", kind: "procedure", label: "Surgical exploration", appropriateness: "harmful", durationMin: 90,
      match: ["laparotomy", "exploratory laparotomy", "diagnostic laparoscopy", "laparoscopy", "operate", "surgical exploration", "take her to theatre", "explore the abdomen"],
      note: "No surgical pathology found. Bowel mildly distended throughout.",
      critique: { what: "Took her to theatre.", why: "A soft abdomen without peritonism, normal imaging and a previous negative laparoscopy — surgery and anaesthetic drugs can worsen an acute porphyria attack.", better: "Think of medical causes of severe abdominal pain: porphyria, DKA, lead, sickle crisis, FMF.", severity: "major" } },
    { id: "antibiotic", kind: "drug", drugClasses: ["antibiotic"], label: "Antibiotic", appropriateness: "unnecessary",
      critique: { what: "Started an antibiotic.", why: "There was no infection — and sulfonamides and some others precipitate porphyria.", better: "Treat the attack: haem, carbohydrate, safe analgesia.", severity: "minor" } },
    { id: "diet", kind: "counsel", label: "Regular carbohydrate-rich meals — no crash dieting", appropriateness: "acceptable",
      match: ["regular meals", "eat regularly", "don t fast", "do not fast", "avoid fasting", "no crash diet", "stop dieting", "carbohydrate rich", "high carbohydrate"] },
    { id: "family-screening", kind: "counsel", label: "Family screening & genetic counselling", appropriateness: "acceptable",
      match: ["family screening", "screen the family", "screen her family", "genetic counselling", "genetic counseling", "test her relatives", "test the family", "test family members"],
      praise: "Arranged family screening — relatives can carry the gene silently." },
    { id: "alert", kind: "counsel", label: "Safe-drug list & alert card", appropriateness: "acceptable",
      match: ["safe drug list", "drug list", "medical alert", "alert card", "porphyria card", "medic alert", "list of safe drugs", "unsafe drugs"],
      praise: "Gave her a safe-drug list and alert card." },
  ],

  hazards: [
    { id: "porphyric-crisis", label: "Progressing acute porphyric attack — respiratory paralysis",
      omission: { byMinute: 480, preventedBy: ["haem"] },
      stages: [
        { afterMin: 0, status: "deteriorating", interrupts: true,
          vitals: [{ key: "hr", value: "136" }, { key: "bp", value: "168/104" }, { key: "rr", value: "24" }],
          observation: { role: "nurse", text: "Doctor, she can't lift her arms off the bed now, and her voice is getting weak." },
          examFindings: { neuro: "Power 2/5 at the shoulders, 3/5 at elbows and hips. Areflexia in the arms; knee jerks now absent.", breath: "Single-breath count 14. Neck flexion 3/5." },
          investigations: { electrolytes: { rows: [
            { analyte: "Sodium", value: "117", unit: "mEq/L", reference: "135–145", flag: "critical" },
            { analyte: "Potassium", value: "3.4", unit: "mEq/L", reference: "3.5–5.1", flag: "low" },
          ] } },
          patientSays: "I can't move my arms… it's hard to breathe in fully." },
        { afterMin: 360, status: "critical", interrupts: true,
          vitals: [{ key: "rr", value: "32" }, { key: "spo2", value: "90" }, { key: "hr", value: "142" }, { key: "gcs", value: "14" }],
          observation: { role: "nurse", text: "She's breathing fast and shallow and her saturation is dropping. Her belly moves in when she breathes in." },
          examFindings: { breath: "Single-breath count 7; paradoxical abdominal movement; weak cough." },
          patientSays: "(Whispers.) Can't… breathe…" },
        { afterMin: 600, status: "deceased",
          vitals: [{ key: "spo2", value: "0" }, { key: "hr", value: "0" }, { key: "bp", value: "0/0" }, { key: "gcs", value: "3" }],
          observation: { role: "nurse", text: "Respiratory arrest — no pulse." } },
      ],
      rescue: [["haem"]],
      fullRecoveryWindowMin: 300,
      lastRescueMin: 540,
      recovery: [
        { afterMin: 720, status: "guarded", vitals: [{ key: "hr", value: "112" }, { key: "bp", value: "142/90" }],
          patientSays: "The pain is less. My arms are still weak." },
        { afterMin: 4320, status: "improving", vitals: [{ key: "hr", value: "92" }, { key: "bp", value: "126/80" }],
          patientSays: "I could hold the cup today, doctor." },
      ],
      review: {
        cause: "An acute porphyric attack was not treated with haem.",
        whyItCausedHarm: "Partial HMBS deficiency plus inducers (the combined pill, fasting, alcohol) push hepatic ALA synthase up; the neurotoxic precursors ALA and PBG accumulate, causing autonomic, motor and central nervous system dysfunction — the motor neuropathy can ascend to the respiratory muscles.",
        earliestRescueWindow: "As soon as PBG is raised — or before, if the picture is typical and the test will be delayed.",
        correctRescueSequence: [
          "Stop every porphyrinogenic drug (including the combined pill)",
          "Haem arginate 3 mg/kg (max 250 mg) IV daily × 4 days",
          "IV carbohydrate (10% dextrose) while haem is arranged",
          "Safe analgesia (morphine), antiemetic (ondansetron), propranolol for tachycardia",
          "Correct sodium slowly (≤ 8 mEq/L per 24 h)",
          "HDU: single-breath count or FVC 4-hourly; ventilate early if falling",
        ],
        lastRealisticRescueWindow: "Before established respiratory muscle weakness; haem stops progression but axonal damage recovers over months.",
      } },
    { id: "porphyrinogenic-drug", label: "Attack worsened by a porphyrinogenic drug",
      stages: [
        { afterMin: 30, status: "deteriorating", interrupts: true,
          vitals: [{ key: "hr", value: "142" }, { key: "bp", value: "174/108" }],
          observation: { role: "nurse", text: "Doctor — she's having a fit! Generalised jerking, frothing at the mouth." },
          patientSays: "(Post-ictal, confused.) Where… where am I?" },
        { afterMin: 240, status: "critical", interrupts: true,
          vitals: [{ key: "rr", value: "30" }, { key: "spo2", value: "91" }],
          observation: { role: "nurse", text: "Her weakness is spreading — she can barely cough." },
          examFindings: { breath: "Single-breath count 9; weak neck flexion.", neuro: "Power 2/5 in all proximal muscles; areflexic." } },
        { afterMin: 540, status: "deceased",
          vitals: [{ key: "spo2", value: "0" }, { key: "hr", value: "0" }, { key: "bp", value: "0/0" }],
          observation: { role: "nurse", text: "Respiratory arrest." } },
      ],
      rescue: [["haem"], ["stop-porphyrinogenic", "measure:stop-drug"]],
      fullRecoveryWindowMin: 180,
      lastRescueMin: 480,
      recovery: [
        { afterMin: 720, status: "guarded", vitals: [{ key: "hr", value: "114" }, { key: "bp", value: "146/92" }] },
      ],
      review: {
        cause: "A porphyrinogenic drug was given during an acute porphyric attack.",
        whyItCausedHarm: "Enzyme-inducing drugs (barbiturates, carbamazepine, phenytoin, valproate, sulfonamides, progestogens) increase hepatic haem demand and ALA synthase activity — more ALA and PBG, a deeper attack, seizures and paralysis.",
        earliestRescueWindow: "Before prescribing: check the drug against a porphyria safe list.",
        correctRescueSequence: ["Stop the drug", "Haem arginate", "Treat seizures with levetiracetam or a benzodiazepine; correct sodium", "HDU respiratory monitoring"],
        lastRealisticRescueWindow: "Within hours — before respiratory muscle failure.",
      } },
  ],

  followUp: [
    { when: "ideal", status: "improving",
      lines: [
        { role: "system", kind: "status", text: "Two weeks later — porphyria clinic" },
        { role: "patient", kind: "speech", text: "The pain went after the third dose. My arms are getting stronger with physiotherapy. I carry the drug card everywhere." },
        { role: "system", kind: "finding", text: "PBG falling; sodium 136; HMBS variant confirmed. Combined pill stopped — copper IUD. Father and cousins referred for testing." },
      ] },
    { when: "acceptable", status: "stable",
      lines: [
        { role: "system", kind: "status", text: "Three weeks later" },
        { role: "patient", kind: "speech", text: "I needed a few days in the ICU, but I'm walking now. My hands are still weak." },
      ] },
    { when: "any", status: "guarded",
      lines: [
        { role: "system", kind: "status", text: "Six weeks later — rehabilitation ward" },
        { role: "patient", kind: "speech", text: "I was on the ventilator for a month. I'm learning to hold a spoon again." },
      ] },
  ],

  truth: {
    diagnosis: "Acute intermittent porphyria — acute neurovisceral attack",
    qualifier: "Severe attack with SIADH hyponatraemia, proximal motor neuropathy and autonomic features (tachycardia, hypertension, constipation), precipitated by the combined pill, crash dieting and alcohol in the premenstrual phase. Urine PBG > 30× normal; family history of an unexplained fatal paralytic illness.",
    reasoning: [
      { stage: "History", text: "Recurrent premenstrual attacks of severe diffuse abdominal pain with a negative laparoscopy; vomiting, constipation, dark urine that darkens on standing; new proximal weakness, insomnia and a hallucination; the combined pill, fasting and alcohol; an aunt who died paralysed." },
      { stage: "Examination", text: "Tachycardia 128 and BP 158/100; a soft, diffusely tender abdomen without peritonism; proximal motor weakness with upper-limb areflexia; no skin lesions; single-breath count 22." },
      { stage: "Investigation", text: "Sodium 121 with SIADH indices; urine PBG 68 mg/g creatinine (> 10× ULN) and ALA raised; amylase, imaging and lead normal; NCS motor axonal neuropathy; plasma and faecal porphyrins normal (AIP)." },
      { stage: "Diagnosis", text: "Acute intermittent porphyria in a severe attack — haem now, remove triggers, monitor respiration." },
    ],
  },

  rubric: {
    diagnosisAccept: ["acute intermittent porphyria", "aip", "acute porphyria", "acute hepatic porphyria", "porphyria", "porphyric crisis", "acute porphyric attack", "porphyria attack"],
    diagnosisPartial: ["siadh", "hyponatraemia", "hyponatremia", "variegate porphyria", "hereditary coproporphyria"],
    differentials: ["guillain barre syndrome", "gbs", "lead poisoning", "acute pancreatitis", "appendicitis", "intestinal obstruction", "biliary colic", "renal colic", "ovarian torsion", "ectopic pregnancy", "diabetic ketoacidosis", "vasculitis", "polyarteritis nodosa", "familial mediterranean fever", "abdominal migraine", "functional abdominal pain", "siadh", "hyponatraemia"],
    idealTreatment: [["haem"], ["stop-ocp"], ["icu"]],
    expertActionCount: 24,
    expectsReassessment: true,
    definitiveTreatment: { ids: ["haem"], byMinute: 360, label: "IV haem arginate" },
    weights: { history: 18, examination: 12, differential: 12, investigationSelection: 12, investigationInterpretation: 12, treatment: 16, drugSafety: 10, reassessment: 4, efficiency: 2, outcome: 2 },
    misses: {
      previous: { what: "Did not ask about previous attacks.", why: "Recurrent unexplained attacks with a negative laparoscopy are the hallmark of acute porphyria.", better: "Ask about previous similar episodes, investigations and operations.", severity: "major" },
      urine: { what: "Did not ask about urine colour.", why: "Dark urine that darkens on standing is the bedside clue to porphyrin precursors.", better: "Ask about urine colour — and look at it.", severity: "major" },
      weakness: { what: "Did not ask about weakness.", why: "Motor neuropathy marks a severe attack that can paralyse the respiratory muscles.", better: "Ask about weakness and tingling in every patient with unexplained abdominal pain.", severity: "major" },
      meds: { what: "Did not take a medication history.", why: "The combined pill was a precipitant; injections at earlier visits may have been too.", better: "Ask about hormones, anticonvulsants, antibiotics and anything given at previous visits.", severity: "major" },
      family: { what: "Did not ask about family history.", why: "AIP is autosomal dominant — an aunt who died paralysed in the ICU was the biggest clue of all.", better: "Ask about similar illnesses and unexplained deaths in the family.", severity: "moderate" },
      triggers: { what: "Did not ask about fasting or alcohol.", why: "Calorie restriction and alcohol are classic triggers.", better: "Ask about diet, fasting, alcohol, smoking and stress.", severity: "moderate" },
      neuro: { what: "Did not examine the nervous system.", why: "Proximal weakness with areflexia is the sign of a severe attack.", better: "Examine power and reflexes in every unexplained abdominal pain.", severity: "major" },
      breath: { what: "Did not assess respiratory muscle strength.", why: "Single-breath count or FVC tells you when ventilation is coming.", better: "Single-breath count and neck flexion at baseline, then 4-hourly.", severity: "moderate" },
      electrolytes: { what: "No sodium.", why: "Sodium 121 explains her confusion and puts her at risk of seizures.", better: "Check electrolytes in every acute abdomen with vomiting.", severity: "major" },
      "urine-pbg": { what: "No urine PBG.", why: "It is the diagnostic test — and the only way out of the cycle of normal scans.", better: "Spot urine PBG in any unexplained severe abdominal pain with a neurological, psychiatric or urinary clue.", severity: "major" },
      haem: { what: "No haem arginate.", why: "Haem is the only specific treatment; glucose alone is for mild attacks.", better: "Haem arginate 3 mg/kg IV daily for 4 days, started early.", severity: "major" },
      "stop-ocp": { what: "Left her on the combined pill.", why: "Progestogens are potent precipitants of attacks.", better: "Stop the pill; offer a copper IUD.", severity: "moderate" },
    },
    strengths: {
      previous: "Uncovered the pattern of recurrent attacks.",
      urine: "Asked about — and looked at — the urine.",
      family: "Found the family history.",
      neuro: "Examined power and reflexes.",
      breath: "Measured respiratory muscle strength.",
      electrolytes: "Found the hyponatraemia.",
      "urine-pbg": "Sent urine PBG.",
      haem: "Gave haem arginate.",
      "stop-ocp": "Stopped the combined pill.",
      "breath-monitor": "Set up serial respiratory monitoring.",
      "family-screening": "Arranged family screening.",
    },
  },

  teaching: {
    patientBand: "severe",
    severityBands: [
      { id: "latent", label: "Latent carrier",
        recognition: ["HMBS variant, no attacks (most carriers)"],
        investigation: ["Gene test in relatives of a proband"],
        treatment: ["Avoid porphyrinogenic drugs, fasting, alcohol, smoking"],
        followUp: ["Alert card; counselling"] },
      { id: "mild", label: "Mild attack",
        recognition: ["Pain and vomiting; no neuropathy; sodium normal"],
        investigation: ["Urine PBG; sodium"],
        treatment: ["Stop precipitants; IV/oral carbohydrate; safe analgesia; consider haem"],
        followUp: ["Daily review for progression"] },
      { id: "severe", label: "Severe attack",
        recognition: ["Motor neuropathy, hyponatraemia, seizures, hallucinations", "Marked tachycardia and hypertension"],
        investigation: ["PBG, sodium, osmolality; single-breath count / FVC"],
        treatment: ["Haem arginate 3 mg/kg × 4 days", "HDU/ICU; early ventilation if FVC falls", "Correct sodium slowly; safe anticonvulsants"],
        followUp: ["Rehabilitation; neuropathy recovers over months"] },
      { id: "recurrent", label: "Recurrent attacks (≥ 4 a year)",
        recognition: ["Frequent, often cyclical (luteal phase) attacks"],
        investigation: ["Trigger review; ferritin; renal function"],
        treatment: ["Givosiran (monthly SC); GnRH analogue for cyclical attacks; prophylactic haem", "Liver transplantation for refractory disease"],
        followUp: ["Specialist porphyria centre"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Haem arginate", brand: "Normosang", dose: "3 mg/kg (max 250 mg) in 100 mL 20% albumin over 30 min", route: "IV", frequency: "Once daily", duration: "4 days",
        indication: "Acute attack of hepatic porphyria with severe pain, neuropathy or hyponatraemia",
        mechanism: "Restores the hepatic regulatory haem pool → negative feedback represses ALA synthase-1 → ALA and PBG production falls.",
        whyItWorks: "Shortens attacks and halts neuropathy progression — best given early.",
        avoidWhen: ["Known hypersensitivity"],
        adverseEffects: ["Phlebitis (use a large vein, flush well)", "Transient coagulopathy", "Iron overload with repeated courses"],
        monitoring: ["Urine PBG", "Venous access site", "Ferritin with repeated use"] },
      { generic: "10% dextrose", brand: "D10", dose: "≈ 2 L / 24 h (300–400 g carbohydrate/day)", route: "IV", frequency: "Continuous", duration: "Until eating normally",
        indication: "Mild attacks, or while haem is being arranged",
        mechanism: "Glucose suppresses hepatic ALA synthase-1 via PGC-1α (the 'glucose effect').",
        whyItWorks: "A modest reduction in precursor production.",
        avoidWhen: ["Worsening hyponatraemia — monitor sodium closely"],
        adverseEffects: ["Hyponatraemia", "Hyperglycaemia"],
        monitoring: ["Sodium 6–12-hourly", "Glucose"] },
      { generic: "Givosiran", brand: "Givlaari", dose: "2.5 mg/kg", route: "SC", frequency: "Monthly", duration: "Long-term",
        indication: "Recurrent attacks of acute hepatic porphyria",
        mechanism: "siRNA targeting hepatic ALAS1 mRNA → lowers ALA and PBG.",
        whyItWorks: "Cuts annual attack rates by about three-quarters.",
        avoidWhen: ["Severe hepatic impairment"],
        adverseEffects: ["Injection-site reactions", "Raised creatinine, transaminases", "Homocysteine rise"],
        monitoring: ["LFT, creatinine monthly initially"] },
    ],
    routines: [
      { label: "Preventing the next attack",
        steps: [
          { order: 1, step: "Check every new medicine against a porphyria safe list", note: "drugs-porphyria.org / NAPOS — show it to every doctor and chemist" },
          { order: 2, step: "Eat regular meals with carbohydrate", note: "No crash diets, no long fasts" },
          { order: 3, step: "Avoid alcohol and smoking" },
          { order: 4, step: "Non-hormonal contraception", note: "Copper IUD — no combined pill or progestogens" },
          { order: 5, step: "Carry an alert card", note: "'Acute porphyria — check drugs before prescribing'" },
        ],
        avoid: ["Barbiturates, carbamazepine, phenytoin, valproate", "Sulfonamides (Septran), griseofulvin", "Combined pills and progestogens", "Fasting and alcohol"],
        improvementTimeline: "Pain settles within 2–4 days of haem; motor neuropathy recovers over months, sometimes incompletely." },
    ],
    followUp: {
      interval: "2 weeks after discharge, then every 3–6 months",
      reassess: ["Attack frequency and triggers", "Sodium, creatinine, LFT", "Neuropathy recovery", "Family screening progress", "Long-term: CKD, hypertension; liver ultrasound 6-monthly after age 50 (HCC risk)"],
      redFlags: ["Abdominal pain with dark urine", "Weakness or breathlessness", "Confusion or seizures"],
      whenToEscalate: ["≥ 4 attacks a year → givosiran", "Cyclical attacks → GnRH analogue", "Refractory disease → liver transplant assessment"],
    },
    treatmentFailure: { steps: [
      "Check precipitants — a hidden drug, infection, fasting, the menstrual cycle",
      "Check the diagnosis — urine PBG must be raised during symptoms",
      "Check severity — neuropathy needs HDU and ventilation planning",
      "Repeat haem course; consider prophylactic haem",
      "Escalate — givosiran, specialist porphyria centre, liver transplant",
    ] },
    pearl: "When the pain is out of proportion to a soft abdomen, the scans are clean, and the urine darkens on the window sill — think porphyria before the next laparotomy. Then check every drug on the chart against a porphyria safe list: one 'routine' anticonvulsant for her low-sodium seizure can turn an attack into respiratory paralysis.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "With a sodium of 121 she was close to a seizure. The reflex — phenytoin or valproate, or phenobarbitone if they failed — are all porphyrinogenic and can deepen the attack into ascending paralysis.",
      sequence: ["Correct sodium cautiously", "Levetiracetam, gabapentin or a benzodiazepine for seizures", "Haem arginate", "Respiratory monitoring in HDU"],
    },
  },
};
