import type { ClinicalCaseDefinition } from "../case-definition";
import { radiograph } from "./media";

export const idDengue: ClinicalCaseDefinition = {
  id: "id-dengue-01",
  specialty: "Infectious Disease",
  track: "opd",
  level: "chc",
  setting: "OPD",
  weight: 5,
  difficulty: 2,
  patient: { name: "Aman", age: 26, sex: "Male", city: "Mukherjee Nagar, Delhi", occupation: "Civil-services aspirant", context: "Fever clinic" },
  arrivalMinuteOfDay: 19 * 60 + 30,
  briefing: "October, 19:30. A 26-year-old student has come to the evening fever clinic with his roommate.",
  initialStatus: "guarded",
  opening: [
    { role: "patient", kind: "speech", text: "Doctor, I've had fever for four days. Today I feel much weaker, and my stomach hurts." },
  ],
  baselineVitals: {
    temp: { key: "temp", value: "99.8" },
    hr: { key: "hr", value: "108" },
    bp: { key: "bp", value: "106/84" },
    rr: { key: "rr", value: "20" },
    spo2: { key: "spo2", value: "97" },
    rbs: { key: "rbs", value: "96" },
    weight: { key: "weight", value: "64" },
    height: { key: "height", value: "175" },
    urine: { key: "urine", value: "18" },
  },
  profile: { thrombocytopenia: true, fluidToleranceMl: 4000 },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential",
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened"],
      reply: "Fever for four days, doctor. And today I feel very weak and my stomach hurts.",
      fact: "Fever × 4 days; weakness and abdominal pain today" },
    { id: "fever", group: "hpi", label: "Fever pattern", importance: "essential", abnormal: true,
      match: ["fever", "temperature", "how high", "chills", "rigors", "since when", "how long", "tell me about", "tell me more", "pattern", "day of fever", "how many days"],
      reply: "High fever, 103–104, with chills since Friday. Since this morning it has come down — but I feel worse, not better.",
      fact: "Day 4; high fever settling since morning (defervescence) while feeling worse" },
    { id: "aches", group: "hpi", label: "Aches & headache", importance: "useful",
      match: ["body ache", "bodyache", "aches", "pain in the body", "joint pain", "headache", "eyes", "behind the eyes", "muscle pain"],
      reply: "Terrible body ache, like my bones are breaking, and pain behind my eyes when I move them.",
      fact: "Severe myalgia; retro-orbital pain" },
    { id: "abdo", group: "hpi", label: "Abdominal pain", importance: "essential", abnormal: true,
      match: ["abdominal pain", "stomach", "stomach pain", "abdomen", "tummy", "belly", "where does it hurt", "pain"],
      reply: "Since this morning — on the upper right side, under the ribs. It's constant.",
      fact: "Right upper quadrant pain since morning" },
    { id: "vomiting", group: "hpi", label: "Vomiting", importance: "essential", abnormal: true,
      match: ["vomit", "vomiting", "vomited", "nausea", "throw up", "keep water down", "eat", "eating", "appetite", "drink"],
      reply: "I vomited four times today. I can't keep even water down.",
      fact: "Persistent vomiting ×4 today; not tolerating oral fluids" },
    { id: "bleeding", group: "hpi", label: "Bleeding", importance: "essential", abnormal: true,
      match: ["bleed", "bleeding", "gums", "nose bleed", "nosebleed", "blood", "spots", "rash", "red spots", "black stools", "blood in urine", "bruise", "bruising"],
      reply: "My gums bled when I brushed this morning. And there are small red spots on my legs.",
      fact: "Gum bleeding; petechiae on legs" },
    { id: "urine", group: "systemic", label: "Urine output", importance: "essential", abnormal: true,
      match: ["urine", "passing urine", "pass urine", "urination", "pee", "how much urine", "toilet"],
      reply: "Only once since morning. Dark yellow.",
      fact: "Oliguria — passed urine once since morning" },
    { id: "lethargy", group: "systemic", label: "Lethargy", importance: "useful", abnormal: true, speaker: "attendant",
      match: ["drowsy", "sleepy", "lethargic", "weak", "weakness", "restless", "confused", "fainted", "dizzy", "giddiness"],
      reply: "He couldn't even stand in the queue, doctor. He was dizzy when he got up from the bed.",
      fact: "Lethargy; postural dizziness" },
    { id: "breath", group: "systemic", label: "Breathing", importance: "useful",
      match: ["breathless", "breathlessness", "breathing", "shortness of breath", "cough", "chest"],
      reply: "No breathlessness. Just tired.",
      fact: "No breathlessness" },
    { id: "meds", group: "medication", label: "Medicines taken", importance: "essential", abnormal: true,
      match: ["medicine", "medicines", "tablets", "tablet", "taken anything", "taking any", "painkiller", "painkillers", "chemist", "what did you take", "medication", "drugs"],
      reply: "Dolo 650, three times a day. Yesterday the chemist also gave me Combiflam for the body ache — I took two.",
      fact: "Paracetamol 650 TDS; Combiflam (ibuprofen + paracetamol) ×2 yesterday" },
    { id: "contacts", group: "social", label: "Contacts & exposure", importance: "useful",
      match: ["contacts", "anyone else", "others", "neighbours", "pg", "hostel", "roommate", "mosquito", "mosquitoes", "travel", "dengue around", "outbreak"],
      reply: "Two boys in my PG have dengue. There are a lot of mosquitoes this season.",
      fact: "Dengue cases in his PG; no travel" },
    { id: "past", group: "past", label: "Past history", importance: "useful",
      match: ["past", "medical history", "illness", "diabetes", "bp", "asthma", "heart", "kidney", "dengue before", "previous dengue", "comorbidities", "any disease", "medical problems"],
      reply: "Never been ill like this. I've never had dengue before, as far as I know.",
      fact: "No comorbidities; no known previous dengue" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful",
      match: ["allergy", "allergic", "allergies", "drug reaction"],
      reply: "No allergies.",
      fact: "No known drug allergies" },
  ],

  exam: [
    { id: "general", group: "general-exam", label: "General examination", importance: "essential", abnormal: true, match: [],
      finding: "Lethargic but oriented. Flushed face; conjunctival suffusion. Petechiae over both shins. No pallor or icterus. No lymphadenopathy.",
      fact: "Lethargic; flushed; petechiae" },
    { id: "hydration", group: "general-exam", label: "Hydration", importance: "useful", abnormal: true, match: [],
      finding: "Tongue dry. Skin turgor reduced.",
      fact: "Dehydrated" },
    { id: "crt", group: "general-exam", label: "Perfusion", importance: "essential", abnormal: true, match: [],
      finding: "Capillary refill 3 s. Peripheries cool to the wrists.",
      fact: "CRT 3 s; cool peripheries" },
    { id: "abdomen", group: "systemic-exam", label: "Abdomen", importance: "essential", abnormal: true, match: [],
      finding: "Tender right hypochondrium. Liver palpable 2 cm below the costal margin, soft and tender. Mild shifting dullness. No guarding.",
      fact: "Tender hepatomegaly; mild ascites",
      patientReaction: "That's where it hurts, doctor." },
    { id: "rs", group: "systemic-exam", label: "Respiratory", importance: "useful", abnormal: true, match: [],
      finding: "Respiratory rate 20. Reduced breath sounds and stony dullness at the right base.",
      fact: "Right basal effusion" },
    { id: "tourniquet", group: "general-exam", label: "Tourniquet test", importance: "useful", abnormal: true,
      match: ["tourniquet", "tourniquet test", "hess test", "capillary fragility"],
      finding: "Tourniquet test positive — 24 petechiae per square inch.",
      fact: "Tourniquet test positive" },
    { id: "skin", group: "local-exam", label: "Skin", importance: "useful", abnormal: true, match: [],
      finding: "Scattered non-blanching petechiae over both shins and ankles. No purpura or ecchymoses.",
      fact: "Petechiae — legs" },
  ],

  investigations: [
    { id: "cbc", priority: "essential",
      rows: [
        { analyte: "Haemoglobin", value: "16.1", unit: "g/dL", reference: "13.0–17.0", flag: "normal" },
        { analyte: "Haematocrit", value: "49", unit: "%", reference: "40–50", flag: "high" },
        { analyte: "Total leucocyte count", value: "2,800", unit: "/µL", reference: "4,000–11,000", flag: "low" },
        { analyte: "Neutrophils", value: "38", unit: "%", reference: "40–75", flag: "low" },
        { analyte: "Lymphocytes", value: "52", unit: "%", reference: "20–45", flag: "high" },
        { analyte: "Platelets", value: "0.62", unit: "lakh/µL", reference: "1.5–4.5", flag: "low" },
      ],
      report: "Haematocrit 49% — his baseline from a college medical last year was 42%.",
      teaching: { whenToOrder: "Every suspected dengue, then serially (6–12 hourly in the critical phase).", whatItTellsYou: "Rising haematocrit with falling platelets signals plasma leakage — the core of dengue danger." } },
    { id: "dengue", priority: "essential",
      rows: [
        { analyte: "Dengue NS1 antigen", value: "Positive", reference: "Negative", flag: "high" },
        { analyte: "Dengue IgM", value: "Positive", reference: "Negative", flag: "high" },
        { analyte: "Dengue IgG", value: "Negative", reference: "Negative", flag: "normal" },
      ],
      teaching: { whenToOrder: "NS1 in the first 5 days; IgM from day 5. Both together around day 4–5.", whatItTellsYou: "Confirms dengue; IgG negative suggests primary infection." } },
    { id: "lft", priority: "useful",
      rows: [
        { analyte: "Total bilirubin", value: "1.0", unit: "mg/dL", reference: "0.3–1.2", flag: "normal" },
        { analyte: "AST (SGOT)", value: "212", unit: "U/L", reference: "< 40", flag: "high" },
        { analyte: "ALT (SGPT)", value: "148", unit: "U/L", reference: "< 41", flag: "high" },
        { analyte: "Albumin", value: "3.1", unit: "g/dL", reference: "3.5–5.2", flag: "low" },
      ],
      teaching: { whenToOrder: "Warning signs, hepatomegaly, or before hepatotoxic drugs.", whatItTellsYou: "Dengue hepatitis (AST > ALT); low albumin from leakage." } },
    { id: "rft", priority: "useful", teaching: { whenToOrder: "Warning signs, oliguria, before fluid therapy.", whatItTellsYou: "Renal function, sodium and potassium." } },
    { id: "electrolytes", priority: "useful", teaching: { whenToOrder: "Vomiting, IV fluids.", whatItTellsYou: "Sodium and potassium." } },
    { id: "usg-abdomen", priority: "useful", noMedia: true,
      report: "Gallbladder wall oedematous and thickened (6 mm). Mild ascites. Small right pleural effusion. Liver mildly enlarged with normal echotexture.",
      teaching: { whenToOrder: "Suspected plasma leakage — abdominal pain, tender liver.", whatItTellsYou: "Gallbladder wall oedema, ascites and effusions — objective signs of leakage." } },
    { id: "cxr", priority: "situational",
      media: radiograph("xray", "PA", [{ id: "pleural-effusion", side: "right", severity: 1 }], 15, "Posteroanterior chest radiograph.", "PA erect"),
      report: "Blunting of the right costophrenic angle. Lung fields otherwise clear. Heart size normal.",
      teaching: { whenToOrder: "Breathlessness or suspected effusion.", whatItTellsYou: "Pleural effusion from leakage." } },
    { id: "malaria", priority: "useful", teaching: { whenToOrder: "Every acute febrile illness in endemic season — co-infection happens.", whatItTellsYou: "Excludes malaria." } },
    { id: "widal", priority: "unnecessary", teaching: { whenToOrder: "Rarely useful — single titres mislead.", whatItTellsYou: "Little." } },
    { id: "blood-culture", priority: "unnecessary", teaching: { whenToOrder: "If bacterial sepsis is suspected.", whatItTellsYou: "Bacteraemia." } },
    { id: "procalcitonin", priority: "unnecessary", teaching: { whenToOrder: "Suspected bacterial co-infection.", whatItTellsYou: "Bacterial inflammation." } },
  ],

  therapeutics: [
    { id: "admit", kind: "admit", measureIds: ["admit"], label: "Admit", appropriateness: "ideal",
      praise: "Admitted him — warning signs in the critical phase mean hospital care." },
    { id: "iv-fluids", kind: "drug", drugIds: ["rl", "ns"], label: "IV crystalloid", appropriateness: "ideal",
      vitalsAfter: [{ key: "hr", value: "96" }, { key: "bp", value: "112/82" }, { key: "urine", value: "45" }],
      praise: "Started isotonic crystalloid for warning signs." },
    { id: "paracetamol", kind: "drug", drugIds: ["paracetamol"], label: "Paracetamol", appropriateness: "ideal", doseRange: { min: 500, max: 1000, unit: "mg" } },
    { id: "monitoring", kind: "supportive", measureIds: ["monitor"], label: "Vitals and urine-output monitoring", appropriateness: "ideal" },
    { id: "ors", kind: "drug", drugIds: ["ors"], label: "Oral rehydration", appropriateness: "acceptable" },
    { id: "antiemetic", kind: "drug", drugIds: ["ondansetron", "domperidone", "metoclopramide"], label: "Antiemetic", appropriateness: "acceptable" },
    { id: "ppi", kind: "drug", drugIds: ["pantoprazole", "omeprazole", "rabeprazole", "esomeprazole"], label: "PPI", appropriateness: "neutral" },
    { id: "nsaid", kind: "drug", drugClasses: ["nsaid"], label: "NSAID", appropriateness: "dangerous",
      critique: { what: "Gave an NSAID in dengue.", why: "NSAIDs impair the few platelets left and injure gastric mucosa — bleeding becomes likely.", better: "Paracetamol only (max 3–4 g/day); tepid sponging for fever.", severity: "major" } },
    { id: "platelets", kind: "drug", drugIds: ["platelet-transfusion"], label: "Platelet transfusion", appropriateness: "unnecessary",
      critique: { what: "Transfused platelets.", why: "Prophylactic platelet transfusion does not prevent bleeding or shock in dengue; it adds transfusion risks and volume.", better: "Transfuse only for significant bleeding, or extremely low counts with a bleeding risk.", severity: "moderate" } },
    { id: "steroid", kind: "drug", drugIds: ["dexamethasone", "prednisolone", "methylprednisolone", "hydrocortisone"], label: "Corticosteroid", appropriateness: "unnecessary",
      critique: { what: "Gave a steroid.", why: "Steroids have no proven benefit in dengue and may raise bleeding and infection risk.", better: "Fluids and monitoring.", severity: "minor" } },
    { id: "antibiotic", kind: "drug", drugClasses: ["antibiotic"], label: "Antibiotic", appropriateness: "unnecessary",
      critique: { what: "Started an antibiotic.", why: "Dengue is viral; there was no evidence of bacterial infection.", better: "Reserve antibiotics for documented co-infection.", severity: "minor" } },
    { id: "stop-nsaid", kind: "counsel", label: "Stop NSAIDs — paracetamol only", appropriateness: "ideal",
      concernsDrugs: ["nsaid"],
      match: ["stop combiflam", "no combiflam", "avoid combiflam", "avoid painkillers", "no painkillers", "only paracetamol", "paracetamol only", "avoid nsaid", "avoid nsaids", "no nsaids", "no ibuprofen", "avoid ibuprofen", "stop ibuprofen", "stop painkillers", "dont take combiflam", "do not take combiflam"],
      response: [{ role: "patient", kind: "speech", text: "Okay doctor — only Dolo from now on." }],
      praise: "Stopped the NSAID he had been given by the chemist." },
    { id: "discharge", kind: "discharge", measureIds: ["discharge"], label: "Discharge home", appropriateness: "harmful",
      critique: { what: "Sent him home.", why: "Abdominal pain, persistent vomiting, mucosal bleeding, lethargy, hepatomegaly, oliguria and a rising haematocrit are warning signs — he was entering the critical phase.", better: "Admit, start IV crystalloid, and monitor haematocrit, pulse pressure and urine output.", severity: "major" } },
  ],

  hazards: [
    { id: "dengue-shock", label: "Dengue shock syndrome",
      omission: { byMinute: 300, preventedBy: ["admit"] },
      stages: [
        { afterMin: 0, status: "critical", interrupts: true,
          vitals: [{ key: "bp", value: "94/82" }, { key: "hr", value: "132" }, { key: "rr", value: "26" }, { key: "temp", value: "97.8" }, { key: "urine", value: "0" }],
          observation: { role: "attendant", text: "Doctor, he fainted in the toilet. He's cold and sweaty and doesn't make sense when he talks." },
          examFindings: { crt: "Capillary refill 5 s. Cold, clammy, mottled peripheries.", general: "Restless, sweaty, confused. Petechiae spreading." },
          investigations: { cbc: { rows: [
            { analyte: "Haemoglobin", value: "17.4", unit: "g/dL", reference: "13.0–17.0", flag: "high" },
            { analyte: "Haematocrit", value: "54", unit: "%", reference: "40–50", flag: "critical" },
            { analyte: "Total leucocyte count", value: "3,100", unit: "/µL", reference: "4,000–11,000", flag: "low" },
            { analyte: "Platelets", value: "0.21", unit: "lakh/µL", reference: "1.5–4.5", flag: "critical" },
          ] } },
          patientSays: "(Restless.) Water… so thirsty…" },
        { afterMin: 120, status: "critical",
          vitals: [{ key: "bp", value: "70/52" }, { key: "hr", value: "148" }, { key: "rr", value: "32" }, { key: "spo2", value: "92" }, { key: "gcs", value: "11" }],
          observation: { role: "nurse", text: "BP isn't recording reliably. He's drowsy." } },
        { afterMin: 320, status: "deceased",
          vitals: [{ key: "bp", value: "0/0" }, { key: "hr", value: "0" }, { key: "gcs", value: "3" }],
          observation: { role: "nurse", text: "Cardiac arrest — no return of circulation." } },
      ],
      rescue: [["iv-fluids"], ["admit"]],
      fullRecoveryWindowMin: 75,
      lastRescueMin: 280,
      recovery: [
        { afterMin: 60, status: "guarded", vitals: [{ key: "bp", value: "100/78" }, { key: "hr", value: "114" }, { key: "urine", value: "30" }], patientSays: "A bit better… less dizzy." },
        { afterMin: 720, status: "improving", vitals: [{ key: "bp", value: "112/74" }, { key: "hr", value: "92" }, { key: "urine", value: "60" }], patientSays: "I feel much better today." },
      ],
      review: {
        cause: "Warning signs in the critical phase were not acted on — no admission, no IV fluids, no monitoring.",
        whyItCausedHarm: "In the critical phase (around defervescence, day 3–7) capillaries leak plasma → haemoconcentration → falling preload → narrowing pulse pressure → compensated, then decompensated shock.",
        earliestRescueWindow: "At presentation: warning signs (abdominal pain, persistent vomiting, mucosal bleeding, lethargy, tender liver, oliguria, rising haematocrit) → admit and start IV crystalloid.",
        correctRescueSequence: [
          "Recognise compensated shock — narrow pulse pressure, tachycardia, CRT > 2 s, cold peripheries",
          "Crystalloid bolus 10–20 mL/kg over 15–60 min; reassess after each",
          "Then taper — 10 → 7 → 5 → 3 mL/kg/h — guided by haematocrit, pulse pressure and urine output (≥ 0.5 mL/kg/h)",
          "Haematocrit falling with instability → suspect bleeding → transfuse packed cells",
          "Persistent shock → colloid, ICU; stop fluids 24–48 h after leakage settles to avoid overload",
        ],
        lastRealisticRescueWindow: "Before profound shock — within a few hours of decompensation; prolonged shock leads to organ failure and bleeding.",
      } },
  ],

  followUp: [
    { when: "ideal", status: "recovered",
      lines: [
        { role: "system", kind: "status", text: "Discharge review" },
        { role: "patient", kind: "speech", text: "I'm eating properly again, doctor. No fever for three days. The nurse said my platelets are rising." },
        { role: "system", kind: "finding", text: "Afebrile ×72 h. Platelets 1.1 lakh/µL and rising. Haematocrit 42%. Recovery-phase rash on the legs." },
      ] },
    { when: "acceptable", status: "improving",
      lines: [{ role: "patient", kind: "speech", text: "Better, but I'm still very weak." }] },
    { when: "any", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "I'm recovering slowly, doctor." }] },
  ],

  truth: {
    diagnosis: "Dengue with warning signs",
    qualifier: "Critical phase (day 4, defervescence) — plasma leakage with haemoconcentration, thrombocytopenia, dengue hepatitis; NSAID exposure",
    reasoning: [
      { stage: "History", text: "Four days of high fever with myalgia and retro-orbital pain in October, cases in his PG; fever settling while he worsens — abdominal pain, persistent vomiting, gum bleeding, oliguria, lethargy; took Combiflam." },
      { stage: "Examination", text: "Tachycardia, BP 106/84 (pulse pressure 22), CRT 3 s, tender hepatomegaly, ascites, right basal effusion, petechiae, positive tourniquet test." },
      { stage: "Investigation", text: "NS1 and IgM positive; haematocrit 49% (baseline 42%), platelets 62,000, leucopenia; AST > ALT; USG: gallbladder wall oedema, ascites, effusion." },
      { stage: "Diagnosis", text: "Dengue with warning signs in the critical phase — admit, IV crystalloid, close monitoring, paracetamol only." },
    ],
  },

  rubric: {
    diagnosisAccept: ["dengue with warning signs", "dengue warning signs", "dengue haemorrhagic fever", "dengue hemorrhagic fever", "dhf", "severe dengue", "dengue critical phase", "dengue with plasma leakage", "dengue shock"],
    diagnosisPartial: ["dengue", "dengue fever", "dengue infection", "viral fever", "thrombocytopenia"],
    differentials: ["malaria", "chikungunya", "typhoid", "enteric fever", "leptospirosis", "scrub typhus", "covid", "influenza", "viral hepatitis", "sepsis", "zika"],
    idealTreatment: [["admit"], ["iv-fluids"], ["paracetamol"], ["stop-nsaid"], ["monitoring"]],
    expertActionCount: 18,
    expectsReassessment: true,
    definitiveTreatment: { ids: ["admit"], byMinute: 120, label: "Admission" },
    misses: {
      fever: { what: "Did not establish the day of illness and the fever trend.", why: "Day 4 with fever settling while he worsens is the critical phase — the most dangerous time in dengue.", better: "Ask which day of fever it is and whether it is settling.", severity: "major" },
      vomiting: { what: "Did not ask about vomiting.", why: "Persistent vomiting is a warning sign and makes oral rehydration impossible.", better: "Ask about vomiting and oral intake in every febrile patient.", severity: "moderate" },
      bleeding: { what: "Did not ask about bleeding.", why: "Mucosal bleeding is a warning sign.", better: "Ask about gums, nose, stools, urine and skin spots.", severity: "moderate" },
      urine: { what: "Did not ask about urine output.", why: "Oliguria is an early sign of falling perfusion.", better: "Ask when they last passed urine and how much.", severity: "moderate" },
      meds: { what: "Did not ask what he had taken.", why: "He had taken Combiflam (ibuprofen) — an NSAID with a falling platelet count.", better: "Ask about every tablet, especially from the chemist, and stop NSAIDs.", severity: "major" },
      crt: { what: "Did not assess perfusion.", why: "CRT, peripheral temperature and pulse pressure detect compensated shock before the BP falls.", better: "Check CRT and pulse pressure at every assessment.", severity: "major" },
      cbc: { what: "No blood count.", why: "Haematocrit and platelets track leakage and guide fluids.", better: "CBC at presentation and serially.", severity: "major" },
      dengue: { what: "Dengue was not confirmed.", why: "NS1/IgM confirm the diagnosis in season.", better: "NS1 (day 1–5) ± IgM (from day 5).", severity: "moderate" },
      admit: { what: "Did not admit.", why: "Warning signs mean the patient needs IV fluids and monitoring in hospital.", better: "Admit every patient with warning signs.", severity: "major" },
      "iv-fluids": { what: "No IV fluids.", why: "With vomiting, oliguria and haemoconcentration he cannot maintain his intravascular volume orally.", better: "Isotonic crystalloid 5–7 mL/kg/h for 1–2 h, then taper by haematocrit and urine output.", severity: "major" },
      "stop-nsaid": { what: "The NSAID was not stopped.", why: "Ibuprofen with thrombocytopenia invites bleeding.", better: "Paracetamol only; tell the patient and family explicitly.", severity: "major" },
      monitoring: { what: "No monitoring plan.", why: "The critical phase is managed by numbers — pulse pressure, haematocrit and urine output.", better: "Hourly vitals and urine output; haematocrit every 6–12 hours.", severity: "moderate" },
    },
    strengths: {
      fever: "Pinned down day 4 and defervescence — the critical phase.",
      meds: "Found the Combiflam.",
      bleeding: "Asked about bleeding.",
      urine: "Asked about urine output.",
      crt: "Assessed perfusion, not just BP.",
      tourniquet: "Performed a tourniquet test.",
      cbc: "Ordered a CBC to track haematocrit and platelets.",
      dengue: "Confirmed with NS1/IgM.",
      admit: "Admitted for warning signs.",
      "iv-fluids": "Started isotonic crystalloid.",
    },
  },

  teaching: {
    patientBand: "warning",
    severityBands: [
      { id: "group-a", label: "Dengue without warning signs",
        recognition: ["Fever with 2 of: aches, headache, retro-orbital pain, rash, leucopenia, positive tourniquet", "Drinking well, passing urine, no warning signs"],
        investigation: ["CBC; NS1 (day 1–5) or IgM (from day 5)"],
        treatment: ["Home care: oral fluids 2.5–3 L/day, paracetamol (max 3 g/day), rest", "No NSAIDs, no steroids, no antibiotics"],
        followUp: ["Daily review (CBC) from day 3 until 48 h after defervescence; return immediately with any warning sign"] },
      { id: "warning", label: "Dengue with warning signs",
        recognition: ["Abdominal pain, persistent vomiting, mucosal bleeding, lethargy/restlessness", "Liver > 2 cm, clinical fluid accumulation", "Rising haematocrit with rapidly falling platelets"],
        investigation: ["CBC 6–12 hourly; LFT, RFT, electrolytes; USG for leakage"],
        treatment: ["Admit; isotonic crystalloid 5–7 mL/kg/h × 1–2 h → 3–5 → 2–3 mL/kg/h", "Titrate to pulse pressure, haematocrit and urine ≥ 0.5 mL/kg/h", "Paracetamol only"],
        followUp: ["Fluids usually needed 24–48 h; stop when leakage settles"] },
      { id: "severe", label: "Severe dengue",
        recognition: ["Shock — narrow pulse pressure ≤ 20, hypotension, CRT > 2 s, cold peripheries", "Severe bleeding; organ impairment (AST/ALT > 1000, altered sensorium, myocarditis)"],
        investigation: ["Serial haematocrit, lactate, ABG, coagulation"],
        treatment: ["Crystalloid bolus 10–20 mL/kg; repeat by response", "Colloid if refractory; PRBC if haematocrit falls with instability (bleeding)", "ICU care"],
        followUp: ["Continuous monitoring; watch for overload in recovery"] },
      { id: "recovery", label: "Recovery-phase complications",
        recognition: ["Fluid overload as leaked plasma returns — breathlessness, crackles, effusions", "Bradycardia, 'islands of white in a sea of red' rash"],
        investigation: ["CXR, haematocrit"],
        treatment: ["Stop IV fluids; diuretic if overloaded"],
        followUp: ["Fatigue may persist for weeks"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Paracetamol", brand: "Dolo 650", dose: "650 mg (10–15 mg/kg)", route: "PO", frequency: "6–8 hourly as needed (max 3–4 g/day)", duration: "While febrile",
        indication: "Fever and pain in dengue",
        mechanism: "Central COX inhibition → resets the hypothalamic set-point and raises the pain threshold, without affecting platelets.",
        whyItWorks: "Controls symptoms without the bleeding risk of NSAIDs.",
        avoidWhen: ["Liver failure; reduce dose with marked hepatitis"],
        adverseEffects: ["Hepatotoxicity in overdose"],
        monitoring: ["Total daily dose — include all combination products"] },
      { generic: "Ringer lactate", brand: "Ringer Lactate (Fresenius Kabi)", dose: "5–7 mL/kg/h initially", route: "IV", frequency: "Continuous infusion, titrated", duration: "Usually 24–48 h",
        indication: "Dengue with warning signs or shock",
        mechanism: "Isotonic crystalloid → expands intravascular volume → restores preload and perfusion.",
        whyItWorks: "Replaces leaking plasma volume until capillary integrity returns.",
        avoidWhen: ["Fluid overload, recovery phase"],
        adverseEffects: ["Pulmonary oedema and effusions if over-given"],
        monitoring: ["Pulse pressure, HR, CRT, urine output, haematocrit 6–12 hourly"] },
      { generic: "Oral rehydration salts", brand: "Electral", dose: "1 sachet in 1 L water", route: "PO", frequency: "Sips through the day", duration: "Febrile and critical phase (if tolerating orally)",
        indication: "Oral rehydration in dengue without warning signs",
        mechanism: "Sodium–glucose co-transport → water absorption in the gut.",
        whyItWorks: "Maintains intravascular volume at home.",
        avoidWhen: ["Persistent vomiting — needs IV fluids"],
        adverseEffects: ["None significant"],
        monitoring: ["Urine output at least every 4–6 h"] },
    ],
    routines: [
      { label: "Critical-phase fluid plan (warning signs)",
        steps: [
          { order: 1, step: "Start isotonic crystalloid", howMuch: "5–7 mL/kg/h for 1–2 h (≈ 350–450 mL/h for 64 kg)" },
          { order: 2, step: "Reassess", note: "HR, BP and pulse pressure, CRT, urine output, haematocrit" },
          { order: 3, step: "Taper if improving", howMuch: "3–5 mL/kg/h for 2–4 h, then 2–3 mL/kg/h" },
          { order: 4, step: "If worsening", note: "Repeat haematocrit — rising: increase fluids; falling with instability: think bleeding → transfuse" },
          { order: 5, step: "Stop", note: "When stable for 24–48 h and the patient can drink — prevent overload" },
        ] },
      { label: "Home care (no warning signs)",
        steps: [
          { order: 1, step: "Drink 2.5–3 litres a day", note: "ORS, coconut water, juices, soups" },
          { order: 2, step: "Paracetamol only", note: "No Combiflam, ibuprofen, diclofenac or aspirin" },
          { order: 3, step: "Daily CBC from day 3" },
          { order: 4, step: "Return immediately", note: "Abdominal pain, vomiting, bleeding, drowsiness, not passing urine for 6 h" },
        ] },
    ],
    followUp: {
      interval: "Daily while admitted; discharge 24–48 h after shock resolves and platelets rise",
      reassess: ["Haematocrit trend", "Platelets", "Urine output", "Signs of overload in recovery"],
      redFlags: ["Cold extremities, narrow pulse pressure", "Bleeding, black stools", "Breathlessness in recovery (overload)"],
      whenToEscalate: ["Shock not responding to two boluses → ICU, colloid", "Falling haematocrit with instability → transfusion", "Organ impairment → ICU"],
    },
    treatmentFailure: { steps: [
      "Check the phase — critical phase lasts 24–48 h; expect leakage",
      "Check the diagnosis — co-infection (malaria, leptospirosis, scrub typhus)",
      "Check severity — pulse pressure, lactate, haematocrit trend",
      "Check complications — occult bleeding, overload, myocarditis",
      "Alternative — colloid for refractory shock; blood for bleeding",
      "Escalate — ICU",
    ] },
    pearl: "Dengue kills in the critical phase — usually day 3 to 7, just as the fever falls. The fever coming down is not good news until the haematocrit, the pulse pressure and the urine output say so. Paracetamol only — and always ask what the chemist already gave.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "Sent home on day 4 with warning signs, he would likely have returned in dengue shock that night. Given ibuprofen, he would have bled.",
      sequence: ["Admit with warning signs", "Crystalloid 5–7 mL/kg/h, titrated", "Shock: 10–20 mL/kg bolus, reassess", "Paracetamol only"],
    },
  },
};
