import type { ClinicalCaseDefinition } from "../case-definition";
import { ecg } from "./media";

export const medPad: ClinicalCaseDefinition = {
  id: "med-pad-leriche-01",
  specialty: "Medicine",
  track: "opd",
  level: "college",
  setting: "OPD",
  weight: 4,
  difficulty: 2,
  patient: { name: "Sanjay", age: 47, sex: "Male", city: "Janakpuri, Delhi", occupation: "Accounts manager at a private firm", context: "Medicine OPD" },
  arrivalMinuteOfDay: 14 * 60 + 2,
  briefing: "A 47-year-old man has come to the Medicine OPD. His wife waits outside.",
  opening: [
    { role: "patient", kind: "speech", text: "Namaste, doctor. I haven't been feeling well for the past few weeks." },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "158/96" },
    hr: { key: "hr", value: "88" },
    rr: { key: "rr", value: "16" },
    temp: { key: "temp", value: "98.4" },
    spo2: { key: "spo2", value: "97" },
    rbs: { key: "rbs", value: "236" },
    weight: { key: "weight", value: "82" },
    height: { key: "height", value: "168" },
    bmi: { key: "bmi", value: "29.1" },
  },
  profile: { currentDrugs: ["metformin", "isosorbide-dinitrate"] },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential",
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened", "whats wrong", "what is wrong", "not feeling well", "unwell"],
      reply: "I just don't feel right, doctor. Tired all the time. My wife said I should finally get checked.",
      fact: "Unwell for weeks — fatigue" },
    { id: "fatigue", group: "hpi", label: "Fatigue & osmotic symptoms", importance: "useful", abnormal: true,
      match: ["tired", "tiredness", "fatigue", "weak", "weakness", "energy", "how long", "since when", "tell me more", "how are you feeling", "drained", "thirst", "thirsty", "urine", "urination", "passing urine", "frequency", "nocturia", "polyuria", "at night"],
      reply: "For about two months I feel completely drained by evening. I'm thirsty all the time, and I get up three or four times at night to pass urine.",
      fact: "Fatigue, polydipsia, nocturia ×2 months" },
    { id: "weight", group: "systemic", label: "Weight & appetite", importance: "minor",
      match: ["weight loss", "losing weight", "lost weight", "weight", "appetite"],
      reply: "I think I've lost two or three kilos without trying. Appetite is fine.",
      fact: "~2–3 kg unintentional weight loss" },
    { id: "claudication", group: "hpi", label: "Exertional leg pain", importance: "essential", abnormal: true,
      match: ["pain", "any pain", "legs", "leg", "leg pain", "calf", "calves", "thigh", "thighs", "hip", "hips", "buttock", "buttocks", "cramp", "cramps", "walking", "walk", "anything else", "any other problem", "other complaints", "any other complaint"],
      reply: "Yes — when I walk, my hips and both thighs start aching, like a cramp. I have to stop. After two or three minutes of standing it goes away, and I can walk again.",
      fact: "Exertional buttock & thigh pain, both sides; relieved by 2–3 min rest" },
    { id: "walking-distance", group: "hpi", label: "Walking tolerance", importance: "essential", abnormal: true,
      match: ["how far", "distance", "walking distance", "how much can you walk", "walking tolerance", "how many metres", "how many meters", "how long can you walk", "stairs", "climb", "exercise tolerance"],
      reply: "A year ago I'd walk to the market and back — about a kilometre — without any problem. Now I have to stop after about two hundred metres. Stairs are worse.",
      fact: "Claudication distance ~200 m (was > 1 km a year ago)" },
    { id: "rest-pain", group: "hpi", label: "Rest pain", importance: "useful",
      match: ["rest pain", "pain at rest", "pain at night", "while sleeping", "night pain", "when lying", "pain when resting", "dangle", "hang your legs"],
      reply: "No. When I'm resting, there's no pain at all.",
      fact: "No rest pain" },
    { id: "ulcers", group: "hpi", label: "Wounds / ulcers", importance: "useful",
      match: ["ulcer", "ulcers", "wound", "wounds", "non healing", "cut", "injury", "black toe", "gangrene", "discolouration", "colour change"],
      reply: "No wounds, doctor. Nothing like that.",
      fact: "No ulcers or tissue loss" },
    { id: "neuropathy", group: "systemic", label: "Sensory symptoms", importance: "useful", abnormal: true,
      match: ["numbness", "numb", "tingling", "burning feet", "pins and needles", "sensation", "feel the floor"],
      reply: "Sometimes my feet tingle at night, mostly the soles.",
      fact: "Nocturnal tingling of soles" },
    { id: "chest", group: "systemic", label: "Chest symptoms", importance: "essential", abnormal: true,
      match: ["chest pain", "chest", "heaviness", "angina", "breathless", "breathlessness", "shortness of breath", "palpitations", "heart"],
      reply: "Sometimes when I climb stairs quickly, I get a heaviness in the middle of my chest. It goes away when I stop. Twice I put the tablet under my tongue that our local doctor gave me.",
      fact: "Exertional central chest heaviness, relieved by rest / SL nitrate" },
    { id: "past", group: "past", label: "Comorbidities", importance: "essential", abnormal: true,
      match: ["comorbidities", "comorbidity", "diabetes", "sugar", "past history", "medical history", "illness", "any disease", "bp", "blood pressure", "hypertension", "thyroid", "heart disease", "known case", "medical problems", "other conditions"],
      reply: "Yes. I have type 2 diabetes — for six years now. Two years ago a doctor said my BP was high, but I never started tablets for it.",
      fact: "Type 2 diabetes × 6 y; raised BP noted 2 y ago — never treated" },
    { id: "meds", group: "medication", label: "Medications", importance: "essential", abnormal: true,
      match: ["medicines", "medicine", "medication", "tablets", "tablet", "taking any", "drugs", "what do you take", "treatment for diabetes", "current medicines", "sublingual", "under the tongue", "under your tongue", "chest pain tablet", "prescription"],
      reply: "Metformin 500, twice a day — though honestly I miss the evening one quite often. And the small tablet for chest heaviness — Sorbitrate. I keep it in my wallet. I've used it twice in the last three months.",
      fact: "Metformin 500 mg BD (poor adherence); isosorbide dinitrate 5 mg SL SOS — used twice in 3 months" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful",
      match: ["allergy", "allergic", "allergies", "drug reaction", "reaction to any"],
      reply: "No allergies, doctor.",
      fact: "No known drug allergies" },
    { id: "sexual", group: "sexual", label: "Sexual history", importance: "essential", abnormal: true,
      match: ["sexual", "erection", "erections", "erectile", "intimacy", "sexual problems", "sexual health", "married life", "performance", "impotence", "libido", "relations", "physical relations"],
      reply: "(Lowers his voice.) Doctor… for the last six months or so I've had trouble with erections. It's been affecting things at home. I wanted to ask if there's some tablet for it.",
      fact: "Erectile dysfunction × 6 months; asking for a tablet" },
    { id: "smoking", group: "social", label: "Smoking", importance: "essential", abnormal: true,
      match: ["smoke", "smoking", "cigarettes", "cigarette", "bidi", "tobacco", "gutka", "pan", "chew", "nicotine"],
      reply: "About twelve cigarettes a day, since I was twenty-two. I've tried to quit a couple of times.",
      fact: "Smoker — 12/day × 25 years (~15 pack-years)" },
    { id: "alcohol", group: "social", label: "Alcohol", importance: "useful",
      match: ["alcohol", "drink", "drinking", "beer", "whisky", "peg", "pegs"],
      reply: "Two pegs on weekends, sometimes.",
      fact: "Alcohol ~2 drinks at weekends" },
    { id: "diet", group: "diet", label: "Diet", importance: "useful",
      match: ["diet", "eat", "eating", "food", "meals", "breakfast", "what do you eat", "sweets"],
      reply: "Parathas in the morning, rice and dal, a sweet after dinner. I eat out a lot for work.",
      fact: "High refined-carbohydrate diet; frequent eating out" },
    { id: "activity", group: "social", label: "Physical activity", importance: "minor",
      match: ["exercise", "physical activity", "active", "gym", "sports", "sedentary", "desk"],
      reply: "No proper exercise. I sit at a desk all day.",
      fact: "Sedentary" },
    { id: "family", group: "family", label: "Family history", importance: "useful", abnormal: true,
      match: ["family", "father", "mother", "siblings", "brother", "sister", "parents", "heart attack in the family", "runs in"],
      reply: "My father had a heart attack at fifty-eight. My mother is diabetic.",
      fact: "Father — MI at 58; mother — diabetes" },
    { id: "vision", group: "systemic", label: "Vision", importance: "minor",
      match: ["vision", "eyes", "eyesight", "blurred", "blurring", "see clearly"],
      reply: "Reading has become a little blurred. I thought it was just age.",
      fact: "Blurred near vision" },
  ],

  exam: [
    { id: "general", group: "general-exam", label: "General examination", importance: "minor", abnormal: true, match: [],
      finding: "Conscious, oriented, comfortable. Central obesity. No pallor, icterus, cyanosis, clubbing, lymphadenopathy or pedal oedema." },
    { id: "peripheral-pulses", group: "systemic-exam", label: "Peripheral pulses", importance: "essential", abnormal: true,
      match: ["peripheral pulses", "foot pulses", "pedal pulses", "dorsalis pedis", "posterior tibial", "femoral pulse", "femoral pulses", "femorals", "popliteal pulse", "popliteal", "leg pulses", "dpa", "pta", "lower limb pulses", "pulses in the legs", "pulses of the legs", "check pulses", "palpate pulses", "radio femoral delay", "radiofemoral"],
      finding: "Femoral pulses feeble on both sides, with a bruit over each femoral artery. Popliteal, dorsalis pedis and posterior tibial pulses not palpable bilaterally. Radial pulses normal.",
      fact: "Feeble femorals with bruits; distal pulses absent bilaterally" },
    { id: "feet", group: "local-exam", label: "Legs & feet", importance: "essential", abnormal: true, match: [],
      finding: "Skin over both shins shiny and hairless. Toenails thickened. Feet cool to touch. Capillary refill in the toes 4 s. No ulcers, gangrene or callosities.",
      fact: "Trophic changes; cool feet; CRT 4 s; no tissue loss" },
    { id: "buerger", group: "local-exam", label: "Buerger's test", importance: "useful", abnormal: true,
      match: ["buerger", "buergers", "buerger test", "buergers test", "leg elevation", "elevate the legs", "dependent rubor", "pallor on elevation"],
      finding: "Both feet blanch at about 40° of elevation (Buerger's angle ~40°). Dependent rubor when the legs hang over the couch.",
      fact: "Buerger's angle ~40°; dependent rubor" },
    { id: "abdomen", group: "systemic-exam", label: "Abdomen", importance: "useful", abnormal: true, match: [],
      finding: "Soft, non-tender. No organomegaly. A bruit is audible just above and to the left of the umbilicus.",
      fact: "Periumbilical bruit" },
    { id: "cns", group: "systemic-exam", label: "Neurological", importance: "useful", abnormal: true, match: [],
      finding: "Higher functions normal. Power 5/5 in all limbs. Ankle reflexes diminished bilaterally. Vibration sense reduced at both great toes. 10 g monofilament felt at 7 of 10 sites on each sole.",
      fact: "Reduced ankle jerks, vibration and monofilament sensation" },
    { id: "eyes", group: "systemic-exam", label: "Eyes & fundus", importance: "useful", abnormal: true, match: [],
      finding: "Pupils equal and reactive. Fundus: scattered dot-blot haemorrhages and hard exudates in both eyes; no new vessels.",
      fact: "Dot-blot haemorrhages and hard exudates, both eyes" },
    { id: "cvs", group: "systemic-exam", label: "Cardiovascular", importance: "useful", match: [],
      finding: "Apex in the 5th intercostal space, mid-clavicular line, heaving in character. S1 and S2 normal. No murmurs.",
      fact: "Heaving apex; no murmurs" },
    { id: "genital", group: "local-exam", label: "Genital", importance: "minor", match: [],
      finding: "Performed with a chaperone. Normal external genitalia. Testes normal in size. No penile plaques.",
      fact: "Normal genital examination" },
    { id: "waist", group: "general-exam", label: "Waist circumference", importance: "minor", abnormal: true,
      match: ["waist", "waist circumference", "abdominal girth", "girth"],
      finding: "Waist circumference 102 cm.",
      fact: "Waist 102 cm" },
  ],

  investigations: [
    { id: "abi", priority: "essential",
      rows: [
        { analyte: "Right ABI", value: "0.62", reference: "1.00–1.40", flag: "low" },
        { analyte: "Left ABI", value: "0.58", reference: "1.00–1.40", flag: "low" },
      ],
      report: "Brachial systolic 162 (R) / 158 (L) mmHg. Highest ankle systolic 100 (R) / 94 (L) mmHg.",
      teaching: { whenToOrder: "Any patient with exertional leg pain, absent pulses, non-healing foot wounds — and every diabetic over 50 or smoker over 40.", whatItTellsYou: "ABI < 0.90 confirms PAD; 0.4–0.9 claudication range; < 0.4 critical. Diabetic calcification can falsely raise it (> 1.4) — then use toe pressures." } },
    { id: "arterial-doppler", priority: "useful",
      report: "Monophasic, dampened waveforms from both common femoral arteries distally. High-grade narrowing of the distal abdominal aorta extending into both common iliac arteries, with collateral flow. Femoro-popliteal segments patent with post-stenotic waveforms.",
      teaching: { whenToOrder: "After an abnormal ABI, to localise disease and plan any intervention.", whatItTellsYou: "Level and severity of stenosis — here, aorto-iliac." } },
    { id: "hba1c", priority: "essential", rows: [{ analyte: "HbA1c", value: "9.4", unit: "%", reference: "< 5.7", flag: "high" }],
      teaching: { whenToOrder: "Every diabetic at diagnosis and every 3 months until at target.", whatItTellsYou: "Average glucose over ~3 months." } },
    { id: "fbs", priority: "useful", rows: [{ analyte: "Fasting plasma glucose", value: "178", unit: "mg/dL", reference: "70–99", flag: "high" }],
      teaching: { whenToOrder: "To titrate therapy alongside HbA1c.", whatItTellsYou: "Basal glycaemic control." } },
    { id: "ppbs", priority: "useful", rows: [{ analyte: "2-h post-prandial glucose", value: "264", unit: "mg/dL", reference: "< 140", flag: "high" }],
      teaching: { whenToOrder: "To titrate therapy.", whatItTellsYou: "Post-meal excursions." } },
    { id: "lipid", priority: "essential",
      rows: [
        { analyte: "Total cholesterol", value: "238", unit: "mg/dL", reference: "< 200", flag: "high" },
        { analyte: "LDL cholesterol", value: "158", unit: "mg/dL", reference: "< 100", flag: "high" },
        { analyte: "HDL cholesterol", value: "34", unit: "mg/dL", reference: "> 40", flag: "low" },
        { analyte: "Triglycerides", value: "246", unit: "mg/dL", reference: "< 150", flag: "high" },
        { analyte: "Non-HDL cholesterol", value: "204", unit: "mg/dL", reference: "< 130", flag: "high" },
      ],
      teaching: { whenToOrder: "All patients with diabetes or vascular disease.", whatItTellsYou: "Baseline before high-intensity statin; target LDL < 55 mg/dL in very-high-risk patients." } },
    { id: "rft", priority: "essential",
      rows: [
        { analyte: "Urea", value: "32", unit: "mg/dL", reference: "15–40", flag: "normal" },
        { analyte: "Creatinine", value: "1.0", unit: "mg/dL", reference: "0.7–1.3", flag: "normal" },
        { analyte: "Sodium", value: "138", unit: "mEq/L", reference: "135–145", flag: "normal" },
        { analyte: "Potassium", value: "4.4", unit: "mEq/L", reference: "3.5–5.1", flag: "normal" },
        { analyte: "eGFR", value: "88", unit: "mL/min/1.73m²", reference: "> 90", flag: "low" },
      ],
      teaching: { whenToOrder: "Before ACE inhibitors/ARBs, SGLT2 inhibitors and metformin dose changes.", whatItTellsYou: "Renal function and potassium." } },
    { id: "uacr", priority: "useful", rows: [{ analyte: "UACR", value: "86", unit: "mg/g", reference: "< 30", flag: "high" }],
      teaching: { whenToOrder: "Yearly in every diabetic.", whatItTellsYou: "Albuminuria — early diabetic kidney disease and a strong indication for ACEi/ARB and SGLT2 inhibitors." } },
    { id: "urine-rm", priority: "situational",
      rows: [
        { analyte: "Appearance", value: "Pale yellow, clear", flag: "normal" },
        { analyte: "Protein", value: "Trace", reference: "Nil", flag: "high" },
        { analyte: "Glucose", value: "2+", reference: "Nil", flag: "high" },
        { analyte: "Ketones", value: "Nil", reference: "Nil", flag: "normal" },
        { analyte: "Pus cells", value: "1–2", unit: "/hpf", reference: "0–5", flag: "normal" },
      ],
      teaching: { whenToOrder: "Routine in diabetes.", whatItTellsYou: "Glycosuria, ketonuria, proteinuria, infection." } },
    { id: "ecg", priority: "useful",
      media: ecg({ rate: 88, rhythm: "sinus", morphology: { qrsScale: { V1: 1.5, V2: 1.4, V5: 1.6, V6: 1.4, aVL: 1.3, I: 1.2 } } }, "Twelve-lead ECG at 88 per minute."),
      report: "Rate 88/min. PR 162 ms. QRS 92 ms. QTc 418 ms. Axis +20°. SV1 + RV5 = 38 mm.",
      teaching: { whenToOrder: "Exertional chest symptoms, hypertension, diabetes with vascular disease.", whatItTellsYou: "LVH, prior infarction, ischaemia, arrhythmia." } },
    { id: "vit-b12", priority: "useful", rows: [{ analyte: "Vitamin B12", value: "182", unit: "pg/mL", reference: "211–911", flag: "low" }],
      teaching: { whenToOrder: "Long-term metformin users, especially with neuropathic symptoms.", whatItTellsYou: "Metformin-associated B12 deficiency, which worsens neuropathy." } },
    { id: "echo", priority: "situational",
      report: "Concentric LV hypertrophy (IVS 12 mm). LVEF 58%. Grade I diastolic dysfunction. No regional wall motion abnormality.",
      teaching: { whenToOrder: "Exertional chest symptoms or LVH on ECG; before cilostazol if heart failure is possible.", whatItTellsYou: "LV function, hypertrophy, wall motion." } },
    { id: "ct-angio", name: "CT angiography — aorta & lower limbs", short: "CT angiography", category: "imaging",
      match: ["ct angiography", "cta", "ct angio", "angiography", "peripheral angiography", "angiogram", "dsa", "digital subtraction"],
      turnaroundMin: 120, cost: 12000, priority: "situational",
      report: "Long-segment severe stenosis of the infrarenal aorta extending into both common iliac arteries, with near-occlusion on the left. Extensive lumbar and pelvic collaterals. Femoro-popliteal and tibial vessels opacify via collaterals.",
      teaching: { whenToOrder: "When revascularisation is being planned for lifestyle-limiting claudication or limb-threatening ischaemia — not at the first visit.", whatItTellsYou: "Anatomy for endovascular or surgical repair." } },
    { id: "troponin", priority: "unnecessary", teaching: { whenToOrder: "Acute chest pain or suspected ACS.", whatItTellsYou: "Myocardial injury." } },
    { id: "tft", priority: "unnecessary", teaching: { whenToOrder: "Symptoms or signs of thyroid disease.", whatItTellsYou: "Thyroid status." } },
    { id: "cxr", priority: "unnecessary", teaching: { whenToOrder: "Respiratory symptoms or heart failure signs.", whatItTellsYou: "Lungs and heart size." } },
  ],

  therapeutics: [
    { id: "antiplatelet", kind: "drug", drugIds: ["clopidogrel", "aspirin"], label: "Single antiplatelet", appropriateness: "ideal",
      doseRange: { min: 75, max: 150, unit: "mg" } },
    { id: "atorvastatin-hi", kind: "drug", drugIds: ["atorvastatin"], label: "High-intensity atorvastatin", appropriateness: "ideal", doseRange: { min: 40, max: 80, unit: "mg" } },
    { id: "rosuvastatin-hi", kind: "drug", drugIds: ["rosuvastatin"], label: "High-intensity rosuvastatin", appropriateness: "ideal", doseRange: { min: 20, max: 40, unit: "mg" } },
    { id: "raas", kind: "drug", drugIds: ["telmisartan", "losartan", "olmesartan", "ramipril", "enalapril"], label: "ACE inhibitor / ARB", appropriateness: "ideal" },
    { id: "ccb", kind: "drug", drugIds: ["amlodipine", "cilnidipine"], label: "Calcium-channel blocker", appropriateness: "acceptable" },
    { id: "thiazide", kind: "drug", drugIds: ["chlorthalidone", "hydrochlorothiazide", "indapamide"], label: "Thiazide-like diuretic", appropriateness: "acceptable" },
    { id: "beta-blocker", kind: "drug", drugIds: ["metoprolol", "bisoprolol", "atenolol"], label: "Cardioselective β-blocker", appropriateness: "acceptable" },
    { id: "sglt2", kind: "drug", drugIds: ["dapagliflozin", "empagliflozin"], label: "SGLT2 inhibitor", appropriateness: "ideal" },
    { id: "glp1", kind: "drug", drugIds: ["semaglutide"], label: "GLP-1 receptor agonist", appropriateness: "ideal" },
    { id: "metformin", kind: "drug", drugIds: ["metformin"], label: "Metformin (optimised)", appropriateness: "acceptable" },
    { id: "dpp4", kind: "drug", drugIds: ["sitagliptin", "vildagliptin", "teneligliptin"], label: "DPP-4 inhibitor", appropriateness: "acceptable" },
    { id: "sulfonylurea", kind: "drug", drugIds: ["glimepiride", "gliclazide"], label: "Sulfonylurea", appropriateness: "acceptable" },
    { id: "insulin", kind: "drug", drugClasses: ["insulin"], label: "Insulin", appropriateness: "unnecessary",
      critique: { what: "Started insulin at the first visit.", why: "HbA1c 9.4% without ketosis or catabolic symptoms can be controlled orally; agents with cardiovascular and renal benefit matter more here.", better: "Optimise metformin, add an SGLT2 inhibitor (± GLP-1 RA); reassess in 3 months.", severity: "minor" } },
    { id: "cilostazol", kind: "drug", drugIds: ["cilostazol"], label: "Cilostazol", appropriateness: "acceptable",
      praise: "Considered cilostazol for symptom relief, with no heart failure to contraindicate it." },
    { id: "pentoxifylline", kind: "drug", drugIds: ["pentoxifylline"], label: "Pentoxifylline", appropriateness: "unnecessary",
      critique: { what: "Prescribed pentoxifylline.", why: "It is barely better than placebo for walking distance.", better: "Supervised exercise first; cilostazol if symptoms remain lifestyle-limiting.", severity: "minor" } },
    { id: "anticoagulant", kind: "drug", drugClasses: ["anticoagulant"], label: "Anticoagulant", appropriateness: "harmful",
      critique: { what: "Started an anticoagulant.", why: "Full anticoagulation adds bleeding risk without benefit in stable claudication.", better: "Single antiplatelet + high-intensity statin.", severity: "major" } },
    { id: "pde5", kind: "drug", drugIds: ["sildenafil", "tadalafil"], label: "PDE-5 inhibitor", appropriateness: "dangerous",
      critique: { what: "Prescribed a PDE-5 inhibitor for erectile dysfunction.", why: "He carries sublingual isosorbide dinitrate for exertional chest heaviness. Combined with a PDE-5 inhibitor, nitrates cause profound, prolonged hypotension.", better: "Address ED as a vascular symptom: control risk factors, stop smoking, evaluate the angina; avoid PDE-5 inhibitors while nitrates may be used.", severity: "major" } },
    { id: "nrt", kind: "drug", drugIds: ["nicotine-replacement", "bupropion"], label: "Pharmacotherapy for smoking cessation", appropriateness: "ideal" },
    { id: "b12", kind: "drug", drugIds: ["methylcobalamin"], label: "Vitamin B12 replacement", appropriateness: "acceptable" },
    { id: "smoking-cessation", kind: "counsel", label: "Smoking cessation", appropriateness: "ideal",
      match: ["quit smoking", "stop smoking", "smoking cessation", "give up smoking", "leave smoking", "no smoking", "stop cigarettes", "quit cigarettes", "stop the cigarettes", "must stop smoking", "cessation"],
      response: [{ role: "patient", kind: "speech", text: "I know, doctor. I'll really try this time. Is there something that helps with the craving?" }],
      praise: "Made smoking cessation the centrepiece — the single most effective intervention for PAD." },
    { id: "exercise", kind: "counsel", label: "Structured walking programme", appropriateness: "ideal",
      match: ["exercise", "walking programme", "walking program", "walk until pain", "walk till pain", "walk until the pain", "supervised exercise", "walking exercise", "walk daily", "exercise therapy", "walk every day", "walking daily", "structured exercise", "keep walking"],
      response: [{ role: "patient", kind: "speech", text: "So I should walk even though it hurts — stop, rest, then walk again?" }],
      praise: "Prescribed a structured walking programme — as effective as angioplasty for claudication." },
    { id: "foot-care", kind: "counsel", label: "Diabetic foot care", appropriateness: "acceptable",
      match: ["foot care", "inspect feet", "inspect your feet", "check your feet", "footwear", "dont walk barefoot", "do not walk barefoot", "proper footwear", "diabetic footwear", "look at your feet"],
      praise: "Taught diabetic foot care — PAD and neuropathy together make foot ulcers likely." },
    { id: "diet-counsel", kind: "counsel", label: "Diet counselling", appropriateness: "acceptable",
      match: ["diet", "reduce sugar", "low salt", "reduce salt", "avoid sweets", "cut down", "dietician", "diet advice", "less oil", "healthy eating", "weight loss", "lose weight"] },
    { id: "avoid-nitrate-pde5", kind: "counsel", label: "Avoid PDE-5 inhibitors with nitrates", appropriateness: "acceptable",
      concernsDrugs: ["pde5"],
      match: ["avoid sildenafil", "no sildenafil", "avoid viagra", "not with sorbitrate", "never with sorbitrate", "cannot take sildenafil", "cant take sildenafil", "dangerous with sorbitrate"],
      response: [{ role: "patient", kind: "speech", text: "I didn't know those two tablets could react. Thank you for telling me." }],
      praise: "Explicitly warned against PDE-5 inhibitors with nitrates." },
    { id: "vascular-referral", kind: "referral", label: "Vascular surgery referral", appropriateness: "acceptable",
      match: ["vascular surgeon", "vascular surgery", "refer to vascular", "vascular referral", "vascular opinion", "vascular consult"],
      praise: "Referred to vascular surgery for lifestyle-limiting aorto-iliac disease." },
    { id: "cardiology-referral", kind: "referral", label: "Cardiology referral", appropriateness: "acceptable",
      match: ["cardiology", "cardiologist", "refer to cardiology", "cardiology referral", "cardiology opinion", "stress test", "tmt", "stress echo", "treadmill"],
      praise: "Arranged cardiac evaluation for exertional angina — PAD patients usually have coronary disease." },
    { id: "eye-referral", kind: "referral", label: "Ophthalmology referral", appropriateness: "acceptable",
      match: ["ophthalmology", "ophthalmologist", "eye specialist", "retina", "eye referral", "refer to eye"] },
    { id: "admit", kind: "admit", measureIds: ["admit"], label: "Admission", appropriateness: "unnecessary",
      critique: { what: "Admitted a stable outpatient.", why: "Claudication without rest pain or tissue loss is managed in the OPD.", better: "Start therapy, arrange investigations as an outpatient, review in 4–6 weeks.", severity: "minor" } },
  ],
  hazards: [],

  followUp: [
    { when: "ideal", status: "improving",
      vitals: [{ key: "bp", value: "134/82" }, { key: "rbs", value: "158" }, { key: "weight", value: "79" }],
      lines: [{ role: "patient", kind: "speech", text: "My sugar readings are much better, doctor. I'm down to two cigarettes a day with the gum, and I'm trying to stop completely. I walk every morning — I can manage about 400 metres now before I need to stop." }],
      facts: [{ group: "hpi", label: "Walking tolerance (follow-up)", value: "~400 m before claudication" }] },
    { when: "acceptable", status: "stable",
      vitals: [{ key: "bp", value: "146/90" }, { key: "rbs", value: "192" }],
      lines: [{ role: "patient", kind: "speech", text: "The sugar is a little better. The leg pain is about the same — I still stop after a couple of hundred metres." }] },
    { when: "harmful", status: "guarded",
      lines: [{ role: "patient", kind: "speech", text: "I haven't felt right on the new tablets, doctor. Some days I feel very dizzy." }] },
    { when: "untreated", status: "stable",
      vitals: [{ key: "bp", value: "162/98" }, { key: "rbs", value: "252" }],
      lines: [{ role: "patient", kind: "speech", text: "Honestly, doctor, it's worse. Now I have to stop after a hundred metres. And the chest heaviness came again last week." }] },
  ],

  truth: {
    diagnosis: "Peripheral arterial disease — aorto-iliac (Leriche syndrome)",
    qualifier: "Intermittent claudication at ~200 m, ABI 0.62 / 0.58; with uncontrolled type 2 diabetes (HbA1c 9.4%), untreated hypertension, atherogenic dyslipidaemia, albuminuria and exertional angina — very high cardiovascular risk",
    reasoning: [
      { stage: "History", text: "Buttock and thigh pain on walking ~200 m, gone within minutes of rest; erectile dysfunction; 25 years of smoking, diabetes, untreated BP; exertional chest heaviness." },
      { stage: "Examination", text: "BP 158/96. Feeble femoral pulses with bruits, absent distal pulses, cool hairless shins, aortic bruit." },
      { stage: "Investigation", text: "ABI 0.62 / 0.58; Doppler localises disease to the distal aorta and iliacs; HbA1c 9.4%, LDL 158, UACR 86." },
      { stage: "Diagnosis", text: "Aorto-iliac PAD — the Leriche triad of claudication, erectile dysfunction and weak femoral pulses — in a polyvascular, very-high-risk patient." },
    ],
  },

  rubric: {
    diagnosisAccept: ["peripheral arterial disease", "peripheral artery disease", "peripheral vascular disease", "pad", "pvd", "leriche", "leriche syndrome", "aortoiliac", "aorto iliac", "aortoiliac occlusive disease", "aortoiliac disease", "intermittent claudication", "chronic limb ischaemia", "chronic limb ischemia", "lower limb ischaemia", "lower limb ischemia", "atherosclerotic occlusive"],
    diagnosisPartial: ["claudication", "uncontrolled diabetes", "type 2 diabetes", "diabetes", "hypertension", "erectile dysfunction", "diabetic neuropathy", "neuropathy", "metabolic syndrome", "dyslipidaemia", "dyslipidemia", "coronary artery disease", "angina", "atherosclerosis"],
    differentials: ["lumbar canal stenosis", "spinal stenosis", "neurogenic claudication", "diabetic neuropathy", "peripheral neuropathy", "venous claudication", "osteoarthritis", "hip arthritis", "compartment syndrome", "stable angina", "coronary artery disease", "b12 deficiency", "diabetic amyotrophy"],
    idealTreatment: [["antiplatelet"], ["atorvastatin-hi", "rosuvastatin-hi"], ["raas"], ["sglt2", "glp1"], ["smoking-cessation", "nrt"], ["exercise"]],
    expertActionCount: 22,
    followUpDays: { min: 14, max: 90 },
    expectsReassessment: false,
    misses: {
      claudication: { what: "Did not uncover the exertional leg pain.", why: "He came with vague fatigue; the defining symptom only appears if you ask about pain on walking.", better: "In every diabetic smoker, ask: “Do your legs hurt when you walk? Where? How far? What makes it go?”", severity: "major" },
      "walking-distance": { what: "Did not quantify walking tolerance.", why: "Claudication distance grades severity, tracks response and decides whether to intervene.", better: "Ask how far they can walk before pain, and how that has changed.", severity: "moderate" },
      sexual: { what: "Did not take a sexual history.", why: "Erectile dysfunction here is a vascular symptom (part of the Leriche triad) — and he wanted a tablet that would have been dangerous with his nitrate.", better: "Ask men with vascular risk factors about erections — it is often the first sign of atherosclerosis.", severity: "moderate" },
      meds: { what: "Did not take a full medication history.", why: "He keeps sublingual isosorbide dinitrate in his wallet — the key safety fact before any PDE-5 inhibitor.", better: "Ask specifically about tablets taken only sometimes — under the tongue, for chest pain, from other doctors.", severity: "major" },
      chest: { what: "Did not ask about chest symptoms.", why: "PAD is a marker of systemic atherosclerosis; most patients have coronary disease, and he has exertional angina.", better: "Screen every PAD patient for angina and cerebrovascular symptoms.", severity: "moderate" },
      smoking: { what: "Did not ask about smoking.", why: "Smoking is the strongest modifiable risk factor for PAD and its progression to amputation.", better: "Quantify pack-years and readiness to quit.", severity: "major" },
      "peripheral-pulses": { what: "Did not examine the peripheral pulses.", why: "Feeble femorals with bruits and absent distal pulses localise the disease to the aorto-iliac segment.", better: "Palpate femoral, popliteal, dorsalis pedis and posterior tibial pulses; auscultate for bruits.", severity: "major" },
      feet: { what: "Did not examine the legs and feet.", why: "Trophic changes, temperature and capillary refill grade ischaemia; ulcers or gangrene would make this limb-threatening.", better: "Inspect shins and feet, compare temperature, check capillary refill and look between the toes.", severity: "moderate" },
      abi: { what: "Did not measure the ankle–brachial index.", why: "ABI is the cheap, bedside test that confirms PAD and grades it.", better: "ABI in every patient with exertional leg pain or absent foot pulses.", severity: "major" },
      lipid: { what: "No lipid profile.", why: "Baseline before high-intensity statin therapy; LDL target < 55 mg/dL.", better: "Fasting lipids at the first visit.", severity: "moderate" },
      hba1c: { what: "No HbA1c.", why: "Needed to grade glycaemic control and choose therapy.", better: "HbA1c at the first visit, then 3-monthly.", severity: "moderate" },
      rft: { what: "No renal function.", why: "Required before ACEi/ARB and SGLT2 inhibitors.", better: "Creatinine, eGFR and potassium at baseline.", severity: "minor" },
      antiplatelet: { what: "No antiplatelet.", why: "Symptomatic PAD carries a high risk of MI and stroke; antiplatelet therapy reduces it.", better: "Clopidogrel 75 mg OD (or aspirin 75 mg OD).", severity: "major" },
      "atorvastatin-hi": { what: "No high-intensity statin.", why: "Statins reduce cardiovascular events and improve walking distance in PAD.", better: "Atorvastatin 40–80 mg or rosuvastatin 20–40 mg at night.", severity: "major" },
      raas: { what: "Hypertension and albuminuria left without an ACEi/ARB.", why: "BP 158/96 with UACR 86 mg/g — RAAS blockade protects kidneys and heart.", better: "Telmisartan 40 mg OD; recheck creatinine and potassium in 1–2 weeks.", severity: "moderate" },
      sglt2: { what: "No agent with cardiovascular and renal benefit for his diabetes.", why: "With albuminuria and established atherosclerosis, SGLT2 inhibitors or GLP-1 RAs reduce events, not just glucose.", better: "Dapagliflozin 10 mg OD (or empagliflozin), plus metformin optimised.", severity: "moderate" },
      "smoking-cessation": { what: "Did not address smoking.", why: "Continuing to smoke doubles the risk of progression to critical limb ischaemia and amputation.", better: "Clear advice to stop, plus nicotine replacement or bupropion and follow-up.", severity: "major" },
      exercise: { what: "No exercise prescription.", why: "A structured walking programme improves claudication distance by 50–200%.", better: "Walk to moderate pain, rest, repeat — 30–45 min, at least 3 times a week, for 12 weeks.", severity: "moderate" },
    },
    strengths: {
      claudication: "Teased out exertional leg pain from a vague presentation.",
      "walking-distance": "Quantified the claudication distance.",
      sexual: "Took a sexual history — erectile dysfunction completes the Leriche triad.",
      meds: "Found the sublingual nitrate in his wallet.",
      chest: "Screened for coronary symptoms in a vascular patient.",
      "peripheral-pulses": "Examined all lower-limb pulses and listened for bruits.",
      buerger: "Performed Buerger's test.",
      abi: "Confirmed PAD with an ankle–brachial index.",
      "vit-b12": "Checked B12 in a long-term metformin user with neuropathic symptoms.",
      uacr: "Screened for albuminuria.",
      antiplatelet: "Started antiplatelet therapy.",
      "atorvastatin-hi": "Chose a high-intensity statin.",
      "rosuvastatin-hi": "Chose a high-intensity statin.",
      raas: "Used an ACEi/ARB for hypertension with albuminuria.",
      sglt2: "Chose a glucose-lowering drug with cardiorenal benefit.",
    },
  },

  teaching: {
    patientBand: "lifestyle-limiting",
    severityBands: [
      { id: "asymptomatic", label: "Asymptomatic PAD",
        recognition: ["ABI < 0.90 without symptoms", "Often found on screening diabetics and smokers"],
        investigation: ["ABI; lipids, HbA1c, renal function"],
        treatment: ["Stop smoking", "Statin; antiplatelet if ABI clearly reduced or other vascular disease", "Control BP and diabetes"],
        followUp: ["Annual ABI and foot examination"] },
      { id: "claudication", label: "Mild claudication",
        recognition: ["Calf (or thigh/buttock) pain on walking > 200 m, relieved by rest", "ABI 0.7–0.9"],
        investigation: ["ABI; risk-factor screen"],
        treatment: ["Smoking cessation", "Supervised walking programme", "Antiplatelet + high-intensity statin", "BP and glucose control"],
        followUp: ["Review at 3 months — walking distance, risk factors"] },
      { id: "lifestyle-limiting", label: "Lifestyle-limiting claudication",
        recognition: ["Short walking distance (≤ 200 m) limiting work or life", "ABI 0.4–0.7", "Buttock claudication + ED + weak femorals = aorto-iliac (Leriche)"],
        investigation: ["Arterial Doppler; CT angiography when intervention is planned", "Cardiac evaluation for angina"],
        treatment: ["All of the above, plus cilostazol 100 mg BD (no heart failure)", "Vascular referral — endovascular stenting or bypass if inadequate response at 3–6 months"],
        followUp: ["4–6 weeks for risk-factor titration; 3 months for walking distance"] },
      { id: "cltl", label: "Chronic limb-threatening ischaemia",
        recognition: ["Rest pain (worse at night, relieved by hanging the leg)", "Non-healing ulcer or gangrene", "ABI < 0.4, toe pressure < 30 mmHg"],
        investigation: ["Urgent arterial imaging; wound swab and X-ray if infected"],
        treatment: ["Urgent vascular referral for revascularisation", "Analgesia, wound care, infection control"],
        followUp: ["Days, not months"] },
      { id: "acute", label: "Acute limb ischaemia",
        recognition: ["Sudden pain, pallor, pulselessness, paraesthesia, paralysis, perishingly cold limb", "Embolic (AF) or thrombotic"],
        investigation: ["Do not delay for imaging if the limb is threatened"],
        treatment: ["IV unfractionated heparin immediately", "Emergency vascular surgery — embolectomy, thrombolysis or bypass"],
        followUp: ["Watch for reperfusion injury and compartment syndrome"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Clopidogrel", brand: "Clopilet", dose: "75 mg", route: "PO", frequency: "Once daily", duration: "Lifelong",
        indication: "Symptomatic peripheral arterial disease",
        mechanism: "Irreversibly blocks the platelet P2Y12 ADP receptor → platelets cannot activate and aggregate.",
        whyItWorks: "Prevents the platelet-rich thrombi that cause MI, stroke and limb events on ruptured plaque.",
        avoidWhen: ["Active bleeding", "Severe liver disease"],
        adverseEffects: ["Bleeding, bruising", "Dyspepsia"],
        monitoring: ["Bleeding; combine with a PPI only if GI-bleed risk is high (prefer pantoprazole)"] },
      { generic: "Atorvastatin", brand: "Atorva", dose: "40–80 mg", route: "PO", frequency: "Once daily at night", duration: "Lifelong",
        indication: "All patients with PAD (very high cardiovascular risk)",
        mechanism: "Inhibits HMG-CoA reductase → less hepatic cholesterol synthesis → more LDL receptors → lower LDL; also stabilises plaque.",
        whyItWorks: "Lower LDL means fewer plaque ruptures — fewer heart attacks, strokes and amputations.",
        avoidWhen: ["Pregnancy", "Active liver disease"],
        adverseEffects: ["Myalgia", "Raised transaminases (rare)", "Small rise in glucose"],
        monitoring: ["Lipids at 6–8 weeks (target LDL < 55 mg/dL)", "ALT at baseline; CK if muscle symptoms"] },
      { generic: "Telmisartan", brand: "Telma", dose: "40 mg", route: "PO", frequency: "Once daily", duration: "Long-term",
        indication: "Hypertension with diabetes and albuminuria",
        mechanism: "Blocks angiotensin II AT1 receptors → vasodilatation, lower aldosterone, reduced glomerular pressure.",
        whyItWorks: "Lowers BP and protects the kidney by reducing intraglomerular pressure and albumin leak.",
        avoidWhen: ["Pregnancy", "Bilateral renal artery stenosis", "Hyperkalaemia"],
        adverseEffects: ["Hyperkalaemia", "Rise in creatinine (up to 30% acceptable)", "Dizziness"],
        monitoring: ["Creatinine and potassium at 1–2 weeks", "BP target < 130/80"] },
      { generic: "Dapagliflozin", brand: "Forxiga", dose: "10 mg", route: "PO", frequency: "Once daily", duration: "Long-term",
        indication: "Type 2 diabetes with albuminuria / cardiovascular disease",
        mechanism: "Blocks SGLT2 in the proximal tubule → glucose and sodium excreted in urine.",
        whyItWorks: "Lowers glucose, BP and weight, and reduces intraglomerular pressure — slowing kidney decline and heart failure.",
        avoidWhen: ["Type 1 diabetes or ketosis", "Recurrent genital infections", "Volume depletion"],
        adverseEffects: ["Genital mycotic infection", "Volume depletion", "Euglycaemic ketoacidosis (rare)"],
        monitoring: ["eGFR", "Genital hygiene advice", "Hold during acute illness (sick-day rules)"] },
      { generic: "Cilostazol", brand: "Pletoz", dose: "100 mg", route: "PO", frequency: "Twice daily, 30 min before meals", duration: "Review at 3 months",
        indication: "Lifestyle-limiting claudication despite exercise",
        mechanism: "Inhibits phosphodiesterase-3 → raises cAMP in platelets and vascular smooth muscle → vasodilatation and antiplatelet effect.",
        whyItWorks: "Improves walking distance by ~50% in responders.",
        avoidWhen: ["Any heart failure (increased mortality with PDE-3 inhibitors)", "Active bleeding"],
        adverseEffects: ["Headache", "Palpitations", "Loose stools"],
        monitoring: ["Stop if no benefit after 3 months"] },
      { generic: "Nicotine replacement (gum)", brand: "Nicotex", dose: "2 mg (4 mg if > 20 cigarettes/day)", route: "PO", frequency: "Chew-and-park when craving; max 20/day", duration: "8–12 weeks, then taper",
        indication: "Smoking cessation",
        mechanism: "Delivers nicotine without smoke → occupies nicotinic receptors → blunts withdrawal and craving.",
        whyItWorks: "Roughly doubles quit rates compared with willpower alone.",
        avoidWhen: ["Within 2 weeks of an MI (relative)"],
        adverseEffects: ["Jaw ache, hiccups, dyspepsia"],
        monitoring: ["Smoking status at every visit"] },
    ],
    routines: [
      { label: "Walking prescription",
        steps: [
          { order: 1, step: "Warm up", note: "5 minutes at an easy pace" },
          { order: 2, step: "Walk until the pain is moderate (3–4/10)", note: "Not at the first twinge — push gently into it" },
          { order: 3, step: "Stop and rest until the pain settles", note: "Usually 2–5 minutes, standing or sitting" },
          { order: 4, step: "Walk again — repeat the cycle", howMuch: "30–45 minutes in total", note: "At least 3 times a week, ideally daily, for 12 weeks" },
        ],
        avoid: ["Stopping altogether because of pain", "Smoking — it cancels the benefit"],
        improvementTimeline: "Walking distance improves noticeably at 4–8 weeks; maximal benefit at 3–6 months." },
      { label: "Daily foot care",
        steps: [
          { order: 1, step: "Inspect both feet every evening", note: "Use a mirror for the soles; look between toes" },
          { order: 2, step: "Wash in lukewarm water; dry between the toes" },
          { order: 3, step: "Moisturise heels — not between toes" },
          { order: 4, step: "Wear closed, well-fitting footwear with socks", note: "Never walk barefoot, even at home" },
        ],
        avoid: ["Hot-water bottles or heaters on numb feet", "Cutting corns yourself"] },
    ],
    followUp: {
      interval: "2–4 weeks for BP, glucose and potassium; 3 months for walking distance and HbA1c",
      reassess: ["Walking distance", "Smoking status", "BP (< 130/80)", "HbA1c (< 7%)", "LDL (< 55 mg/dL)", "Creatinine and K⁺ after ACEi/ARB", "Feet"],
      redFlags: ["Pain at rest or at night", "Any foot wound or discolouration", "Sudden cold, pale, painful leg — emergency", "Chest pain at rest"],
      whenToEscalate: ["Lifestyle-limiting claudication after 3–6 months of exercise + cilostazol → vascular imaging and revascularisation", "Rest pain or tissue loss → urgent vascular referral", "Angina → cardiology evaluation"],
    },
    treatmentFailure: { steps: [
      "Check adherence — walking programme, tablets, and smoking (ask directly)",
      "Check the diagnosis — spinal stenosis and neuropathy mimic claudication",
      "Check severity — repeat ABI; look for rest pain and tissue loss",
      "Check complications — angina, renal decline, foot infection",
      "Alternative therapy — add cilostazol; intensify statin, consider ezetimibe",
      "Escalate — vascular referral for endovascular or surgical revascularisation",
    ] },
    pearl: "Ask every diabetic smoker how far they can walk — and ask men about erections. Buttock claudication, erectile dysfunction and weak femoral pulses together are aorto-iliac disease until proven otherwise. And never prescribe a PDE-5 inhibitor without asking about nitrates: patients don't think of a tablet kept in their wallet as a “medicine.”",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "He asked for a tablet for erections, and he keeps Sorbitrate in his wallet. Sildenafil or tadalafil with any nitrate causes profound, prolonged hypotension — collapse at home, myocardial ischaemia, even death.",
      sequence: ["Lie flat with legs raised", "IV access and crystalloid boluses titrated to BP", "Withhold all nitrates for 24–48 h", "Monitor and do an ECG", "Vasopressors in ICU if refractory"],
    },
  },
};
