import type { ClinicalCaseDefinition } from "../case-definition";
import { photo, radiograph } from "./media";

/** Apex Institute OPD: "fever not settling" — SLE with class IV lupus nephritis. */
export const medSleApex: ClinicalCaseDefinition = {
  id: "med-sle-apex-01",
  specialty: "Medicine",
  track: "opd",
  level: "apex",
  setting: "OPD",
  weight: 2,
  difficulty: 3,
  patient: { name: "Farheen", age: 24, sex: "Female", city: "Lucknow", occupation: "MA student", context: "OPD" },
  arrivalMinuteOfDay: 11 * 60 + 20,
  briefing: "11:20. Medicine OPD at a national referral institute. A 24-year-old woman referred from Lucknow with 'fever not settling', carrying a thick file of reports.",
  initialStatus: "guarded",
  opening: [
    { role: "patient", kind: "speech", text: "Doctor, I've had fever on and off for two months. My joints hurt, and now my face and feet are swelling. Three doctors gave me antibiotics — nothing worked." },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "156/98" },
    hr: { key: "hr", value: "102" },
    rr: { key: "rr", value: "18" },
    spo2: { key: "spo2", value: "98" },
    temp: { key: "temp", value: "100.4" },
    rbs: { key: "rbs", value: "96" },
    weight: { key: "weight", value: "52" },
  },
  profile: { pregnancyPossible: true, weightKg: 52 },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential", abnormal: true,
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened"],
      reply: "Fever for two months — usually in the evenings, 100 or 101. It goes with Dolo and comes back.",
      fact: "Intermittent low-grade fever × 2 months" },
    { id: "joint-pain", group: "hpi", label: "Joint pains", importance: "essential", abnormal: true,
      match: ["joint", "joints", "joint pain", "arthritis", "fingers", "wrists", "knees", "morning stiffness", "stiffness", "hands"],
      reply: "My fingers and wrists ache and swell, both sides. In the morning they're stiff for about half an hour.",
      fact: "Symmetrical small-joint pain and swelling (hands, wrists); 30 min morning stiffness" },
    { id: "rash", group: "hpi", label: "Rash & sun", importance: "essential", abnormal: true,
      match: ["rash", "skin", "face", "redness", "red", "cheeks", "sun", "sunlight", "photosensitivity", "tanning", "blisters"],
      reply: "My cheeks went red after a wedding in the sun — I thought it was tanning and went to the parlour. Sunlight makes it worse.",
      fact: "Facial rash after sun exposure; photosensitivity" },
    { id: "ulcers", group: "systemic", label: "Mouth ulcers", importance: "useful", abnormal: true,
      match: ["mouth ulcer", "mouth ulcers", "ulcers", "ulcer", "sores", "mouth", "palate"],
      reply: "There are some sores on the roof of my mouth. They don't hurt much.",
      fact: "Painless palatal ulcers" },
    { id: "hair", group: "systemic", label: "Hair loss", importance: "useful", abnormal: true,
      match: ["hair", "hair fall", "hair loss", "losing hair", "bald"],
      reply: "My hair is coming out in bunches when I comb it.",
      fact: "Diffuse hair loss" },
    { id: "renal", group: "systemic", label: "Swelling & urine", importance: "essential", abnormal: true,
      match: ["swelling", "swollen", "puffy", "face swelling", "feet", "legs", "urine", "frothy", "foamy", "passing urine", "urine colour", "less urine", "blood in urine"],
      reply: "My face is puffy in the mornings and my feet swell by evening — for three weeks. My urine has become very frothy.",
      fact: "Periorbital puffiness, pedal oedema, frothy urine × 3 weeks" },
    { id: "chest", group: "systemic", label: "Chest pain", importance: "useful", abnormal: true,
      match: ["chest pain", "chest", "pain on breathing", "deep breath", "breathless", "breathing", "cough"],
      reply: "For a week, a sharp pain on the left side when I take a deep breath.",
      fact: "Pleuritic left chest pain × 1 week" },
    { id: "constitutional", group: "systemic", label: "Weight & fatigue", importance: "useful", abnormal: true,
      match: ["weight", "weight loss", "appetite", "tired", "fatigue", "weakness", "energy"],
      reply: "I've lost about four kilos. I'm tired all the time.",
      fact: "4 kg weight loss; fatigue" },
    { id: "raynaud", group: "systemic", label: "Cold fingers", importance: "minor", abnormal: true,
      match: ["cold", "white fingers", "blue fingers", "fingers change colour", "raynaud", "raynauds"],
      reply: "In winter my fingers go white and then blue.",
      fact: "Raynaud's phenomenon" },
    { id: "tb", group: "past", label: "TB exposure", importance: "useful",
      match: ["tb", "tuberculosis", "tb contact", "night sweats", "cough with sputum", "anyone with cough", "att"],
      reply: "No one at home has TB. No cough or night sweats.",
      fact: "No TB contact or symptoms" },
    { id: "meds", group: "medication", label: "Medicines", importance: "essential", abnormal: true,
      match: ["medicines", "medicine", "medication", "tablets", "taking any", "drugs", "antibiotics", "what did they give", "treatment so far", "injections", "painkiller", "painkillers"],
      reply: "Azee, then Taxim-O, then five days of injections — Monocef. Dolo for the fever and Combiflam for the joints, two or three a day.",
      fact: "Three antibiotic courses; daily ibuprofen–paracetamol (Combiflam)" },
    { id: "obstetric", group: "obstetric", label: "Periods, pregnancy & contraception", importance: "essential",
      match: ["periods", "last period", "lmp", "menstrual", "pregnant", "pregnancy", "married", "miscarriage", "miscarriages", "contraception", "planning", "baby", "children"],
      reply: "My periods are regular; the last one was two weeks ago. I got married six months ago — we're not planning a baby yet, we use condoms. No pregnancies.",
      fact: "LMP 2 weeks ago; married 6 months; condoms; G0" },
    { id: "family", group: "family", label: "Family history", importance: "minor",
      match: ["family", "mother", "father", "sister", "relatives", "anyone in the family"],
      reply: "My mother's sister has a thyroid problem. Nothing else.",
      fact: "Maternal aunt — thyroid disease" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful",
      match: ["allergy", "allergic", "allergies", "drug reaction", "sulfa"],
      reply: "No allergies.",
      fact: "No known drug allergies" },
  ],

  exam: [
    { id: "general", group: "general-exam", label: "General examination", importance: "essential", abnormal: true, match: [],
      finding: "Thin, tired young woman. Pallor present. Periorbital puffiness and bilateral pitting pedal oedema. Small, mobile, non-tender cervical lymph nodes. No icterus or clubbing.",
      fact: "Pallor, periorbital and pedal oedema, small cervical nodes" },
    { id: "skin", group: "local-exam", label: "Skin & face", importance: "essential", abnormal: true,
      match: ["skin", "face", "rash", "cheeks", "malar", "examine the rash", "look at the rash", "scalp", "hair"],
      finding: "Erythematous, slightly raised rash over both cheeks and the bridge of the nose, sparing the nasolabial folds. Diffuse non-scarring hair thinning.",
      fact: "Malar rash sparing nasolabial folds; non-scarring alopecia",
      media: photo({ site: "cheek", phototype: 4, seed: 2408, lesions: [
        { morphology: "erythema", count: 14, size: 20, confluence: 0.9, region: "malar" },
      ] }, "Close-up clinical photograph of the left cheek.", "Left cheek · close-up") },
    { id: "oral", group: "local-exam", label: "Oral cavity", importance: "useful", abnormal: true,
      match: ["oral cavity", "mouth", "palate", "throat", "tongue", "oral ulcer", "look in the mouth"],
      finding: "Two shallow, painless ulcers on the hard palate.",
      fact: "Painless palatal ulcers" },
    { id: "joints", group: "local-exam", label: "Joints", importance: "essential", abnormal: true,
      match: ["joints", "joint", "hands", "wrists", "fingers", "mcp", "pip", "synovitis", "musculoskeletal"],
      finding: "Tender, mildly swollen MCP and PIP joints of both hands and both wrists. No deformity, no nodules.",
      fact: "Symmetrical small-joint synovitis; non-deforming" },
    { id: "rs", group: "systemic-exam", label: "Respiratory", importance: "useful", abnormal: true, match: [],
      finding: "Reduced breath sounds and stony dullness at the left base; pleural rub just above it.",
      fact: "Small left effusion with pleural rub" },
    { id: "cvs", group: "systemic-exam", label: "Cardiovascular", importance: "useful", match: [],
      finding: "Tachycardic, regular. Normal heart sounds; no murmur or rub.",
      fact: "Tachycardia; no murmur or rub" },
    { id: "abdomen", group: "systemic-exam", label: "Abdomen", importance: "minor", match: [],
      finding: "Soft, non-tender. Spleen tip just palpable. No ascites.",
      fact: "Spleen tip palpable" },
  ],

  investigations: [
    { id: "cbc", priority: "essential",
      rows: [
        { analyte: "Haemoglobin", value: "8.9", unit: "g/dL", reference: "12.0–15.5", flag: "low" },
        { analyte: "MCV", value: "86", unit: "fL", reference: "80–100", flag: "normal" },
        { analyte: "Total leucocyte count", value: "3,100", unit: "/µL", reference: "4,000–11,000", flag: "low" },
        { analyte: "Lymphocytes (absolute)", value: "860", unit: "/µL", reference: "1,000–4,800", flag: "low" },
        { analyte: "Platelets", value: "0.98", unit: "lakh/µL", reference: "1.5–4.5", flag: "low" },
      ],
      teaching: { whenToOrder: "Every prolonged fever and every suspected connective-tissue disease.", whatItTellsYou: "Pancytopenia with lymphopenia in a febrile young woman points to SLE, not sepsis." } },
    { id: "urine-rm", priority: "essential",
      rows: [
        { analyte: "Protein", value: "3+", reference: "Nil", flag: "high" },
        { analyte: "RBCs", value: "25–30", unit: "/hpf", reference: "0–2", flag: "high" },
        { analyte: "Dysmorphic RBCs", value: "> 60%", reference: "—", flag: "high" },
        { analyte: "Casts", value: "RBC casts present", reference: "None", flag: "critical" },
        { analyte: "Pus cells", value: "4–6", unit: "/hpf", reference: "0–5", flag: "normal" },
      ],
      teaching: { whenToOrder: "Every patient with fever and joint pains — and every suspected lupus, at every visit.", whatItTellsYou: "An active sediment (dysmorphic RBCs, RBC casts, proteinuria) means glomerulonephritis." } },
    { id: "upcr", name: "Urine protein–creatinine ratio", short: "UPCR", category: "lab", minLevel: "district",
      match: ["upcr", "urine protein creatinine", "protein creatinine ratio", "spot urine protein", "24 hour urine protein", "24 h urine protein", "urine protein quantification", "quantify proteinuria", "urinary protein"],
      turnaroundMin: 120, cost: 450, priority: "essential",
      rows: [{ analyte: "Urine protein : creatinine", value: "2.8", unit: "g/g", reference: "< 0.2", flag: "high" }],
      teaching: { whenToOrder: "Any dipstick proteinuria in suspected lupus — then every visit.", whatItTellsYou: "Quantifies proteinuria; the main measure of response to induction." } },
    { id: "rft", priority: "essential",
      rows: [
        { analyte: "Urea", value: "58", unit: "mg/dL", reference: "15–40", flag: "high" },
        { analyte: "Creatinine", value: "1.6", unit: "mg/dL", reference: "0.5–1.1", flag: "high" },
        { analyte: "eGFR", value: "44", unit: "mL/min/1.73m²", reference: "> 90", flag: "low" },
        { analyte: "Potassium", value: "4.9", unit: "mEq/L", reference: "3.5–5.1", flag: "normal" },
      ],
      teaching: { whenToOrder: "With any active urine sediment.", whatItTellsYou: "A rising creatinine in nephritis means organ-threatening disease — treat urgently." } },
    { id: "ana", priority: "essential",
      rows: [{ analyte: "ANA (HEp-2 IFA)", value: "Positive, 1:640", reference: "< 1:80", flag: "high" }],
      report: "Homogeneous nuclear pattern.",
      teaching: { whenToOrder: "Suspected SLE — a screening test.", whatItTellsYou: "Very sensitive; a negative ANA makes SLE unlikely. Not specific on its own." } },
    { id: "anti-dsdna", name: "Anti-double-stranded DNA antibody", short: "Anti-dsDNA", category: "lab", minLevel: "college",
      match: ["anti dsdna", "anti ds dna", "dsdna", "ds dna", "double stranded dna", "anti dna"],
      turnaroundMin: 240, cost: 1400, priority: "essential",
      rows: [{ analyte: "Anti-dsDNA (ELISA)", value: "312", unit: "IU/mL", reference: "< 30", flag: "high" }],
      teaching: { whenToOrder: "ANA-positive patients with suspected SLE.", whatItTellsYou: "Specific for SLE; high titres go with nephritis and activity." } },
    { id: "complement", name: "Complement C3 & C4", short: "C3/C4", category: "lab", minLevel: "college",
      match: ["c3", "c4", "complement", "complements", "c3 c4", "complement levels"],
      turnaroundMin: 240, cost: 1600, priority: "essential",
      rows: [
        { analyte: "C3", value: "42", unit: "mg/dL", reference: "90–180", flag: "low" },
        { analyte: "C4", value: "6", unit: "mg/dL", reference: "10–40", flag: "low" },
      ],
      teaching: { whenToOrder: "Suspected SLE and at every lupus nephritis review.", whatItTellsYou: "Low C3/C4 = complement consumption by immune complexes — active disease." } },
    { id: "renal-biopsy", name: "Renal biopsy (light microscopy, IF, EM)", short: "Renal biopsy", category: "histopath", minLevel: "college",
      match: ["renal biopsy", "kidney biopsy", "biopsy of kidney", "biopsy", "percutaneous renal biopsy"],
      turnaroundMin: 1440, cost: 12000, priority: "essential",
      report: "ISN/RPS class IV-G (A) lupus nephritis: diffuse endocapillary proliferation in 70% of glomeruli, wire-loop lesions and hyaline thrombi; 'full-house' immunofluorescence (IgG, IgA, IgM, C3, C1q); subendothelial deposits on EM. Activity index 11/24, chronicity index 2/12.",
      teaching: { whenToOrder: "Lupus with proteinuria ≥ 0.5 g/day, an active sediment or unexplained fall in eGFR.", whatItTellsYou: "Class, activity and chronicity — which decide induction therapy and prognosis." } },
    { id: "lft", priority: "useful",
      rows: [
        { analyte: "Total bilirubin", value: "0.8", unit: "mg/dL", reference: "0.3–1.2", flag: "normal" },
        { analyte: "AST (SGOT)", value: "38", unit: "U/L", reference: "< 40", flag: "normal" },
        { analyte: "ALT (SGPT)", value: "31", unit: "U/L", reference: "< 41", flag: "normal" },
        { analyte: "Albumin", value: "2.6", unit: "g/dL", reference: "3.5–5.0", flag: "low" },
      ],
      teaching: { whenToOrder: "Baseline before immunosuppression.", whatItTellsYou: "Low albumin from proteinuria; baseline for drug toxicity." } },
    { id: "esr", priority: "useful", rows: [{ analyte: "ESR", value: "88", unit: "mm/1st h", reference: "< 20", flag: "high" }],
      teaching: { whenToOrder: "Inflammation screen.", whatItTellsYou: "High ESR with a near-normal CRP is typical of active lupus." } },
    { id: "crp", priority: "useful", rows: [{ analyte: "CRP", value: "7", unit: "mg/L", reference: "< 6", flag: "high" }],
      teaching: { whenToOrder: "Fever work-up.", whatItTellsYou: "A markedly high CRP in lupus suggests infection or serositis." } },
    { id: "apla", name: "Antiphospholipid antibodies (LA, aCL, anti-β2GP1)", short: "APLA", category: "lab", minLevel: "college",
      match: ["antiphospholipid", "apla", "aps", "lupus anticoagulant", "anticardiolipin", "beta 2 glycoprotein", "b2gp1", "acl"],
      turnaroundMin: 480, cost: 4500, priority: "useful",
      rows: [
        { analyte: "Lupus anticoagulant", value: "Not detected", reference: "Not detected", flag: "normal" },
        { analyte: "Anticardiolipin IgG/IgM", value: "8 / 5", unit: "GPL/MPL", reference: "< 20", flag: "normal" },
        { analyte: "Anti-β2 glycoprotein I", value: "Negative", reference: "Negative", flag: "normal" },
      ],
      teaching: { whenToOrder: "Every new SLE — before pregnancy and before oestrogen contraception.", whatItTellsYou: "Thrombosis and pregnancy-loss risk; guides anticoagulation and contraception." } },
    { id: "dct", name: "Direct Coombs test & reticulocytes", short: "DCT", category: "lab",
      match: ["coombs", "dct", "direct coombs", "direct antiglobulin", "reticulocyte", "retic", "haemolysis screen", "hemolysis screen", "ldh"],
      turnaroundMin: 90, cost: 600, priority: "useful",
      rows: [
        { analyte: "Direct Coombs test", value: "Positive (2+)", reference: "Negative", flag: "high" },
        { analyte: "Reticulocytes", value: "3.6", unit: "%", reference: "0.5–2.5", flag: "high" },
      ],
      teaching: { whenToOrder: "Anaemia in suspected SLE.", whatItTellsYou: "Autoimmune haemolysis — a haematological criterion." } },
    { id: "cxr", priority: "useful",
      media: radiograph("xray", "PA", [{ id: "pleural-effusion", side: "left", severity: 1 }], 64, "Posteroanterior chest radiograph.", "PA erect"),
      report: "Blunting of the left costophrenic angle with a small meniscus. Lungs otherwise clear. Heart size normal.",
      teaching: { whenToOrder: "Pleuritic pain or breathlessness; before immunosuppression (TB).", whatItTellsYou: "Serositis (effusion) here; no TB or pneumonia." } },
    { id: "usg-abdomen", priority: "useful",
      report: "Both kidneys 11.4 and 11.7 cm with increased cortical echogenicity and preserved corticomedullary differentiation; no hydronephrosis. Spleen 12.6 cm. Minimal free fluid.",
      teaching: { whenToOrder: "Before renal biopsy.", whatItTellsYou: "Normal-sized kidneys — suitable for biopsy; no obstruction." } },
    { id: "viral-markers", priority: "useful",
      teaching: { whenToOrder: "Before immunosuppression.", whatItTellsYou: "HBV reactivation and HIV change the plan." } },
    { id: "igra", name: "Interferon-gamma release assay", short: "IGRA", category: "lab", minLevel: "district",
      match: ["igra", "quantiferon", "mantoux", "tuberculin", "tst", "latent tb", "tb test"],
      turnaroundMin: 1440, cost: 2800, priority: "useful",
      rows: [{ analyte: "IGRA (QuantiFERON-TB Gold Plus)", value: "Negative", reference: "Negative", flag: "normal" }],
      teaching: { whenToOrder: "Before high-dose steroids and immunosuppression in India.", whatItTellsYou: "Latent TB that would need preventive therapy." } },
    { id: "upt", priority: "essential", rows: [{ analyte: "Urine pregnancy test", value: "Negative", reference: "Negative", flag: "normal" }],
      teaching: { whenToOrder: "Before mycophenolate, cyclophosphamide or ACE inhibitors in any woman who could be pregnant.", whatItTellsYou: "These drugs are teratogenic — confirm she is not pregnant first." } },
    { id: "blood-culture", priority: "situational",
      teaching: { whenToOrder: "High spiking fever or a new murmur.", whatItTellsYou: "Sterile here — the fever is lupus." } },
    { id: "widal", priority: "unnecessary", teaching: { whenToOrder: "Rarely — it is unreliable.", whatItTellsYou: "Not a test for a two-month fever with nephritis." } },
    { id: "ct-abdomen", priority: "unnecessary", teaching: { whenToOrder: "Not indicated here.", whatItTellsYou: "Radiation and contrast in a failing kidney, with no question to answer." } },
    { id: "mri-brain", priority: "unnecessary", teaching: { whenToOrder: "Neuropsychiatric lupus.", whatItTellsYou: "No neurological features here." } },
  ],

  therapeutics: [
    { id: "pulse-mp", kind: "drug", drugIds: ["methylprednisolone"], label: "IV methylprednisolone pulse", appropriateness: "ideal",
      doseRange: { min: 250, max: 1000, unit: "mg" },
      praise: "Started pulse methylprednisolone for organ-threatening nephritis." },
    { id: "oral-steroid", kind: "drug", drugIds: ["prednisolone"], label: "Oral prednisolone", appropriateness: "acceptable",
      doseRange: { min: 20, max: 60, unit: "mg" } },
    { id: "mmf", kind: "drug", drugIds: ["mycophenolate"], label: "Mycophenolate mofetil induction", appropriateness: "ideal",
      doseRange: { min: 500, max: 1500, unit: "mg" },
      praise: "Chose mycophenolate induction for class IV nephritis." },
    { id: "cyclo", kind: "drug", drugIds: ["cyclophosphamide"], label: "IV cyclophosphamide (Euro-Lupus)", appropriateness: "ideal",
      doseRange: { min: 400, max: 1000, unit: "mg" },
      praise: "Chose Euro-Lupus cyclophosphamide induction." },
    { id: "hcq", kind: "drug", drugIds: ["hydroxychloroquine"], label: "Hydroxychloroquine", appropriateness: "ideal",
      doseRange: { min: 200, max: 400, unit: "mg" },
      praise: "Started hydroxychloroquine — it reduces flares, thrombosis and death in every patient with lupus." },
    { id: "raas", kind: "drug", drugIds: ["telmisartan", "losartan", "olmesartan", "ramipril", "enalapril"], label: "ACE inhibitor / ARB for proteinuria", appropriateness: "acceptable",
      praise: "Added RAAS blockade for proteinuria and BP." },
    { id: "bone", kind: "drug", drugIds: ["calcium-carbonate", "vitamin-d3"], label: "Calcium & vitamin D", appropriateness: "acceptable" },
    { id: "ppi-rule", kind: "drug", drugIds: ["pantoprazole", "omeprazole", "rabeprazole", "esomeprazole"], label: "Gastroprotection", appropriateness: "neutral" },
    { id: "nsaid", kind: "drug", drugClasses: ["nsaid"], label: "NSAID", appropriateness: "harmful", arms: "nsaid-aki",
      critique: { what: "Gave an NSAID to a patient with active nephritis.", why: "NSAIDs reduce renal blood flow and sodium excretion — they worsen kidney function, oedema and BP in lupus nephritis.", better: "Paracetamol for pain; steroids treat the arthritis. Stop Combiflam.", severity: "major" } },
    { id: "stop-nsaid", kind: "counsel", concernsDrugs: ["nsaid"], label: "Stop Combiflam / NSAIDs", appropriateness: "ideal",
      match: ["stop combiflam", "no combiflam", "avoid painkillers", "stop painkillers", "no painkillers", "stop the painkiller"],
      praise: "Stopped the NSAIDs that were hurting her kidneys." },
    { id: "antibiotic", kind: "drug", drugClasses: ["antibiotic"], label: "Another antibiotic", appropriateness: "unnecessary",
      critique: { what: "Started another antibiotic.", why: "Three courses had already failed; the fever is lupus. Antibiotics delay the diagnosis and add drug reactions.", better: "Look for the multisystem pattern — and dip the urine.", severity: "moderate" } },
    { id: "contraception", kind: "counsel", label: "Contraception & pregnancy planning", appropriateness: "ideal",
      match: ["contraception", "avoid pregnancy", "don t get pregnant", "do not get pregnant", "birth control", "family planning", "plan pregnancy", "pregnancy planning", "use contraception", "copper t", "iucd", "progesterone only", "reliable contraception"],
      response: [{ role: "patient", kind: "speech", text: "I understand — no pregnancy until the doctors say the lupus is quiet. Can I have a copper-T?" }],
      praise: "Counselled on contraception before teratogenic drugs — and on planning pregnancy when the disease is quiet." },
    { id: "sun", kind: "counsel", label: "Sun protection", appropriateness: "acceptable",
      match: ["sunscreen", "sun protection", "avoid sun", "avoid sunlight", "cover up", "spf"] },
    { id: "salt", kind: "counsel", label: "Low-salt diet", appropriateness: "acceptable",
      match: ["low salt", "salt restriction", "reduce salt", "less salt"] },
    { id: "admit", kind: "admit", measureIds: ["admit"], label: "Admit", appropriateness: "ideal",
      praise: "Admitted for biopsy and pulse therapy." },
    { id: "dialysis", kind: "procedure", label: "Dialysis", appropriateness: "unnecessary",
      match: ["dialysis", "haemodialysis", "hemodialysis"],
      critique: { what: "Arranged dialysis.", why: "Creatinine 1.6 with normal potassium and no overload is not an indication.", better: "Treat the nephritis.", severity: "minor" } },
    { id: "att", kind: "supportive", label: "Empirical anti-TB treatment", appropriateness: "unnecessary",
      match: ["start att", "empirical att", "anti tubercular", "anti tb treatment", "akt 4"],
      critique: { what: "Started empirical anti-TB treatment.", why: "There was no evidence of TB, and it delayed the treatment she needed.", better: "Rule TB out (CXR, IGRA), then immunosuppress.", severity: "moderate" } },
  ],

  hazards: [
    { id: "untreated-nephritis", label: "Untreated class IV lupus nephritis",
      omission: { byMinute: 2880, preventedBy: ["pulse-mp", "oral-steroid", "mmf", "cyclo"] },
      stages: [
        { afterMin: 0, status: "deteriorating", interrupts: true,
          vitals: [{ key: "bp", value: "172/108" }, { key: "weight", value: "55" }],
          observation: { role: "nurse", text: "Doctor, her BP is 172/108 and she has passed very little urine today. She's complaining of a headache." },
          investigations: { rft: { rows: [
            { analyte: "Urea", value: "96", unit: "mg/dL", reference: "15–40", flag: "high" },
            { analyte: "Creatinine", value: "2.6", unit: "mg/dL", reference: "0.5–1.1", flag: "high" },
            { analyte: "Potassium", value: "5.4", unit: "mEq/L", reference: "3.5–5.1", flag: "high" },
          ] } },
          patientSays: "My head is pounding and my face is so swollen." },
        { afterMin: 1440, status: "critical", interrupts: true,
          vitals: [{ key: "bp", value: "186/116" }, { key: "spo2", value: "92" }, { key: "rr", value: "26" }],
          observation: { role: "nurse", text: "She's breathless lying flat, and her urine output is 200 mL in 24 hours." },
          investigations: { rft: { rows: [
            { analyte: "Creatinine", value: "4.1", unit: "mg/dL", reference: "0.5–1.1", flag: "critical" },
            { analyte: "Potassium", value: "6.1", unit: "mEq/L", reference: "3.5–5.1", flag: "critical" },
          ] } } },
      ],
      rescue: [["pulse-mp", "oral-steroid"], ["mmf", "cyclo"]],
      fullRecoveryWindowMin: 1440,
      lastRescueMin: 4320,
      recovery: [
        { afterMin: 2880, status: "improving", vitals: [{ key: "bp", value: "142/88" }],
          patientSays: "The swelling is less, and my joints don't hurt now." },
      ],
      review: {
        cause: "Class IV lupus nephritis went without induction immunosuppression.",
        whyItCausedHarm: "Immune-complex deposition drives proliferative glomerular inflammation; untreated, it causes rapidly declining GFR, hypertension and fluid overload — and scarring that becomes irreversible.",
        earliestRescueWindow: "As soon as the active sediment and rising creatinine are found — pulse steroids need not wait for the biopsy report.",
        correctRescueSequence: [
          "Admit; BP control; stop NSAIDs",
          "Renal biopsy as soon as safe (BP < 160/100, platelets > 50,000)",
          "Methylprednisolone 500 mg IV daily × 3, then prednisolone 0.5 mg/kg tapering",
          "Mycophenolate 1–1.5 g twice daily, or Euro-Lupus cyclophosphamide 500 mg IV every 2 weeks × 6",
          "Hydroxychloroquine; ACE inhibitor/ARB once not pregnant; contraception",
        ],
        lastRealisticRescueWindow: "Days, not weeks: the longer proliferative nephritis runs, the more nephrons are lost for good.",
      } },
    { id: "nsaid-aki", label: "NSAID-induced worsening of renal function",
      stages: [
        { afterMin: 720, status: "deteriorating", interrupts: true,
          vitals: [{ key: "bp", value: "168/104" }, { key: "weight", value: "54" }],
          observation: { role: "nurse", text: "Her urine output has dropped and her feet are more swollen." },
          investigations: { rft: { rows: [
            { analyte: "Creatinine", value: "2.3", unit: "mg/dL", reference: "0.5–1.1", flag: "high" },
            { analyte: "Potassium", value: "5.6", unit: "mEq/L", reference: "3.5–5.1", flag: "high" },
          ] } } },
      ],
      rescue: [["stop-nsaid", "measure:stop-drug"]],
      fullRecoveryWindowMin: 720,
      lastRescueMin: 2880,
      recovery: [{ afterMin: 1440, status: "guarded", vitals: [{ key: "bp", value: "150/94" }] }],
      review: {
        cause: "An NSAID was given during active lupus nephritis.",
        whyItCausedHarm: "Prostaglandins keep afferent arterioles open when the kidney is inflamed; blocking them drops GFR, retains sodium and raises potassium and BP.",
        earliestRescueWindow: "At the first prescription — she had already been taking Combiflam two or three times a day.",
        correctRescueSequence: ["Stop all NSAIDs", "Paracetamol for pain", "Recheck creatinine and potassium in 24–48 h"],
        lastRealisticRescueWindow: "Usually reversible within days if stopped early.",
      } },
  ],

  followUp: [
    { when: "ideal", status: "improving",
      lines: [
        { role: "system", kind: "status", text: "Lupus clinic — 3 months later" },
        { role: "patient", kind: "speech", text: "My joints are fine and the swelling has gone. I take every tablet, I wear sunscreen, and I got the copper-T." },
        { role: "system", kind: "finding", text: "UPCR 0.6 g/g; creatinine 1.0 mg/dL; C3 82 mg/dL; Hb 11.2 g/dL. Prednisolone tapered to 10 mg; mycophenolate 1.5 g twice daily; hydroxychloroquine 200 mg twice daily." },
      ] },
    { when: "acceptable", status: "stable",
      lines: [
        { role: "system", kind: "status", text: "Lupus clinic — 3 months later" },
        { role: "patient", kind: "speech", text: "I'm better, doctor, but the froth in my urine hasn't gone completely." },
        { role: "system", kind: "finding", text: "UPCR 1.6 g/g; creatinine 1.3 mg/dL — partial response." },
      ] },
    { when: "any", status: "guarded",
      lines: [
        { role: "system", kind: "status", text: "Nephrology ward — 3 weeks later" },
        { role: "patient", kind: "speech", text: "They say my kidneys are working at a quarter. I'm scared of the dialysis." },
      ] },
  ],

  truth: {
    diagnosis: "Systemic lupus erythematosus with lupus nephritis (ISN/RPS class IV)",
    qualifier: "Active multisystem SLE — fever, malar rash, photosensitivity, oral ulcers, non-scarring alopecia, non-erosive arthritis, pleuritis, cytopenias with Coombs-positive haemolysis — ANA 1:640, anti-dsDNA high, low C3/C4; nephritic–nephrotic sediment with rising creatinine; biopsy class IV-G (A). Worsened by daily NSAIDs.",
    reasoning: [
      { stage: "History", text: "Two months of fever unresponsive to three antibiotic courses; symmetrical small-joint arthritis, a sun-provoked facial rash, palatal ulcers, hair loss, pleuritic pain, frothy urine and swelling — in a 24-year-old woman taking Combiflam daily." },
      { stage: "Examination", text: "BP 156/98, pallor, periorbital and pedal oedema, malar rash sparing the nasolabial folds, palatal ulcers, small-joint synovitis, left effusion with rub." },
      { stage: "Investigation", text: "Pancytopenia with lymphopenia, DCT positive; RBC casts and UPCR 2.8; creatinine 1.6; ANA 1:640, anti-dsDNA 312, C3/C4 low; biopsy class IV-G (A)." },
      { stage: "Diagnosis", text: "SLE with proliferative (class IV) lupus nephritis — organ-threatening disease needing induction immunosuppression now." },
    ],
  },

  rubric: {
    diagnosisAccept: ["lupus nephritis", "systemic lupus erythematosus", "sle", "lupus", "class iv lupus nephritis", "diffuse proliferative lupus nephritis", "sle with nephritis", "sle with lupus nephritis"],
    diagnosisPartial: ["glomerulonephritis", "nephritic syndrome", "nephrotic syndrome", "rapidly progressive glomerulonephritis", "rpgn", "connective tissue disease", "mixed connective tissue disease", "mctd", "immune complex glomerulonephritis"],
    differentials: ["tuberculosis", "enteric fever", "typhoid", "infective endocarditis", "lymphoma", "rheumatoid arthritis", "drug induced lupus", "post streptococcal glomerulonephritis", "iga nephropathy", "anca vasculitis", "vasculitis", "mctd", "parvovirus", "hiv", "adult onset still s disease", "dermatomyositis"],
    idealTreatment: [["pulse-mp", "oral-steroid"], ["mmf", "cyclo"], ["hcq"], ["contraception"]],
    expertActionCount: 28,
    followUpDays: { min: 7, max: 14 },
    expectsReassessment: false,
    definitiveTreatment: { ids: ["pulse-mp", "mmf", "cyclo"], byMinute: 2880, label: "Induction immunosuppression" },
    weights: { history: 15, examination: 10, differential: 10, investigationSelection: 15, investigationInterpretation: 15, treatment: 20, drugSafety: 10, reassessment: 0, efficiency: 0, outcome: 5 },
    misses: {
      renal: { what: "Did not ask about swelling or urine.", why: "Frothy urine and puffiness turn a 'fever of unknown origin' into a kidney emergency.", better: "Ask about urine, swelling and BP in every prolonged fever.", severity: "major" },
      rash: { what: "Did not ask about rash or sun sensitivity.", why: "A photosensitive malar rash is one of the most specific clues to SLE.", better: "Ask about rashes, the sun, ulcers and hair loss.", severity: "moderate" },
      meds: { what: "Did not take a medication history.", why: "Daily Combiflam was hurting her kidneys, and three antibiotic courses had already failed.", better: "Ask exactly what has been taken, how often, and for how long.", severity: "major" },
      obstetric: { what: "Did not ask about pregnancy and contraception.", why: "Mycophenolate, cyclophosphamide and ACE inhibitors are teratogenic.", better: "Ask about LMP, pregnancy plans and contraception before prescribing.", severity: "major" },
      skin: { what: "Did not examine the skin.", why: "The malar rash was the visible clue.", better: "Look at the face, scalp and sun-exposed skin.", severity: "moderate" },
      joints: { what: "Did not examine the joints.", why: "Non-deforming symmetrical synovitis supports SLE over rheumatoid arthritis.", better: "Examine hands, wrists and knees for synovitis and deformity.", severity: "minor" },
      "urine-rm": { what: "No urine microscopy.", why: "The urine sediment is the cheapest, fastest way to find lupus nephritis.", better: "Dip and examine the urine in every suspected lupus — every visit.", severity: "major" },
      "renal-biopsy": { what: "No renal biopsy.", why: "Class, activity and chronicity decide induction therapy and prognosis.", better: "Biopsy any lupus patient with proteinuria ≥ 0.5 g/day or an active sediment.", severity: "moderate" },
      upt: { what: "No pregnancy test before teratogenic drugs.", why: "Mycophenolate causes major birth defects and miscarriage.", better: "UPT before mycophenolate, cyclophosphamide or ACE inhibitors.", severity: "moderate" },
      hcq: { what: "No hydroxychloroquine.", why: "It is the backbone of lupus treatment — fewer flares, less thrombosis, better survival.", better: "Hydroxychloroquine ≤ 5 mg/kg/day for every patient unless contraindicated.", severity: "moderate" },
      contraception: { what: "No contraception counselling.", why: "Pregnancy during active nephritis or on mycophenolate is dangerous for mother and baby.", better: "Reliable contraception (copper-T or progestogen-only) now; plan pregnancy after ≥ 6 months of quiescence on pregnancy-safe drugs.", severity: "major" },
    },
    strengths: {
      renal: "Asked about urine and swelling.",
      rash: "Picked up the photosensitive rash.",
      meds: "Found the daily Combiflam.",
      obstetric: "Took a pregnancy and contraception history.",
      "urine-rm": "Examined the urine sediment.",
      "anti-dsdna": "Sent anti-dsDNA.",
      complement: "Checked complement levels.",
      "renal-biopsy": "Arranged a renal biopsy.",
      igra: "Screened for latent TB before immunosuppression.",
      hcq: "Started hydroxychloroquine.",
      contraception: "Counselled on contraception.",
      "stop-nsaid": "Stopped the NSAIDs.",
    },
  },

  teaching: {
    patientBand: "severe",
    severityBands: [
      { id: "mild", label: "Mild — skin and joints",
        recognition: ["Rash, arthralgia/arthritis, fatigue; no organ threat"],
        investigation: ["CBC, urine, creatinine, ANA, anti-dsDNA, C3/C4"],
        treatment: ["Hydroxychloroquine; sun protection", "Short low-dose steroid or NSAID only if kidneys normal"],
        followUp: ["3–6 monthly; urine every visit"] },
      { id: "moderate", label: "Moderate — serositis, cytopenias",
        recognition: ["Pleurisy, pericarditis, moderate cytopenias, extensive rash"],
        investigation: ["As above + CXR, echo, Coombs"],
        treatment: ["Hydroxychloroquine + prednisolone 0.3–0.5 mg/kg", "Steroid-sparing: azathioprine, methotrexate or mycophenolate"],
        followUp: ["Monthly until controlled"] },
      { id: "severe", label: "Severe — organ-threatening (nephritis III/IV/V, CNS)",
        recognition: ["Active sediment, proteinuria, rising creatinine", "Seizures, psychosis, myelitis"],
        investigation: ["Renal biopsy; UPCR; APLA"],
        treatment: ["IV methylprednisolone pulses → oral taper", "Mycophenolate or Euro-Lupus cyclophosphamide induction", "Hydroxychloroquine, RAAS blockade, BP control"],
        followUp: ["2-weekly in induction; aim for ≥ 25% fall in proteinuria by 3 months"] },
      { id: "life-threatening", label: "Life-threatening",
        recognition: ["RPGN, pulmonary haemorrhage, catastrophic APS, TTP-like illness"],
        investigation: ["ICU-level work-up"],
        treatment: ["Pulses + cyclophosphamide or rituximab; plasma exchange in selected cases"],
        followUp: ["ICU"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Hydroxychloroquine", brand: "HCQS", dose: "200 mg twice daily (≤ 5 mg/kg actual body weight/day; reduce if eGFR < 30)", route: "PO", frequency: "Twice daily", duration: "Lifelong",
        indication: "Every patient with SLE unless contraindicated",
        mechanism: "Raises endosomal pH and blocks toll-like receptor 7/9 signalling → less type I interferon and autoantibody-driven inflammation.",
        whyItWorks: "Reduces flares, renal damage and thrombosis, and improves survival.",
        avoidWhen: ["Pre-existing maculopathy"],
        adverseEffects: ["Retinal toxicity with long use", "GI upset", "Skin pigmentation"],
        monitoring: ["Baseline eye examination; annual screening after 5 years"] },
      { generic: "Mycophenolate mofetil", brand: "Mycept", dose: "1–1.5 g twice daily (induction)", route: "PO", frequency: "Twice daily", duration: "6 months induction, then maintenance for ≥ 3 years",
        indication: "Class III/IV ± V lupus nephritis",
        mechanism: "Inhibits inosine monophosphate dehydrogenase → blocks de novo purine synthesis that T and B lymphocytes depend on.",
        whyItWorks: "As effective as cyclophosphamide for induction, with less gonadal toxicity.",
        avoidWhen: ["Pregnancy (teratogenic — stop ≥ 6 weeks before conception)", "Active serious infection"],
        adverseEffects: ["Diarrhoea, leucopenia", "Infections", "Miscarriage and birth defects"],
        monitoring: ["CBC 2-weekly initially, LFT", "Contraception throughout"] },
      { generic: "Cyclophosphamide (Euro-Lupus)", brand: "Endoxan", dose: "500 mg IV every 2 weeks × 6", route: "IV", frequency: "Fortnightly", duration: "3 months, then MMF or azathioprine maintenance",
        indication: "Class III/IV lupus nephritis (alternative induction)",
        mechanism: "Alkylating agent → cross-links DNA in dividing lymphocytes.",
        whyItWorks: "Low-dose Euro-Lupus regimen is as effective as high-dose with fewer infections and less ovarian failure.",
        avoidWhen: ["Pregnancy", "Active infection", "Severe cytopenias"],
        adverseEffects: ["Infection", "Ovarian failure (dose-related)", "Haemorrhagic cystitis (mesna, hydration)", "Malignancy long-term"],
        monitoring: ["CBC at 10–14 days after each dose", "Urine for haematuria"] },
      { generic: "Methylprednisolone", brand: "Solu-Medrol", dose: "250–1000 mg (commonly 500 mg)", route: "IV", frequency: "Daily", duration: "3 days, then oral prednisolone 0.5 mg/kg tapering to ≤ 7.5 mg by 3–6 months",
        indication: "Organ-threatening lupus (nephritis, CNS)",
        mechanism: "Glucocorticoid-receptor mediated suppression of inflammatory gene transcription and lymphocyte activity.",
        whyItWorks: "Rapid control of inflammation while slower immunosuppressants take effect — and allows lower oral doses.",
        avoidWhen: ["Uncontrolled infection"],
        adverseEffects: ["Hyperglycaemia, hypertension", "Infection", "Psychosis", "Avascular necrosis, bone loss"],
        monitoring: ["Glucose, BP", "Calcium/vitamin D; bone protection"] },
    ],
    routines: [
      { label: "Living with lupus",
        steps: [
          { order: 1, step: "Sunscreen every morning", howMuch: "SPF 50, a teaspoon for face and neck; reapply after 3 hours outdoors" },
          { order: 2, step: "Hydroxychloroquine every day", note: "Even when well — it prevents flares" },
          { order: 3, step: "Reliable contraception", note: "Copper-T or progestogen-only; plan pregnancy with the team after 6 months of quiet disease" },
          { order: 4, step: "Low-salt diet; check BP at home", note: "Target below 130/80" },
          { order: 5, step: "Vaccines before strong immunosuppression", note: "Inactivated only: flu, pneumococcal, hepatitis B" },
        ],
        avoid: ["Painkillers like Combiflam (kidneys)", "Stopping steroids suddenly", "Live vaccines while immunosuppressed", "Oestrogen pills if antiphospholipid antibodies are positive"],
        improvementTimeline: "Joint pain and fever settle within days of steroids; proteinuria should fall by a quarter by 3 months and by half by 6 months." },
    ],
    followUp: {
      interval: "Every 2 weeks during induction, then monthly",
      reassess: ["BP, weight, oedema", "Creatinine, UPCR, urine sediment", "CBC (mycophenolate), LFT", "C3/C4 and anti-dsDNA", "Steroid taper and side-effects"],
      redFlags: ["Fever on immunosuppression (infection until proven otherwise)", "Falling urine output, breathlessness", "Severe headache, seizures, confusion"],
      whenToEscalate: ["No ≥ 25% fall in proteinuria by 3 months → switch induction or add rituximab / belimumab", "Rising creatinine → repeat biopsy", "Pregnancy wish → pre-pregnancy counselling; switch to azathioprine"],
    },
    treatmentFailure: { steps: [
      "Check adherence — hydroxychloroquine levels if available",
      "Check the diagnosis — thrombotic microangiopathy, APS nephropathy, drug toxicity",
      "Check severity — repeat biopsy if creatinine rises",
      "Switch induction (MMF ↔ cyclophosphamide) or add rituximab or belimumab",
      "Escalate — plasma exchange only for specific indications",
    ] },
    pearl: "Three courses of antibiotics for 'fever not settling' is a diagnosis waiting to be made. In a young woman with fever, joint pains, a sun-sensitive rash and frothy urine, dip the urine — an active sediment turns a 'PUO' into lupus nephritis, and that kidney is on a clock.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "Another NSAID for her joints, or another antibiotic for her fever, would have bought time for the nephritis — and her creatinine would have doubled within days.",
      sequence: ["Stop NSAIDs", "Urine sediment, creatinine, UPCR", "Pulse steroids while arranging biopsy", "Mycophenolate or cyclophosphamide; hydroxychloroquine", "Contraception before teratogens"],
    },
  },
};
