import type { ClinicalCaseDefinition } from "../case-definition";

/** Phone consult: a son calls about his father's chest pain at night. */
export const phAcs: ClinicalCaseDefinition = {
  id: "ph-acs-01",
  specialty: "Cardiology",
  track: "phone",
  level: "district",
  setting: "Teleconsult",
  phoneVitals: ["bp", "hr", "rbs"],
  weight: 3,
  difficulty: 2,
  patient: { name: "Suresh", age: 56, sex: "Male", city: "Talwandi, Kota", occupation: "Cloth merchant", context: "Teleconsult" },
  arrivalMinuteOfDay: 23 * 60 + 10,
  briefing: "23:10. Your phone rings. A young man's voice: his father has chest pain and is sweating.",
  initialStatus: "guarded",
  opening: [
    { role: "attendant", kind: "speech", text: "Doctor, sorry to call so late — my father has pain in his chest for about forty minutes and he's sweating a lot. What should we do?" },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "150/94" },
    hr: { key: "hr", value: "98" },
    rr: { key: "rr", value: "22" },
    temp: { key: "temp", value: "98.4" },
    rbs: { key: "rbs", value: "212" },
  },
  profile: { currentDrugs: ["telmisartan", "metformin", "sildenafil"], weightKg: 78 },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["what happened", "what is the problem", "whats the problem", "what brings", "chief complaint", "how can i help", "what seems to be", "tell me what happened", "what is going on", "whats going on"],
      reply: "He was watching TV after dinner and suddenly got pain in the middle of his chest. It's been about forty minutes. He's sweating even under the fan.",
      fact: "Chest pain at rest, ~40 min, with sweating" },
    { id: "character", group: "hpi", label: "Character & radiation", importance: "essential", abnormal: true,
      match: ["what kind of pain", "type of pain", "describe the pain", "how does the pain feel", "what does it feel like", "heaviness", "pressure", "tightness", "squeezing", "burning", "sharp", "where is the pain", "where exactly", "radiate", "radiating", "spread", "spreading", "left arm", "arm", "jaw", "neck", "back", "shoulder", "character"],
      reply: "(The father takes the phone, breathless.) Like a heavy stone sitting on my chest, doctor… it's going into my left arm and my jaw.",
      fact: "Central crushing heaviness radiating to left arm and jaw" },
    { id: "onset", group: "hpi", label: "Onset & duration", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["how long", "since when", "when did", "started", "start", "onset", "duration", "continuous", "constant", "coming and going", "comes and goes", "still there", "is the pain still", "has it gone", "better or worse"],
      reply: "It started around half past ten, while he was sitting. It hasn't gone even for a minute — if anything it's worse.",
      fact: "Onset ~22:30 at rest; continuous, not easing" },
    { id: "associated", group: "systemic", label: "Associated symptoms", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["sweating", "sweat", "vomit", "vomiting", "nausea", "breathless", "breathlessness", "breathing", "short of breath", "dizzy", "dizziness", "giddy", "faint", "fainted", "palpitations", "heart racing", "uneasy", "restless"],
      reply: "He's drenched in sweat and he vomited once. He says he can't take a full breath and feels very weak.",
      fact: "Diaphoresis, vomiting ×1, breathlessness, weakness" },
    { id: "prior", group: "hpi", label: "Previous episodes", importance: "useful", abnormal: true, speaker: "attendant",
      match: ["before", "previous", "first time", "earlier", "ever had", "similar", "on walking", "walking", "exertion", "climbing", "stairs", "angina", "last few days", "recently"],
      reply: "He just told me — for two weeks he's had a little tightness climbing to the shop's upper floor. It went off with rest, so he didn't say anything.",
      fact: "2 weeks of exertional chest tightness, relieved by rest (new angina)" },
    { id: "past", group: "past", label: "Past history", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["medical history", "past history", "any illness", "illnesses", "bp", "blood pressure", "hypertension", "sugar", "diabetes", "diabetic", "heart problem", "heart disease", "cholesterol", "known case", "comorbidities", "any disease", "stroke", "kidney"],
      reply: "He has BP and sugar for eight years. Never any heart problem before.",
      fact: "Hypertension and type 2 diabetes × 8 years" },
    { id: "meds", group: "medication", label: "Medicines taken today", importance: "essential", abnormal: true,
      match: ["medicines", "medicine", "medication", "medications", "tablets", "tablet", "taking any", "what does he take", "what do you take", "drugs", "taken anything", "took anything", "taken any", "viagra", "sildenafil", "tadalafil", "manforce", "penegra", "sexual", "erection", "blue tablet"],
      reply: "(The father, quietly.) Telma for BP, a sugar tablet… and — this evening I took one Manforce tablet. Around eight o'clock.",
      fact: "Telmisartan, metformin; sildenafil (Manforce) taken ~20:00 today" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful", speaker: "attendant",
      match: ["allergy", "allergic", "allergies", "reaction to", "aspirin allergy"],
      reply: "No allergies that we know of.",
      fact: "No known drug allergies" },
    { id: "habits", group: "social", label: "Smoking", importance: "useful", abnormal: true, speaker: "attendant",
      match: ["smoke", "smoking", "smoker", "bidi", "cigarette", "tobacco", "gutka", "alcohol", "drink"],
      reply: "He smokes about ten bidis a day. He doesn't drink.",
      fact: "Smoker — 10 bidis/day" },
    { id: "family", group: "family", label: "Family history", importance: "minor", abnormal: true, speaker: "attendant",
      match: ["family", "brother", "father", "anyone in the family", "heart attack in the family", "relatives"],
      reply: "His elder brother had a heart attack at fifty.",
      fact: "Brother — MI at 50" },
    { id: "location", group: "social", label: "Distance & transport", importance: "useful", speaker: "attendant",
      match: ["where are you", "where do you live", "how far", "nearest hospital", "near you", "hospital nearby", "location", "address", "transport", "vehicle", "car", "do you have a car", "ambulance nearby"],
      reply: "We're in Talwandi, Kota. The district hospital is about 4 km — they have a heart unit now. A private heart hospital is 6 km. We have a car.",
      fact: "4 km from district hospital (cath lab); car available" },
    { id: "home-meds", group: "medication", label: "Medicines at home", importance: "useful", speaker: "attendant",
      match: ["at home", "medicine box", "do you have aspirin", "any aspirin", "disprin", "ecosprin", "sorbitrate", "isordil", "what medicines do you have", "first aid box"],
      reply: "We have Disprin and Dolo in the medicine box — and my uncle's Sorbitrate tablets.",
      fact: "At home: Disprin (aspirin 350 mg), paracetamol, Sorbitrate" },
  ],

  exam: [],
  investigations: [],

  therapeutics: [
    { id: "hospital-now", kind: "referral", label: "Ambulance (108) to a PCI-capable hospital now", appropriateness: "ideal", durationMin: 2,
      match: ["108", "call 108", "911", "call 911", "999", "call 999", "paramedics", "ems", "emergency services", "ambulance", "call an ambulance", "call the ambulance", "go to hospital", "go to the hospital", "take him to hospital", "take him to the hospital", "bring him to hospital", "bring him to the hospital", "nearest hospital", "emergency department", "emergency room", "casualty", "cath lab", "rush him", "come to the hospital", "go to the emergency", "heart hospital", "district hospital", "refer", "referral", "shift him", "admit him", "hospital immediately", "hospital right now"],
      response: [{ role: "attendant", kind: "speech", text: "Okay — my sister is calling 108 on her phone… They say twelve minutes. I'll stay on the line with you." }],
      praise: "Got an ambulance moving within minutes — in a heart attack, every 30 minutes of delay costs heart muscle and lives." },
    { id: "aspirin-load", kind: "drug", drugIds: ["aspirin"], label: "Chew aspirin 300–350 mg now", appropriateness: "ideal",
      doseRange: { min: 150, max: 350, unit: "mg" },
      praise: "Had him chew a loading dose of aspirin straight away." },
    { id: "nitrate", kind: "drug", drugIds: ["isosorbide-dinitrate", "gtn", "isosorbide-mononitrate"], label: "Sublingual nitrate", appropriateness: "dangerous", arms: "nitrate-pde5",
      critique: { what: "Advised a sublingual nitrate (Sorbitrate).", why: "He took sildenafil three hours earlier. A PDE-5 inhibitor plus a nitrate causes profound, refractory hypotension — in a heart that is already short of blood.", better: "Before any nitrate, ask about sildenafil (within 24 h) or tadalafil (within 48 h). Here: aspirin to chew and an ambulance — no nitrate.", severity: "major" } },
    { id: "avoid-nitrate", kind: "counsel", concernsDrugs: ["nitrate"], label: "No Sorbitrate — sildenafil taken today", appropriateness: "ideal",
      match: ["no sorbitrate", "not sorbitrate", "avoid sorbitrate", "no nitrate", "avoid nitrate", "avoid nitrates"],
      response: [{ role: "attendant", kind: "speech", text: "Okay, doctor — no Sorbitrate. I'll keep it away." }],
      praise: "Recognised the sildenafil and kept nitrates away." },
    { id: "rest", kind: "counsel", label: "Rest — no walking or exertion", appropriateness: "acceptable", durationMin: 1,
      match: ["lie down", "rest", "sit down", "let him rest", "don t let him walk", "do not let him walk", "don t walk", "do not walk", "no exertion", "keep him calm", "stay calm", "don t move", "do not move", "keep him still", "make him sit", "make him lie", "don t climb", "do not climb"],
      response: [{ role: "attendant", kind: "speech", text: "He's sitting on the sofa, leaning back. I won't let him move." }] },
    { id: "no-driving", kind: "counsel", label: "He must not drive", appropriateness: "acceptable", durationMin: 1,
      match: ["don t drive", "do not drive", "should not drive", "shouldn t drive", "not drive himself", "he can t drive", "he cannot drive"],
      response: [{ role: "attendant", kind: "speech", text: "No, no — he won't drive." }] },
    { id: "legs-up", kind: "supportive", label: "Lie flat with legs raised", appropriateness: "acceptable", durationMin: 1,
      match: ["lie him flat", "lay him flat", "lie flat", "lay him down", "raise his legs", "raise the legs", "legs up", "lift his legs", "feet up", "legs raised", "elevate his legs"],
      response: [{ role: "attendant", kind: "speech", text: "He's lying flat on the floor now, with his legs up on the sofa." }] },
    { id: "phone-cpr", kind: "supportive", label: "Telephone-guided CPR", appropriateness: "acceptable", durationMin: 2, rescues: ["stemi-delay"],
      match: ["cpr", "start cpr", "chest compressions", "compressions", "push on his chest", "press on his chest", "push hard", "press hard", "pump his chest", "hands only", "press the centre of the chest", "push in the centre"],
      response: [{ role: "attendant", kind: "speech", text: "I'm pressing on the middle of his chest — hard and fast, counting out loud. My uncle will take over when I'm tired." }],
      praise: "Coached hands-only CPR over the phone — bystander CPR doubles survival from cardiac arrest." },
    { id: "nsaid", kind: "drug", drugIds: ["ibuprofen", "diclofenac", "aceclofenac", "nimesulide", "mefenamic-acid", "naproxen", "etoricoxib", "ketorolac"], label: "NSAID painkiller", appropriateness: "harmful",
      critique: { what: "Advised an NSAID painkiller.", why: "NSAIDs raise the risk of re-infarction, heart failure and death in acute MI — and dull the very symptom that says 'go now'.", better: "Aspirin to chew, then hospital. No painkillers from the medicine box.", severity: "moderate" } },
    { id: "antacid", kind: "drug", drugClasses: ["ppi", "h2-blocker"], label: "Antacid for 'gas'", appropriateness: "unnecessary",
      critique: { what: "Treated the pain as acidity.", why: "Calling crushing chest pain with sweating 'gas' is how heart attacks are missed at home.", better: "Treat it as an acute coronary syndrome until an ECG says otherwise.", severity: "moderate" } },
    { id: "p2y12", kind: "drug", drugIds: ["clopidogrel", "ticagrelor"], label: "P2Y12 inhibitor at home", appropriateness: "neutral" },
    { id: "sorbitrate-check", kind: "counsel", label: "Ask about sildenafil before nitrates", appropriateness: "acceptable",
      match: ["check before sorbitrate", "before giving sorbitrate"] },
  ],

  hazards: [
    { id: "stemi-delay", label: "Heart attack left at home — cardiac arrest",
      omission: { byMinute: 18, preventedBy: ["hospital-now"] },
      stages: [
        { afterMin: 0, status: "deteriorating", interrupts: true,
          vitals: [{ key: "bp", value: "104/68" }, { key: "hr", value: "114" }],
          observation: { role: "attendant", text: "Doctor, he's gone very pale and he vomited again. He says the pain is much worse — he's clutching his chest." },
          patientSays: "(Breathless.) It's crushing me… crushing…" },
        { afterMin: 10, status: "critical", interrupts: true,
          vitals: [{ key: "bp", value: "0/0" }, { key: "hr", value: "0" }],
          observation: { role: "attendant", text: "Doctor! He's slumped over — he's not answering me! He's making a snoring sound and his eyes are open but he isn't looking at me!" },
          patientSays: "(No response — irregular gasping.)" },
        { afterMin: 24, status: "deceased",
          vitals: [{ key: "bp", value: "0/0" }, { key: "hr", value: "0" }],
          observation: { role: "attendant", text: "(Crying.) He's stopped breathing… he's gone cold, doctor…" } },
      ],
      rescue: [["hospital-now"]],
      fullRecoveryWindowMin: 9,
      lastRescueMin: 20,
      recovery: [
        { afterMin: 12, status: "guarded", vitals: [{ key: "bp", value: "102/66" }, { key: "hr", value: "106" }],
          observation: { role: "attendant", text: "The ambulance is here. They've put stickers on his chest and oxygen — they say the ECG shows a heart attack and they're taking him straight to the district hospital's cath lab." } },
        { afterMin: 120, status: "stable", vitals: [{ key: "bp", value: "118/76" }, { key: "hr", value: "86" }],
          observation: { role: "attendant", text: "(Text message.) They opened the blocked artery and put a stent. He's in the ICU, awake and talking." } },
      ],
      review: {
        cause: "A man with a probable heart attack was kept at home instead of being sent to hospital at once.",
        whyItCausedHarm: "An occluded coronary artery loses muscle by the minute; ischaemic myocardium is electrically unstable, and ventricular fibrillation — most common in the first hours — kills before reaching hospital.",
        earliestRescueWindow: "In the first minute of the call: continuous chest pain with sweating needs an ambulance now, not more questions.",
        correctRescueSequence: [
          "Call 108 (or go by car to the nearest ECG/thrombolysis-capable hospital if the ambulance is far) — never with the patient driving",
          "Chew aspirin 300–350 mg unless allergic",
          "No nitrate if sildenafil < 24 h or tadalafil < 48 h; no NSAIDs or antacids 'for gas'",
          "Rest; unlock the door; stay on the line",
          "If he collapses and isn't breathing normally: hands-only CPR, 100–120/min, until the ambulance arrives",
        ],
        lastRealisticRescueWindow: "Before the arrest — afterwards only immediate CPR and early defibrillation give a chance.",
      } },
    { id: "nitrate-pde5", label: "Nitrate within hours of sildenafil — profound hypotension",
      prescribedOnsetMin: 4,
      stages: [
        { afterMin: 4, status: "critical", interrupts: true,
          vitals: [{ key: "bp", value: "72/40" }, { key: "hr", value: "126" }],
          observation: { role: "attendant", text: "Doctor — he put the Sorbitrate under his tongue and now he's gone completely white. He says everything is going dark… he's sliding off the sofa!" },
          patientSays: "(Faintly.) Can't see… so dizzy…" },
        { afterMin: 22, status: "critical",
          vitals: [{ key: "bp", value: "64/36" }, { key: "hr", value: "134" }],
          observation: { role: "attendant", text: "He's cold and sweaty and not answering properly. The machine shows 64 over 36!" } },
        { afterMin: 45, status: "deceased",
          vitals: [{ key: "bp", value: "0/0" }, { key: "hr", value: "0" }],
          observation: { role: "attendant", text: "He's not breathing, doctor…" } },
      ],
      rescue: [["legs-up", "hospital-now"]],
      fullRecoveryWindowMin: 12,
      lastRescueMin: 38,
      recovery: [
        { afterMin: 6, status: "guarded", vitals: [{ key: "bp", value: "94/60" }, { key: "hr", value: "112" }],
          observation: { role: "attendant", text: "With his legs up he's opening his eyes. The machine says 94 over 60." } },
        { afterMin: 60, status: "stable", vitals: [{ key: "bp", value: "112/72" }, { key: "hr", value: "100" }] },
      ],
      review: {
        cause: "A sublingual nitrate was advised three hours after sildenafil.",
        whyItCausedHarm: "Both drugs raise cGMP in vascular smooth muscle — nitrates by releasing nitric oxide, sildenafil by blocking its breakdown (PDE-5). Together they cause profound venous and arterial dilatation: preload and BP collapse, and coronary perfusion falls in an already ischaemic heart.",
        earliestRescueWindow: "Before the advice: one question about 'Viagra-type' tablets prevents it entirely.",
        correctRescueSequence: [
          "No further nitrate",
          "Lie flat with legs raised",
          "Ambulance — IV fluids, and vasopressors in hospital if needed",
          "Continue aspirin and ACS pathway",
        ],
        lastRealisticRescueWindow: "Within about half an hour; prolonged hypotension extends the infarct and can trigger arrest.",
      } },
  ],

  followUp: [
    { when: "ideal", status: "improving",
      lines: [
        { role: "system", kind: "status", text: "Next morning — the son calls back" },
        { role: "attendant", kind: "speech", text: "Doctor, they did angiography at one in the night and put a stent. The heart doctor said chewing the aspirin and coming fast saved most of his heart." },
        { role: "system", kind: "finding", text: "Anterior STEMI. Primary PCI to the proximal LAD; door-to-balloon 58 minutes. LVEF 50%." },
      ] },
    { when: "acceptable", status: "stable",
      lines: [
        { role: "system", kind: "status", text: "Next morning — the son calls back" },
        { role: "attendant", kind: "speech", text: "They gave him a clot-dissolving injection at the district hospital and did the angiography this morning. They said part of his heart is weak." },
        { role: "system", kind: "finding", text: "Anterior STEMI; thrombolysed with tenecteplase, then PCI to the LAD next day. LVEF 40%." },
      ] },
    { when: "any", status: "guarded",
      lines: [
        { role: "system", kind: "status", text: "Two days later — the son calls back" },
        { role: "attendant", kind: "speech", text: "He's in the ICU, doctor. They say the attack was big and his heart is pumping weakly." },
      ] },
  ],

  truth: {
    diagnosis: "Suspected acute coronary syndrome — acute myocardial infarction",
    qualifier: "40 minutes of continuous crushing central chest pain at rest, radiating to the left arm and jaw, with sweating and vomiting, after two weeks of new exertional angina, in a smoker with diabetes and hypertension. Sildenafil taken three hours earlier — nitrates contraindicated. (Confirmed later: anterior STEMI.)",
    reasoning: [
      { stage: "History", text: "Continuous central heaviness for 40 minutes at rest, radiating to arm and jaw; sweating, vomiting, breathlessness; two weeks of crescendo exertional tightness; smoker with diabetes, hypertension and a brother with early MI." },
      { stage: "Examination", text: "None possible on the phone. The home BP machine reads 150/94, pulse 98 — normal numbers do not exclude an MI." },
      { stage: "Investigation", text: "None at home. The ECG — within 10 minutes of reaching hospital, or in the ambulance — decides between STEMI (reperfusion) and NSTE-ACS." },
      { stage: "Diagnosis", text: "Suspected ACS on history alone: act on it — ambulance, aspirin, no nitrate after sildenafil." },
    ],
  },

  rubric: {
    diagnosisAccept: ["acute coronary syndrome", "acs", "myocardial infarction", "heart attack", "acute mi", "ami", "stemi", "nstemi", "st elevation myocardial infarction", "unstable angina", "suspected acs", "cardiac chest pain", "anterior wall mi", "awmi", "mi"],
    diagnosisPartial: ["angina", "stable angina", "ischaemic heart disease", "ischemic heart disease", "ihd", "coronary artery disease", "cad"],
    differentials: ["aortic dissection", "pulmonary embolism", "gerd", "acid peptic disease", "pericarditis", "pneumothorax", "panic attack", "oesophageal spasm", "esophageal spasm", "musculoskeletal chest pain", "costochondritis", "cholecystitis", "pancreatitis"],
    idealTreatment: [["hospital-now"], ["aspirin-load"]],
    expertActionCount: 8,
    expectsReassessment: false,
    definitiveTreatment: { ids: ["hospital-now"], byMinute: 10, label: "Ambulance to a PCI-capable hospital" },
    weights: { history: 30, examination: 0, differential: 15, investigationSelection: 0, investigationInterpretation: 0, treatment: 25, drugSafety: 15, reassessment: 0, efficiency: 10, outcome: 5 },
    misses: {
      meds: { what: "Did not ask what he had taken today.", why: "He took sildenafil three hours earlier — a nitrate would have dropped his BP catastrophically.", better: "Before any nitrate, ask directly about sildenafil or tadalafil (Manforce, Penegra, Tadacip) in the last 24–48 hours.", severity: "major" },
      character: { what: "Did not characterise the pain.", why: "Central heaviness radiating to the arm and jaw is the single most useful feature on the phone.", better: "Ask where, what it feels like, and where it spreads.", severity: "moderate" },
      onset: { what: "Did not establish duration and whether the pain was ongoing.", why: "Continuous pain for more than 15–20 minutes means infarction is under way.", better: "Ask when it started and whether it is still there.", severity: "moderate" },
      associated: { what: "Did not ask about sweating, vomiting or breathlessness.", why: "Autonomic features make an ACS much more likely and signal a large infarct.", better: "Ask about sweating, vomiting, breathlessness and fainting.", severity: "moderate" },
      past: { what: "Did not ask about risk factors.", why: "Diabetes, hypertension and smoking raise the pre-test probability — and diabetics can have atypical pain.", better: "Ask about BP, sugar, cholesterol, smoking and heart disease.", severity: "minor" },
      "hospital-now": { what: "Did not send him to hospital urgently.", why: "Reperfusion — primary PCI or thrombolysis — is time-critical, and early VF happens at home.", better: "Call 108 or go to the nearest capable hospital now.", severity: "major" },
      "aspirin-load": { what: "No aspirin advised.", why: "Chewed aspirin reduces MI mortality by about a quarter and is in most Indian homes.", better: "Chew one Disprin or 325 mg aspirin now, unless allergic.", severity: "moderate" },
    },
    strengths: {
      character: "Characterised the pain precisely.",
      meds: "Found the sildenafil — the question that prevents a fatal interaction.",
      associated: "Asked about sweating and vomiting.",
      location: "Checked distance and transport before advising.",
      "hospital-now": "Sent him to hospital by ambulance at once.",
      "aspirin-load": "Advised chewing aspirin.",
      "avoid-nitrate": "Explicitly kept Sorbitrate away.",
    },
  },

  teaching: {
    patientBand: "high-risk",
    severityBands: [
      { id: "high-risk", label: "Possible ACS — high risk",
        recognition: ["Central pressure or heaviness > 10–15 minutes, at rest", "Sweating, vomiting, breathlessness, fainting", "Radiation to arm, jaw or back; known CAD or risk factors"],
        investigation: ["Nothing at home — ECG within 10 minutes of reaching hospital (or in the ambulance)"],
        treatment: ["Ambulance (108) or nearest ECG/thrombolysis-capable hospital now", "Chew aspirin 300–350 mg unless allergic", "No nitrate after sildenafil (24 h) or tadalafil (48 h), or if SBP < 90", "Patient must not drive; rest"],
        followUp: ["Stay on the line; be ready to coach CPR"] },
      { id: "settled", label: "Possible ACS — pain settled",
        recognition: ["Typical pain that has now eased", "New or worsening exertional pain (crescendo angina)"],
        investigation: ["ECG and troponin the same day"],
        treatment: ["Same-day emergency assessment — not 'OPD tomorrow'", "Aspirin if no contraindication"],
        followUp: ["Return immediately if pain recurs"] },
      { id: "low-risk", label: "Low-risk, likely non-cardiac",
        recognition: ["Sharp, positional or reproducible on pressure", "Seconds-long pain; young without risk factors"],
        investigation: ["Clinic review; ECG if any doubt"],
        treatment: ["Safety-net advice"],
        followUp: ["Red flags explained"] },
      { id: "arrest", label: "Cardiac arrest",
        recognition: ["Unresponsive and not breathing normally (gasping)"],
        investigation: ["—"],
        treatment: ["Hands-only CPR 100–120/min, 5–6 cm deep", "Ambulance; AED if available"],
        followUp: ["—"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Aspirin", brand: "Disprin", dose: "300–350 mg (one Disprin), chewed", route: "PO", frequency: "Once, now — then 75–150 mg daily", duration: "Lifelong after ACS",
        indication: "Suspected acute coronary syndrome",
        mechanism: "Irreversibly acetylates platelet COX-1 → blocks thromboxane A₂ → less platelet aggregation on the ruptured plaque.",
        whyItWorks: "Chewing gives antiplatelet effect within 15–20 minutes and cuts MI mortality by about a quarter.",
        avoidWhen: ["True aspirin allergy", "Active major bleeding"],
        adverseEffects: ["Gastric irritation", "Bleeding"],
        monitoring: ["—"] },
      { generic: "Isosorbide dinitrate (when NOT to)", brand: "Sorbitrate", dose: "5 mg sublingual", route: "SL", frequency: "Once; may repeat after 5 min", duration: "—",
        indication: "Ongoing ischaemic pain with adequate BP — in hospital or with clinician oversight",
        mechanism: "Nitric oxide donor → venodilatation (lower preload) and coronary vasodilatation.",
        whyItWorks: "Relieves angina; it does not reduce MI mortality.",
        avoidWhen: ["Sildenafil within 24 h or tadalafil within 48 h", "SBP < 90 mmHg", "Right-ventricular infarction", "Severe aortic stenosis"],
        adverseEffects: ["Hypotension, syncope", "Headache"],
        monitoring: ["BP before and after each dose"] },
      { generic: "Tenecteplase", brand: "Elaxim", dose: "30–50 mg by weight (half dose if ≥ 75 years)", route: "IV", frequency: "Single bolus", duration: "Once",
        indication: "STEMI when primary PCI cannot be done within 120 minutes",
        mechanism: "Fibrin-specific plasminogen activator → dissolves the coronary thrombus.",
        whyItWorks: "Restores flow — the earlier, the more muscle saved (best within 3 hours).",
        avoidWhen: ["Previous intracranial haemorrhage", "Ischaemic stroke < 3 months", "Active bleeding", "Aortic dissection"],
        adverseEffects: ["Bleeding, including intracranial (~1%)"],
        monitoring: ["ST resolution at 60–90 min; transfer for angiography (pharmaco-invasive strategy)"] },
    ],
    routines: [
      { label: "Advising a caller with chest pain",
        steps: [
          { order: 1, step: "Is the pain still there, how long, sweating or breathless?", note: "Ongoing pain > 15 min with sweating = act now" },
          { order: 2, step: "Ambulance (108) — or the nearest hospital with an ECG if the ambulance is far", note: "Never alone, never with the patient driving" },
          { order: 3, step: "Chew one Disprin (aspirin 325–350 mg)", note: "Unless truly allergic" },
          { order: 4, step: "Ask about Viagra-type tablets before any Sorbitrate", note: "Sildenafil 24 h, tadalafil 48 h" },
          { order: 5, step: "Rest; unlock the door; keep the phone on speaker" },
          { order: 6, step: "If he collapses and isn't breathing normally: push hard and fast in the centre of the chest", howMuch: "100–120 per minute, 5–6 cm deep" },
        ],
        avoid: ["Antacids or 'gas' tablets instead of hospital", "Painkillers like Combiflam or diclofenac", "Sorbitrate after sildenafil or tadalafil", "Waiting until morning"],
        improvementTimeline: "Targets at hospital: ECG within 10 minutes; thrombolysis within 30 minutes; primary PCI within 90 minutes of arrival." },
    ],
    followUp: {
      interval: "Cardiology review 1–2 weeks after discharge, then every 3 months in the first year",
      reassess: ["Chest pain and breathlessness", "Dual antiplatelet adherence (aspirin + ticagrelor/clopidogrel for 12 months)", "High-intensity statin; LDL < 55 mg/dL", "BP, sugar (HbA1c), smoking cessation", "Echo — LVEF after 6–12 weeks"],
      redFlags: ["Chest pain at rest again", "Breathlessness lying flat or ankle swelling", "Fainting or palpitations"],
      whenToEscalate: ["Recurrent angina on treatment → repeat angiography", "LVEF ≤ 35% after 3 months → ICD evaluation"],
    },
    treatmentFailure: { steps: [
      "Pain continuing in hospital → repeat ECG every 15–30 minutes",
      "STEMI and PCI not possible within 120 minutes → thrombolyse within 30 minutes",
      "Failed thrombolysis (< 50% ST resolution at 60–90 min) → rescue PCI",
      "Cardiogenic shock → emergency PCI regardless of delay",
    ] },
    pearl: "On the phone you have three jobs: recognise the heart attack, get an ambulance moving, and make the home safe — aspirin to chew, nobody driving, and no Sorbitrate until you've asked about Viagra-type tablets. Everything else can wait for the ECG.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "Sorbitrate is often the first thing a family reaches for — and he had taken sildenafil three hours earlier. The combination drops blood pressure profoundly; in a heart already starved of blood, that can be fatal.",
      sequence: ["Ask about PDE-5 inhibitors before any nitrate", "If it's already been taken: lie flat, legs raised", "Ambulance — IV fluids and vasopressors in hospital", "No further nitrates"],
    },
    extraInvestigations: [
      { id: "ecg", name: "12-lead ECG", whenToOrder: "Within 10 minutes of reaching hospital — or by the ambulance crew.", whatItTellsYou: "STEMI (reperfusion now) versus NSTE-ACS.", cost: 200, priority: "essential" },
      { id: "troponin", name: "High-sensitivity troponin", whenToOrder: "On arrival and at 1–3 hours.", whatItTellsYou: "Myocardial injury — the basis for NSTEMI.", cost: 1200, priority: "essential" },
      { id: "echo", name: "2D echocardiography", whenToOrder: "Before discharge.", whatItTellsYou: "LV function and complications.", cost: 2500, priority: "useful" },
    ],
  },
};
