import type { ClinicalCaseDefinition } from "../case-definition";
import { radiograph } from "./media";

export const surgAppendicitis: ClinicalCaseDefinition = {
  id: "surg-appendicitis-01",
  specialty: "Surgery",
  track: "emergency",
  level: "district",
  setting: "ER",
  weight: 3,
  difficulty: 2,
  patient: { name: "Rahul", age: 24, sex: "Male", city: "Laxmi Nagar, Delhi", occupation: "Delivery executive", context: "Emergency" },
  arrivalMinuteOfDay: 22 * 60 + 40,
  briefing: "22:40. A 24-year-old man has been wheeled into the emergency department by his roommate.",
  initialStatus: "guarded",
  opening: [
    { role: "system", kind: "action", text: "Triage: abdominal pain since this morning, vomited twice. Vitals on the board." },
    { role: "patient", kind: "speech", text: "Doctor, my stomach has been hurting since morning. It's getting worse." },
  ],
  baselineVitals: {
    temp: { key: "temp", value: "100.6" },
    hr: { key: "hr", value: "104" },
    bp: { key: "bp", value: "124/80" },
    rr: { key: "rr", value: "18" },
    spo2: { key: "spo2", value: "98" },
    rbs: { key: "rbs", value: "108" },
    weight: { key: "weight", value: "64" },
    height: { key: "height", value: "172" },
    pain: { key: "pain", value: "7" },
  },
  triageVitals: ["temp", "hr", "bp", "spo2"],
  profile: { allergies: ["penicillin"] },

  history: [
    { id: "cc", group: "complaint", label: "Chief complaint", importance: "essential",
      match: ["what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "what happened", "whats wrong"],
      reply: "Stomach pain since this morning, doctor. It keeps getting worse.",
      fact: "Abdominal pain since morning, worsening" },
    { id: "site", group: "hpi", label: "Site & migration", importance: "essential", abnormal: true,
      match: ["where", "site", "location", "where is the pain", "where does it hurt", "show me", "start", "started", "begin", "began", "how did it start", "when did", "since when", "how long", "tell me about the pain", "tell me more", "pain", "first", "move", "moved", "shift", "shifted"],
      reply: "It started around my belly button early this morning, a dull ache. By afternoon it moved down here — to the lower right side. Now it's sharp, and it's there all the time.",
      fact: "Periumbilical → right lower quadrant over ~10 h; now constant and sharp" },
    { id: "character", group: "hpi", label: "Character & severity", importance: "useful",
      match: ["type of pain", "character", "nature", "sharp", "dull", "colicky", "severity", "how bad", "score", "out of 10", "intensity", "constant", "comes and goes", "cramping"],
      reply: "It's a constant, sharp pain. Maybe seven out of ten. Walking and coughing make it worse.",
      fact: "Constant, sharp, 7/10; worse on movement and coughing" },
    { id: "aggravating", group: "hpi", label: "Aggravating / relieving", importance: "useful",
      match: ["worse", "aggravate", "movement", "cough", "relieve", "better", "anything helps", "position", "comfortable"],
      reply: "Moving makes it worse. Every bump in the auto on the way here hurt. Lying still with my knees up helps a little.",
      fact: "Worse with movement; lies still" },
    { id: "radiation", group: "hpi", label: "Radiation", importance: "minor",
      match: ["radiate", "radiation", "spread", "go anywhere", "back pain", "groin", "shoulder", "travel"],
      reply: "No, it stays in one place now.",
      fact: "No radiation" },
    { id: "vomiting", group: "hpi", label: "Nausea & vomiting", importance: "essential", abnormal: true,
      match: ["vomit", "vomiting", "vomited", "nausea", "nauseous", "throw up", "threw up", "feel sick"],
      reply: "I vomited twice — after the pain started. I feel sick just thinking about food.",
      fact: "Vomited ×2 after pain onset; nausea" },
    { id: "appetite", group: "hpi", label: "Appetite & last meal", importance: "useful", abnormal: true,
      match: ["appetite", "hungry", "eaten", "last meal", "when did you last eat", "last ate", "food", "anything to eat"],
      reply: "I haven't eaten anything since last night. Not hungry at all. The last thing I had was a cup of tea at six this morning.",
      fact: "Anorexia; last intake tea at 06:00" },
    { id: "fever", group: "systemic", label: "Fever", importance: "useful", abnormal: true,
      match: ["fever", "temperature", "chills", "rigors", "shivering", "feverish"],
      reply: "I've been feeling a bit feverish since the evening.",
      fact: "Feverish since evening" },
    { id: "bowel", group: "systemic", label: "Bowel habit", importance: "useful",
      match: ["bowel", "stool", "stools", "motion", "motions", "diarrhoea", "diarrhea", "constipation", "constipated", "loose", "gas", "flatus", "toilet"],
      reply: "I passed stool once this morning — normal. No loose motions.",
      fact: "Bowels opened this morning, normal" },
    { id: "urinary", group: "systemic", label: "Urinary symptoms", importance: "essential",
      match: ["urine", "urinary", "burning", "pass urine", "passing urine", "urination", "blood in urine", "frequency", "kidney stone", "stone", "peeing"],
      reply: "No burning, no blood. Urine is normal.",
      fact: "No urinary symptoms" },
    { id: "testes", group: "systemic", label: "Scrotal symptoms", importance: "useful",
      match: ["testis", "testes", "testicle", "testicles", "scrotum", "scrotal", "groin swelling", "balls"],
      reply: "No, nothing there. No pain or swelling.",
      fact: "No scrotal pain or swelling" },
    { id: "past", group: "past", label: "Past history", importance: "useful",
      match: ["past history", "medical history", "illness", "comorbid", "comorbidities", "diabetes", "bp", "asthma", "similar", "before", "previous episode", "previous episodes", "surgery", "operation", "operated", "tuberculosis", "known case"],
      reply: "Never had anything like this. No illnesses, no operations.",
      fact: "No prior illness or surgery" },
    { id: "meds", group: "medication", label: "Medications taken", importance: "useful",
      match: ["medicine", "medicines", "tablet", "taken anything", "painkiller", "painkillers", "took anything", "taking anything", "medication"],
      reply: "I took one Meftal Spas from the chemist at noon. It didn't help much.",
      fact: "Mefenamic acid + dicyclomine ×1 at noon" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "essential", abnormal: true,
      match: ["allergy", "allergic", "allergies", "drug reaction", "reaction to any", "reaction"],
      reply: "Yes — penicillin. I got a rash all over and my lips swelled up after an injection when I was in school.",
      fact: "PENICILLIN ALLERGY — urticaria and lip angioedema" },
    { id: "habits", group: "social", label: "Smoking / alcohol", importance: "minor",
      match: ["smoke", "smoking", "alcohol", "drink", "tobacco", "cigarettes"],
      reply: "I smoke sometimes — three or four a day. No alcohol.",
      fact: "Smokes 3–4/day" },
    { id: "family", group: "family", label: "Family history", importance: "minor",
      match: ["family", "mother", "father", "siblings", "parents"],
      reply: "Nothing like this in the family.",
      fact: "Non-contributory" },
  ],

  exam: [
    { id: "general", group: "general-exam", label: "General examination", importance: "useful", abnormal: true, match: [],
      finding: "Lying still on the trolley with his knees slightly flexed; looks uncomfortable. Tongue dry. No pallor or icterus." },
    { id: "hydration", group: "general-exam", label: "Hydration", importance: "minor", abnormal: true, match: [],
      finding: "Tongue dry. Skin turgor mildly reduced." },
    { id: "abdomen", group: "systemic-exam", label: "Abdomen", importance: "essential", abnormal: true, match: [],
      finding: "Right lower quadrant moves poorly with respiration. Tenderness maximal at McBurney's point with voluntary guarding in the right iliac fossa. No palpable mass. Bowel sounds sluggish.",
      fact: "RIF tenderness with guarding; sluggish bowel sounds",
      patientReaction: "Aah — yes, right there!" },
    { id: "mcburney", group: "local-exam", label: "McBurney's point", importance: "essential", abnormal: true,
      match: ["mcburney", "mcburneys", "mcburneys point", "mcburney point", "right iliac fossa", "rif", "rif tenderness", "right lower quadrant", "rlq"],
      finding: "Marked tenderness at McBurney's point.",
      fact: "Tender at McBurney's point",
      patientReaction: "Aah! That's exactly where it hurts." },
    { id: "rebound", group: "local-exam", label: "Rebound tenderness", importance: "useful", abnormal: true,
      match: ["rebound", "rebound tenderness", "blumberg", "release tenderness"],
      finding: "Rebound tenderness present in the right iliac fossa.",
      fact: "Rebound tenderness, RIF",
      patientReaction: "Ow — letting go hurts more than pressing!" },
    { id: "rovsing", group: "local-exam", label: "Rovsing's sign", importance: "useful", abnormal: true,
      match: ["rovsing", "rovsings", "rovsings sign", "press the left side", "left iliac fossa", "lif"],
      finding: "Pressure in the left iliac fossa produces pain in the right iliac fossa.",
      fact: "Rovsing's sign positive" },
    { id: "psoas", group: "local-exam", label: "Psoas sign", importance: "useful", abnormal: true,
      match: ["psoas", "psoas sign", "iliopsoas", "hip extension"],
      finding: "Pain in the right iliac fossa on passive extension of the right hip.",
      fact: "Psoas sign positive" },
    { id: "obturator", group: "local-exam", label: "Obturator sign", importance: "minor",
      match: ["obturator", "obturator sign", "internal rotation"],
      finding: "Mild discomfort on internal rotation of the flexed right hip.",
      fact: "Obturator sign equivocal" },
    { id: "cough-test", group: "local-exam", label: "Cough / heel-drop test", importance: "minor", abnormal: true,
      match: ["cough test", "dunphy", "heel drop", "markle", "jump", "percussion tenderness"],
      finding: "Pain in the right iliac fossa on coughing and on heel drop.",
      fact: "Dunphy's and heel-drop positive" },
    { id: "renal-angle", group: "local-exam", label: "Renal angles", importance: "useful",
      match: ["renal angle", "renal angles", "costovertebral", "cva tenderness", "flank", "loin", "punch"],
      finding: "No renal angle tenderness.",
      fact: "Renal angles non-tender" },
    { id: "murphy", group: "local-exam", label: "Murphy's sign", importance: "minor",
      match: ["murphy", "murphys", "murphys sign", "gallbladder", "right upper quadrant", "ruq", "right hypochondrium"],
      finding: "Murphy's sign negative. No right upper quadrant tenderness.",
      fact: "Murphy's negative" },
    { id: "genital", group: "local-exam", label: "Scrotum & hernial orifices", importance: "useful",
      match: ["scrotum", "testes", "testis", "testicles", "scrotal examination", "hernia", "hernial orifices", "inguinal"],
      finding: "Both testes normal in position, size and consistency; non-tender. Hernial orifices free.",
      fact: "Testes normal; hernial orifices free" },
    { id: "pr", group: "local-exam", label: "Per-rectal", importance: "minor", match: [],
      finding: "Performed with a chaperone. Tenderness on the right side of the rectum. No mass, no blood on the glove.",
      fact: "Right-sided rectal tenderness" },
  ],

  investigations: [
    { id: "cbc", priority: "essential",
      rows: [
        { analyte: "Haemoglobin", value: "14.8", unit: "g/dL", reference: "13.0–17.0", flag: "normal" },
        { analyte: "Total leucocyte count", value: "14,600", unit: "/µL", reference: "4,000–11,000", flag: "high" },
        { analyte: "Neutrophils", value: "84", unit: "%", reference: "40–75", flag: "high" },
        { analyte: "Lymphocytes", value: "11", unit: "%", reference: "20–45", flag: "low" },
        { analyte: "Platelets", value: "2.9", unit: "lakh/µL", reference: "1.5–4.5", flag: "normal" },
        { analyte: "Haematocrit", value: "45", unit: "%", reference: "40–50", flag: "normal" },
      ],
      teaching: { whenToOrder: "Every suspected acute abdomen.", whatItTellsYou: "Leucocytosis with neutrophilia supports inflammation and feeds the Alvarado score." } },
    { id: "crp", priority: "useful", rows: [{ analyte: "CRP", value: "48", unit: "mg/L", reference: "< 6", flag: "high" }],
      teaching: { whenToOrder: "Equivocal cases; very high CRP suggests complicated appendicitis.", whatItTellsYou: "Degree of inflammation." } },
    { id: "usg-abdomen", priority: "essential",
      media: radiograph("usg", "Right iliac fossa, linear probe", [{ id: "appendix-thickened" }], 23, "Greyscale ultrasound image of the right iliac fossa.", "Linear 9 MHz · graded compression"),
      report: "The appendix is non-compressible, 9 mm in outer diameter, with an 8 mm echogenic focus casting a posterior acoustic shadow at its base. Surrounding echogenic fat. Minimal free fluid in the right iliac fossa. Rest of the abdomen normal.",
      teaching: { whenToOrder: "First-line imaging for suspected appendicitis, especially in the young.", whatItTellsYou: "A non-compressible appendix > 6 mm, appendicolith, periappendiceal fat stranding or collection." } },
    { id: "urine-rm", priority: "useful",
      teaching: { whenToOrder: "Every RIF pain — excludes UTI and ureteric colic.", whatItTellsYou: "Pyuria or haematuria pointing to the urinary tract (mild pyuria can occur in appendicitis)." } },
    { id: "rft", priority: "useful", teaching: { whenToOrder: "Before surgery and contrast.", whatItTellsYou: "Renal function, electrolytes after vomiting." } },
    { id: "electrolytes", priority: "useful", teaching: { whenToOrder: "Vomiting, before surgery.", whatItTellsYou: "Sodium and potassium." } },
    { id: "coag", priority: "useful", teaching: { whenToOrder: "Pre-operatively in many units.", whatItTellsYou: "Clotting before surgery." } },
    { id: "blood-group", priority: "useful", teaching: { whenToOrder: "Before any emergency surgery.", whatItTellsYou: "Group and save." } },
    { id: "viral-markers", priority: "useful", teaching: { whenToOrder: "Pre-operative screening per institutional policy.", whatItTellsYou: "HIV, HBsAg, HCV status." } },
    { id: "ecg", priority: "situational", teaching: { whenToOrder: "Pre-anaesthetic in patients > 40 or with cardiac risk.", whatItTellsYou: "Rhythm, ischaemia." } },
    { id: "cxr", priority: "situational", teaching: { whenToOrder: "Respiratory symptoms, or to exclude basal pneumonia mimicking RIF pain.", whatItTellsYou: "Lungs, free gas." } },
    { id: "ct-abdomen", priority: "unnecessary",
      teaching: { whenToOrder: "When the diagnosis is uncertain after ultrasound — equivocal scan, the elderly, the obese, or a suspected mass/abscess.", whatItTellsYou: "Appendix, abscess, alternative diagnoses. Not needed in a young man with classic findings and a positive ultrasound." } },
    { id: "xray-abdomen", priority: "unnecessary", teaching: { whenToOrder: "Suspected perforation or obstruction.", whatItTellsYou: "Free gas, air–fluid levels." } },
    { id: "amylase-lipase", priority: "unnecessary", teaching: { whenToOrder: "Epigastric pain radiating to the back.", whatItTellsYou: "Pancreatitis." } },
    { id: "upt", priority: "unnecessary", teaching: { whenToOrder: "Every woman of reproductive age with abdominal pain.", whatItTellsYou: "Pregnancy / ectopic — not applicable here." } },
  ],

  therapeutics: [
    { id: "npo", kind: "supportive", measureIds: ["npo"], label: "Nil by mouth", appropriateness: "ideal" },
    { id: "iv-access", kind: "supportive", measureIds: ["iv-access"], label: "IV access", appropriateness: "acceptable" },
    { id: "iv-fluids", kind: "drug", drugIds: ["rl", "ns", "dns"], label: "IV crystalloid", appropriateness: "ideal" },
    { id: "analgesia", kind: "drug", drugIds: ["paracetamol"], label: "Paracetamol", appropriateness: "ideal", doseRange: { min: 500, max: 1000, unit: "mg" } },
    { id: "opioid-analgesia", kind: "drug", drugIds: ["morphine", "tramadol", "fentanyl", "pentazocine"], label: "Opioid analgesia", appropriateness: "acceptable",
      praise: "Gave adequate analgesia — it does not mask the signs of appendicitis." },
    { id: "nsaid-analgesia", kind: "drug", drugIds: ["ketorolac", "diclofenac", "aceclofenac", "ibuprofen"], label: "NSAID analgesia", appropriateness: "acceptable" },
    { id: "antiemetic", kind: "drug", drugIds: ["ondansetron", "metoclopramide", "domperidone"], label: "Antiemetic", appropriateness: "acceptable" },
    { id: "cephalosporin", kind: "drug", drugIds: ["ceftriaxone", "cefuroxime"], label: "IV cephalosporin", appropriateness: "ideal",
      praise: "Chose a third-generation cephalosporin despite the penicillin allergy — cross-reactivity is low and it was the right call." },
    { id: "fluoroquinolone", kind: "drug", drugIds: ["ciprofloxacin", "levofloxacin"], label: "Fluoroquinolone", appropriateness: "acceptable" },
    { id: "metronidazole", kind: "drug", drugIds: ["metronidazole"], label: "Metronidazole", appropriateness: "ideal" },
    { id: "penicillin", kind: "drug", drugClasses: ["penicillin"], label: "Penicillin-class antibiotic", appropriateness: "dangerous",
      critique: { what: "Gave a penicillin-class antibiotic.", why: "He reported penicillin allergy with lip swelling — an IgE-mediated reaction. Piperacillin–tazobactam and amoxicillin–clavulanate are penicillins.", better: "Ceftriaxone + metronidazole (3rd-generation cephalosporins have low cross-reactivity), or ciprofloxacin + metronidazole if the reaction was severe.", severity: "major" } },
    { id: "carbapenem", kind: "drug", drugIds: ["meropenem"], label: "Carbapenem", appropriateness: "unnecessary",
      critique: { what: "Used meropenem for uncomplicated appendicitis.", why: "Carbapenems are reserved for resistant organisms or septic shock; overuse drives resistance.", better: "Ceftriaxone + metronidazole.", severity: "minor" } },
    { id: "antispasmodic", kind: "drug", drugIds: ["drotaverine", "hyoscine"], label: "Antispasmodic", appropriateness: "unnecessary" },
    { id: "surgical-consult", kind: "referral", label: "Surgical consultation", appropriateness: "acceptable",
      match: ["surgery consult", "surgical consult", "call surgeon", "call the surgeon", "surgery opinion", "surgical opinion", "refer to surgery", "general surgery", "surgery referral", "surgical referral", "inform surgeon", "surgery team"],
      response: [{ role: "system", kind: "action", text: "Surgery resident informed — on the way." }],
      praise: "Involved the surgical team early." },
    { id: "admit", kind: "admit", measureIds: ["admit"], label: "Admit under surgery", appropriateness: "acceptable" },
    { id: "consent", kind: "counsel", label: "Informed consent", appropriateness: "acceptable",
      match: ["consent", "take consent", "informed consent", "explain the surgery", "explain the procedure", "high risk consent"],
      response: [{ role: "patient", kind: "speech", text: "If it needs an operation, please do it, doctor. I just want the pain to stop." }] },
    { id: "appendicectomy", kind: "procedure", label: "Laparoscopic appendicectomy", appropriateness: "ideal", durationMin: 80,
      match: ["laparoscopic appendicectomy", "lap appendicectomy", "laparoscopic appendectomy", "lap appendectomy", "appendicectomy", "appendectomy", "appendix surgery", "remove the appendix", "remove appendix", "take up for surgery", "posted for surgery", "emergency surgery", "open appendicectomy", "lanz incision", "shift to ot", "shift to operation theatre", "take to ot", "take him to ot", "operate", "surgery"],
      note: "Under general anaesthesia: inflamed, oedematous appendix with a faecolith at its base; no perforation. Minimal turbid fluid in the pelvis, aspirated. Base secured with endoloops; specimen sent for histopathology. Uneventful.",
      altNote: { ifHazard: "perforation", note: "Under general anaesthesia: gangrenous appendix perforated near its base, faecolith free in the peritoneal cavity, ~300 mL of purulent fluid in the pelvis and paracolic gutters. Converted to open; appendicectomy and thorough peritoneal lavage; drain placed. Specimen sent for histopathology." },
      settingAfter: "IPD", statusAfter: "stable",
      vitalsAfter: [{ key: "temp", value: "99.4" }, { key: "hr", value: "88" }, { key: "pain", value: "3" }, { key: "bp", value: "122/78" }],
      rescues: ["perforation"],
      praise: "Took him for laparoscopic appendicectomy — definitive treatment — in good time." },
    { id: "laparotomy", kind: "procedure", label: "Exploratory laparotomy", appropriateness: "acceptable", durationMin: 110,
      match: ["laparotomy", "exploratory laparotomy", "explore the abdomen", "peritoneal lavage", "open the abdomen"],
      note: "Under general anaesthesia via midline incision: inflamed appendix; appendicectomy performed. Lavage given.",
      altNote: { ifHazard: "perforation", note: "Under general anaesthesia via midline incision: perforated gangrenous appendix with purulent peritonitis. Appendicectomy, peritoneal lavage, drains placed." },
      settingAfter: "IPD", statusAfter: "stable",
      vitalsAfter: [{ key: "temp", value: "99.6" }, { key: "hr", value: "92" }, { key: "pain", value: "4" }],
      critique: { what: "Chose a laparotomy for uncomplicated appendicitis.", why: "A midline laparotomy adds pain, ileus and hernia risk when a laparoscopic or Lanz approach suffices.", better: "Laparoscopic appendicectomy.", severity: "minor" } },
    { id: "discharge", kind: "discharge", measureIds: ["discharge"], label: "Discharge home", appropriateness: "harmful",
      critique: { what: "Sent him home.", why: "Migratory RIF pain, anorexia, vomiting, fever, RIF guarding and leucocytosis give an Alvarado score of 10 — this needs surgery, not discharge.", better: "Admit under surgery, keep NPO, IV fluids, analgesia, antibiotics, and appendicectomy.", severity: "major" } },
  ],

  hazards: [
    { id: "perforation", label: "Perforated appendicitis with peritonitis",
      omission: { byMinute: 480, preventedBy: ["appendicectomy", "laparotomy"] },
      stages: [
        { afterMin: 0, status: "deteriorating", interrupts: true,
          vitals: [{ key: "temp", value: "102.4" }, { key: "hr", value: "122" }, { key: "bp", value: "108/66" }, { key: "rr", value: "24" }, { key: "pain", value: "9" }],
          observation: { role: "system", text: "The patient's pain has suddenly become severe and spread across the whole abdomen. He is shivering." },
          examFindings: { abdomen: "Generalised tenderness with board-like rigidity. Rebound tenderness throughout. Bowel sounds absent.", mcburney: "Exquisitely tender — the whole abdomen is tender now.", general: "Lying absolutely still, flushed, shivering. Tongue dry." },
          patientSays: "The whole stomach is hurting now… I can't move.",
          investigations: {
            cbc: { rows: [
              { analyte: "Haemoglobin", value: "14.2", unit: "g/dL", reference: "13.0–17.0", flag: "normal" },
              { analyte: "Total leucocyte count", value: "21,800", unit: "/µL", reference: "4,000–11,000", flag: "critical" },
              { analyte: "Neutrophils", value: "90", unit: "%", reference: "40–75", flag: "high" },
              { analyte: "Platelets", value: "2.4", unit: "lakh/µL", reference: "1.5–4.5", flag: "normal" },
            ] },
            crp: { rows: [{ analyte: "CRP", value: "186", unit: "mg/L", reference: "< 6", flag: "critical" }] },
            "usg-abdomen": { report: "Free fluid with internal echoes in the pelvis and right paracolic gutter. A complex collection in the right iliac fossa; the appendix is not separately visualised. Dilated small-bowel loops with sluggish peristalsis.", media: radiograph("usg", "Right iliac fossa, curvilinear probe", [{ id: "appendix-thickened", severity: 3 }], 29, "Greyscale ultrasound image of the right iliac fossa.", "Curvilinear 3.5 MHz") },
            abg: { rows: [
              { analyte: "pH", value: "7.31", reference: "7.35–7.45", flag: "low" },
              { analyte: "pCO₂", value: "32", unit: "mmHg", reference: "35–45", flag: "low" },
              { analyte: "HCO₃⁻", value: "17", unit: "mEq/L", reference: "22–26", flag: "low" },
              { analyte: "Lactate", value: "3.4", unit: "mmol/L", reference: "< 2.0", flag: "high" },
            ] },
          } },
        { afterMin: 150, status: "critical",
          vitals: [{ key: "temp", value: "103.2" }, { key: "hr", value: "134" }, { key: "bp", value: "86/52" }, { key: "rr", value: "28" }, { key: "spo2", value: "94" }],
          observation: { role: "nurse", text: "Doctor, BP is 86 by 52. He's drowsy and his hands are cold." },
          patientSays: "(Drowsy.) So cold…" },
        { afterMin: 330, status: "critical",
          vitals: [{ key: "bp", value: "72/40" }, { key: "hr", value: "144" }, { key: "rr", value: "32" }, { key: "spo2", value: "90" }, { key: "gcs", value: "12" }],
          observation: { role: "nurse", text: "He's barely responding. Urine bag is almost empty." } },
        { afterMin: 560, status: "deceased",
          vitals: [{ key: "bp", value: "0/0" }, { key: "hr", value: "0" }, { key: "gcs", value: "3" }],
          observation: { role: "nurse", text: "Cardiac arrest — no return of circulation after resuscitation." } },
      ],
      rescue: [["appendicectomy", "laparotomy"], ["iv-fluids"], ["cephalosporin", "fluoroquinolone"]],
      fullRecoveryWindowMin: 150,
      lastRescueMin: 520,
      recovery: [
        { afterMin: 60, status: "guarded", vitals: [{ key: "temp", value: "101.0" }, { key: "hr", value: "112" }, { key: "bp", value: "104/66" }], patientSays: "Still sore, but the pain isn't everywhere now." },
        { afterMin: 720, status: "improving", vitals: [{ key: "temp", value: "99.4" }, { key: "hr", value: "92" }, { key: "bp", value: "118/76" }, { key: "pain", value: "3" }], patientSays: "Much better today, doctor." },
      ],
      review: {
        cause: "Definitive surgery was not done in time — the inflamed, obstructed appendix perforated.",
        whyItCausedHarm: "A faecolith obstructs the lumen → rising pressure, bacterial overgrowth and venous congestion → ischaemia and gangrene → perforation → faecal-purulent peritonitis → sepsis and septic shock.",
        earliestRescueWindow: "At presentation: Alvarado 10, positive ultrasound — appendicectomy within a few hours of the decision.",
        correctRescueSequence: [
          "Recognise peritonitis — generalised rigidity, fever, tachycardia",
          "Two large-bore cannulae; 30 mL/kg crystalloid if hypotensive or lactate ≥ 4",
          "Blood cultures, then IV antibiotics within 1 hour (ceftriaxone + metronidazole — no penicillins in this patient)",
          "Urgent source control: laparoscopic/open appendicectomy with peritoneal lavage",
          "Catheterise; chart urine output; vasopressors if hypotension persists after fluids",
        ],
        lastRealisticRescueWindow: "Within a few hours of perforation, before established septic shock and organ failure.",
      } },
  ],

  followUp: [
    { when: "ideal", status: "recovered",
      lines: [
        { role: "patient", kind: "speech", text: "I'm feeling fine, doctor. I'll be back on the bike next week." },
        { role: "system", kind: "finding", text: "Port sites healed. No tenderness. Afebrile." },
      ] },
    { when: "acceptable", status: "improving",
      lines: [{ role: "patient", kind: "speech", text: "Mostly fine. A little sore near the wound." }] },
    { when: "any", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "I'm better than I was, doctor." }] },
  ],

  truth: {
    diagnosis: "Acute appendicitis",
    qualifier: "Uncomplicated (non-perforated), with an appendicolith — Alvarado score 10/10",
    reasoning: [
      { stage: "History", text: "Periumbilical pain migrating to the right iliac fossa over ~10 h, then vomiting and anorexia; fever; no urinary or scrotal symptoms. Penicillin allergy." },
      { stage: "Examination", text: "Fever 100.6 °F, HR 104. McBurney's tenderness with guarding and rebound; Rovsing's and psoas signs positive; renal angles and testes normal." },
      { stage: "Investigation", text: "TLC 14,600 with 84% neutrophils; CRP 48. USG: non-compressible 9 mm appendix with an appendicolith and fat stranding." },
      { stage: "Diagnosis", text: "Acute appendicitis (Alvarado 10) — for laparoscopic appendicectomy with non-penicillin prophylaxis." },
    ],
  },

  rubric: {
    diagnosisAccept: ["acute appendicitis", "appendicitis", "appendicular inflammation", "acute suppurative appendicitis", "obstructive appendicitis"],
    diagnosisPartial: ["appendicular mass", "appendicular abscess", "acute abdomen", "peritonitis", "right iliac fossa pain", "rif pain"],
    differentials: ["mesenteric adenitis", "meckel", "meckels diverticulitis", "renal colic", "ureteric colic", "ureteric calculus", "urinary tract infection", "uti", "pyelonephritis", "testicular torsion", "torsion", "terminal ileitis", "crohn", "ileocaecal tuberculosis", "abdominal tuberculosis", "gastroenteritis", "typhoid", "enteric perforation", "inguinal hernia", "cholecystitis", "pneumonia", "psoas abscess"],
    idealTreatment: [["npo"], ["iv-fluids"], ["analgesia", "opioid-analgesia", "nsaid-analgesia"], ["cephalosporin", "fluoroquinolone"], ["metronidazole"], ["appendicectomy", "laparotomy"]],
    expertActionCount: 18,
    followUpDays: { min: 7, max: 14 },
    expectsReassessment: true,
    definitiveTreatment: { ids: ["appendicectomy", "laparotomy"], byMinute: 360, label: "Appendicectomy" },
    weights: { history: 15, examination: 15, differential: 10, investigationSelection: 10, investigationInterpretation: 10, treatment: 15, drugSafety: 10, reassessment: 5, efficiency: 5, outcome: 5 },
    misses: {
      site: { what: "Did not establish where the pain started and where it went.", why: "Migration from the umbilicus to the right iliac fossa is the single most specific historical feature of appendicitis.", better: "Ask: “Where did it start? Has it moved?”", severity: "major" },
      vomiting: { what: "Did not ask about vomiting.", why: "In appendicitis, pain precedes vomiting; vomiting first suggests gastroenteritis.", better: "Ask about nausea, vomiting and their timing relative to the pain.", severity: "moderate" },
      urinary: { what: "Did not ask about urinary symptoms.", why: "Ureteric colic and UTI are the commonest mimics of right iliac fossa pain.", better: "Ask about burning, frequency, haematuria and loin pain.", severity: "moderate" },
      allergy: { what: "Did not ask about allergies.", why: "He has a penicillin allergy with angioedema — and the reflex ER antibiotic, piperacillin–tazobactam, is a penicillin.", better: "Ask about allergies before any antibiotic, every time.", severity: "major" },
      abdomen: { what: "Did not examine the abdomen properly.", why: "Localised RIF tenderness with guarding and rebound is the core sign.", better: "Inspect, palpate gently from the left iliac fossa, then the RIF; check guarding, rebound, Rovsing's.", severity: "major" },
      mcburney: { what: "Did not examine McBurney's point.", why: "Point tenderness here carries 2 points on the Alvarado score.", better: "Palpate one-third of the way from the right ASIS to the umbilicus.", severity: "moderate" },
      cbc: { what: "Did not order a blood count.", why: "Leucocytosis with a left shift adds 3 Alvarado points.", better: "CBC with differential in every acute abdomen.", severity: "moderate" },
      "usg-abdomen": { what: "No ultrasound.", why: "Ultrasound confirms the diagnosis and shows the appendicolith, which argues against antibiotics-only treatment.", better: "USG of the right iliac fossa with graded compression.", severity: "moderate" },
      npo: { what: "Did not keep him nil by mouth.", why: "He is heading to general anaesthesia; a full stomach risks aspiration.", better: "NPO from the moment surgery is likely.", severity: "moderate" },
      "iv-fluids": { what: "No IV fluids.", why: "Fever, vomiting and a dry tongue — he is volume-depleted before anaesthesia.", better: "Ringer lactate, guided by heart rate and urine output.", severity: "moderate" },
      analgesia: { what: "Left him in pain.", why: "Analgesia does not mask the diagnosis; untreated pain is cruel and raises sympathetic drive.", better: "IV paracetamol 1 g ± titrated morphine.", severity: "moderate" },
      cephalosporin: { what: "No pre-operative antibiotic.", why: "Pre-operative antibiotics cut wound infection and intra-abdominal abscess.", better: "Ceftriaxone 1 g IV + metronidazole 500 mg IV — not a penicillin in this patient.", severity: "moderate" },
      metronidazole: { what: "No anaerobic cover.", why: "Appendiceal flora includes Bacteroides; anaerobic cover is standard.", better: "Metronidazole 500 mg IV with the cephalosporin.", severity: "minor" },
      appendicectomy: { what: "No appendicectomy.", why: "With an appendicolith, antibiotics alone fail often; delay risks perforation.", better: "Laparoscopic appendicectomy, ideally within a few hours of the decision.", severity: "major" },
    },
    strengths: {
      site: "Elicited the classic migration of pain.",
      allergy: "Asked about allergies — and found the penicillin allergy.",
      urinary: "Excluded urinary causes from the history.",
      testes: "Asked about scrotal symptoms to exclude torsion.",
      rovsing: "Elicited Rovsing's sign.",
      psoas: "Checked the psoas sign.",
      genital: "Examined the scrotum — testicular torsion must never be missed.",
      "usg-abdomen": "Confirmed with ultrasound rather than reflex CT.",
      npo: "Kept him nil by mouth.",
    },
  },

  teaching: {
    patientBand: "uncomplicated",
    severityBands: [
      { id: "uncomplicated", label: "Uncomplicated",
        recognition: ["Migratory RIF pain, anorexia, vomiting, low-grade fever", "Localised RIF tenderness ± rebound", "Alvarado ≥ 7; USG: non-compressible appendix > 6 mm"],
        investigation: ["CBC, CRP, urine R/M; UPT in women", "USG first-line; CT if equivocal"],
        treatment: ["NPO, IV fluids, analgesia", "Pre-op ceftriaxone + metronidazole", "Laparoscopic appendicectomy", "Antibiotics-first is an option only without an appendicolith, after shared decision-making"],
        followUp: ["Discharge in 24–48 h; review at 7–10 days with histopathology"] },
      { id: "appendicolith", label: "Complicated — appendicolith / gangrene",
        recognition: ["Appendicolith on imaging", "Higher fever, CRP > 100", "Gangrenous wall on CT"],
        investigation: ["USG / CT"],
        treatment: ["Early appendicectomy — antibiotics-first fails in ~40% with an appendicolith", "Post-op antibiotics 3–5 days if gangrenous"],
        followUp: ["Watch for pelvic abscess (day 5–10 fever)"] },
      { id: "mass", label: "Appendicular mass / abscess",
        recognition: ["Pain for > 3–5 days", "Tender RIF mass; swinging fever with abscess"],
        investigation: ["CT abdomen to define phlegmon vs abscess"],
        treatment: ["Phlegmon: conservative (Ochsner–Sherren) — NPO, IV antibiotics, charting of mass, pulse and temperature", "Abscess > 3 cm: percutaneous drainage + antibiotics", "Interval appendicectomy at 6–8 weeks if recurrent or age > 40 (exclude malignancy)"],
        followUp: ["Colonoscopy if > 40 years"] },
      { id: "peritonitis", label: "Perforation with peritonitis",
        recognition: ["Sudden spread of pain, generalised rigidity", "High fever, tachycardia, hypotension"],
        investigation: ["Lactate, cultures; imaging must not delay surgery"],
        treatment: ["Resuscitation, IV antibiotics within 1 hour", "Emergency appendicectomy with lavage", "Septic-shock care — fluids, vasopressors, ICU"],
        followUp: ["Prolonged antibiotics; watch for residual collections"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Ceftriaxone", brand: "Monocef", dose: "1 g", route: "IV", frequency: "Once pre-operatively (12-hourly if continued)", duration: "Single dose if uncomplicated",
        indication: "Surgical prophylaxis / intra-abdominal infection",
        mechanism: "Binds penicillin-binding proteins → blocks peptidoglycan cross-linking → bacterial cell wall lysis.",
        whyItWorks: "Covers the Gram-negative gut organisms (E. coli, Klebsiella) involved in appendicitis.",
        avoidWhen: ["Previous anaphylaxis to a cephalosporin", "Neonates with jaundice (calcium co-administration)"],
        adverseEffects: ["Rash", "Diarrhoea, C. difficile", "Biliary sludge with prolonged use"],
        monitoring: ["Observe 30 min after the first dose in penicillin-allergic patients"] },
      { generic: "Metronidazole", brand: "Metrogyl", dose: "500 mg", route: "IV", frequency: "8-hourly", duration: "Single pre-op dose if uncomplicated; 3–5 days if complicated",
        indication: "Anaerobic cover",
        mechanism: "Reduced inside anaerobes to toxic radicals that break bacterial DNA.",
        whyItWorks: "Kills Bacteroides and other anaerobes in faecal flora.",
        avoidWhen: ["First trimester (relative)", "Alcohol within 48 h (disulfiram-like reaction)"],
        adverseEffects: ["Metallic taste", "Nausea", "Peripheral neuropathy with long courses"],
        monitoring: ["Not usually needed for short courses"] },
      { generic: "Paracetamol", brand: "Dolo 650", dose: "650 mg PO, or 1 g IV infusion", route: "IV", frequency: "6-hourly (max 4 g/day)", duration: "As required",
        indication: "Analgesia and antipyresis",
        mechanism: "Central COX inhibition and descending serotonergic modulation → raises the pain threshold and resets the hypothalamic set-point.",
        whyItWorks: "Effective analgesia and fever control without bleeding risk or gastric injury.",
        avoidWhen: ["Liver failure", "Chronic alcohol excess (reduce dose)"],
        adverseEffects: ["Hepatotoxicity in overdose"],
        monitoring: ["Daily total dose"] },
      { generic: "Ondansetron", brand: "Emeset", dose: "4 mg", route: "IV", frequency: "8-hourly as needed", duration: "Peri-operative",
        indication: "Nausea and vomiting",
        mechanism: "Blocks 5-HT3 receptors in the gut and chemoreceptor trigger zone.",
        whyItWorks: "Stops vagal and central signalling that triggers vomiting.",
        avoidWhen: ["Long QT"],
        adverseEffects: ["Headache, constipation", "QT prolongation"],
        monitoring: ["ECG if other QT-prolonging drugs"] },
    ],
    routines: [
      { label: "After laparoscopic appendicectomy",
        steps: [
          { order: 1, step: "Sips of water 6 hours after surgery", note: "Then liquids → soft diet on day 1" },
          { order: 2, step: "Walk on the evening of surgery", note: "Reduces ileus and clots" },
          { order: 3, step: "Port-site care", note: "Keep dry for 48 h; shower after that" },
          { order: 4, step: "Return to work", howMuch: "Desk work in ~1 week", note: "No heavy lifting or bike riding for 2–3 weeks" },
        ],
        avoid: ["Heavy lifting for 2–3 weeks"],
        improvementTimeline: "Most are home in 24–48 h and back to normal activity in 1–2 weeks." },
    ],
    followUp: {
      interval: "7–10 days",
      reassess: ["Wound / port sites", "Fever, bowel function", "Histopathology report"],
      redFlags: ["Fever after day 5", "Increasing pain or distension", "Discharge from a wound", "Diarrhoea with fever (pelvic abscess)"],
      whenToEscalate: ["Fever with pelvic tenderness → USG/CT for collection → drainage", "Histopathology showing a neoplasm → surgical oncology"],
    },
    treatmentFailure: { steps: [
      "Check adherence to the plan — was surgery actually done, were antibiotics given?",
      "Check the diagnosis — mesenteric adenitis, Meckel's, Crohn's, ileocaecal TB, gynaecological causes",
      "Check severity — has it perforated or formed a mass?",
      "Check complications — wound infection, pelvic abscess, ileus",
      "Alternative — percutaneous drainage for abscess; change antibiotics per culture",
      "Escalate — re-look laparoscopy / laparotomy",
    ] },
    pearl: "Pain that begins around the umbilicus and settles in the right iliac fossa, followed by vomiting and anorexia, is appendicitis until proven otherwise. And allergies are not a formality in surgical patients: the reflex pre-op antibiotic in many Indian ERs — piperacillin–tazobactam — is a penicillin.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "He reported penicillin allergy with lip swelling. Piperacillin–tazobactam or amoxicillin–clavulanate would have caused anaphylaxis within minutes; delaying surgery would have allowed perforation by early morning.",
      sequence: ["Ask about allergies before any antibiotic", "Choose ceftriaxone + metronidazole", "If anaphylaxis: adrenaline 0.5 mg IM, oxygen, fluids, then antihistamine and steroid", "Do not let a diagnosed appendicitis wait overnight without a plan"],
    },
  },
};
