import type { ClinicalCaseDefinition } from "../case-definition";
import { ecg } from "./media";

/**
 * The guided demo case: short, classic and forgiving, built for learning the
 * screen — talk to the family, check the sugar, treat, and watch him wake up.
 * Never picked at random; started from "Try a demo case" or the guided-case card.
 */
export const tutHypoglycaemia: ClinicalCaseDefinition = {
  id: "tut-hypoglycaemia-01",
  guided: true,
  specialty: "Emergency",
  track: "emergency",
  level: "chc",
  setting: "ER",
  weight: 0,
  difficulty: 1,
  patient: { name: "Ramesh", age: 62, sex: "Male", city: "Kanpur, Uttar Pradesh", occupation: "Retired clerk", context: "Emergency" },
  arrivalMinuteOfDay: 8 * 60 + 40,
  briefing: "08:40. A 62-year-old man is helped into the emergency room by his wife — sweaty, confused and slurring his words.",
  initialStatus: "deteriorating",
  opening: [
    { role: "system", kind: "action", text: "Triage: confused and sweating, brought by his wife. Vitals on the board." },
    { role: "attendant", kind: "speech", text: "Doctor, please see him — since his morning walk he isn't making any sense!" },
    { role: "patient", kind: "speech", text: "Hmm… where… where am I?" },
  ],
  baselineVitals: {
    bp: { key: "bp", value: "148/88" },
    hr: { key: "hr", value: "112" },
    rr: { key: "rr", value: "18" },
    spo2: { key: "spo2", value: "97" },
    temp: { key: "temp", value: "97.4" },
    rbs: { key: "rbs", value: "42" },
    gcs: { key: "gcs", value: "13" },
    weight: { key: "weight", value: "68" },
  },
  triageVitals: ["bp", "hr", "rr", "spo2", "temp"],
  profile: { currentDrugs: ["glimepiride", "metformin"], weightKg: 68 },

  history: [
    { id: "cc", group: "complaint", label: "What happened", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["what happened", "what brings you", "what brought you", "main problem", "chief complaint", "what is the problem", "whats the problem", "how can i help", "what seems to be", "tell me about", "since when", "how long", "started", "onset", "symptoms"],
      reply: "He went for his morning walk without breakfast. When he came back he was sweating badly, shaking, and talking nonsense. That was about an hour ago.",
      fact: "Sweating, tremor and confusion for ~1 hour, after a morning walk without breakfast" },
    { id: "diabetes", group: "past", label: "Past history", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["diabetes", "diabetic", "sugar patient", "has sugar", "bp", "blood pressure", "past", "medical history", "known case", "any disease", "illness", "medical problems", "heart", "kidney", "comorbidities", "comorbidity"],
      reply: "He has had sugar for twelve years, and BP. No heart problem that we know of.",
      fact: "Type 2 diabetes × 12 years; hypertension" },
    { id: "meds", group: "medication", label: "Medications", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["medicines", "medicine", "medication", "tablets", "tablet", "taking any", "drugs", "sugar tablet", "insulin", "prescription", "dose", "glimepiride", "amaryl"],
      reply: "Glimepiride in the morning and metformin twice a day. Last week the doctor increased the glimepiride to 2 mg. He took it this morning, before his walk.",
      fact: "Glimepiride increased to 2 mg last week, taken this morning; metformin" },
    { id: "meal", group: "diet", label: "Last meal", importance: "essential", abnormal: true, speaker: "attendant",
      match: ["eat", "ate", "eaten", "eating", "last eat", "last ate", "last meal", "did he eat", "food", "meal", "breakfast", "dinner", "skipped", "fasting", "empty stomach", "appetite", "diet"],
      reply: "He skipped breakfast — he wanted to walk first. Last night he barely ate; he said his stomach was upset.",
      fact: "No breakfast; poor intake last night" },
    { id: "episodes", group: "hpi", label: "Previous episodes", importance: "useful", abnormal: true, speaker: "attendant",
      match: ["before", "previous", "similar", "happened before", "first time", "past episodes", "episodes", "shaky", "low sugar"],
      reply: "Last week he felt shaky once before lunch. Tea and biscuits fixed it, so we didn't think much of it.",
      fact: "A milder shaky spell last week, relieved by food" },
    { id: "injury", group: "hpi", label: "Fall / head injury", importance: "useful", speaker: "attendant",
      match: ["fall", "fell", "head injury", "hit his head", "injury", "trauma", "accident", "fit", "seizure", "convulsion", "fits", "weakness", "paralysis", "one side"],
      reply: "No, he didn't fall or hit his head. No fits. He's moving his arms and legs normally.",
      fact: "No fall, head injury, seizure or limb weakness" },
    { id: "illness", group: "systemic", label: "Recent illness", importance: "useful", speaker: "attendant",
      match: ["fever", "vomiting", "vomit", "loose motions", "diarrhoea", "diarrhea", "infection", "cough", "urine", "burning"],
      reply: "No fever. He vomited once last night after dinner, nothing since.",
      fact: "One vomit last night; no fever" },
    { id: "alcohol", group: "social", label: "Alcohol / smoking", importance: "minor", speaker: "attendant",
      match: ["alcohol", "drink", "drinking", "smoke", "smoking", "tobacco"],
      reply: "He doesn't drink or smoke.",
      fact: "No alcohol or smoking" },
    { id: "allergy", group: "allergy", label: "Allergies", importance: "useful", speaker: "attendant",
      match: ["allergy", "allergic", "allergies", "drug reaction"],
      reply: "No allergies.",
      fact: "No known drug allergies" },
  ],

  exam: [
    { id: "general", group: "general-exam", label: "General examination", importance: "essential", abnormal: true, match: [],
      finding: "Drowsy but rousable to voice. Confused, slurred speech. Profuse sweating; cold, clammy skin. Fine tremor of both hands.",
      fact: "Drowsy, confused; sweaty and clammy; tremor" },
    { id: "cns", group: "systemic-exam", label: "Neurological", importance: "essential", abnormal: true, match: [],
      finding: "GCS 13 (E3 V4 M6). Pupils equal and reactive. Moves all four limbs; no focal weakness. Plantars flexor. No neck stiffness.",
      fact: "GCS 13; no focal deficit; no neck stiffness" },
    { id: "cvs", group: "systemic-exam", label: "Cardiovascular", importance: "useful", match: [],
      finding: "Pulse 112/min, regular, good volume. Heart sounds normal; no murmurs.",
      fact: "Regular tachycardia; normal heart sounds" },
    { id: "rs", group: "systemic-exam", label: "Respiratory", importance: "minor", match: [],
      finding: "Chest clear. No added sounds.",
      fact: "Chest clear" },
  ],

  investigations: [
    { id: "ecg", priority: "useful",
      media: ecg({ rate: 112, rhythm: "sinus" }, "Twelve-lead ECG at about 110 per minute."),
      report: "Sinus tachycardia, 112/min. Normal axis. No ST-segment or T-wave changes.",
      teaching: { whenToOrder: "Older diabetics with sweating and a fast pulse — a silent heart attack can look like this.", whatItTellsYou: "Here, sinus tachycardia from the adrenaline surge of hypoglycaemia; no ischaemia." } },
    { id: "rft", priority: "useful",
      rows: [
        { analyte: "Urea", value: "32", unit: "mg/dL", reference: "15–40", flag: "normal" },
        { analyte: "Creatinine", value: "1.0", unit: "mg/dL", reference: "0.7–1.3", flag: "normal" },
        { analyte: "Sodium", value: "138", unit: "mEq/L", reference: "135–145", flag: "normal" },
        { analyte: "Potassium", value: "4.1", unit: "mEq/L", reference: "3.5–5.1", flag: "normal" },
      ],
      teaching: { whenToOrder: "Every sulfonylurea low — weak kidneys make the drug last much longer.", whatItTellsYou: "Normal kidneys: the dose increase and missed meals explain this low." } },
    { id: "hba1c", priority: "situational",
      rows: [{ analyte: "HbA1c", value: "6.2", unit: "%", reference: "Target 7–7.5% for him", flag: "low" }],
      teaching: { whenToOrder: "When the intensity of diabetes treatment needs review.", whatItTellsYou: "6.2% at 62 on a sulfonylurea means he is over-treated." } },
    { id: "ct-head", priority: "unnecessary",
      teaching: { whenToOrder: "A focal deficit, head injury, or confusion that persists after the sugar is corrected.", whatItTellsYou: "Not needed when the confusion clears with glucose." } },
  ],

  therapeutics: [
    { id: "dextrose", kind: "drug", drugIds: ["dextrose-25"], label: "IV 25% dextrose", appropriateness: "ideal",
      response: [{ role: "system", kind: "action", text: "25% dextrose going in through the IV line." }],
      rescues: ["neuroglycopenia"],
      praise: "Gave IV dextrose without delay." },
    { id: "glucagon", kind: "drug", drugIds: ["glucagon"], label: "IM glucagon", appropriateness: "acceptable",
      rescues: ["neuroglycopenia"],
      praise: "Used glucagon — the right move when IV access is difficult." },
    { id: "d10", kind: "drug", drugIds: ["d10"], label: "10% dextrose infusion", appropriateness: "ideal",
      praise: "Started a 10% dextrose infusion — sulfonylurea lows come back for hours." },
    { id: "oral-glucose-rule", kind: "supportive", measureIds: ["oral-glucose"], label: "Oral glucose", appropriateness: "harmful",
      critique: { what: "Gave oral glucose to a drowsy, confused patient.", why: "With a GCS of 13 he can't protect his airway — sugar water can go into his lungs.", better: "IV 25% dextrose (or IM glucagon); oral glucose only once he's fully awake and swallowing safely.", severity: "moderate" } },
    { id: "admit", kind: "admit", measureIds: ["admit"], label: "Admit for observation", appropriateness: "ideal",
      praise: "Admitted him — glimepiride can drop the sugar again for 24–72 hours." },
    { id: "hold-glimepiride", kind: "counsel", label: "Stop glimepiride", appropriateness: "ideal",
      concernsDrugs: ["glimepiride"],
      match: ["stop glimepiride", "hold glimepiride", "withhold glimepiride", "stop the sugar tablet", "stop sulfonylurea", "stop sulphonylurea", "reduce glimepiride"],
      praise: "Stopped the glimepiride that caused it." },
    { id: "monitor-rule", kind: "supportive", measureIds: ["monitor"], label: "Cardiac monitoring", appropriateness: "acceptable" },
    { id: "iv-access-rule", kind: "supportive", measureIds: ["iv-access"], label: "IV access", appropriateness: "acceptable" },
    { id: "insulin", kind: "drug", drugClasses: ["insulin"], label: "Insulin", appropriateness: "dangerous",
      critique: { what: "Gave insulin to a hypoglycaemic patient.", why: "His sugar was already 42 mg/dL — insulin drives it lower: seizures, coma, brain injury.", better: "Check the sugar first in every confused diabetic; treat lows with IV dextrose.", severity: "major" } },
  ],

  hazards: [
    { id: "neuroglycopenia", label: "Prolonged severe hypoglycaemia — seizure",
      omission: { byMinute: 20, preventedBy: ["dextrose", "glucagon"] },
      stages: [
        { afterMin: 0, status: "critical", interrupts: true,
          vitals: [{ key: "rbs", value: "31" }, { key: "gcs", value: "8" }, { key: "hr", value: "126" }, { key: "spo2", value: "93" }],
          observation: { role: "nurse", text: "Doctor — he's fitting! Jerking all four limbs, not responding." },
          examFindings: { general: "Generalised tonic-clonic seizure; frothing at the mouth; drenched in sweat.", cns: "GCS 8. Unresponsive to voice." },
          patientSays: "(Unresponsive.)" },
        { afterMin: 30, status: "critical",
          vitals: [{ key: "rbs", value: "24" }, { key: "gcs", value: "6" }],
          observation: { role: "nurse", text: "The fit has stopped, but he isn't waking up." } },
      ],
      rescue: [["dextrose", "glucagon"]],
      fullRecoveryWindowMin: 15,
      lastRescueMin: 120,
      recovery: [
        { afterMin: 0, status: "guarded", vitals: [{ key: "rbs", value: "132" }, { key: "gcs", value: "12" }, { key: "hr", value: "104" }], patientSays: "(Drowsy, mumbling.)" },
        { afterMin: 30, status: "improving", vitals: [{ key: "gcs", value: "15" }, { key: "rbs", value: "128" }],
          examFindings: { general: "Awake and oriented; tired after the seizure.", cns: "GCS 15. No focal deficit." },
          patientSays: "My head hurts… what happened, doctor?" },
      ],
      review: {
        cause: "Severe hypoglycaemia was not treated in time.",
        whyItCausedHarm: "The brain runs almost entirely on glucose. Below about 40 mg/dL neurons stop working — confusion, then seizures and coma; prolonged, it causes permanent injury.",
        earliestRescueWindow: "On arrival: check the capillary sugar within minutes of seeing any confused diabetic.",
        correctRescueSequence: ["Capillary glucose now", "IV 25% dextrose 50–100 mL (or IM glucagon 1 mg)", "Recheck the sugar in 15 minutes", "10% dextrose infusion", "Admit; stop the sulfonylurea"],
        lastRealisticRescueWindow: "Within the first hour of a seizure — sooner is better for the brain.",
      } },
  ],

  onResponse: {
    vitals: [{ key: "rbs", value: "146" }, { key: "gcs", value: "15" }, { key: "hr", value: "94" }, { key: "bp", value: "136/82" }],
    examFindings: {
      general: "Awake, alert and oriented. Sweating has stopped; skin warm and dry. No tremor.",
      cns: "GCS 15. Oriented to time, place and person. No focal deficit.",
    },
    patientSays: "Much better now, doctor. Just a little tired.",
    says: "Huh… doctor? I feel better now… What happened to me?",
  },

  followUp: [
    { when: "ideal", status: "recovered",
      lines: [
        { role: "system", kind: "status", text: "Diabetes clinic, two weeks later" },
        { role: "patient", kind: "speech", text: "No more shaky spells, doctor. I eat breakfast before my walk now, and I check my sugar if I feel strange." },
        { role: "system", kind: "finding", text: "Glimepiride stopped; metformin continued; a DPP-4 inhibitor added. Fasting sugars 110–140 mg/dL." },
      ] },
    { when: "acceptable", status: "stable",
      lines: [{ role: "patient", kind: "speech", text: "I'm fine now, doctor, but I felt shaky once more before lunch." }] },
    { when: "any", status: "guarded",
      lines: [{ role: "attendant", kind: "speech", text: "He had another low at night, doctor. We gave him sugar and brought him in." }] },
  ],

  truth: {
    diagnosis: "Hypoglycaemia — sulfonylurea-induced",
    qualifier: "Glimepiride dose increased last week, taken this morning without breakfast after poor intake — confusion (neuroglycopenia) with sweating, tremor and tachycardia (adrenaline response)",
    reasoning: [
      { stage: "History", text: "A known diabetic on glimepiride, dose just increased, took it, skipped breakfast and went walking; poor intake last night; a milder shaky spell last week." },
      { stage: "Examination", text: "Confused and drowsy (GCS 13), sweaty, clammy, tremulous, tachycardic — with no focal deficit." },
      { stage: "Investigation", text: "Capillary blood glucose 42 mg/dL. ECG: sinus tachycardia." },
      { stage: "Diagnosis", text: "Symptomatic hypoglycaemia — symptoms, a low sugar, and recovery with glucose — caused by a sulfonylurea." },
    ],
  },

  rubric: {
    diagnosisAccept: ["hypoglycaemia", "hypoglycemia", "low blood sugar", "low sugar", "sulfonylurea induced hypoglycaemia", "sulphonylurea induced hypoglycaemia", "drug induced hypoglycaemia", "hypoglycaemic encephalopathy", "neuroglycopenia", "hypoglycemic"],
    diagnosisPartial: ["altered sensorium", "encephalopathy", "metabolic encephalopathy", "diabetes", "type 2 diabetes"],
    differentials: ["stroke", "seizure", "sepsis", "hyponatraemia", "head injury", "alcohol intoxication", "diabetic ketoacidosis", "hyperosmolar", "hypoxia", "meningitis"],
    idealTreatment: [["dextrose", "glucagon"], ["d10"], ["hold-glimepiride"], ["admit"]],
    expertActionCount: 8,
    expectsReassessment: true,
    definitiveTreatment: { ids: ["dextrose", "glucagon"], byMinute: 20, label: "IV dextrose" },
    misses: {
      meds: { what: "Did not ask about his diabetes medicines.", why: "The recent glimepiride increase is the cause — and it decides how long he must be watched.", better: "In every confused diabetic, ask what they take and what changed.", severity: "major" },
      meal: { what: "Did not ask when he last ate.", why: "A sulfonylurea on an empty stomach is the classic set-up for a low.", better: "Ask about the last meal and recent intake.", severity: "moderate" },
      cns: { what: "No neurological examination.", why: "Focal signs would point to a stroke — and a low sugar can itself mimic one.", better: "GCS, pupils, limbs and plantars in every confused patient.", severity: "moderate" },
      dextrose: { what: "No IV dextrose.", why: "Every minute of severe hypoglycaemia risks seizures and permanent brain injury.", better: "IV 25% dextrose (50–100 mL) now; recheck the sugar in 15 minutes.", severity: "major" },
      d10: { what: "No dextrose infusion afterwards.", why: "Glimepiride keeps lowering the sugar for 24–72 hours; one bolus wears off within an hour.", better: "10% dextrose infusion and hourly sugars.", severity: "moderate" },
      admit: { what: "Not admitted for observation.", why: "Sulfonylurea lows come back, often at night.", better: "Admit; hourly sugars until stable on food.", severity: "moderate" },
      "hold-glimepiride": { what: "Glimepiride wasn't stopped.", why: "It caused this — and his HbA1c of 6.2% says he's over-treated.", better: "Stop it; switch to a drug that doesn't cause lows.", severity: "moderate" },
    },
    strengths: {
      meds: "Found the glimepiride dose increase.",
      meal: "Asked about the missed meal.",
      cns: "Checked for focal signs.",
      dextrose: "Gave IV dextrose promptly.",
      d10: "Started a dextrose infusion to prevent a relapse.",
      admit: "Admitted him for observation.",
      "hold-glimepiride": "Stopped the glimepiride.",
    },
  },

  teaching: {
    patientBand: "severe",
    severityBands: [
      { id: "mild", label: "Mild (level 1: 54–69 mg/dL)",
        recognition: ["Shaky, sweaty, hungry, palpitations", "Alert and able to eat"],
        investigation: ["Capillary glucose"],
        treatment: ["15–20 g fast sugar — 3 teaspoons of sugar in water, glucose tablets, or juice", "Recheck in 15 minutes; repeat if still below 70", "Then a meal or snack"],
        followUp: ["Find the cause: a missed meal, exercise, or the dose"] },
      { id: "moderate", label: "Moderate (level 2: below 54 mg/dL)",
        recognition: ["Confusion, slurred speech, odd behaviour", "Still able to swallow"],
        investigation: ["Capillary glucose; renal function"],
        treatment: ["Oral glucose if swallowing safely; otherwise IV dextrose", "Recheck in 15 minutes"],
        followUp: ["Review medicines; observe if on a sulfonylurea or insulin"] },
      { id: "severe", label: "Severe (level 3: needs someone else's help)",
        recognition: ["Drowsy, unable to swallow safely, seizure or coma"],
        investigation: ["Capillary glucose; RFT; ECG in older patients"],
        treatment: ["IV 25% dextrose 50–100 mL", "No IV access: glucagon 1 mg IM", "Then a 10% dextrose infusion", "Admit — sulfonylurea lows recur for 24–72 h"],
        followUp: ["Stop the culprit drug; relax the HbA1c target"] },
    ],
    treatmentByBand: {},
    drugs: [
      { generic: "Dextrose 25%", brand: "D25", dose: "50–100 mL (12.5–25 g)", route: "IV", frequency: "Stat; repeat if glucose < 70 at 15 min", duration: "Single bolus",
        indication: "Severe or symptomatic hypoglycaemia",
        mechanism: "Delivers glucose straight into the blood.",
        whyItWorks: "The brain runs on glucose — restoring it reverses confusion within minutes.",
        avoidWhen: ["A small or tissued vein — it's irritant; use a good vein and flush after"],
        adverseEffects: ["Phlebitis; tissue injury if it leaks", "Rebound hypoglycaemia once it wears off (sulfonylureas)"],
        monitoring: ["Capillary glucose at 15 minutes, then hourly"] },
      { generic: "Glucagon", brand: "GlucaGen", dose: "1 mg (0.5 mg if under 25 kg)", route: "IM", frequency: "Stat", duration: "Single dose",
        indication: "Severe hypoglycaemia without IV access",
        mechanism: "Releases glucose from the liver's glycogen stores.",
        whyItWorks: "Raises blood glucose within 10–15 minutes.",
        avoidWhen: ["Depleted glycogen — starvation, alcohol, liver disease (works poorly)"],
        adverseEffects: ["Nausea and vomiting"],
        monitoring: ["Glucose at 15 minutes; food once awake"] },
      { generic: "Dextrose 10% infusion", brand: "D10", dose: "About 100 mL/h, titrated", route: "IV", frequency: "Continuous", duration: "Until stable on food (often 24 h)",
        indication: "Preventing a relapse after a sulfonylurea low",
        mechanism: "A steady glucose supply while the drug wears off.",
        whyItWorks: "A bolus lasts about an hour; glimepiride acts for a day or more.",
        avoidWhen: ["Fluid overload"],
        adverseEffects: ["High sugar, low sodium, phlebitis"],
        monitoring: ["Hourly capillary glucose; sodium"] },
    ],
    routines: [
      { label: "The rule of 15 — for mild lows at home",
        steps: [
          { order: 1, step: "Check the sugar if you feel shaky, sweaty or strange", note: "If you can't check, treat anyway" },
          { order: 2, step: "Take 15 g of fast sugar", howMuch: "3 teaspoons of sugar in water, or half a glass of juice" },
          { order: 3, step: "Wait 15 minutes, then check again", note: "Still below 70 mg/dL? Repeat step 2" },
          { order: 4, step: "Eat a proper snack or meal", note: "Roti, biscuits or fruit — so it doesn't come back" },
        ],
        avoid: ["Taking the sugar tablet and skipping the meal", "Exercising on an empty stomach", "Driving when the sugar is low"],
        improvementTimeline: "Confusion, drowsiness, or a low that keeps coming back → hospital immediately." },
    ],
    followUp: {
      interval: "1–2 weeks",
      reassess: ["Home glucose log, especially fasting and before lunch", "Any further lows", "Kidney function"],
      redFlags: ["Confusion or drowsiness", "Lows at night", "A low that doesn't recover with sugar"],
      whenToEscalate: ["Recurrent lows despite changes → review every medicine; look for other causes (alcohol, liver, adrenal, kidney)"],
    },
    treatmentFailure: { steps: [
      "Recheck the glucose — and the meter",
      "Think of the drug: sulfonylureas and long-acting insulin need longer infusions",
      "Think of other causes: alcohol, liver failure, adrenal insufficiency, sepsis, kidney failure",
      "Confusion that persists after a normal sugar → stroke, seizure or infection (CT head, LP)",
    ] },
    pearl: "Check the sugar in every confused, sweaty, drowsy or 'stroke-like' patient — before the CT, before the antibiotics, before anything. It takes a minute, and the cure takes a minute more. And a sulfonylurea low is a long low: one bolus is never enough.",
    hazardTeaching: {
      title: "What could have gone wrong",
      body: "Without glucose in the next 20 minutes his brain would have run out of fuel: a seizure, then coma, and possibly permanent injury.",
      sequence: ["Capillary glucose immediately", "IV 25% dextrose 50–100 mL (or IM glucagon)", "Recheck in 15 minutes", "10% dextrose infusion", "Admit; stop the sulfonylurea"],
    },
  },
};
