import type { Metadata } from "next";

import { A, LegalPage, List, Section } from "@/components/legal/legal-page";
import { PublicPage } from "@/components/shell/public-page";

export const metadata: Metadata = { title: "Disclaimer", description: "RamAI is an educational simulation, not medical advice." };
export const dynamic = "force-dynamic";

export default function DisclaimerPage() {
  return (
    <PublicPage>
      <LegalPage
        eyebrow="Disclaimer"
        title="For learning, not for real patients."
        intro="RamAI is an educational simulation for doctors, medical students and other healthcare learners. Please read this before you use it."
      >
        <Section title="Not medical advice">
          <p>
            Nothing on RamAI is medical advice, and nothing here should be used to diagnose, treat or manage a real person. RamAI does not replace
            clinical judgement, supervision, local protocols or current guidelines. Using RamAI does not create a doctor–patient relationship with
            anyone.
          </p>
        </Section>

        <Section title="Every patient is fictional">
          <p>Cases, patients, families, places and events are invented for teaching. Any resemblance to real people is coincidental.</p>
        </Section>

        <Section title="Content can be simplified, outdated or wrong">
          <List>
            <li>
              Cases, findings, investigations, drug doses and teaching are simplified for learning and may contain errors or fall behind current
              practice.
            </li>
            <li>Always check doses, indications and contraindications against current guidelines and your local formulary before using them in practice.</li>
            <li>
              Versions for India, the USA and the UK adapt names, units, brands and prices. These are approximations, not a statement of local
              practice or of real prices.
            </li>
            <li>Where AI features are switched on, some replies are generated by a language model and can be inaccurate.</li>
          </List>
        </Section>

        <Section title="Scores are for practice">
          <p>
            Scores, ranks, badges and leagues measure performance in the simulation only. They are not a professional assessment, a qualification or
            continuing-education credit.
          </p>
        </Section>

        <Section title="Names of institutions and brands">
          <p>
            Care levels are described with familiar examples — such as AIIMS-level or Harvard-level — only to convey difficulty. RamAI is not
            affiliated with, sponsored or endorsed by AIIMS, Harvard, the NHS or any other institution. Drug brand names belong to their owners;
            mentioning them is not an endorsement.
          </p>
        </Section>

        <Section title="In an emergency">
          <p>Call your local emergency number — 108 or 112 in India, 911 in the USA, 999 in the UK — or go to the nearest emergency department.</p>
        </Section>

        <Section title="Limitation of liability">
          <p>
            RamAI is provided for education "as is". To the extent the law allows, RamAI is not responsible for any decision made or action taken
            based on its content. See the <A href="/terms">terms</A> for details.
          </p>
        </Section>
      </LegalPage>
    </PublicPage>
  );
}
